### ISSUE TITLE
Import from ODK

### ISSUE THREAD

**Issue by dannyparsons** [africanmathsinitiative/R-Instat#1728]
@stevenndungu We have a very exciting dialog for you to work on. We would like to be able to import data directly from an ODK into R-Instat. 
We now know how to do import data from a kobo or ona form directly into an R data frame!
Please can you create the simple design for the dialog attached with help from @maxwellfundi and @Lunalo.
I will then send details later today of the code that's needed to go in the dialog.
Let me know if you need any help.
![img-20160915-wa0014](https://cloud.githubusercontent.com/assets/11214914/18547001/ff04c14e-7b38-11e6-94b9-8da215490381.jpg)

**Comment by dannyparsons** [comment]
@stevenndungu I have now added an Instat object method called "import_from_ODK" which you can use for the dialog. @Lunalo should be able to help with this and the parameters should be obvious.

Some more information:
1. The "Find Forms" button should only be enabled when both username and password have been filled in.
2. To fill the choose forms combo box you will need to use the "get_odk_form_names" function I have created in the file stand_alone_functions.R. This code should be run internally to get the names and add them to the combo box. Don't worry if you are not sure how to do this part. I can discuss with you and John.
3. Ok should only be enabled once a form has been chosen.

**Comment by stevenndungu** [comment]
I have received the work. Let me work on it with help of Maxwell and John.
Thanks.
Steve

**Comment by stevenndungu** [comment]
Ok thanks, will do that.Danny Parsons <notifications@github.com> wrote:@stevenndungu I have now added an Instat object method called "import_from_ODK" which you can use for the dialog. @Lunalo should be able to help with this and the parameters should be obvious.

Some more information:
1. The "Find Forms" button should only be enabled when both username and password have been filled in.
2. To fill the choose forms combo box you will need to use the "get_odk_form_names" function I have created in the file stand_alone_functions.R. This code should be run internally to get the names and add them to the combo box. Don't worry if you are not sure how to do this part. I can discuss with you and John.
3. Ok should only be enabled once a form has been chosen.

—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/africanmathsinitiative/Instat","title":"africanmathsinitiative/Instat","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/africanmathsinitiative/Instat"}},"updates":{"snippets":[{"icon":"PERSON","message":"@dannyparsons in #1728: @stevenndungu I have now added an Instat object method called \"import_from_ODK\" which you can use for the dialog. @Lunalo should be able to help with this and the parameters should be obvious.\r\n\r\nSome more information:\r\n1. The \"Find Forms\" button should only be enabled when both username and password have been filled in.\r\n2. To fill the choose forms combo box you will need to use the \"get_odk_form_names\" function I have created in the file stand_alone_functions.R. This code should be run internally to get the names and add them to the combo box. Don't worry if you are not sure how to do this part. I can discuss with you and John.\r\n3. Ok should only be enabled once a form has been chosen."}],"action":{"name":"View Issue","url":"https://github.com/africanmathsinitiative/Instat/issues/1728#issuecomment-247320699"}}}

**Comment by dannyparsons** [comment]
Now in place and working, but may need more additions in future.

**Comment by dannyparsons** [comment]
Few corrections for the dialog:

- Form spelt incorrectly on button
- Text in password textbox is different to normal text boxes (font is too big)

**Comment by maxwellfundi** [comment]
This dialog is in place and works well. This could be Closed.

**Comment by dannyparsons** [comment]
The second point: Text in password textbox is different to normal text boxes (font is too big) still needs to be addressed and the text box for that is sort of cut off on the dialog. Someone could quickly look into this.

**Comment by stevenndungu** [comment]
I can quickly check on that

**Comment by stevenndungu** [comment]
@dannyparsons, can I close issue? looks like its fully implemented.

**Comment by dannyparsons** [comment]
First version is implemented, but more work needed to get the data imported in the correct formats.

**Comment by rdstern** [comment]
I have made this into Version 0.4.1, but it could become 0.4.2 once we add that milestone.

Here is information from Sebastian on possible improvements.  
He will be with me at a (climatic) workshop in mid-September.  But I have already been asked for help on ODK in R-Instat by Lesotho Met.  So it could be good to include some enhancements by then if possible.  It relates to Stats4SD interests.

Here is his message, sent on 24 July 2017:
"Roger just told me you are working on adding functions to bring ODK collected data into R-Instat.
I sent the attached functions to read and label ODK data into R to Dani around a year ago, but the attached version is more robust.

The main function is odkFormat. It sets the variable format based on the XLSForm type and creates a labeled version of the data set and a list with all codes and labels.
Help functions: revarnames (brings the XLSForm into a format odkFormat can use) and readonadata (simply reads in the data). 

At the moment, you need the XLSForm and the data in your working folder. The obvious next steps if you decide to use these functions would be:
•	Pull the data and form from the ODK server (I understand this functionality is already there in R-Instat?)
•	Use the codebook to label the data in R-Instat

These functions are probably not written or documented the way a programmer would do it, so feel welcome to ask me if you need any guidance using them.
Big advantage is, I have used and tested them on a number of data sets, so they run pretty robust."
[readodk.zip](https://github.com/africanmathsinitiative/R-Instat/files/1193510/readodk.zip)
