### ISSUE TITLE
A new "Enter" dialogue but start with the current calculator!

### ISSUE THREAD

**Issue by rdstern** [africanmathsinitiative/R-Instat#1751]
This is a new dialogue, It is in the **Organise > Column: Generate** menu and to be added just after Regular Sequence.  It is called "Enter" and is to enter a column of data.  It might later also be added to Manipulate > Column: Text.  There it would be the first name and again called "Enter".
It is not especially urgent.  But it is an easy dialogue to implement and hence might be a useful piece of work for Steve.
I would also like all team members to have a variety of pieces of work to do, so they are usually not working on just one task.  This is particularly important so no one get's completely stuck at any point.  If you are stuck on one problem, then you have another piece of work to be doing, while you wait for discussions.

If you have the old Instat loaded (you probably should) then this is the equivalent of the Manage > Data > Enter dialogue there.  In particular you will notice that it includes a keyboard again!

First I would like you to see what the command will do.  It will be based on the current calculator dialogue, so open that one first (in R-Instat).  As you use it, then see if you can see any bugs, or scope for enhancements.  If you can, then add them to this thread.  (So far, in the calculator, I can see one enhancement I would like, and also one bug.)

OK, now open the standard survey data set - which has 36 rows.
In the "Expression" field: type
1) (1:36) and press OK, then get the dialogue back and
2) seq(1,18.5,0.5) and press OK.  Then
3) c(letters,month.abb[1:10]) and press OK.   

Have you made any mistakes yet?  I hope you have, so you see what the error messages are like.  Try a few more, for example what happens if you do:

4) c(letters,month.abb), or just
5) letters

The calculate dialogue does trap these errors, where the column being generates is a different length to the data frame.  An alternative (not for now) would be to add NA if the generated column is too short, and just put the 36 observations in, when it is too long.  HoweverI think we can exist without changing these for now.

Did you find anything?  I noticed:

1) the Try feature was disabled at the beginning, but is now enabled.  I thuink it should stay disabled for now. (That's the small bug I found.)
2) It would be really nice if we could look back at the previous calculations - not just the very last one.  That's the pull-down which remains empty for now.

Anyway on to the real "Enter" dialogue.  I hope you can see that it should be easy, because you can start with the calculator dialogue and change that one!

**Comment by rdstern** [comment]
Now this is to suggest the new Enter dialogue.  It will be similar to the existing calculate, both in the dialogue itself, and in how it passes the information to R.

The dialogue first.  Adapt the calculate dialogue in the following way:
a) The label "Expression" can change to "Data"
b) You choose a data frame - so that part is there, but you don't choose any columns.  For the control with just the data frame you could look, for example at Organise > Data Object > Copy Data Frame, or Delete Data Frame - (though they seem to be messed up for now!)
c) Get rid of the drop-down from the calculator, because there will just be a single set of keys.  But keep the "Show Arguments" checkbox.  Default is that it is not enabled.
d) Then you need a single keyboard.
e) Below that I am not sure about the Try.  It probably isn't needed.
f) Save into could have the default prefix "Data".
g) Rest as normal.
Now for the keyboard.

1) It has the number keys.
2) It has the clear and delete keys I guess.
3) It has E
4) It has full stop"."
5) It has comma ",".
6) It has colon ":"
7) it has an NA key - this just gives "NA".
8) It has minus "-".
9) It has () where the cursor is then within the brackets.  It may also be good to have the single brackets as well.  let's see how the keyboard goes.
10) It has square brackets []
11)  There are 4 (sort of command keys.  First one is "c" and this gives c() when used.
12). Second one is "rep", which gives "rep()"  (When "Show arguments is checked, then it gives rep(x=,times=,length=,each=)
13.  Third one is "seq" which gives seq().  When arguments is enabled it gives seq(from=,to=,by=)
14. Fourth one is also "seq", but give the key "seq2" say.  When pressed it gives seq(,,length=zzz).  Here zzz is the length of the data frame.  With arguments enabled it gives seq(from=,to,=,length=zzz) again as length of the data frame.  
15 Just to explain we need 2 separate forms for the seq command, because if you give by and length together that generates a fault.

When this is run, then it should be as for calculate.  But if the length is too short then it continues with NA.  If the length is too long, then it truncates.  It doesn't give an error in either case.

One [possible enhancement (for later, but discuss with Danny) is from the regular sequence dialogue.  This shows what the resulting sequence will be.  That would be a great feature to add here.  It is like the "Try" on the existing calculator.
 
Roger

**Comment by stevenndungu** [comment]
Ok, fine Rogers. Will be working on it as from tommorow. rdstern <notifications@github.com> wrote:Now this is to suggest the new Enter dialogue.  It will be similar to the existing calculate, both in the dialogue itself, and in how it passes the information to R.

The dialogue first.  Adapt the calculate dialogue in the following way:
a) The label "Expression" can change to "Data"
b) You choose a data frame - so that part is there, but you don't choose any columns.  For the control with just the data frame you could look, for example at Organise > Data Object > Copy Data Frame, or Delete Data Frame - (though they seem to be messed up for now!)
c) Get rid of the drop-down from the calculator, because there will just be a single set of keys.  But keep the "Show Arguments" checkbox.  Default is that it is not enabled.
d) Then you need a single keyboard.
e) Below that I am not sure about the Try.  It probably isn't needed.
f) Save into could have the default prefix "Data".
g) Rest as normal.
Now for the keyboard.

1) It has the number keys.
2) It has the clear and delete keys I guess.
3) It has E
4) It has full stop"."
5) It has comma ",".
6) It has colon ":"
7) it has an NA key - this just gives "NA".
8) It has minus "-".
9) It has () where the cursor is then within the brackets.  It may also be good to have the single brackets as well.  let's see how the keyboard goes.
10) It has square brackets []
11)  There are 4 (sort of command keys.  First one is "c" and this gives c() when used.
12). Second one is "rep", which gives "rep()"  (When "Show arguments is checked, then it gives rep(x=,times=,length=,each=)
13.  Third one is "seq" which gives seq().  When arguments is enabled it gives seq(from=,to=,by=)
14. Fourth one is also "seq", but give the key "seq2" say.  When pressed it gives seq(,,length=zzz).  Here zzz is the length of the data frame.  With arguments enabled it gives seq(from=,to,=,length=zzz) again as length of the data frame.
15 Just to explain we need 2 separate forms for the seq command, because if you give by and length together that generates a fault.

When this is run, then it should be as for calculate.  But if the length is too short then it continues with NA.  If the length is too long, then it truncates.  It doesn't give an error in either case.

One [possible enhancement (for later, but discuss with Danny) is from the regular sequence dialogue.  This shows what the resulting sequence will be.  That would be a great feature to add here.  It is like the "Try" on the existing calculator.

Roger      

—You are receiving this because you were assigned.Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/africanmathsinitiative/Instat","title":"africanmathsinitiative/Instat","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/africanmathsinitiative/Instat"}},"updates":{"snippets":[{"icon":"PERSON","message":"@rdstern in #1751: Now this is to suggest the new Enter dialogue.  It will be similar to the existing calculate, both in the dialogue itself, and in how it passes the information to R.\r\n\r\nThe dialogue first.  Adapt the calculate dialogue in the following way:\r\na) The label \"Expression\" can change to \"Data\"\r\nb) You choose a data frame - so that part is there, but you don't choose any columns.  For the control with just the data frame you could look, for example at Organise \u003e Data Object \u003e Copy Data Frame, or Delete Data Frame - (though they seem to be messed up for now!)\r\nc) Get rid of the drop-down from the calculator, because there will just be a single set of keys.  But keep the \"Show Arguments\" checkbox.  Default is that it is not enabled.\r\nd) Then you need a single keyboard.\r\ne) Below that I am not sure about the Try.  It probably isn't needed.\r\nf) Save into could have the default prefix \"Data\".\r\ng) Rest as normal.\r\nNow for the keyboard.\r\n\r\n1) It has the number keys.\r\n2) It has the clear and delete keys I guess.\r\n3) It has E\r\n4) It has full stop\".\"\r\n5) It has comma \",\".\r\n6) It has colon \":\"\r\n7) it has an NA key - this just gives \"NA\".\r\n8) It has minus \"-\".\r\n9) It has () where the cursor is then within the brackets.  It may also be good to have the single brackets as well.  let's see how the keyboard goes.\r\n10) It has square brackets []\r\n11)  There are 4 (sort of command keys.  First one is \"c\" and this gives c() when used.\r\n12). Second one is \"rep\", which gives \"rep()\"  (When \"Show arguments is checked, then it gives rep(x=,times=,length=,each=)\r\n13.  Third one is \"seq\" which gives seq().  When arguments is enabled it gives seq(from=,to=,by=)\r\n14. Fourth one is also \"seq\", but give the key \"seq2\" say.  When pressed it gives seq(,,length=zzz).  Here zzz is the length of the data frame.  With arguments enabled it gives seq(from=,to,=,length=zzz) again as length of the data frame.  \r\n15 Just to explain we need 2 separate forms for the seq command, because if you give by and length together that generates a fault.\r\n\r\nWhen this is run, then it should be as for calculate.  But if the length is too short then it continues with NA.  If the length is too long, then it truncates.  It doesn't give an error in either case.\r\n\r\nOne [possible enhancement (for later, but discuss with Danny) is from the regular sequence dialogue.  This shows what the resulting sequence will be.  That would be a great feature to add here.  It is like the \"Try\" on the existing calculator.\r\n \r\nRoger      "}],"action":{"name":"View Issue","url":"https://github.com/africanmathsinitiative/Instat/issues/1751#issuecomment-247833335"}}}

**Comment by stevenndungu** [comment]
Hi Roger,

I have implemented the New Enter menu as you had suggested with little
enhancements to finish up tomorrow morning. Have a  check on it and give
your comment on it so far.

Just a clarification: On the E button (i.e, is it the base of 10,
abbreviation exponential,or?) am not sure which to pick on.Thanks

Steven

**Comment by stevenndungu** [comment]
Just noticed now that the mail you send me missed missed this section! (yet contains very important information - [will fix that])
 "16) There are also 5 other "keys". One is "LETTERS", second is "letters", third is "month-", 4th is "month+" and 5th is "pi". When they are pressed they give exactly what is on the key, excpet that "month-" gives "month.abb" and month+" gives "month.name". If necessary you can shorten the keys to show "LTRS", "ltrs","mon-", "mon+" and "pi".

I make that 29 keys overall. That could be 2 blocks of 4 by 4. The first block could then be the existing calculator with the "." moved over and the "-" moved up. Then the remaining keys are in the second block. The dialogue doesn't have to be too wide, because you don't need the space on the left for the columns of the data frame.

When this is run, then it should be as for calculate. But if the length is too short then it continues with NA. If the length is too long, then it truncates. It doesn't give an error in either case."

**Comment by rdstern** [comment]
I reply to your query: Just a clarification: On the E button (i.e, is it the base of 10,
abbreviation exponential,or?) am not sure which to pick on.Thanks

Yes, I was assuming you could enter data into R as 4E03 or 4E-5.  I suggested capital E because I think that will work and then we don't confuse it with the number e.  We need to test it.

Roger

**Comment by stevenndungu** [comment]
Ok, thanks. I did make the changes on commend number (16) overnight. I hope
the designer is now as expected.

**Comment by dannyparsons** [comment]
This in now merged in the code @rdstern can test and give feedback.

**Comment by rdstern** [comment]
Thank you.  I will try it.  Meanwhile the help topic ID is 458

**Comment by stevenndungu** [comment]
Getting back to the Enter dialogue
This dialogue is almost complete with two more pending issues. Which I didn't address previously while working on this dlg;
1) "When this is run, then it should be as for calculate. But if the length is too short then it continues with NA. If the length is too long, then it truncates. It doesn't give an error in either case." as suggested by Roger. I still have not gotten how to implement this (doing findings on it).

Question (Clarification): should the addition of NA's be done to all functions or only on seq,seq2,letters,LETTERS. Considering, for instance the case of month.name and month.abb, should it not keep looping from Jan- Dec until all rows are done(like it does now)?

2) "Addition of a feature that shows what the resulting sequence will be. Similar to the "Try" on the existing calculator."

**Comment by dannyparsons** [comment]
@FrancoisJRenaud asked who should edit the R code to handle the different lengths. Since this is a core method in R I suggest me or @stevekogo does this, it should be fairly quick so probably easier for me to just do instead of discussing first with @stevekogo. 
But I'm happy that others may want to start getting into the R code. A first step could be to understand the changes that will be made to fix this issue and then could start on other R methods.

**Comment by dannyparsons** [comment]
I will update the R method to avoid this bug.

**Comment by stevenndungu** [comment]
Great

**Comment by stevenndungu** [comment]
@dannyparsons Are you done with method or still in progress?

**Comment by dannyparsons** [comment]
I didn't do this yet, thanks for the reminder.

**Comment by AlexSananka** [comment]
What's the state of this?It looks it has been open for some time.
