### ISSUE TITLE
Bug in specific plots with ucrVariablesAsFactors

### ISSUE THREAD

**Issue by FrancoisJRenaud** [africanmathsinitiative/R-Instat#1874]
When choosing x and multiple y's in the main dialogue, everything is fine. Example:

"dash" dlgScatterPlot code generated by the dialog Scatter Plot
survey_temp <- InstatDataObject$get_data_frame(use_current_filter=FALSE, data_name="survey", stack_data=TRUE, id.vars="Field", measure.vars=c("Size","Yield"))
ggplot(data=survey_temp, mapping=aes(colour=variable, y=value, x=Field)) + geom_point()

However, if I choose multiple y in my main, and then go to the options to choose x, come back and run, then it tries to run: 

survey_temp <- InstatDataObject$get_data_frame(data.name="survey") 

Comment : obviously not nice as the names are not matching  !!! then it tries to run

ggplot(data= survey_temp, mapping = aes(colour = variable, y = value, x= Fert)) + geom_point()

... and this cannot work as Value and Variable are not in Survey !! Right ?

**Comment by dannyparsons** [comment]
Yes, that looks like an error in that control that should be fixed.
Another bug in this control is if you add aesthetics from the subdialog, they are not necessarily carried over in the stacked data because they were chosen from a different selector to the one on the main dialog. There should be a link between the selectors so that all the correct columns are carried in the stack.

**Comment by FrancoisJRenaud** [comment]
@dannyparsons  I have been trying to solve this by running the ucrVariablesAsFactors.SetReceiverStatus() after coming back from the BoxPlotOptions, in the hope to recover the missing parameters: stack_data=TRUE, id.vars="Field", measure.vars=c("Size","Yield") in the clsCurrDataFrame. However, these still don't appear in the toscript even if the ucrVariablesAsFactors.SetReceiverStatus() sets them properly in clsCurrDataFrame. Actually I beleive that they (parameters) where never taken away (from clsCurrDataFrame, while going through the sdgLayerOptions), which I initially thought. I am stuck. How comes these parameters are not sent through anymore after having clicked on BoxPlotOptions and returned. Is it related to some assignto thing ?

**Comment by dannyparsons** [comment]
Ok maybe this is something I should just look into as well on my side and then we discuss to share what we find.

**Comment by dannyparsons** [comment]
I have identified the problem which is in returning to the main dialog from sub dialog. Fixing this properly relates to sub dialog linking correctly. For the beta can we disable the two sub dialogs when multiple y values selected (plot options needs to be disabled because of #1215). I have done boxplot in #2085. Can someone do the other specific graphs? I will make a new issue for this.

**Comment by FrancoisJRenaud** [comment]
Will do with the dialogues containing VariablesAsFactor, that are not being edited by someone else: 
histogram and line (dlgHistogram and dlgPlot).
