### ISSUE TITLE
Issues with geoms

### ISSUE THREAD

**Issue by maxwellfundi** [africanmathsinitiative/R-Instat#1907]
I think we will have to edit our control to suit new needs. I have been looking at the abline specifically and I found out some few things 
1. You find that the linetype is numeric and you might be drawing more than one line and so you would have to type in figures eg 1,3,4,5 which we can not do using a nud
2. when we have added no aesparameter for the geoms, the system crashes. Looking at abline again, the parameters we have can all go to layer parameters other than the aesthetics and hence left without any aesthetics. how do we do this?
Again, the mandatory parameters for this are Slope and intercept. These can not be mapped to variables and hence also go to layer parameters.
 I need your opinions on these issues
 ggplot(data=survey_temp, mapping=aes(y=Yield, x=Field)) + geom_point() +geom_abline(slope=c(.2,0.6, 0.4,0.5,0.7), intercept=c(30,40,50,60,20),linetype=c(1,3,4,6,5)) this is a good example where I would want to draw multiple ablines with different linetypes
 Another bug I found - when you create a layer, then go into it, edit it by removing some aes, they don't get removed at all....

**Comment by FrancoisJRenaud** [comment]
The usage of the three geoms: abline, vline and hline is rather different from other geoms, as they take mandatory parameters, and aesthetics are not really relevant. For example, abline requires slope and intercept, which are the key parameters as opposed to mentioning aesthetics. The specific dlgAblinePlot for instance should probably display slope and intercept parameters instead of aesthetics, however, this is not quite possible in the sdgLayerOptions. Actually, none of the aesthetics seem to produce any relevant outcome for abline, as x and y are simply not available, and setting colour, alpha, size and linetype doesn't change the outcome (which is sort of expectable). So what could be done is hide all aesthetics, or only show the useless ones, but make it mandatory to fill in the parameters slope and intercept (maybe send a message when trying to click ok, without having filled in the parameters, to explain to the user that he/she needs to fill in mandatory parameters). 
Now about the issue explained above, either each abline the user wants to make would require another layer, or, if we want the user to be able to make several lines within one layer, the parameter data types for slope and intercept could be arrays of numeric values for example. These arrays need to be of the same lenght though. Would be nice to be able to 'add an abline', which would add a little numeric up-down in all parameters such as slope, intercept, type, colour,... ? 
Same discussion for vline and hline, which are determined by xintercept and yintercept and not by aesthetics ! Also the values could be mean(some variable) or median(some variable) which depend on the variable that is used on other layers as an x aesthetic or y aesthetic. All this presents a significant amount of challenges ...

**Comment by FrancoisJRenaud** [comment]
Apparently it's not currently possible to have no aesthetics parameters for a geom...

**Comment by dannyparsons** [comment]
It would be good to discuss these geoms again as they are useful. I think you need to look at them again more closely:

> Same discussion for vline and hline, which are determined by xintercept and yintercept and not by aesthetics !

^ Not true! yintercept in hline can be a parameter OR an aes. The aes is very useful for facets. If you only want a single line, then you can use the layer parameter, if you want more then you need the values in a data frame. What's nice is that if you can put yintercept in both aes and parameter, then the parameter one overrides without an error. So it works like the colour parameter in other geoms, it can go in both.

So implementing something here should be fairly easy and then we can do very nice multi data frame plots! The only difficulty may be checking the layer is complete, which means the right thing is in the aes OR the parameter. But I suggest we get the layers working first and then sort the structures for the checking.
