### ISSUE TITLE
Organise - linking to OpenRefine and developing the Organise menu further

### ISSUE THREAD

**Issue by rdstern** [africanmathsinitiative/R-Instat#1914]
This is not a high priority.  But it could be very useful, particularly if someone becomes interested in this area.  

It could also be very easy to implement, because the **rrefine** package is designed simply to export data to open refine, and then to be able to transfer results back from OpenRefine to R data frames. This could be implemented either in the File menu or in the Organise > Check data menu - or both.

OpenRefine describes itself as "A free, open source, power tool for working with messy data."  Now we also want our own Organise menu to be able to handle messy data, but OpenRefine goes a lot further than we could hope to do ever.  So in a follow-up message I suggest what we might still do in the Organise menu.  That will not negate the value of the links to OpenRefine.

It is possible that Danny/David might suggest that OpenRefine be given a higher priority because of the corruption work.  It would do some of the work of cleaning messy data sets from the web-crawling software using the internet.  In the current corruption project this step is being done by the Cambridge team, but this could do that sort of cleaning for data from other countries, and that is one of the longer-term aims of the corruption project.

In addition I like the 3 videos that describe the use of the software.  They should be of general interest, even though they were produced for when it was called GoogleRefine.  These videos are interesting in their own right.  They are also examples of videos of a sensible length, and very clear, and with subtitles that help the understanding - and would make translation easy.  They don't look difficult to produce and might be examples that we could follow, for R-Instat videos. Here is a link to the OpenRefine web page and the three videos: http://openrefine.org/ 

Roger

**Comment by rdstern** [comment]
I am keen that R-Instat is as good as R can be in handling messy data.  And we are getting close with the Organise menu.
One area to be completed is the facilities to handle text (character) columns.  This will be partly through making the **Organise > Column: Calculate >  Calculations** dialogue as powerful as possible, and then by completing the **Organise > Column: Text** dialogues.

I particularly would like R-Instat to be able to cope with questionnaires that have "open" answers.  They could be one or more sentences and we want to extract the key points from them in successive columns.  (There will still be some messy things we can't do, shown in the OpenRefine second video and that's fine.  We just need to know the limits of what we can do, and then be able to use more appropriate software if the data go beyond those limits.  And we need to document what we can't do, as well as what we can do!

 I hypothesise that (with one exception) we don't need to do anything other than is in the **stringr** package.   And the missing features there are largely the missing dialogues in the **Organise > Column: Text** menu.  However, before I get to the exception, notice that **stringr** does have commands:

str_locate_all and str_match_all and they might produce results into a new data frame.  It also has str_extract_all, but that also has an interesting "simplify" argument.  And if you look at some of the examples, then we would like to help (inexperienced) users with the wide range of expressions.  Here are some of the examples:
shopping_list <- c("apples x4", "bag of flour", "bag of sugar", "milk x2")
str_extract(shopping_list, "\\d")
str_extract(shopping_list, "[a-z]+")
str_extract(shopping_list, "[a-z]{1,4}")
str_extract(shopping_list, "\\b[a-z]{1,4}\\b")
# Extract all matches
str_extract_all(shopping_list, "[a-z]+")
str_extract_all(shopping_list, "\\b[a-z]+\\b")
str_extract_all(shopping_list, "\\d")

How do we make this easy?  Do we need more keyboards?

The main exception is the partial matching.  I think we do want to be able to measure distances and this is the stringdist package.

This will be great when it is all working, but it will take some careful thought.

**Comment by lilyclements** [comment]
I have only looked into rrefine so far, but it seems fairly straight forward. It consists of seven commands

**1. refine_check**
_which for some reason doesn't work on my R-Studio. I'm trying to download OpenRefine to try it out but this is so far not overly successful._
This checks whether rrefine can connect to OpenRefine. So, in turn, would check if R-Instat can connect to OpenRefine.

**2. refine_delete**
This deletes the project from OpenRefine
I do not know the urgency of this feature, however, I am a non-OpenRefine user so that point might be highly discredited. It does not look particularly difficult to implement, however!

**3. refine_export**
This exports from OpenRefine. So for us, this would be the "Import from OpenRefine" option
This does yield one question as one of it's parameters are
format = "csv"
So, I do not know how it will react to other file formats.

**4. refine_id**
This gets the OpenRefine unique project.id name for the project.name
As with point 2., I do not know the urgency of this feature, however, I am a non-OpenRefine user so many may disagree!

**5. refine_metadata**
This enables the user to import all project metadata from OpenRefine.

**6. refine_path**
This calls the path to OpenRefine
I am planning to have a look into this once I have OpenRefine up and running!

**7. refine_upload**
This is our "Export to OpenRefine" option

So, the main two we are interested in are refine_export and refine_upload
I feel refine_metadata is an interesting addition that we could include in the "Import from OpenRefine" option

Hopefully tomorrow I can get OpenRefine up and working to be clearer on this - especially on refine_path and refine_id - and also look into files on refine_export. I just wanted to share findings so far.


As for the videos, I think they're very good. Simple, short, easy and informative! I like how they explain through the problem with an example too.

**Comment by rdstern** [comment]
There has been so much work and correspondence on these 2 dialogues.  

Are they now good candidates to be visible together with the OK not enabled label?

**Comment by dannyparsons** [comment]
Yes I think so.

**Comment by lilyclements** [comment]
I can add the OK not enabled label shortly - however, before I do they need to be enabled on the main form. Shall I do this or is someone else currently doing something on the main form? I don't want a conflict.

**Comment by dannyparsons** [comment]
go ahead on frmMain

**Comment by lilyclements** [comment]
I enabled and added the ucr for "Export to OpenRefine". However, the "Import To OpenRefine" dialog is currently blank so I haven't enabled that option

**Comment by stevenndungu** [comment]
@lilyclements what is the progress on this?

**Comment by lilyclements** [comment]
I believe that Import to OpenRefine is still a blank dialog, and that Export to OpenRefine is not working still

**Comment by stevenndungu** [comment]
Yeah, I see. Will having a look at the Export/Import to OpenRefine  dlgs. Thanks

**Comment by dannyparsons** [comment]
They are not urgent dialogs, so we can leave them as they are for now. But may come back to them at some point.

**Comment by lilyclements** [comment]
This can be closed @dannyparsons
