### ISSUE TITLE
Writing our own wrappers?

### ISSUE THREAD

**Issue by rdstern** [africanmathsinitiative/R-Instat#1970]
I have come to this question sort of "backwards-way-on".  Here are 3 introductory points:

a) Mosaic is an R teaching project in the US.  We are making use of it for a number of dialogues.
b) It has written wrappers round very simple R commands and we are using them.  A particular example is t.test (also t_test in Mosaic to distinguish it from t.test in the stats package)
c) They are still not great and I was planning to write to them, so they could be improved.

However, we will also be writing our own wrappers, etc soon.  So I wonder whether we should do these particular wrappers also ourselves?  They could be an easy way into the topic and perhaps also into package writing.

This becomes a more general topic in that we should (soon?) also be writing our own package, or packages.  I wonder how soon.  I had a look for simple related packages already in R and a relevant one is called PROPcis.  It is very small and is described thus:

"Computes confidence intervals for single proportions as well as for differences in dependent and
independent proportions, the odds-ratio and the relative risk in a 2x2 table. Intervals are available
for independent samples and matched pairs. The functions are partly written by assistants of Alan
Agresti, see website http://www.stat.ufl.edu/~aa/cda/cda.html."

So my general question is on starting to write packages in R.  This also relates to the team progressing well now, plus the move soon to climatic, where we will be writing more of our own code - indeed a lot has been written.  I wonder when we should start?  The team in Kenya is getting ready (I feel) for some multi-tasking, but I don't want to distract too many from the work they now have.  

I was assuming we might start the package writing in December, i.e. while Francois is still in Maseno.  Am I right about this?  And should I leave enhancements to simple things like t-test to us, (partly as an easy way in), or should I discuss with the Mosaic folks?

Roger

**Comment by FrancoisJRenaud** [comment]
Dear all, 

maybe we could start by discussing this around a Skype call ? I m not sure I have all the necessary information/understanding of the needs, in order to produce a sensible opinion about it. 

From what I see here, coding packages in R would be warmly welcomed as an interesting, skill developing, task (to be confirmed by others of course @stevenndungu @maxwellfundi  @Lunalo ) ? On a training biased point of view, could help to stimulate the coding skills of the team, by working on the non-systematic design of methods, in an environment that might be less confusing than the R-instat vb.NET spider web, where creativity can be shadowed by the necessity of understanding the existing machinery of code... To be discussed.

Concerning the three introductory points: what about making contributions to other packages like mosaic ? 

Regards

François

**Comment by dannyparsons** [comment]
Writing to Mosaic about the improvements we suggest in their functions is a good idea, then if they do it, it's less work for us.

Most of our R code is tied in to the Instat object (and then soon the climate object) and so that would form at least 1 package. Where we write simple wrappers to R functions like Mosaic has done, we could consider putting those into their own little package.

I was thinking that we should have our own R package(s) by version 1, so not necessarily starting in December, but possibly.

Much of the work to create a package is "admin" stuff of getting the R code into the right folder and file structure, and then testing it passes all the tests. Documentation is another part, but the required amount is fairly basic. I was thinking this would be less of a team task and more something 1 or maybe 2 people to get stuck into to understand the details, which could be someone in Kenya.
