### ISSUE TITLE
Sub-dialog consistency needed 

### ISSUE THREAD

**Issue by volloholic** [africanmathsinitiative/R-Instat#2014]
@africanmathsinitiative/instat it has been brought to my attention that sub-dialogues have been being implemented in different was across the code. To ensure that we have software that works consistently and solidly with natural understandable behaviour we need to make sure that we have the same consistency with sub-dialog implementation as I believe we have on our dialog implementation. 

The heart of this consistency is of course our user control buttons. On the main dialogues I believe that everyone is familiar with what all the buttons do why they're there and how they should be implemented in the code. With the sub-dialog I am not sure we have had the discussions which can give everyone a common understanding of how the should be used and what the implications for the code are. 

For example are people clear about why sub-dialogues don't have a reset or cancel button? What are the implications for the code? How would this be different if we decided to have the reset cancel buttons? Why was the decision made to go with the version without reset and cancel?

I recognise that implementing this fully and well is a big job and would possibly distract us from other work which is more pressing in other ways. however at the moment people are building fixes to the consistency problems that arise in different ways across the code. We should really tackle this problem once and for all fully to make the software stable in the long run. There would also be other side benefits from addressing this problem fully.  I suggest we should have a full team Skype discussion about this at some point. So that everyone is aware of the issues when working on sub-dialogues.

**Comment by maxwellfundi** [comment]
I completely agree with your concerns as it has been something i had asked about recently. It will be good to have a Skype meeting at some point convenient to everyone.
I could suggest maybe tomorrow. I wonder if everyone is okay with it.

**Comment by FrancoisJRenaud** [comment]
Yup, tomorrow morning? Or today since everyone seems connected?

**Comment by maxwellfundi** [comment]
I would suggest tomorrow 14:00 hrs Kenyan time.

**Comment by FrancoisJRenaud** [comment]
Dear all,

Just a few thoughts about this. Concerning the reset and cancel buttons on sdg, I don't think a reset would be particularly happy. However, a cancel button would be nice in case the user has filled in loads of crap got confused and doesn't want it to be taken into account (I ve already been in situations where I was looking for a cancel button on sdg's, even if it was probably because I was afraid that return would make everything crash).

I ve been thinking of this uniformity problem because of the  situation with the graphics. Sometimes the main dialog gives through the RSyntax, sometimes it gives through other "code containers" or more general information stored in booleans, lists, ... sometimes all of these. Sometimes all these links between main and sdg are set at once, using one particular sub (that also calls the setup of the ucr's), sometimes the set-up process is scattered all over, or at least uses different functions and subs (flexibility that might be needed !)... Now uniformity would be very very welcome (also in the communication between ucr's and dialogs), however, I m getting used to all this and it is all looking quite smart once understood. I m already getting too easily into refining little details and not making enough progress on core important tasks that need to move on, so I start to think that some of these things could stay like they are for now. Unless you see value in making these progresses now, as they would hopefully smoothen the code and make bugfixing/addons/generaldevelopmentofthesoftware/... easier. For instance we might find questions like the following easier to answer : in the hope to create a help button on sdg's, how do we get systematically the help id of the main dialog on the subdialogue without editting ALL dialogs (@Maxwell issue #2000 ) ?

Passing through the RSyntax to the subdialog could be a nice uniform attitude. It is supposed to contain all the necessary information about the dialog, even though for the moment this is not always true. In case getting to the ideal RSyntax will take too long, uniformity might take another flavour, like at least gathering together all the things that need to be given through, in a format that is transparent and make the linking happen all at once. It can be quite painful to go and dig into the RSyntax to find the RParameter of an Rfunction of an RParameter of the Rsyntax. It might make it difficult to picture clearly who we are talking about, so it makes sense to extract that one info from RSyntax, give it an independent life and why not send it with other similar ambassadors of the RSyntax in sdg. Or RSyntax could be the ship, for these ambassadors to reach the sdg. Either ways, and probably many others. 

Now on main dialogs, the RSyntax (and probably other code containers) (seem to be)/are always edited on the spot, when settings are modified on the dialog.  One good reason Danny gave me for this is the necessity to be at any time able to visualise the script in construction via the toscript button (which can be quite nice for debugging to avoid crashes btw). This also sounds good for passing the whole "up to date dialog's info" to the sdg in one go.  

Going back to the cancel button idea, I have the feeling that we don't need to edit our RSyntax, or whatever has been given through, on the spot like on the main dlg's. RThings/RSyntax could be adapted to the choices of the user only when we click on return (so the subdialog would act as a mechanical toy doing nothing serious, serious things would only take place when click return; the final setting would then finally be "brought to life"). Choices could then be easily ignored when cancel is used. Alternatively, if on the spot is the preferred philosophy, one would probably only edit local clones, and still only proceed to the linking with the main dialog at the beginning and at the end. Finally one could make a copy of what has been passed through at the beginning and merge back with that copy in case of cancel.

I hope this doesn't sound too confused and might give something to react to when Skyping. 

Very best wishes,

Fr

**Comment by lilyclements** [comment]
@dannyparsons I think this issue can now be closed. We have created (and still are creating) consistency between subs through updating the dialogs.

**Comment by lilyclements** [comment]
@dannyparsons I think this issue can now be closed. We have created (and still are creating) consistency between subs through updating the dialogs.
