### ISSUE TITLE
Organise > Delete sheets

### ISSUE THREAD

**Issue by rdstern** [africanmathsinitiative/R-Instat#2250]
This is a sort-of bug!

If I have 3 sheets open, say called a, b, c.

I choose to delete a.  

1) It takes a long time.  I am deleting large sheets though.  Perhaps I need to accept this?
2) But what I call the bug, is that when a has been deleted it still shows the data from sheet a, but the tab at the bottom is now showing sheet b.  So it gives the impression it has deleted the wrong sheet.  It hasn't - the deleting action is fine, I think.  If you go to sheet c, and then back to sheet b then it is all fine.  

But it is a bit unnerving before that!

I have suggested John, but it could be anyone who looks at that.

**Comment by dannyparsons** [comment]
I believe this is an issue with reogrid caused by that fact that it doesn't refresh when you delete a sheet, until you "do something" like change tabs. I agree it's confusing. It's worth seeing if there's a way to force a refresh in reogird, otherwise contact them to ask about it.
I've seen bugs similar to this before so I wouldn't be surprised if this is a simple bug for reo to fix.

**Comment by dannyparsons** [comment]
fixed
