### ISSUE TITLE
Additional Layers on specific graphs

### ISSUE THREAD

**Issue by dannyparsons** [africanmathsinitiative/R-Instat#2267]
For some of the specific graphs, adding an additional layer doesn't do anything. But for some it does. I can't remember which ones, but can someone go through all dialogs and check? It should be a simple fix, if it hasn't already, but I checked fairly recently and it didn't work in some cases.

**Comment by FrancoisJRenaud** [comment]
should I work at the same time on #1948 ?

**Comment by dannyparsons** [comment]
No, this is something simple to fix in specific plot dialogs, whereas the other is more complex. In general, one issue per pull request.

**Comment by FrancoisJRenaud** [comment]
This is not as easy as expected. It is not that adding layers doesn't work on some specific graphs. Only the first specific graph dialogue that is opended will have that functionality... That's because RSyntax of the urAdditionalLayers on sdgPlots is set in the initialise dialogue of sdgPLots. Also the RSyntax of sdgPlots is set in the initialise dialog of the main graphic dlg. Hence the first on that's opens sdgPLots will have it's RSyntax linked with the ucrAddLay's RSyntax, then the last main dialog to have been initialised is the one that shares RSyntax with sdgPlots... see #2274
