### ISSUE TITLE
Describe > Specific > Bar Chart general issue?  (update on sjPlot wanted)

### ISSUE THREAD

**Issue by FrancoisJRenaud** [africanmathsinitiative/R-Instat#2268]
As a response to @rdstern 's email below, I create this issue to discuss what we want out of this brilliant package sjPlot... the recipients of the email where @maxwellfundi, as well as @dannyparsons  and @volloholic 

> Hi all,
> 
> I was looking for something else and stumbled over the sjplot package.  This uses ggplot2 and has some nice articles also.  I don’t know if we need (or wish) to use the package.  However it has some nice examples of finished ggplots and we should be able to produce them easily with “our” system.  Examples include bar charts with numbers and percentages on the top of the bars.  See examples in the attached file on customise and on frequencies – which includes a violin plot!  This is just one example of starting with a problem and producing the plot! 
> 
> I think they are trying to do in command mode, what we are doing with dialogues.  But we may wish to include some of their functions as well?  Do they simplify any of your work – at least for some of the specific graphs?  Can we produce all of them reasonably easily – the examples shown are mostly from the bar chart menu.  For is I think some of the options – like including labels with frequencies, might become checkboxes on the main menu?
> 
> These are all from here: https://strengejacke.wordpress.com/sjplot-r-package/
> 
> There are many other examples.  I was looking at them because of their regression plotting capabilities.

In particular have a look at sjp.frq and sjp.grpfrq and sjp.stackfrq then for themes _Customize plot appearance_ article.

I am happy for us to go and peak into these functions to see how they do all this with ggplot2, and add these features on our specific graphs dialogues, etc. or we could also add these functions as dialogues in our describe menu. I would probably recommend both, but to begin with I really like the idea of getting all these very very good looking graphs for free through adding a few dialogues... For frq, grpfrq and stackfrq, these could all go into one potentially ? What do you think ?

About the themes, I don't know how much value their functions bring. I didn't get my head around the details on either packages...

**Comment by FrancoisJRenaud** [comment]
A new email from @rdstern : 

> A follow-up and now I am getting serious:
> 
> I do like this set of likert plots, see the attached.  They are sort of stacked (coord-flip) bar charts, but the examples on http://stackoverflow.com/questions/14415674/reordering-groups-in-likert-plots-with-r  don’t look as good – or easy – to me. 
> 
> It would be useful enough – to me – to have the likert one as a specific type.  I hope it fits our dialogue “scheme”, because I can imagine other examples in the future.  Then, if you wanted to use the basic ggplot tools, you go to general.
> 
> Does this work?  It is important for us, because many surveys have sets of questions that are on (say) a 1 to 5 scale with 5 being great and 1 being awful.  Of course we could stack them and thwey are “just” orderd factor columns.  But this “command” looks neat!
> 
> And this set of graphs and analyses is designed for social scientists – so very popular.  And (in McKnight) Jane Maland Cady will like this!
> 
> Roger

**Comment by FrancoisJRenaud** [comment]
Sorry our emails crossed each other. So I was mainly suggesting, should we just add these functions as dialogues for now ? Quick way to get these amazing graphs for free, like usual, in the spirit of using available packages. Don't know if these can be coherently inserted in the describe menu ?

**Comment by rdstern** [comment]
It is exciting.  However we need to be realistic.  One possible "test" is to see how well the graphs produced (perhaps outside R-Instat.  Could we (for example) produce a likert graph with a specialised dialogue just for that, and then take the resulting graph and use out facetting dialogues, then use graph and combine graph, etc.

And, as you say, many of the others, that I looked at first, are really examples of bar charts.  Perhaps they don't need a special dialogue, but just some extra options on the existing bar-chart dialogue?  What I am also keen to check is that (at least) some of the nice features of the examples can be produced reasonably easily anyway.  This is all part of coming from the problem, rather than the tool.  So, if someone asks how you could produce a bar chart with the numbers and percentages added, then how would you do it?  And if we then feel that is a really useful (and commonly demanded) feature, then how can we make it easy.  That's where I did like some of the sjplot examples.  I had the feeling that he understood to sort of demands that social scientists would make, and what they would expect from their SPSS and Stata (and Excel) experiences.

**Comment by FrancoisJRenaud** [comment]
Yes that makes sense. It also matches with Danny's concerns about compatibility with the way graphics are implemented now... so will be investigating with @maxwellfundi. I don't yet know how to add these nice percentages. Will be a good point to start having a closer look at themes as well I guess. However there are quite a few other tasks on fire for the moment ...

**Comment by rdstern** [comment]
The nice (default) graphs in the sjplot package seems now to me to link with a bit of logic we can apply to our own graphics menu and it can be illustrated well by the Describe > Specific > Bar Charts dialogue.  This is the idea that the "general" system and logic of ggplot is to build up the graphs "layer-by-layer"  However we commonly want examples that include multiple layers.  In bar charts we would often like to include the counts, (and possibly percentages) within the chart, as is done in the examples in sjplot.  

And these are even more interesting in a stacked bar chart, because there you usually lose the precise information on the count of most of the bars, but it is included in the text label.

So, could we allow this sort of option on the main dialogue of the bar chart.  (This could be as simply as having 2 check-boxes.  If we want more flexibility, then we would have to go to the sub-dialogue and consider it as an additional layer.  And we could perhaps go there after ticking the default to change the position, and other elements of the layer.

And synchronising this feature would seem possibly to link with the work this week on sub-dialogues.

This is the parallel of my request elsewhere, of being able to add jitter to the main boxplot dialogue.

Roger

**Comment by FrancoisJRenaud** [comment]
Hi @rdstern ,

I hope your visit to Canada was good ! So label and text have been added now. Just the pull request needs to be merged. There should be improvements in the way layer parameters are introduced in order to use their full functionality, but all the most important parameters are available. So I think it would be possible to add the count or percentages to the bar chart as a tick boxes. I had a look at the way they build their labels in sjPlot::frq and to be honest I got lost in the code quite quickly. But on the net I found ways to plot counts and percentages fairly easily: 
http://stackoverflow.com/questions/26553526/how-to-add-frequency-count-labels-to-the-bars-in-a-bar-graph-using-ggplot2
http://stackoverflow.com/questions/29869862/ggplot2-how-to-add-percentage-or-count-labels-above-percentage-bar-plot

It would be a little bit of work to add these, but I think it is not that difficult. What might be challenging is the relation with the options. So I would recommend to wait until the linking works fine.

Maybe a few questions: 
- could you remember us where you were asking for jitter on main dialogues ?
- are you asking for having options about position on the main dialogue for the barchart case for instance ?

As a comment, I have raised a certain amount of remarks about our geoms (parameters handling, aes, and others...) that it would be nice to discuss as handling these may make the kind of changes you are asking for above more accessible ? I will regroup these again in an issue, even though some of these have their own issues already. They are all mentioned in short in ucrGeom.

**Comment by rdstern** [comment]
Hi @FrancoisJRenaud,

This is all sounding very exciting - the progress on so many fronts.

For jitter I was asking on the boxplot dialogue.  And I was assuming the boxplot dialogue could itself also add the violin plots? (Just as bar charts include pie charts, and histograms include frequency plots).

So, these (e.g. jitter) add a second layer which commonly enriches that sort of graph.

In general we distinguish between what might be called "exploratory" and "presentation" graphs.  So, with that concept these second layers are adding information to the graphs really easily.  But they don't give great flexibility.  If you want the flexibility then you add that layer "properly", i.e. via the sub-dialogue for the jitter layer  (which I think still needs to be added.

So, for example the mount of jitter would not be on the main boxplot dialogue.  If you want to change that, then you go to the sub-dialogue.  In the particular case of jitter we could fix an amount, and I would make it (say) 20%.  The default is 40%, which is currently used on the One Variable > Graph dialogue.  Later we might get a bit clever and make the amount of jitter depend in some way on the number of observations - so it increases with sample size - but I am getting carried away now!

We will have to draw this balance between making the main dialogue more complicated - and hence confusing - and giving easy flexibility through this.  So we want a few "good value" check-boxes etc on the main dialogues, without them getting "cluttered".  Then we also have all the wonderful ggplot flexibility on the sub-dialogue.

And I do hope that the sub-dialogue work you are doing now, might mean they are linked?  So clicking to add jitter on the main boxplot dialogue is essentially just the same as going in one particular way to the sub-dialogue and adding it yourself. - and vice-versa.  (So adding jitter on a sub-dialogue from boxplot would tick the jitter check-box on the main dialogue.)     

Similarly for bar charts, the flexibility on where and how to put the text labels is (all) on the sub-dialogue. But putting them there is a set of check-boxes on the main dialogue.  How many check-boxes will also depend partly on how many others there are on the main.  So, on bar/pie charts now there is just flip coordinates.  If there is just one option for text, then I would make it counts (rather than percentages) and inside, rather than on top.  Whether we wanted more options for that layer (e.g. counts plus percents) would also depend partly on how easily adding the percents via the sub-dialogue can be made.

Roger

**Comment by rdstern** [comment]
On bar charts it does seem as though the new ggplot (version 2.2)  has improved various aspects - including the order of stacked bar charts.  It has also improved faceting.  It was released on about 12 November.  I wonder if we are - or should be - using it?
