### ISSUE TITLE
Defining a filter that produces 0 rows

### ISSUE THREAD

**Issue by dannyparsons** [africanmathsinitiative/R-Instat#2439]
Strange bug in the R link when you define a filter that produces a data frame with 0 rows. At some point the R link seems to crash and is unable to run any command. This only seems to happen when the filter produces 0 rows but the command that gives an error is:
`
.temp_value<-InstatDataObject$get_variables_metadata(column=InstatDataObject$get_column_names(include=list(Is_Hidden = FALSE), data_name="survey"), property=data_type_label, data_name="survey")`

It does not produce an R error. The error is:

> An unhandled exception of type 'System.ArgumentOutOfRangeException' occurred in mscorlib.dll
> 
> Additional information: Index was out of range. Must be non-negative and less than the size of the collection.

It looks like an infinite loop error and similar to the error we had with a dplyr function possibly timing out the R link.

When I tried to run `1+1` instead of that line, I got the same error. Possibly a previous line has crashed something in the R link that isn't detected.

**Comment by volloholic** [comment]
Ok this is a good excuse to check the tidyness of our code with respect to the R-Link the top priority is to try to reproduce the error in R-Studio by running the script with all "hidden" code. This is probably best done by introducing a permanent debug feature. 
We could be automatically writing every line of code sent through the r-link to a debug log saved to the instat temp files location it could be named while the software is active with a date and renamed on normal close so that non crash files get over written but files that occur with an abnormal exit of the software remain.
My guess is that  there is an R call which is somehow hanging the R link but should be traceable through debugging the R code.
