### ISSUE TITLE
.NET Framework version

### ISSUE THREAD

**Issue by isedwards** [africanmathsinitiative/R-Instat#2679]
R-Instat is currently targeting .NET version 4.0.  Is there a reason for this? Support for 4.0 ended last year - January 2016. I think it should be straight-forward to switch to 4.5.2 (which has long term support) or try moving to 4.6 (supported on Windows Vista and above) or >=4.6.1 (supported for Windows 7 and above).

https://support.microsoft.com/en-us/gp/framework_faq/en-us

**Comment by dannyparsons** [comment]
Thanks for this info. I wasn't aware support for 4.0 had ended. 
We initially decided on 4.0 so that we could still support XP users, which we felt would probably be a small but not insignificant proportion of our target audience in Africa.
However, we also don't want to compromise the software just to support a minority of XP users.

Given support for 4.0 has ended, probably we should now switch and target >= 4.5.2. I guess 4.6 would be sensible so that we can still support Vista users.

**Comment by isedwards** [comment]
@dannyparsons have you tested on XP? If the software works, you might want to stay on 4.0.  Microsoft may not support 4.0 anymore, but that's mainly because they don't support Win XP either.  I'd mainly want to update the .NET version if I was using Entity Framework etc which are still evolving, but components like WinForms used in R-Instat are frozen and no longer changing

**Comment by dannyparsons** [comment]
We've discussed this again here and I think decided that since we do not currently need any components  beyond 4.0 we will stick with this. But as soon as we need something only available in later .NET versions we will upgrade.
