### ISSUE TITLE
New Menu item: Describe > Two Variables > Frequencies

### ISSUE THREAD

**Issue by rdstern** [africanmathsinitiative/R-Instat#2759]
This will be similar to the previous issue #2757 on the one variable.

It will use the twin commands from the sjplot package , namely **sjt.xtab** for tables and **sjp.xtab** for the corresponding plots.  As with the one variable it could alternatively use the same wrapper commands **sjtab** and **sjplot**. (Note that sjpxtab is used for the graph when percentages are used.  If counts, then the sjplot command is **sjp.grpfrq**.

1. In the **Describe > Two Variables** menu it takes the place of Tabulate (and is now called Frequencies) and goes below the Graph item on this menu.  There is a **line** drawn in the menu and this item is **below the line**.
2. There is the usual selector and two single receivers. The first is called **Row Factor** and the Second is **Column Factor**.  The selector shows only factors or ordered factors, or logical (if we have them yet).
3. It will generate either a frequency table, or a ggplot graph, or both. So there is the control to save a graph at the bottom of the dialogue.
4. There is also a checkbox (default unchecked) with the label Weights: If it is checked, then a single receiver is visible. The selector is now restricted to numeric columns.
5. There is a checkbox with label "**Table**". Default is checked.  If checked, then there is a "group box" visible with **4 check-boxes** inside.  They have the labels Count, Row%, Column%, Cell%.  Default is that Count is checked and the others are not.   (It is OK for none of them to be checked.  Bit silly, but you just get the outline of the table!)  It works!
6. There is a checkbox with label "**Graph**". Default is unchecked. (Don't worry now that both could be unchecked. If so, then for now we could still produce the ggplot graph object and not display it.
7. When Graph is checked there are 4 radio buttons, with the same labels as for the tables.  (But here they are radio buttons - you choose just 1).  The default is **Count**. 
8. There is a checkbox (as in the existing one variable graph, for "Flip Coordinates".

There is an Options button leading to a sub-dialogue. For now leave this blank.  This will include Dodge/Stack, plus options on what to display on the top of the bars.  It will also give the option of a set of line plots, rather than bar charts.

**Comment by lilyclements** [comment]
Is this what we want for the version on Monday 20th? (Is that version 0.3.0?)

**Comment by rdstern** [comment]
Hopefully yes.  This should be simpler to do than the general tables summaries and frequencies, because they call an existing command from a package - like the windrose does.  So I hope these can be done for both the oneway and the twoway.

So, if something is left, (at least till David/Danny are around) then it is to get the more general tabulation dialogues working.

**Comment by rdstern** [comment]
Good that this is sort of working.  I repeat the note 5 from above, because the counts are important and are missing from the options:

"There is a checkbox with label "Table". Default is checked. If checked, then there is a "group box" visible with **4 check-boxes** inside. They have the labels **Count**, Row%, Column%, Cell%. Default is that Count is checked and the others are not. (It is OK for none of them to be checked. Bit silly, but you just get the outline of the table!) It works!
There is a checkbox with label "Graph". Default is unchecked. (Don't worry now that both could be unchecked. If so, then for now we could still produce the ggplot graph object and not display it.
When Graph is checked there are **4 radio buttons**, with the same labels as for the tables. (But here they are radio buttons - you choose just 1). **The default is Count**.

**Comment by stevenndungu** [comment]
@rdstern Sorry on the the count, I had it in place but while @lilyclements was reviewing we missed out on the fact that count default state in R is TRUE so we did not get the difference while checked and unchecked. I am making the  addition by  changing the default state to TRUE.

For the Graph and Table check boxes Danny suggested I change to radio buttons because of the scenario of having both check boxes unchecked. Good that you made clear on your comment so am as well adjusting it too to its previous state.

On html tables, with help of Danny I managed to have the output on the output window for both one way and two way frequencies which was looking quite good but unfortunately there was a problem with the code that re-directs the output. There was a fault where the tables would be given in triplicates instead of a single table. This resulted to getting it back to the previous version to have just the dialogue working until that is sorted (hopefully this week-before next release)

**Comment by rdstern** [comment]
I still don't understand why the Counts checkbox, or Option remains absent from the 4 options in this dialogue.  For the graphs it should be trivial.  For the tables I would be happy for now if none checked gave just counts, i.e. the same as just the first checked.  Ideally there would be a bit of code - user control? for a set of checkboxes where none checked automatically checks the first, when OK is pressed, i.e. next time in to the dialogue, the user sees what has been done.  Or none checked disables OK.

**Comment by rdstern** [comment]
These comments apply to both the one-way and the two-way frequencies.  

1) They are examples of graphs (and tables) that use a special function - here sjp.xtab (and sjp.frq for oneway).  This is similar to the special function used already for wind roses.   
2) Usually we don't do this - we build up the ggplot ourselves.  But we want to take advantage of these special functions when they are useful.  They should all be consistent with one another.
3) You said you want to take ownership.  Here are some ideas to help with this.

So:
1) It is producing a ggplot.  So (obviously?) we should want to save this as we do with all the graphics dialogues.  So that should be added.  I assume it is easy - it should be a custom control, because it is on many dialogues.
2) The one variable dialogue has an "Options" button.  There are many options in using either the frq (for one variable) or  xtab (for two variables).  So there should be an options button also on the two variable dialogue.
3) Then the challenge.  Could you design the sub-dialogue(s).  Remember there will be some differences on the options for producing a table and a graph.  I am happy to try and design this for you, but you may want to try first?
4) then, of course, they have to be implemented.  But try the designs first.

**Comment by stevenndungu** [comment]
@rdstern thanks for the additions above. I am happy starting it off then will ask when not certain on what to do.
A quick check from you:
1) I have changed the design slightly to,
![image](https://cloud.githubusercontent.com/assets/20383893/24403215/817d34f2-13c4-11e7-84c3-dcbb02c4233a.png)
i thought of changing to the above design to accommodate the option of having customized tables and graphs if both table and graph are checked.
![image](https://cloud.githubusercontent.com/assets/20383893/24403411/6b3ea5b2-13c5-11e7-9e39-df09a91fdce0.png)
 what do you think of this?

2) I have checked on the `sjp.xtab`,  margin parameter has 3 options namely `col` for rdo Column, `cell` for rdo Cell and  `row` for rdo Row. I am not sure what to add to count radio button?

**Comment by lilyclements** [comment]
The layout looks okay. I have a few comments on the tiny details of it (Frequencies is spelt wrong on the first image, not equally spaced etc) but I assume I can make them on the pull request? I'm on my phone so can't do pull requests great right now!
Also, in a couple of dialogs now I've seen where we want to have a checkbox for ucrSave but not the corresponding textbox/combobox. Perhaps we should discuss with @dannyparsons if it can be made possible to have a ucrSave with just a checkbox?
What are thoughts on having the four checkboxes under the receivers, and then the group boxes next to one another below the selector and the checkboxes?

Are weights and Flip coordinates only options when the Graph is checked too? Perhaps we should have the checkboxes for Table and Graph above these two options if that is the case so that the four check boxes go
Table
Graph
Weights
Flip Coordinates?

To 2. are you saying `sjp.xtab` doesn't give an option for count for the margins? I'll have a little explore when I get to the office

**Comment by stevenndungu** [comment]
@lilyclements thanks on ucrsave, am happy to discuss that.
When graph is checked we have weights, Flip coordinates and frequencies group box only other options am planning to have them in the subdialog after the form changes you made are merged. Note: weight is for both Table and Graph that's why I placed it above there but flip I can bring it under the Graph checkbox.

Yes, `sjp.xtab`has strictly three options, actually trying a different thing gives this error
`Error in match.arg(margin) : 'arg' should be one of “col”, “cell”, “row”`

**Comment by lilyclements** [comment]
Okay, so the col, cell, row options would be radio buttons. However, there is an option to show the counts or not - surely that is what `show.n` does? This is a boolean which is default `TRUE` and when `FALSE` this doesn't show the counts

**Comment by rdstern** [comment]
In your proposed dialogue above:
a) The label in the first block should remain the same.  It could be Display (Table).  In the second it could be Margin (Graph).
b) You are correct that it does not seem possible, in the graph, to have the y-axis showing the counts.  I have written to the person who produces the package, so please (for now) keep the dialogue as you have it, with the counts disabled.  (I can show you what is wanted easily over skype..  We can do it from our specific graphs dialogue.)
c) We now also need an options button to go to a sub-dialogue.  This will be similar to the one we have for the one-way frequencies, i.e. with the 2 tabs and some of the same options.  I'll look at that in the next comment, below.

**Comment by rdstern** [comment]
I now (already have a reply from Daniel Ludecke - who has written the sjplot package.    On my item be he says as follows:

Dear Roger,

thank you for your feedback. Your first suggestion seems already to be solved:

For counts, you can use `sjp.grpfrq()`: sjp.grpfrq(diamonds$color, diamonds$cut)

**Comment by rdstern** [comment]
I have yet to see how far you have got on the 2-way dialogue.  I presume - like one-way frequencies, for now it will be a choice between a table and a graph.  That will mean the block can be in the same place, making for a neater dialogue.

1. For the graph you have the choice between dodge and stacked.  That is the bar.pos argument, where the default (I think) is side-by-side (dodge).  This is the correct default, so there could just be a checkbox "Stack".  
Most of the other arguments are the same as for the One Variable graphs and tables.  For the graphs they are for showing the counts/percentages and the vjust, etc for these extra labels.

**Comment by stevenndungu** [comment]
I am making the adjustments needed, sorry I got back to one way frequencies to check on the review comments yesterday (I will check with you on skype on the same - because i feel there is a little of mis-understanding of how the dialogue should work from different reviewers, which you can clarify).

**Comment by stevenndungu** [comment]
@rdstern @lilyclements 
Question:
 Is plotting a line graph of categorical variables sensible statistically? 
I thought they are only meant for continuous variables only  to show trend over period of time(?).

  I see that we are doing this In two way frequencies since the receivers are restricted to only have categorical variables only. Well, the package generates a line graph which looks really good and happy with the way it looks but it brings an error at times in R when the variables used have _"Breaks and labels of different lengths_".

Example; 
Load Survey data in R
`sjp.xtab(x=Fertgrp., grp=Variety., type="line", title="", margin="row", show.n=TRUE, show.prc=TRUE)`
this error is generated
`Error in f(..., self = self) : Breaks and labels are different lengths`
And similarly this happens in the implemented dialogue.

Should we still have the line option on graph type?

**Comment by rdstern** [comment]
Well spotted.  I get the same problem.  We can get line plots for the counts using sjplot(...fun="grpfrq"...)

And it may be sensible in some instances for ordered factors.  But (at least for now) let's concentrate on the bar charts.  So get rid (or hide) this control for now.

**Comment by rdstern** [comment]
This is looking much better.  But I strongly suggest you change and use the sjplot command, as mentioned  in the comment above - 10 days ago - and also over skype.  That will make it easy to do the graph for the counts, which are still disabled in the dialogue.

**Comment by stevenndungu** [comment]
Yes, I was to change it last week but unfortunately was not able since I
was off due illness .So, Thursdat I thought it wise to have it still like
that so that we still have something usable on the version produced.

 I will be working to change that for both one way and two way frequencies
in the shortest time possible. Thanks

On Apr 16, 2017 11:53, "rdstern" <notifications@github.com> wrote:

This is looking much better. But I strongly suggest you change and use the
sjplot command, as mentioned in the comment above - 10 days ago - and also
over skype. That will make it easy to do the graph for the counts, which
are still disabled in the dialogue.

—
You are receiving this because you were assigned.
Reply to this email directly, view it on GitHub
<https://github.com/africanmathsinitiative/Instat/issues/2759#issuecomment-294341082>,
or mute the thread

**Comment by AlexSananka** [comment]
Should this be closed?
