### ISSUE TITLE
Prepare > View Data enhancement

### ISSUE THREAD

**Issue by rdstern** [africanmathsinitiative/R-Instat#2776]
This is not a priority.  But I suggest it is very easy, so I would like Steven and Lily to at least discuss it, while in Bagamoyo.

Now we are using the sjplot package the sjt.df function has a very nice feature that enhances the viewing of data.

It presents the data in HTML.  The enhancement is that the data can be sorted on a single column.  So we could display the 10 rows that are the highest yields, etc.

In the Prepare > View Data dialogue, I suggest that "**View in Output Window**" now becomes the first option.
The second is the new one, which is "**View HTML in Output Window**".  This similarly has the number of rows, but not the "Top/Bottom" radio buttons.  Instead there is a checkbox (default unchecked) with "Sort on:" label.  If checked, then a single receiver becomes available.

The **View in Separate Window** is the last of the 3 options. 

If the new option is chosen it runs the sjt.df command with **summary = FALSE**.

**Comment by rdstern** [comment]
When Danny (and David) are there I would like you to have a brief discussion of the sjPlot command view_df.  This has the option to display details about each factor, including the labels, plus the frequencies at each label and also the percentages.  It looks quite nice in the output window.

I haven't checked what it does for date variables, or other special types.  It might be just for factors, in which case it is similar to our Prepare > Column: Factor > Levels/Labels - which I like, but that is for just one factor.  

I think it sits more naturally in the Prepare menu, but it is an alternative also in our Describe > One Variable menu.

It is worth a play with the command to see if we a) Need it, b) If so where it should go.  Of course it could go in 2 places!

**Comment by lilyclements** [comment]
Steven and I have looked over these two functions. Our thoughts are as follows:

1. sjt.df 
This seems pretty straight forward so hopefully will be quite simple to add that to the View dialog.
You said it runs the command `summary = FALSE`, I assume you mean `describe = FALSE` here? So we just run
`sjt.df(df = DataFrame, describe = FALSE, sort.col = COLUMN)`

Steven had two additional points of what to add which I agree with.
a) `altr.row.col = TRUE` so that the alternate rows are shaded which makes it easier to see
b) Potentially `title = ""` so the user can add a title


2. view_df
I was not convinced at first when reading through the parameters since a few are already offered in the software (`show.type`, `show.values`, `show.labels`) . However, by the end of the parameter list, I could see a place for this.

For example, `show.frq` allows you to easily see the frequencies of the factors. While the Levels/Labels dialog does offer this, this allows you to see every variable at once. Steven and I both think that is quite nice. Additionally, since it is in a table, it is a lot easier to see the different levels for datasets with more levels than our current system of looking at it on the Levels/Labels dialog.

Similarly, `show.prc` allows you to see the percentage of frequencies of the factors. This is a nice addition that I don't believe we have in the software. As before, it is easy to look at.

`show.na` is a nice addition too because it is easier to see how many missing values there are through this than with the Levels/Labels dialog. I'm not sure if we have another way to list the number of missing values?

You can also see your weighted frequencies and weighted percentages if you include a weight by variable (`show.wtd.frq`, `show.wtd.prc` respectively)


Neither of us are sure where it would go. Some choices are more for Prepare (show labels/values/type), whereas others (show prc/frq) would fit in nicely in the Describe Menu so perhaps we should offer it in both?

Another point to note is that the user doesn't have to view every variable at once, they can pick which variables to view. So if the user only wanted to see the labels/values/type/frq/prc of only a few variables in their data set then this is a nice way to do it.

**Comment by dannyparsons** [comment]
Both functions look interesting and different.

For `sjt.df` on the survey data with `describe = FALSE`, I get the exact numeric values i.e. 5.4999999 etc. I didn't see any option for rounding? That would be annoying if there isn't. Did you notice this or find any option?

I had a quick look at `view_df` and I didn't see much that was useful for numeric columns (that don't have labels). It does some really nice things for factors! I didn't go through it very well, did you find anything that would be useful for continuous variables? Otherwise, should this be a dialog in the Factor menu?

**Comment by lilyclements** [comment]
I didn't find anything too helpful for numeric columns or for date columns either - other than perhaps that it says the number of NA's? 
I suppose the factor menu is a good place for it to go

**Comment by lilyclements** [comment]
View Data still needs one more enhancement - the controls are either set up or half-set-up for this. With view in HTML format we want to be able to sort with respect ti a variable but this can't  be done yet because this requires a single receiver where the item in the single receiver also has to be an item in the multiple receiver. This means once we can restrict the single receiver to only items which are in another receiver we can add this feature.
