### ISSUE TITLE
dlgOpenFromLibrary

### ISSUE THREAD

**Issue by maxwellfundi** [africanmathsinitiative/R-Instat#2778]
When opening data from library, I would like to be able to double click on the data set from the R packages and its immediately loaded into the software. 

I would find that quite useful..

**Comment by rdstern** [comment]
And when an item is selected (single click) and the user then presses for the special help on that item - which works well, - then I would like it to remain obviously selected when the help is closed.  It is half-selected in that you can press OK and get that data set.  But it doesn't look selected any more.

**Comment by dannyparsons** [comment]
@rdstern your suggestion is a simple setting of the list view which I have now turned on. Note that the highlighted colour is different when the control has focus to when it doesn't. This is deliberate by Windows and I suggest we don't try to change this.

@maxwellfundi's suggestion seems more general than this dialog and links to #3416
Personally I don't mind there not being quick ways to run dialogs - because we want people to think about the options they chose, not just click OK whenever they can. 
When you are testing the software you want to do things as quickly as possible because you know how everything works, but that's not how beginners will feel. I'd rather be conservative and make users take a little longer to do something than have quick ways which a beginner might do accidentally and then get confused by.

**Comment by volloholic** [comment]
I think I agree that loading a dataset shouldn't have a shortcut to pressing ok. Do we all agree? Can we now close this?

**Comment by maxwellfundi** [comment]
I agree with @dannyparsons that for starters they need to be aware of the actions they are doing. We can now close this
