### ISSUE TITLE
Water Balance tidy up

### ISSUE THREAD

**Issue by rdstern** [africanmathsinitiative/R-Instat#2819]
1. The columns are not auto-filling.
2. The Capacity up-down control has a limit of 100.  Far too low.  Make it 500.
3. There are other problems typing into this control.  They may be general or specific to the control.
4. The water balance limit control also has problems.  I tried to input 10mm and it wouldn't let me.  Typing in is also difficult.  Again may be a general issue with the up-down controls or specific.

**Comment by lilyclements** [comment]
Okay, so there is a general issue that the columns do not autofill if you have previously opened the dialog before defining it in climatic. So, if I open Water Balance (or any other of the autofill dialogs), then realise I forgot to define in climatic so I define in climatic, then I reopen water balance - it doesn't autofill since it's already been opened in that "session". Similarly, with defining climatic, say I open it and define my variables, then I close it. Then I realise I wanted to add a DOY column, so I add that and reopen "Define Climatic", the new DOY column does not automatically go in. I discussed this with @stevekogo earlier this week who made the point that perhaps on the first opening, the user does not intentionally define something and so they do not want to keep intentionally not defining it upon each opening. What are your thoughts?

Capacity nud max can be sorted, apologies. I'll look into the nuds in general here to see if it's the VB nud issue or an issue on the dialog.

**Comment by rdstern** [comment]
I suggest there are two options.  The first is that we keep the rule that climatic dialogues (like any others) keep what they had when you used them before.  So they would not autofill after you "corrected" the define dialogue.  As long as the user can complete that field i.e. the column is in the selector, then I am OK with that.  

If the user wants them to autofill, then they press RESET.  My understanding is that this will do a full reset, so we lose what was filled, but then it starts again and will now therefore detect the changes in the define dialogue.

I assume that is what happens now.

The only other logical alternative - to me anyway - is that the define climatic would do a reset itself - of each climatic command.  So then the stuff would be refilled automatically.

My understanding is that the define is sort of optional.  Obviously very useful, but you could fill the dialogues manually if you wish.  Hence the first option above is then the most obvious.

A quick check with David and/or Danny might be useful to confirm.

**Comment by lilyclements** [comment]
Looked at the nuds and increased the maximum for the Capacity to be 500 and Water Balance max to be the maximum possible number. What is the preferred maximum value for Water Balance?

As for the issue with writing in the nuds, it is a Visual Basic issue due to the decimal places. I feel, particularly with the nud for Water Balance then decimal points are surely needed? What are your thoughts?
If you select all the contents in the nud and try to type it assumes you want to type over the numbers in the nud. That is, say the nud value is 0.50 and you wish to change it to 10.00, then as you write "1 0 0 0" it assumes you want to have only one digit before the decimal point since the current nud value only has one digit before the decimal point.
If you, however, select only the part before the decimal points then it writes as you would expect.
This is not ideal! Ideally the will be a way to specify for these nuds to have that when you write in it you can specify where the decimal point goes. That is, you write "1 0 . 0 0"

**Comment by rdstern** [comment]
If you are changing the dialogue to include > for the first time, this would be good, because it can then be used as an alternative for the start of the rains.  So the earliest date when the water balance is more than 40mm could be the start.  

Of course then a sensible question is the first date that it is full.  So that would be the maximum.

The water balance is usually in mms, so I am not keen on decimals.  The only reason I used 0.5 as a value, is because I wanted a small non-zero value.  Happy to have zero really except for possible rounding problems.  And I would like to be able to type 0.5 even if the steps in the up-down are integer.  And happy if the steps were 10mms.

In the capacity up-down I would be happy with steps of 10mms.

**Comment by lilyclements** [comment]
Sorted the nud values out. Currently, I have only implemented where Water Balance =< Rain-Amount. Shall I implement now for the version for today to have Water Balance >= as well as =<?

**Comment by rdstern** [comment]
Only if easy.  It isn't needed for today.

**Comment by lilyclements** [comment]
I'll keep fixing small bugs around the software and see what jobs Danny gives us for corruption. I'll only start on this today if I think I can finish it today!
