### ISSUE TITLE
dlgLabels - enhancement

### ISSUE THREAD

**Issue by lilyclements** [africanmathsinitiative/R-Instat#2857]
Small query about dlgLabels.
@africanmathsinitiative/developers These are general notes and issues from yesterday

1. Unanimous feedback I had from everyone from the AIMS students is that the factor grid here is too small especially when dealing with long names or names with similar starts (e.g, we saw "United" and didn't know if it were UK, USA, UAE, turns out it was United Republic of Tanzania).
I think this is an instance of a software not being easy-to-use (do correct me if I have misunderstood "easy-to-use"!) 

2. Is a search feature possible? We had rows and rows of countries and I wanted "Senegal" which is right in the middle of it all! It would have been great if I could have just typed "S" and been brought to the countries beginning with "S".
Or, in Tanzania's case that it's under "United Republic of Tanzania", ideally I could have written "Tanzania" and it selects the countries with "Tanzania" in it.
I'm not sure how possible that is.
(Similarly so for other dialogs with levels concerned, e.g, dlgRestrict)

I know what I prefer but what do others think? Any input would be a great way to "take ownership" as discussed this week!

**Comment by rdstern** [comment]
Delighted to have this issue opened.  I would like to include a more general context to this all, partly because I have wanted improvements to the Levels/Labels dialogue for some time.  But there are others as well that we could reflect on.

a) Most statistics packages don't deal very well with Factor columns.  We have started OK, and it would be great to do better.
b) We can cope quite well with factor columns where there are just a few levels.  It would be great to be able to handle factor columns well also when there are lots of levels, e.g. for names of the countries.
c) Within all columns we need to check how to cope with wide names or labels.  Currently we are "stuck" in the middle in each of the following ways:  
1) Names of sheets can be wide, i.e. helpful but difficult to see.
2) Ditto for names of columns
3) And for levels of a factor
The other packages cope with part of this problem by having the name short and being able to add a longer label.
I wonder what we should do?

We need to make some progress if we will help one of our main audiences, namely those who have large surveys to analyse.

**Comment by Lunalo** [comment]
@lilyclements 

I encountered the first part of this issue when demonstrating to AIMS students during corruption workshop.

We should  restrict if the user only want to see the levels and their labels but not adding new level(s)

In fact the title of the dialog might be misleading . It is levels/labels. Is there a possibility of splitting this dialog into two?
Add Levels and Levels/Labels.

**Comment by lilyclements** [comment]
I have moved the bug part of the issue to #2861 now to keep it separate.

There are two other things we are discussing here - Dealing with factor columns/etc and the dlgLabels. Perhaps we should split one of these into another issue to discuss them separately?

**Comment by lilyclements** [comment]
As for Rogers point -

In what way do other packages not "deal well" with factors? The only click-and-select package I have used is minitab and I did not use that too much. Apologies if the question is tough to answer. Perhaps when I'm back tomorrow you can show me how on another software programme?

**Comment by dannyparsons** [comment]
It's useful to remember feedback we get from users. 
When there are many levels with long names doing a proper table using another dialog is a better way to really view them. Levels/labels is for editing and adding levels mainly. 
But I can still see it's useful to make the grid bigger in this dialog.

**Comment by dannyparsons** [comment]
I have made the levels/labels dialog and the grid bigger for now while keeping it within the size on minimum screens. I'll close this but there could be specific points related to comments here as new issues.
