### ISSUE TITLE
One Variable Graph - Single Graphs bug

### ISSUE THREAD

**Issue by lilyclements** [africanmathsinitiative/R-Instat#2879]
On One Variable Graph, facets and combine graphs save well. However, there is an error with "Single Graphs"

If I open the dialog for the first time, and select "Single Graphs" and "Save Graph", the graph does not save: 1. it always calls the graph _onevar1_ if I reopen the dialog and add different variables/etc, 2. It doesn't show up on the dlgUseGraph dialog.

If I then save another graph (e.g. Facets or Combine) then the Single Graphs, the "Single Graphs" starts to try to save. They try to save as last_graph if the checkbox is unchecked, or as _onevarX_ if checked (as we would want!). Irregardless of the checkbox being checked or not, the following error occurs:

> Error in self$get_data_objects(data_name)$get_objects(object_name = object_name,  : 
>   one_var2 not found in objects
> 
> 
> The error occurred in attempting to run the following R command(s):
> 
> one_var2 <- InstatDataObject$graph_one_variable(data_name="Blocking", columns=c("x2","x3"), output="single", numeric="geom_boxplot", categorical="geom_bar")
> 
> InstatDataObject$add_graph(data_name="Blocking", graph=one_var2, graph_name="one_var2")
> 
> InstatDataObject$get_graphs(graph_name="one_var2", data_name="Blocking")

I'm not sure why this isn't working for "Single Graphs".
However, I also do not understand how we can save multiple single graphs under one name so could the issue be to do with this?

Any clarity in the error would be appreciated!

**Comment by dannyparsons** [comment]
@maxwellfundi Can you check if this is still an issue?

**Comment by maxwellfundi** [comment]
@dannyparsons  i have tested and retested this and this issues seems not be an issue anymore. This can be closed.

Thanks

**Comment by dannyparsons** [comment]
Did you try doing single graphs? When I did it I just get a combined graph. Did you notice this?

**Comment by maxwellfundi** [comment]
yes, Did single graph for one variable and still saved properly.

**Comment by maxwellfundi** [comment]
I have now tried the single graphs with multiple variables, creates a combined graph... :-(

Method needs to be edited to produce single graphs.... not combined graphs

**Comment by dannyparsons** [comment]
When I did single graphs I get a combine, not single graphs.

**Comment by dannyparsons** [comment]
Yep it's not working. But when I checked single I got this command:
`InstatDataObject$graph_one_variable(data_name="survey", columns=c("Village.","Field","Size","Fert","Variety.","Yield","Fertgrp."), numeric="geom_boxplot", categorical="geom_bar", output="facets", get_area_point="single")`

So it was still passing `output = "facets"`. Have a quick to see what happens if you correct this in the dialog. I think it should be implemented in the method so changing to `output = "single"` might solve it. If not we disable this option for now.

Also, what is `get_area_point="single"`?? Not sure where this has come from.
