### ISSUE TITLE
Do we still need a variable to remain in the selector after it is added in the receiver?

### ISSUE THREAD

**Issue by Lunalo** [africanmathsinitiative/R-Instat#2902]
I want to do a two way table for example. I have two receivers; one for variable x and remaining one for the other

I decide to add x to the receiver and I realize that the variable is still in the selector. If I get into the second receiver, am allowed to add the same variable. This is the current situation which I feel is not appropriate.

So, I suggest we need to be getting rid of a variable in case it is added into the receiver.

**Comment by dannyparsons** [comment]
There are a few dialogs which do this already. Define climatic/corruption for example.

There are two cases: one where you will get an error or cause a bug if a column is in two places (define climatic) and one where you might get something that isn't sensible/appropriate (two way table).

I think we need to separate out these two cases and decide what behaviour we want in each case. My initial feeling is we should exclude columns in the first case but not in the second. Something we may think is not appropriate may be appropriate in special cases so the cautious thing is to allow it.

**Comment by Lunalo** [comment]
Thanks @dannyparsons 

What if we include a check in the TestOK for the second case?

**Comment by dannyparsons** [comment]
That's essentially the same as not allowing it, except in a more annoying way because you will be allowed to have the two receivers with the same column but then won't be able to click OK. If you can't click OK, why did we allow it in the first place? It would also be confusing if you don't realise why OK was disabled. I think we have to either prevent the receivers having the same column or just allow it.
