### ISSUE TITLE
Saving RDS Options - enhancement

### ISSUE THREAD

**Issue by lilyclements** [africanmathsinitiative/R-Instat#2936]
@africanmathsinitiative/developers I was given some feedback yesterday on exporting from RDS from Ric at the SSD:

> it looks as if I can do what I wanted with save as RDS…  It’s a bit clunky – nicer if it was possible to select a bunch of objects to save, including those that are not dataframes. But it works as a minimum.

I think this is a nice idea. I have been doing other work on R-Instat relating to climate data, and it would be good to be able to save graphs, as well as select the few data frames I want to continue on in R.

I'm not sure, however, how easy or possible this is. What do people think?

**Comment by dannyparsons** [comment]
Thanks for this. I keep meaning to write to Ric to discuss this. I think it would be really nice to be able to export an R environment where you basically have all the objects from inside the instat object but as separate variables in the environment so that you can use that in a normal R way.

I think it might be useful for me to follow up with him still on this to check what he's thinking?
