### ISSUE TITLE
Colons after chk/rdos

### ISSUE THREAD

**Issue by lilyclements** [africanmathsinitiative/R-Instat#2983]
@africanmathsinitiative/developers I have been reading a Windows guide on how to use different controls
I plan to systematically go through every dialog (just a couple of dialogs a day for the next few months) to make sure the dialog designs and code order are consistent between them. There are some small changes in these windows guides that I think we should follow that I will email on later tonight. (E.g. Labels should be "Written like this" not "Written Like This")

The biggest change is that the guides say to always have colons after a checkbox if it's leading to a control. (Similarly so for a radio button).
We haven't been doing this.

On our software:
If the checkboxes are checked, then the control is visible
If the checkbox is not checked then the control is not visible
So we never have colons on checkboxes because otherwise when it's not checked, there is just a colon to nowhere

On other Microsoft software:
If the checkboxes are checked, then the control is enabled
If the checkbox is not checked then the control is disabled
So they always have colons on checkboxes because an object is always following it, it's just not necessarily enabled.

I think, since the Windows guide suggests to do it and Visual studio is a windows software, then if a rdo or chk leads to an object, that object should always be visible and the rdo or chk should have a colon.
If the rdo or chk are not checked then the control after it should be disabled
Otherwise, the control after it should be enabled.
This can be another thing I sort when going through the dialogs.

What does everyone think about this?

**Comment by dannyparsons** [comment]
I think it's great to have documents to refer to for Windows design conventions. I imagine by default we will follow them but if we have a good reason not to then we shouldn't have to follow it.

Checkboxes leading to another control is interesting. Am I right that Microsoft never hides controls it just disables them? Then it's easy to always have a colon at the end.

I think we first need to decide if we have a good reason to hide a control instead of disabling it. I know this is done quite a lot in the old Instat. I assumed that was not so as not to clutter the main dialogs when options don't apply, but I'm just guessing. Was that the reason? On some R-Instat dialogs we do disable instead of hide. Do we have a clear distinction between the two cases?

I remember being surprised that controls could just appear out of nowhere when I first used Instat. But now I'm used to it and for example, I quite like in R-Instat the save control where if it's unchecked the long text box disappears. In Microsoft products I sometimes get confused when something is disabled whether that means it doesn't apply or that this option is fixed and I can't change it. So hiding is less ambiguous maybe.

Probably for the first release we just need to be consistent and then we can get feedback from users about whether they like the style of our designs.

**Comment by lilyclements** [comment]
So from what I can see, they dont hide the control if it's after a checkbox or radio. It's just disabled. Perhaps there's one or two which are not visible when it's not checked, but I haven't come across it. 

I would like to know too why we chose to hide the control related to the check or radio, instead of disabling them. It is consistent across the software at least!

That's a good point about the first release. We can keep it as it is for now, as long as that is the same among the whole software, and wait to hear feedback on it
