### ISSUE TITLE
Bug - Generating summaries for a random sample

### ISSUE THREAD

**Issue by jkmusyoka** [africanmathsinitiative/R-Instat#2984]
Using Describe One Variable dialog, I could not produce a number of selected summaries e.g. standard deviation, for a randomly generated data column. The action returned a bug as shown by the error message below.

![image](https://cloud.githubusercontent.com/assets/8112611/25518319/f3acbbc0-2bfb-11e7-9064-43e1cc62f6aa.png)

**Comment by lilyclements** [comment]
Okay, so I'm struggling to replicate this error. I ran this twice: once on my most recent branch, and once on a branch from 10-20 days ago (since you wrote this issue ten days ago), but both times it ran fine.

I created a column using dlgRandomSample
Then I opened dlgDescribeOneVariable and inputted my variables.
I ran the statistics you've listed above in the error, (and tried it with all the summary stats too) and it ran without an error.

Now we've reached a new issue, since you wrote this issue ten days ago and I want to ask specifics about when you ran this - such as which dataset you used, which distribution you selected, etc. however, I cannot imagine you remember these specifics.
I am sorry this wasn't replied to sooner. I will make sure I start to check issues daily.

In the meantime, I'll try different combinations out to replicate this error further!

**Comment by lilyclements** [comment]
Update: I was using the Random Sample dialog not Random Subsets and have managed to replicate this error!

**Comment by volloholic** [comment]
@lilyclements any update on this?

**Comment by lilyclements** [comment]
This is still an issue.
Interestingly, I recoded my column in my new data frame that Random Subsets created, and then that no longer produced an error. Something to look further into.

**Comment by lilyclements** [comment]
Update: The problem here is using the summary system on a data set with only one column. If we do that then we get the error outlined above

**Comment by dannyparsons** [comment]
This is because it's not using the new system yet, therefore we should not fix this now but redo this code for the next release
