### ISSUE TITLE
(Flat) Frequency Tables dialog

### ISSUE THREAD

**Issue by dannyparsons** [africanmathsinitiative/R-Instat#2997]
I would like @rdstern's view on this before someone starts it but I suggest a new dialog which uses the `flat_table` command from `sjmisc`. Possibly this goes under Describe > General > Frequency Tables?
Example:
```
efc %>%
  group_by(e16sex, e42dep) %>%
  select(c172code, n4pstu, c161sex, c175empl) %>%
  flat_table()
```
This is sort of a general version of the 1, 2, 3/4 frequency tables, although the output is only as plain text. It produces a set of multi-way tables where the last variable in select forms the columns of the table and the other variables form the rows where you get all combinations as rows.

As before there can be up to two grouping variables.

I suggest the dialog has:
1. a single receiver for the Column factor
2. a multiple receiver for the Row factors
3. two single receivers for the optional grouping factors
4. a panel of radio buttons for the margin parameter
5. an nud for the digits parameter

**Comment by dannyparsons** [comment]
An alternative to this is to use `structable` from `vcd`. 
Example:
`structable(Village. + Fertgrp. ~ Variety. + Size, survey)`

An advantage is this allows multiple row and column variables with the left and right side of the formula (`flat_table` only allows one column variable).
A disadvantage is that it will ignore value labels for columns (`flat_table` will use them)

-------------------------------------------------------------------------------------------

A second alternative is to use `ftable` from `stats`.
Example:
`ftable(addmargins(table(efc[c("c172code", "n4pstu", "c161sex", "c175empl")])), col.vars = c("n4pstu", "c161sex"))`

The advantage of this over structable is that I can add total margins in the final table by using `addmargins`. 
Other than this, it has the same advantages/disadvantages as `structable` has compared to `flat_table`.

All three produce plain text tables with slight differences in the display.

-------------------------------------------------------------------------------------------

I think our choice depends on what we consider more important. If we want to do the grouping and keep value labels we should use `flat_table`. If we want multiple column variables then `structable` or `ftable` depending on which output looks better. If we also want total margins then we should use `ftable`.

Eventually our own tables system should be able to do everything that all three of these functions can do. So it depends on what's needed in the short term. `flat_table` would be consistent with the other table dialogs although I'm not sure how annoying it would be not be able to have the total margins?

**Comment by lilyclements** [comment]
You have listed three different functions, however, from what I can see, `ftable `does what `structable ` does, but it allows margins and it's using a package we already have in R-Instat. So, is there an advantage to `structable` over `ftable`? If not then I think `structable` can be ruled out?

Between `ftable` and `flat_table` I'm not sure. Since it's only temporary, I think `ftable` as it contains the margins.
What do others think?

**Comment by dannyparsons** [comment]
I haven't looked very closely at the different functions, for example, the differences in how they display tables so I included `structable` in case someone finds an advantage of it (it has the nicest looking code as well). But probably yes we can rule it out.

**Comment by lilyclements** [comment]
I agree. I do like the `structable()` code, especially as it can take several two-way-tables to make them 3/4/morethan4-way. I can explore it further tomorrow?

**Comment by AlexSananka** [comment]
As for me I think `ftable` has an added advantage compared to the other two alternatives because of the added functionality for adding margins which really looks nice.I like how the display for ` flat_table()` looks nice though it has a weakness of not having total margins.The `structable()`  the fact it has a advantage of allowing multiple variables is good but again it lacks the functionality for adding margins(this is annoying).

So as @dannyparsons have said,it depends on what we consider as important,I think for now we can keep using `flat_table()` for consistency of our dialogs but of course `ftable` is better than all the alternatives.

**Comment by AlexSananka** [comment]
Once we have @rdstern suggestions on this then am happy taking up the task.

**Comment by lilyclements** [comment]
I looked into `structable` a little further and found that margins do work on it

e.g.
`structable(addmargins(table(efc[c("c172code", "n4pstu", "c161sex", "c175empl")])), col.vars = c("n4pstu", "c161sex"))`

This gives the same output as `ftable()`. I still prefer `ftable()` to `structable()` for the small reason that the latter doesn't add anything and is in a new package.
So, I looked into `structable` further and it's still between `ftable` and `flattable` for me. Probably leaning towards `ftable` for the same reasons as Alex.

**Comment by rdstern** [comment]
I still have to look at the alternatives, but offer the following thoughts to continue this useful discussion.
a) It is an important example of just the sort of discussion we should be having.  It shows how using R is different to using an "ordinary" statistics package.  Namely when you try to use R there always seem to be multiple ways you could proceed.  In other statistics packages these decisions have been made for you.  So, this discussion is going to be useful to include in our teaching.
b) We can assume that functions in the core R (including base, stats, utils) will be pretty good, because the R people are all pretty fierce critics.  
c) So one of our key issues in our forthcoming tables "system" is the margins.  And the **addmargins** function looks great and very general.  Just what we need.  So we will be using that function anyway.  Hence, as Lily has found, the lack of margins within structable is not a problem.
d) So I have now looked briefly through the vcd and vcdExtra packages and found the following:
d1) It has many data sets - good for examples.  Sadly most of them are in tabular/frequency form.  I would prefer more examples that were on a case basis - simple, so users wee that have first to get the frequencies.  In the 2 packages there are 11 surveys in case form, and 65 already in frequency or tabular form.
d2) It also includes a good variety of other functions that we are almost certainly going to want to use in R-Instat.  I was assuming that we would not be able to do much on the fitting of models to these sort of data - but this package could change that.
d3) So we are likely to want to add these 2 packages anyway - whether we use structable or not.
d4) It has many interesting graphs, including enhanced mosaid plots - which is a popular way to plot frequency-type data.  Sadly not ggplot, though vcdExtra mentions ggplot2 as desirable.

So, not yet an answer, except that we should not rule our structable simply because it adds an extra package.  I understand we are anyway going to have to assess how to load packages better anyway for R-Instat.  This just continues to emphasise that there are some key packages.  Not clear yet, but vcd/vcdExtra may get into that list.

**Comment by rdstern** [comment]
@maxwellfundi and @dannyparsons as we are doing more now on frequencies I think the standard way of plotting them is through mosaic plots.  There is now a new package, called ggmosaic that simply(?) adds a new geom.  The is a vignette.  It looks quite nice.  

I wonder how easy it will be to add?  It isn't urgent, but may be another almost free gift?

**Comment by dannyparsons** [comment]
It should be fairly easy to change the function later so I suggest we start by using one of the functions which allow margins.

Although we can now add margins to `structable` https://github.com/africanmathsinitiative/Instat/issues/2997#issuecomment-298567876 I don't think we can then specify the row and column variable this way. So I suggest we start by using `ftable`. If `flat_table` later adds in options for margins we can switch to that without much change to the code.

**Comment by rdstern** [comment]
We now have the ftable dialogue.  Well done.
We also have the new summary table dialogue.  And this looks great with the html.
I originally felt the ftable dialogue had a limited life, because we would overtake it with the work (still to be done) on our own frequency tables.
But I think it would be good (and easy) to "complete" it.  Even if pretty tables are then better done in a different way, this is good because it uses only functions in really basic R.

1) Could we change the dialogue to be consistent with the summary tables one.  
a) Have a single receiver, rather than two. 
b) Separately to the receiver say how many variables are to be in the columns.  Then if there are say 3 columns overall (Village, Variety, FertGrp) in that order, with number of column variables =3 then automatically the first 2 columns are row variables and the last one is the column variable.
c) This is different to the current dialogue where the columns are given first.  
d) Now the really important addition - we need to add percentages.
This is (I think) the prop.table command, which is in baseR
So add the terms in the dialogue for this.  
The command is prop.table(x, margin =NULL) for overall proportions, which we can multiply by 100 to give percentages.  x is the table of counts.
Or prop.table(x,margin=1) for percentages of the first factor (Village in the example above).
I think this is just what we want?

If the dialogue is like the old Instat then there is a box for the results with radio buttons and the following options:
1) Counts
2) Overall Percentages
3) Percentages of Variable: (Then single receiver with just the columns that were selected in the main receiver - I hope that is possible now?)
I am not sure whether it may be easy to have more than one statistic at the same time, i.e. check-boxes, rather than radio buttons.  If so, this messes with the receiver of a single factor.  In that case I suggest we could have a final option - all!  This may give the tables in turn, but in the future it could be good to be able to have counts and percentages together - as we do with the sjplot frequences case.

This would then move in the dialogues to become Describe > Specific > Frequencies.  

We may then have a second dialogue with the html option, or perhaps these tables can then become html ones.

**Comment by dannyparsons** [comment]
Interesting idea, and needs some discussion before implementing - particularly on whether editing this will take longer than doing the "proper" frequencies dialog through the calculation system.
