### ISSUE TITLE
Problems with R-Instat 10 May Version - mainly graphs and labelled stuff

### ISSUE THREAD

**Issue by rdstern** [africanmathsinitiative/R-Instat#3060]
1.	From survey data-set (where Village, etc comes as character) **Describe > One variable > Frequencies** still does not like a character variable.  Two variable is OK.

2.	I think this part of the issue could be for the sjplot people, rather than for us.  (Interesting though and illustrates the new level of detail I think we should start using).  It is not just bugs, but things that are not quite right, and are inconsistent between 2 ways of doing things in R-Instat.  Both are valid and I suggest we try both.  Here is my example.  I could show more of what I mean in a demonstration.)  
a.	Do a stacked 2-way bar chart with the survey data with Village and Variety using **Describe > 2 Variables > Frequencies**.  I like the way it is labelled in the graph.  
b.	Do the same with **Describe > Specific > Bar chart**.  It seems quite complicated to get it **stacked**.  Can Mike/Patrick do that easily?
c.	But when you get it stacked, then what I like is the legend, which is different to the sjplot in that the bars at the bottom in the graph are also at the bottom in the legend.  I don’t think there is an option for this in the sjplot?  If not, then it would be good to consider this as an issue in the sjplot github? (It was a change in the latest ggplot update that we are using.)

3.	I made all 3 Village, Variety, FertGrp columns into factors and then tried the new **Prepare > Column: Factor > View Labels** with those 3 columns in that order
a.	It allows all columns, not just factor columns, into the receiver.  Do we want this?
b.	With those columns the heading is odd, giving the dplyr R command.
c.	The final factor had 3 extra zeros added.  (This may be because I made the fertgroup first into a Variate, so it automatically added factor labels.  (Possibly when we finalise the issues of factors with levels and labels this will cease to be a problem.)

here is the heading from the output:
"Data frame: dplyr::select(.data = survey_temp, c(Village., Variety., Fertgrp., 
Name	Label	Values	Value Labels	Freq."

4. I think this may be known?
The new **Describe > View Graph** dialogue - what a great feature! I tried with a combined graph from the **Describe > One Variable > Graphics**  and of course it didn't like this.  I thought it wouldn't.  Can we capture this issue earlier, i.e either not put anything we can't graph into the selector, or indicate, in the selector something about the type of graph (as we might indicate the type of column - SPSS does) and then not allow OK with anything where it won't work?  Or check when we press OK, so we give a message earlier?

5. For the column matedata window please could the horizontal "more" bar be shorter initially, so (by default) multiple data frames are visible.

**Comment by stevenndungu** [comment]
Quick response to point 3:
a) We all column data types allowed since when you import a data set  from SPSS with columns that have labels, R/R-Instat understands the variables as numeric variables. The same happens when you import a data set that has labels already coded eg `efc` data set in sjmsc package in R-Instat illustrates this clearly. It saves the user the pain of converting all the factor columns to be of factor data type first.   

b) Yes the heading is quite odd -  this is an issue with `view_df` function. It does not have title parameter and hence it is coded to take the value assigned to the parameter as the title of the output. Well, it is meant to show the whole data set such that the title remains to be the name of the data set eg
`library(sjPlot)
library(sjmisc)
data(efc)
view_df(efc)`
which gives `Data frame: efc` as the title of the output. Changing the structure in order to extract specific columns leads to the issue of it taking the exact expression and pasting it to be title in a similar manner as the case above

**Comment by dannyparsons** [comment]
On 3. I think we do need to make some decisions about factors and labelled variables.
For example, efc have only labelled columns. Yes we can nicely convert them to factors without losing information. However, do we want to require users to convert them to factor before they can use them in dialogs, mainly sjPlot related functions such as view_df and 1/2/3 way frequencies. Steven makes the point that converting would be annoying, especially when the functions work on them without converting. Of course, many other won't and they are not treated as "categorical" by R-Instat unless converted.

**Comment by dannyparsons** [comment]
1. @stevenndungu @AlexSananka add `ignore.strings = FALSE` to the one-way frequencies function and this will work.
2. a & b @rdstern Stacked could be an option on the main dialog for Bar Chart? If so @maxwellfundi can implement this.
2. c They use ggplot I think so it could be they haven't updated to the latest version yet? @rdstern Could you write them a message about this?
4. This relates to other dialogs where we want to display only ggplot graphs for example. I can look into this.
5. I tried to do something on this before and it didn't work well so I will investigate again, possibly need  to understand the grid better to do it.

**Comment by mmumbo** [comment]
_a.	Do a stacked 2-way bar chart with the survey data with Village and Variety using Describe > 2 Variables > Frequencies. I like the way it is labelled in the graph._ 

- The graph looks nice except on the labels should be moved closer to the bars, i.e the label for longer bar in NANDA goes outside the graph.

_b.	Do the same with Describe > Specific > Bar chart. It seems quite complicated to get it stacked. Can Mike/Patrick do that easily?_ Yes, this woks well with us. I think if the labels are added in the bard it will be easy to use at a glance.

**Comment by rdstern** [comment]
Just to respond on the converting of columns to factors in R-Instat - when this is not required in SPSS and could be annoying for the SPSS types.

In the documentation on sjplot (e.g. sjp.xtab it makes a distinction between the first and second arguments, i.e. "sjp.xtab(x, grp, type =...).  So he is thinking that the first argument is x (and could be anything, while the second is a "grp", i.e. for us a factor.  Similarly in the 3 or 4-way he mentions "Both sjplot() and sjtab() support grouped data frames."

We know what groups are - they are factor columns.  So I am now very happy that the first receiver in the frequiences dialogues can be anything, while the others must be factors.  And (to me) any slight inconvenience in defining factor columns is more than outweighed by the simplicity and clarity of the data selector.
If I were able to make a change then it would be to be able to get to the window and hence change the type of a column without closing a dialogue.  But that might open a "can or worms".

**Comment by rdstern** [comment]
I now looked at the updated version.
a) Importing from Excel seems to be fixed.  Phew.
b) I found a curious issue with **Describe > One Variable > Frequencies.**  Please see if you find the same
1) I used our **survey** data from the library (Instat Intro Guide).  
2) So there are 3 character columns.  Village, Variety and FertGrp.
3) It now reads them correctly
4) It displays the results for the first one of them (Village) fine
5) But the variety is all combined together, as though it is a single "level".  So is FertGrp.  Odd!
6) I made Variety into a factor and then it is fine.
7) I then tried with Describe > Two Variables > Frequencies and here FertGrp is fine - i.e. there are 3 categories.  So I guess there could be a problem in the code for the One Variable > Frequencies.
This may be a tricky bug to find?

**Comment by dannyparsons** [comment]
This is very strange - I assume a bug in `sjPlot`. Even when I put in Village last, it's still the only one that displays correctly. So not sure what's special about it. I will investigate further.

**Comment by stevenndungu** [comment]
I have finally identified the problem and how to solve it easily. 
The problem was that the function could not be able to automatically group the string values in character vectors (string variables) based on their similarity (where similarity is estimated by the stringdist-package - from help). And this follows after we have allowed character vectors / string variables to be tabulated by setting the parameter `ignore.strings=F`. 

Now to ensure that all character variables are grouped accordingly in the generated frequency tables, we have to set  the parameters `ignore.strings` and `auto.grp.strings`  to  `False` which is a perfect solution.

This helps in solving more errors I encountered while using different data frames just to find out how different variables would behave. For Instance if I converted efc  variables to character I would get this error
`Error in if (m[cnt, j] <= maxdist && m[i, cnt] <= maxdist) foundBetterToken <- FALSE : 
  missing value where TRUE/FALSE needed`
Using diamonds 
`Error: cannot allocate vector of size 21.7 Gb`

All this are sorted now!

**Comment by dannyparsons** [comment]
Thanks Steven and well done for solving this bug and taking the time to figure it out by testing many data sets. Nicely explained as well, this makes sense now.

So from this I can see we might want to make use of max.string.dist in the dialog. It fits with the ideas in our string dialogs. Probably not for now but maybe something to consider for the sub dialog in future @rdstern?
