### ISSUE TITLE
Boxplots for climatic display of daily data on a monthly/annual basis

### ISSUE THREAD

**Issue by rdstern** [africanmathsinitiative/R-Instat#3076]
This will be a dialogue (perhaps adapted in multiple places in the climatic menu.
The background is that the standard package for quality control of (daily) climatic data (rainfall and max and min temperatures - RCLIMDEX has boxplots as one of its methods.  We will not incorporate RCLIMDEX into R-Instat (unlike RCLIMDEX-PCIC for the indices), because it is programmed in such a way that it will be much quicker and better for us to provide the same tools ourselves.

Boxplots is an example.  In RCLIMDEX they can be produced either by year, or by month (but not both).  When we used the Describe > Specific > Boxplots with year (a factor) as the x variable and Month as the facet, the participants from Lesotho Met were very impressed.  
We did this separately for maxtemp and mintemp.  It is also useful for rainfall, but then just for non-zero values, and with the boxplot width proportional to the number of non-zero days in the month.

Of course the different months are fairly arbitrary as one follows another.  But it is a **natural grouping factor for the quality control**, because the data are usually prepared on monthly sheets and then entered.  So errors (e.g. entering mintemp, instead of maxtemp) are often on a monthly basis.

So how will this fit into our graphics strategy for our set of dialogues.  Well we have **general, specific and tailored**. 

David's example of climatic graphs for the daily data is "tailored", because it automatically is using multiple geoms.  here we think (so far) that most of what we need in these graphs is the boxplot dialogue, but with fields sort of automatically completed in the instances of the dialogue that are in the the climatic menu.  So this is an example of a specific graph.  If we find that we need to add a geom, e.g. a rugplot etc, then it becomes tailored.

I can see where the "overall" dialogue will go - and it can be called Boxplots.  It is in the Climatic > Quality Control > Boxplot.  It might indeed be a violin plot, so the general dialogue is fine here.

**Comment by maxwellfundi** [comment]
@rdstern  I want to take on this task now and implement this dialog as earlier discussed.

**Comment by rdstern** [comment]
Great.  This is also issue #3523 so perhaps these issues can be combined?
There I also suggest the controls and structure of the dialogue.

**Comment by maxwellfundi** [comment]
I have moved this here to combine these two issues #3523 and #3076

Climatic > Check data > Boxplots conceptualised and constructed. Should be easy, because it is just ordinary boxplots with the climatic factors largely specified. (Important, because it will be visible and clearly more flexible than existing climatic QC procedures.)

I hope this will be easy to construct.

The top buttons and the whole left-hand side of the dialogue are taken from the existing Describe > Specific > Boxplot dialogue.
The right-hand side top part looks like the top part of all the other climatic dialogues, e.g. Climatic > Prepare > Start of the rains.
a) Station
b) Date
c) Year
d) Month
e) Data
f) Check box with field More Data for a second column of data
Then possibly a group box below with label Layout.
There are 5 options here. The first 2 refer to a single plot and the second set of 2 refer to the facets.

X-Variable This has the Year column as the default.
Checkbox (default unchecked) 2nd X-Variable. If checked, then default is the 2nd data column.
Checkbox (default unchecked) If checked, then default is Month
Checkbox (default unchecked). If checked, then Default is Station.
Checkbox which is only enabled when both facet variables are checked. It has the label Margins. If checked, then the facets include the margins.
Now there must be something in the Data variable for OK to be enabled. Default is rainfall.

If nothing in the layout has any contents, then this gives a single boxplot of the data column (rare but possible)
If Station is blank and Year is in the layout for the x-variable, then this is a single boxplot of the data by year.
The one bit of coding is that if it is not horizontal then the x-variable label should be vertical.
If there is a second data column (e.g. Tmax and Tmin), then this should work with either the second variable given second, or first. (Only 2 data columns are permitted here.)
Then we have facets. The default is to produce the facets by month.
If there were a second facet variable, then this would usually be the station, with the rows now being months and the columns being stations.
We would then try switching these elements round - except I don't see how the 2 data columns can be in the facets.

**Comment by maxwellfundi** [comment]
@dannyparsons  this can now be closed.

**Comment by rdstern** [comment]
I am trying this dialogue "in anger" for the first time.  Overall it is good.  The list is quite long, but I think they are all simple.
1. The default in this dialogue is RAIN.  That's OK, though it is usually more useful for TMAX or TMIN.  One of those might be better.
2. But when I returned (after using Tmax), it had put RAIN back in.  Not what I wanted!  It should remember this control.
3. I also think the default should be to check the "Vertical x tick markers".  
4. And the setting of that field is not remembered yet either.  Perhaps therefore check the code for the other fields too.
5. I suggest changing the label to "Vertical X labels".  It is actually Vertical X tick mark labels, but that seems too long for here.
6. I managed to get the vertical labels once for the years.  Now I have set it again, but it seems to ignore the field setting and makes the labels horizontal.
7. The x-axis label is given as as.factor(x=JYear).  That's a nasty looking label!  I suggest we don't have an x-axis label.
8. I think we should not have the months and ID as the default facets.  It makes the plots very small.  The default could be to have the year as the x-axis and the ID as the facets.  If there is only one station, then the default is no facets.  
9. I managed to ask for the margin with just one factor and it gave an error.  However, I would like to have the margin for a single factor.  If I have the months as a facet, then the margin is the whole year.
