### ISSUE TITLE
ucrDistribution Extreme Value Error

### ISSUE THREAD

**Issue by stevenndungu** [africanmathsinitiative/R-Instat#3109]
When I choose on Extreme Value Distribution option. The dialogue bug.
It is a problem with ucrDistribution control code on Extreme value, @Lunalo this is something to fix while still updating the control.

This is the error message given:
![image](https://cloud.githubusercontent.com/assets/20383893/26310935/363270bc-3f0b-11e7-9549-8c2149bb26f7.png)

**Comment by Lunalo** [comment]
@stevenndungu  It seems shape is an unused argument  which means it might be not one of the parameters . I will look into that tomorrow.

**Comment by Lunalo** [comment]
@africanmathsinitiative/developers 

I have managed to fix the resseting and and  unusual indexing of the parameters list.

This will be ready by tomorrow to be reviewd

**Comment by lilyclements** [comment]
@Lunalo @stevenndungu so I looked into this and what I think is happening is that the `revd` function is being masked by another package we have loaded.

If you run
`Rand1 <- extRemes::revd(scale=1, loc=0, n=36, shape=0)`
on R-Instat then it works

So, once the package names are added into the ucrDistributions then this should fix?
@Lunalo since you're on the ucrDists perhaps could you fix this?

**Comment by volloholic** [comment]
is this fixed?

**Comment by Lunalo** [comment]
This is now fixed
