### ISSUE TITLE
dlgImportDataset - Needs updating

### ISSUE THREAD

**Issue by lilyclements** [africanmathsinitiative/R-Instat#3381]
dlgImportDataset needs to be updated to the new system still

**Comment by dannyparsons** [comment]
This has now been updated, thanks @stevenndungu for doing most of the work on this.

I had to merge it quickly because I made a fix to a more major on the same branch. This means the import dialog has a few bugs at the moment.

Please test it out and report any issues here. I will continue testing and improving in the morning.

Note that now the preview is only generated for csv and Excel files - this is because other imports do not allow importing a fixed number of rows and we were therefore importing the whole data just for the preview.

Know current issues:
Changing options does not update the preview (but hopefully does update the function which is run)
Changing the lines to preview does not change the preview

**Comment by dannyparsons** [comment]
Issues above now fixed and dialog updated. Please continue to test with all the awkward datasets you have. Open a new issue if any bugs appear.
