### ISSUE TITLE
Hide data frames

### ISSUE THREAD

**Issue by rdstern** [africanmathsinitiative/R-Instat#3392]
I use the frequency tables dialogue and save the data in a data frame.
If I ask for percentages it also produces an extra data frame with the overall count in it.  I don't need that data frame to be visible.  I wasn't asking for margins.

**Comment by dannyparsons** [comment]
The overall value was needed to do the percentages which is why it saves in a data frame. We need to get the hidden data frames working to do this.

**Comment by dannyparsons** [comment]
Should you be able to hide all the data frames? I think not, because I don't see a use of it, and it's going to mean much more changes to code.
If yes, what should you see in the grid, because there's no sheets?

On the sheets right click we have:
Hide - directly hides the selected data frame
Unhide - goes to Hide/Show dialog where you can set the hidden data frames

Should there be an Unhide All as well? Would be nice but not sure we need 3 items just for hiding on the right click.

**Comment by dannyparsons** [comment]
@africanmathsinitiative/developers could someone enable the Hide Data Frames item in Prepare? I didn't do it in case someone was working on frmMain.

**Comment by shadrackkibet** [comment]
Enabled at #4096
