### ISSUE TITLE
logical column types

### ISSUE THREAD

**Issue by dannyparsons** [africanmathsinitiative/R-Instat#3398]
We can produce logical columns e.g. from the calculator. But we don't have convert to logical. Should we?
Here's some R behaviour:
```
as.logical("a")
# NA
as.logical(1)
# TRUE
as.logical(0)
# FALSE
as.logical(4653)
# TRUE
```

**Comment by rdstern** [comment]
Does this link to the discussion on types of column in the data selector?
I suggest we should and usually it will be automatic.  If it is added generally, then it only applies if there are just 2 levels.  Do we restrict it to 0-1 columns, or do we add the labels if the levels are otherwise?
For now I suggest we a) can cope with logical columns that are provided for us automatically, e.g. by a logical calculation or when we input a file that has logical columns.
b) We can make a column of type logical if the values are zero and one.  
In R is anything that is not zero taken as TRUE?  If so, then perhaps we can make any (numeric) column into a logical column, by keeping the values as the labels?

**Comment by volloholic** [comment]
I think there could be great value in a convert to logical but we need to be really careful not to lose data unnecessarily.  That is longer term. Immediately we need to think about dialogues working well with logical columns and possible enabling a simple conversion.

**Comment by dannyparsons** [comment]
The first thing I would like to implement on this is logical columns being recognised as "categorical" or "numeric" in dialogs which will allow them.

**Comment by dannyparsons** [comment]
@shadrackkibet @maxwellfundi can you add a convert to logical option in the convert dialog and on the data and column metadata right click menus? Should be simple as the R method now accepts logical #3943

**Comment by shadrackkibet** [comment]
@dannyparsons  i think you should modify this to cater for non-numeric and columns with numbers other than 0 and 1. Or give message to the user when they try this.

**Comment by dannyparsons** [comment]
At the moment it should give an error when used on non-numeric or non-0,1 columns.

**Comment by rdstern** [comment]
Agreed.  We can already duplicate a column and make it come after the existing column.  If there is a column that could be made into logical, e.g. numerical where 0 might be FALSE and anything else would be  TRUE (but we lose information) then we could offer this option.  But for now, we just stick with the simple situation.

**Comment by rdstern** [comment]
What happens now (or we would like to happen) with the Prepare > Column: Calculate > Calculations dialogue?  There is a Logical keyboard.  Does this (or should this) produce logical columns?  Can that be detected from the calculation?
And can we cope with logical columns nicely in the Filter?

**Comment by dannyparsons** [comment]
Through the calculator you could do `as.logical` for example, and you can do that on any column. You can always produce logical columns e.g. Size > 10 and this works fine.
In the filter you have the same options as for numeric columns currently, so you can do == TRUE or == 1 and this should work fine.

**Comment by dannyparsons** [comment]
We now have an convert to logical on right click and convert dialog. Only 0,1 columns can be converted currently with an error message if other columns are tried.
