### ISSUE TITLE
import .DAT files

### ISSUE THREAD

**Issue by dannyparsons** [africanmathsinitiative/R-Instat#3433]
Currently cannot import .DAT files as not supported by `rio`. If `rio` do not add this before 0.9 (from my suggestion) then we should do this ourselves using `data.table::fread`.

**Comment by dannyparsons** [comment]
@stevenndungu I now have a fix for this using `format = "txt"`. I can show you were to add this when you get there.

**Comment by stevenndungu** [comment]
@dannyparsons  looking at this now

**Comment by dannyparsons** [comment]
fixed by #3463

**Comment by Patowhiz** [comment]
@dannyparsons is there a reason why `format = "csv"` was not used for `dat` files. I checked and found that it `rio` reads them fine if you force it to read the files as `csv`. This issue now relates to issue #6431 and PR #6432.
@rdstern would like the `csv` options enabled for the `dat` files but I need to understand why `txt` was the preferred option.

**Comment by rdstern** [comment]
@Patowhiz I may just be repeating your question.  In the particular example here, the files are actually comma separated.  I wouldn't have a problem with txt, but I just want to be able to have some flexibility e.g. in missing values.  I get nothing just now, as you see above.

**Comment by Patowhiz** [comment]
@rdstern yes. And I would prefer them read as csv if there is no special reason for reading the as txt. Because the implementation will be simple. 
We have 3 options for reading text files, the 2 out of 3 use different package for reading the files. So reading dat as text files would force me to  also design the code in a way that it considers the 3 options.

@rdstern after looking at the dat files that you have sent me, they are separated by white spaces.

![data file](https://user-images.githubusercontent.com/21179007/116378615-2968da00-a7c7-11eb-9f88-f323ebaff2c2.PNG)

**Comment by Patowhiz** [comment]
@rdstern @dannyparsons I also noticed, the .dat file is not included in the file open dialog. Is there any special reason for this? See screenshot below.
![file types](https://user-images.githubusercontent.com/21179007/116378765-456c7b80-a7c7-11eb-85dc-5fd62d1b02c1.png)

**Comment by Patowhiz** [comment]
As agreed by @dannyparsons I have implemented this as text file.
