### ISSUE TITLE
Importing Excel files

### ISSUE THREAD

**Issue by rdstern** [africanmathsinitiative/R-Instat#3453]
[hhModule2CLEAN.zip](https://github.com/africanmathsinitiative/R-Instat/files/1086818/hhModule2CLEAN.zip)

I have an issue importing Excel files - I think.  I have called it a bug, but it may be that I am requesting an enhancement.
These are 2 different Excel files.  They have different names, but the sheet names are the same.  Currently we seem to ignore the file name for Excel and just keep the sheet name.  Also the names overwrite without warning (I think).  
I am not sure of the complete solution, but I would like to be warned at least if a data frame is going to be overwritten.  I think I would also like to keep (somewhere) the file name and not just the sheet name, but I am less sure about that.

To help playing with the import, one of these files if an xls file and the other is xlsx.

**Comment by dannyparsons** [comment]
Slightly changed functionality now so that if you don't select a sheet, the default name is the file name. Once you select a sheet, that becomes the new name. Is that useful?
Doesn't quite keep the file name as you want, maybe we should add a label for the new dataframe and this could include the Excel file name since we want to keep the name short but the label could be longer?

**Comment by dannyparsons** [comment]
Is this functionality good now?

**Comment by rdstern** [comment]
I think it is OK now, but will check
