### ISSUE TITLE
New data type for climatic data?

### ISSUE THREAD

**Issue by rdstern** [africanmathsinitiative/R-Instat#3475]
I like the improvements in the File > Open from Library.  I agree that we should now consistently have the new-style radio buttons.

However that's not the issue.  Just a question really.
I then use the climatic guide data sets and open the Dodoma data.  The last 3 columns are now of a new type, namely (l).  What is that?  

They are temperature and sunshine hours, so simply numeric.
There could be a problem in finding their type, because these data only start in 1958, while the rainfall starts in 1935.  So the first 8000 values (or so) of the 29,000 are missing.  That's life!

**Comment by lilyclements** [comment]
I noticed this when I did a start of rains that my data type was (l) once.
We were having an issue with numeric-types which have been made by a calculation being used in a calculator? Is this to do with solving that?
@dannyparsons what is this data type (l)?

**Comment by dannyparsons** [comment]
Great spot! Two changes affected this:
1. I added (l) for logical columns recently so that's why (l) now appears for logical columns.
Why are these columns coming in a logical? Because of the excel import we are using:
read_excel has a parameter:
```
guess_max
Maximum number of data rows to use for guessing column types.
```
The default is 1000 so because in these columns the first 1000 values are missing values, it can't detect the type and defaults to logical I guess.

We could avoid this by either setting our own default for `guess_max,` which is bigger (or infinite) or by using the other excel import which is `openxlsx::read.xlsx()`. I'm not sure what the better option is at this point.

**Comment by rdstern** [comment]
Can we also say what type we default to, if we can't detect the real type.  I would then suggest (c) because anything can be a (c)?

**Comment by dannyparsons** [comment]
No we can't choose the default type. Character would be nice. I guess it just gets the type of the 1000 NAs, which is logical.

Of course, `openxlsx::read.xlsx` is only for `xlsx`, so we need `read_excel` at least for `xls` files.

**Comment by rdstern** [comment]
OK, then it is just a "feature".  It won't be so common.
I don't want to make the number too large, or it might slow down the reading of the file.  Of course it could be in our Tools > Options so anyone who has this issue regularly can do something about it.  Not bad to be able to have a place to discuss this sort of issue of the type of column.

**Comment by dannyparsons** [comment]
Well it needs to be at least 10,000 for this file. But actually it's a fairly negligible difference in speed even when I made it infinite. I tried with Dodoma and the wide Sudan data. So I think we can just put Inf in since this will always give the correct types.
