### ISSUE TITLE
Start of the rains

### ISSUE THREAD

**Issue by rdstern** [africanmathsinitiative/R-Instat#3499]
I mention Lily, but not seriously, because she is on leave.

The saving doesn't yet work well.  The column is called start_of_rains.  You can change the name in the dialogue, but nothing changes in the name in the output.  So it always overwrites.
It isn't a serious bug, because you can rename the output column and then it is fine.

It is a good example where it will be good to add a variate label once we can.  With that in mind I suggest the column name can just be start1, start2, etc.

The label can then include the definition.  
It is an example (which may be common) where I am not sure we need to be able to edit the label in the dialogue.  It could be automatic from the definition of the start.  Whether there need be a field in the dialogue is for discussion

**Comment by lilyclements** [comment]
At the moment this problem That the column name doesn't change is fixed on a pull request.

We can't do a prefix yet because we aren't using a ucrSave. This is because we are creating a column for a new data frame so this hasn't yet been implemented in the UcrSave.

Changing to start instead of start_of_rains can be fixed when I next get "proper" internet (curewntly using my phone).
