### ISSUE TITLE
Dates in year. 

### ISSUE THREAD

**Issue by volloholic** [africanmathsinitiative/R-Instat#3512]
Be able to display the results (where they are day numbers) as dates in the year, e.g. 04-12 or 4-Dec.  There is discussion of this issue on Stack Overflow.  One way seems to be as an ordered factor, though that might limit the summaries of the columns.  Could we alternatively have it as a labelled column and be able to display the labels, even though it remains numeric?  (If it gets awkward, then we could duplicate the column, so we show the information in one column numerically and have the next column as the ordered factor.

**Comment by dannyparsons** [comment]
It's easy to set the break points for a numeric axis and then to apply labels to these points, which can be characters.
Another option is to make a pseudo date column by adding an arbitrary year (2000) and then using the formatting options for date columns i.e. scale_y_date. This is what I did for the inventory plot, which was easy because it is contained within a method.
```
curr_data[["common_date"]] <- as.Date(paste0("2000-", curr_data[[doy_col]]), "%Y-%j")
ggplot2::scale_y_date(name = "Date", date_breaks = "2 month", labels = function(x) format(x, "%e %b"))
```
This is quite nice. But in general, the first option might be better if we want dialogs to construct this code.

**Comment by dannyparsons** [comment]
This relates to #3513. Other non graph displays would be tables. Do we want this as an option in the grid as well, or elsewhere?

**Comment by dannyparsons** [comment]
solution is being discussed here https://github.com/africanmathsinitiative/R-Instat/issues/4130#issuecomment-514671106
