### ISSUE TITLE
Graphs to be able to display with the dates in year.  

### ISSUE THREAD

**Issue by volloholic** [africanmathsinitiative/R-Instat#3513]
Graphs to be able to display with the dates in year.  This is important for PICSA – and we can do it in the old Instat.  It is more important for this aspect, than in the spreadsheet.

**Comment by dannyparsons** [comment]
It's easy to set the break points for a numeric axis and then to apply labels to these points, which can be characters.
Another option is to make a pseudo date column by adding an arbitrary year (2000) and then using the formatting options for date columns i.e. scale_y_date. This is what I did for the inventory plot, which was easy because it is contained within a method.
```
curr_data[["common_date"]] <- as.Date(paste0("2000-", curr_data[[doy_col]]), "%Y-%j")
ggplot2::scale_y_date(name = "Date", date_breaks = "2 month", labels = function(x) format(x, "%e %b"))
```
This is quite nice. But in general, the first option might be better if we want dialogs to construct this code.

**Comment by Ogik99** [comment]
#5266

**Comment by dannyparsons** [comment]
solution is being discussed here https://github.com/africanmathsinitiative/R-Instat/issues/4130#issuecomment-514671106
