### ISSUE TITLE
New dialog: Duplicates

### ISSUE THREAD

**Issue by volloholic** [africanmathsinitiative/R-Instat#3522]
Prepare > Check Data > Duplicates constructed.  (Important, because useful in climatic quality control.)

**Comment by AlexSananka** [comment]
Can this be elaborated further so that there is a clear picture of what the dialog does and how it might look like so that I can start working on it?

**Comment by rdstern** [comment]
Great.  I would like this one urgently.
It will be a dialogue that could be got working first very simply.  Then I am sure we will want enhancements.
For now I suggest as follows:
a) Our new radio buttons at the top with 2 options, namely **Data Frame** and **Selected Variables**.
b) If Data frame then the main selector just has the data frames.  Otherwise it is our usual selector with the data frame and the variables.
c) If there is the whole data frame then there is no receiver.  Otherwise there is a multiple receiver.  It needs some columns for OK to be activated.
d) It is going (for now) to produce a new column, so there is a control for the name of the new column.  Ideally it would have a default name such as **dup1** .
e) There is an ordinary radio button saying **All duplicate cases** and **Duplicates only** and **Index number of duplicates**.  For now disable the third option.
f) Add tool-tips to the options in e).  All cases are given as being duplicate rows, The first occurrence is not indicated, but further instances are considered duplicates.  Any duplicates are given their index number.  
g) That's all for now in the dialogue.  I am sure there will be more later.
Now the R behind.

Base R has a command **duplicated** and that is the second option.  The package questionr (we have just added) has a command duplicated2, which is the first option.
For later Sam Dumble (I think there is an issue) has written a function for the third option.

**Comment by AlexSananka** [comment]
Great am going to start working on this.
