### ISSUE TITLE
Climatic Wind roses

### ISSUE THREAD

**Issue by volloholic** [africanmathsinitiative/R-Instat#3524]
Check on wind roses and possibly improve.

**Comment by dannyparsons** [comment]
@maxwellfundi can you update us on what this dialog is/isn't doing at the moment?

**Comment by maxwellfundi** [comment]
@rdstern  I was checking where the wind rose was moved and I thought this was a duplication or could these be two separate dialogs and if so, which would be the current dialog we have?

![image](https://user-images.githubusercontent.com/9798689/29353438-cd0d2eaa-8272-11e7-8026-93feffa77100.png)

**Comment by rdstern** [comment]
There should only be one.  The wind rose is a plot so just keep the one called wind rose.
[Seth circular 2 June.pdf](https://github.com/africanmathsinitiative/R-Instat/files/1227529/Seth.circular.2.June.pdf)

I attach Seth's project on circular, which shows some examples of the wind roses.  I am hoping there will soon be a facility for facets so we can have multiple wind roses in the same plot.  I realise that may have to wait a bit.

**Comment by maxwellfundi** [comment]
Great thanks. 

@rdstern  we have the facets included in the main dialog which is a parameter to the function we are currently using.

**Comment by rdstern** [comment]
Great!

**Comment by dannyparsons** [comment]
Great if this is easy, otherwise other climatic tasks should take priority and this can be for 0.4.2

**Comment by maxwellfundi** [comment]
@rdstern the sub dialog looks like this. 

![image](https://user-images.githubusercontent.com/9798689/29357745-4644d83c-8281-11e7-827c-b608454b57cc.png)

last time we said we might want to add other things in the future. Is there anything urgent for the next release needed for this?

**Comment by rdstern** [comment]
This looks good.
I agree with Danny that it would be great to get a version of this dialogue working in 4.1, but only if it is very easy.  Otherwise it can be 4.2.  (If 4.2 then perhaps the dialogue and sub-dialogue could be accessible - as for Prepare Keys > Comments, but with a message that it isn't enabled yet.)
I am happy with those options on the sub-dialogue.  Are there defaults?  If not, then perhaps 8 for the number of directions.  Can there be any number or is it limited?
zero is OK for the default calm for now.  Perhaps 4 cut points.  Does it work if we don't give limits?

**Comment by maxwellfundi** [comment]
We have a functional version of this dialog already.
