### ISSUE TITLE
Enhancing the R busy popup

### ISSUE THREAD

**Issue by rdstern** [africanmathsinitiative/R-Instat#3554]
I like this feature.  I also like the fact we can have a variety of messages in the popup.  But:
1. **On my machine it is popping up too often.**  And quite often it is just for a second and then it is gone.  Also it sometimes pups up multiple times in a single dialogue command (which (I think is multiple R commands).  I suggest the default be set higher - say 5 seconds.  I think Danny suggests 4 seconds.  It is currently 2 seconds.
2. Add this to the **Tools > Options** menu.  If easy, then could we have this frequency in the Options menu in version 4.0.  There we could set the frequency (in seconds) or even turn it off.  If that isn't quick to do, then perhaps it could change to be in Version 4.1.

**Comment by dannyparsons** [comment]
@maxwellfundi Can you do 2.? Similar options to the auto saving you already added i.e. checkbox and nud:
"Show waiting dialog when command takes longer than [ ] seconds to complete".

**Comment by volloholic** [comment]
2. should obviously be done by version 0.4.0 and is easy. However I believe that 4 is too long to go without as a default. I think even 2 seconds is a long time to not have any response. I can see how once you know it's coming it's annoying to be flashing up and down but the default delay should be too short rather than too long, you can then lengthen it if you are getting it too often.

**Comment by dannyparsons** [comment]
Oops, just released the current delay is 0.5 seconds, not 2! That would explain it coming up too much at the moment. I'll set it to 2 seconds now by default. That should be more acceptable for this version.
