### ISSUE TITLE
dlgTwoVariableFit and sdgSimpleRegOptions

### ISSUE THREAD

**Issue by lilyclements** [africanmathsinitiative/R-Instat#3592]
This is looking good. I have three minor points

1. If I select inverse.gaussian, this calls `family=inverse.gaussian()`. Is this intentional to have empty brackets? Similarly for Binomial, Quasibinomial, etc.

2. If I press "reset", it resets the checkbox for the ucrSave but not the contents of the input box.

3. On the sub dialog (sdgSimpleRegOptions) there is a few points:
a) If I go to Graphics > Model. If the checkbox is unchecked then everything is disabled. However, on another tab (Graphics > Residuals) on this sub, if unchecked then everything is invisible. I think they should both have that if unchecked, everything should be invisible.
b) On Graphics > Model on the sub, if I uncheck the checkbox, only one thing is enabled. Is this meant to be enabled or is everything meant to be disabled?
c) On Graphics > Residuals, when unchecked the groupbox is visible but the contents are empty. I think if the contents of a group box are invisible, then the groupbox itself should be too.

@stevenndungu @AlexSananka

**Comment by dannyparsons** [comment]
1. Yes because it is a function and if you select a link it will call `family=inverse.gaussian(link = "1/mu^2")` for example.

3.a) Yes agree should be invisible @stevenndungu @AlexSananka
  b) I think that's a bug
  c) I had some issue with the visibility of a group box when it was linked to a control so I left it like that but agree it's better if the groupbox hides too. Can anyone remember how we did this on other dialogs?

@stevenndungu @AlexSananka can you work on 2 & 3. Ask if anything takes too long.

**Comment by lilyclements** [comment]
3c) why doesn't it work to do say: ucrPnl.AddToLinkedControls(Groupbox)?

**Comment by dannyparsons** [comment]
Because the group box controls the visibility of the controls inside. So when the control sets the visibility of the group box it can override what we want it to do.

**Comment by AlexSananka** [comment]
I am fixing this issues

**Comment by AlexSananka** [comment]
This should be closed now.
