### ISSUE TITLE
Count in Factor (dae::fac.nested) gives error with missing values

### ISSUE THREAD

**Issue by dannyparsons** [africanmathsinitiative/R-Instat#3596]
Bug in `dae::fac.nested`, possibly write to author, modify the function ourselves or find another package to do this that works with missing values

**Comment by rdstern** [comment]
I'm inclined to write to begin with.  (I am happy to do so if you prefer.)  
I checked a bit in the dae package and it looks reasonably useful for a variety of functions in the future.  I am surprised it isn't in our set of packages for data sets, because it has some.  I wonder if they are in an unconventional way?
Usually (in simple use) we won't have missing values in factor columns.  But in our surveys we will.  
Ideally it would treat the NA as another factor level.  Do we want to mention that we plan to include tagged missing soon!  That would give more "levels"!

**Comment by dannyparsons** [comment]
Resolved by David's modification of the function which is now included in the `dae` package.
