### ISSUE TITLE
Problem with recovery log

### ISSUE THREAD

**Issue by rdstern** [africanmathsinitiative/R-Instat#3600]
I think there may be a problem with your recovery log "system".

I describe what happened to me, in more detail, below.  But I think the main problem is that I had an initial error.  Then I continued and later crashed out of R-Instat.
I then restarted and chose to run the log.  It gave me a long message and (I assume) was stuck because of the initial error.  I assume you can't have errors in a log file and expect it to continue.
I was OK to then carry on, but it soon crashed on an aspect that is usually OK. I assume caused by the running of the recovery log.
The initial error was as follows:
a) I loaded diamonds and did a one variable graph of the 9 first variables.  I then tried the **Count in Factor** dialogue - which worked fine.  (I don't think this step is relevant.)
b) I loaded the survey data as well.  I then duplicated the Village column.  I did the **Prepare > Generate > Count in Factor** on the initial Village column.  Then I inserted an NA into the middle of the second Village column.  True enough I got an error when running the Count in Factor dialogue.
c) But R-Instat seemed OK, so I continued for quite a time.  It then crashed out (inexplicably to me) in the help for the diamonds - on **File > Open from Library**.  This was after other help from this dialogue, but I can't repeat this problem now.
d) So I restarted and chose to run the log file.  It seemed to run OK till the **Count in factor** problem.  I quite understand that.  But then I continued, though it seems in a mess now and it quickly crashed me out.  So I restarted and ignored the recovery options!

**Comment by dannyparsons** [comment]
@volloholic should we run each line separately for the recovery log? What should we do for 0.4?

**Comment by dannyparsons** [comment]
This now runs one line at a time, meaning it doesn't stop at the first line that gives an error and should run everything you did before. 
Error messages are also hidden so they don't appear when an error message appeared before.
The waiting dialog might pop up several times because each line is separate now, which might be a bit annoying. That could also be turned off if we wanted and maybe have a special "rerunning log" message box for the whole time.
More work needed to make it smoother generally but should be an improvement now as well.
