### ISSUE TITLE
Column metadata tab keeps changing

### ISSUE THREAD

**Issue by rdstern** [africanmathsinitiative/R-Instat#3614]
I am working with the column metadata open and multiple data frames.
The column metadata seems very keen to always show me the last tab.  In my case this is the data frame called wm (for women).  I am working on the household data (dataframe hh).  I am changing columns with labels into factors.  I have (sorry) changed the number of visible columns to 100 to see all the columns.  

My procedure is to look at the metadata to see which columns have labels, and then right-click in the data to make that column into a factor.  Whenever I do that there is great (and to my mind unnecessary) activity in the metadata, which changes the tab back to the wm data frame.

**Comment by dannyparsons** [comment]
I believe I have fixed this. I used two data sets and when I changed something in either in the data view or the metadata view, the metadata view now stays on the same sheet. I've also corrected the issue of metadata columns sometimes reordering when it refreshes. The order is now: Name, Label and then everything else in alphabetical order. Also, the max labels to display for labeled columns is now 4.

When you change a global option this is slightly different as it may refresh everything, for example, if you change max columns all sheets need to be refreshed. In this case it will go to the last sheet in both grids. This is because a sheet is made the current sheet when it is refreshed. We could modify this behaviour if we wanted.
