### ISSUE TITLE
Delete rows

### ISSUE THREAD

**Issue by rdstern** [africanmathsinitiative/R-Instat#3724]
This was a serious bug - at least for me!
Deleting rows when there is a filter works for the first row (or perhaps set of rows - didn't test that).  When you delete further rows they delete the row ignoring the filter.

Example: I had a large data set of climatic data, 33,000 rows, starting in 1896.  I filtered to show just 3 years from 2003.  Then I deleted one day from 2003.  That was OK.  It was row 23400.
I then deleted a further row.  It didn't appear to delete.  So I repeated it.  Then I looked at the command that had been generated.  It had deleted row 135, which was from 1896.  As I had tried it twice I had lost 2 days from that year.

(And of course we don't have an undelete!)

**Comment by dannyparsons** [comment]
Excellent bug to find! Only that sequence of events would cause this but quite a serious general issue comes out.

Issue:
- Deleting a row on the (unfiltered) data caused the data frame to become a `tibble` (because we use `dplyr` to delete rows).
- `tibble`s do not preserve row names, even when subsetting. So when you applied the filter you might have noticed that the row names were 1 to `n` instead of their original row names in the unfiltered data.
- The grid assumes row names displayed are as in unfiltered data. So since filtered data showed wrong row names => wrong rows were deleted.

It gets complicated because the `dplyr` method is the only way to delete rows without losing attributes somewhere. So instead I've added a check when setting the data to convert `tibble`s back to data frames. This is needed anyway because `tibble`s appear in other places e.g. column summaries produce `tibble`s. This change should only make things more consistent but look out for obscure unintended consequences.

@volloholic @rdstern Would be good to consider `tibble`s generally and at least be clear on our position with them. They are the `tidyverse` "new" data frames (still `data.frame` class so a special case of `data.frame`) and have some advantages. I think the row names issue means they are not compatible with R-Instat at the moment though.
