### ISSUE TITLE
Transform Text BUG!

### ISSUE THREAD

**Issue by shadrackkibet** [africanmathsinitiative/R-Instat#3880]
I was testing this dialog, unfortunately i found  a bug .This is what i did:
I clicked on words at the top radiobuttons and then selected a variable to the receiver then on options groupbox i checked on the checkbox  ("or Column" ) to display a receiver then  select a variable to the receiver. On changing to another radiobutton at the top then it breaks at ucrNud. I don't understand why this happens, perhaps someone can look into this?

**Comment by dannyparsons** [comment]
> it breaks at ucrNud

Can you be more specific? What was the error? Is this an error that was caught by the system or did it crash completely? If so, which line caused the crash and did you look at the values of any of the objects? Did you notice anything unexpected from that?

These are some of the details I expect a developer to mention when reporting a bug as compared to a user.

**Comment by AlexSananka** [comment]
can this be closed now?

**Comment by dannyparsons** [comment]
@shadrackkibet you will need to specify the details of the error here for others to be able to help.

**Comment by shadrackkibet** [comment]
These are the two lines causing a crush in this dialog.
`ucrNudFirstWord.SetRCode(clsWordsFunction, bReset)`
`ucrNudLastWord.SetRCode(clsWordsFunction, bReset)`

**Comment by dannyparsons** [comment]
What are the error messages? Can you look at variables causing the crash using watches with @maxwellfundi?

**Comment by shadrackkibet** [comment]
sure, will like to know how to use watches as well. will look into this with @maxwellfundi .

**Comment by Patowhiz** [comment]
@shadrackkibet @dannyparsons @maxwellfundi   just looked into the form. After going through the same procedure as @shadrackkibet  did, I got an error at line 157,inside the subroutine of `SetToValue(objTemp As Object)` of class ucrNud.vb. The error is an `InvalidCastException` .  It seems like during runtime there is an invalid conversion of **RFunction** to String, probably because the code implicitly tries to cast **RFunction** to the **String**.  Am still trying to understand why the code is the way it is. @shadrackkibet are you still working on this?

**Comment by Patowhiz** [comment]
Well upon investigating the issue further. The same error gets thrown every time I check the checkbox of the First word option or the Last word option (the or Column) .  @africanmathsinitiative/developers could someone explain to me the output am to expect from the words first word option or the last word option from the end users perspective.

**Comment by maxwellfundi** [comment]
Great that we have discussed. I think the bug in the ucrNud would be good to be fixed because it might be appearing somewhere else.

**Comment by maxwellfundi** [comment]
@Patowhiz  @dannyparsons  @shadrackkibet  I think the reason why this bugs is because we are trying to convert Rcodestructure to a string. Am not sure if that is appropriate on the ucrCore `GetValueToSet()` which is a parameter of `SetToValue()` on the ucrNud

**Comment by Patowhiz** [comment]
@shadrackkibet I agree with your assessment 

> The bug actually is because we have a parameter that takes values as an R function and as String other times. The issue needs to be fixed by passing the parameter manually.

`Private Sub SetRCodeForControls(bReset As Boolean)
        bRCodeSet = False
        ucrPnlPad.AddAdditionalCodeParameterPair(clsPadFunction, clsNewRParameter:=New RParameter("side", 2), iAdditionalPairNo:=1)

        ucrReceiverTransformText.SetRCode(ucrBase.clsRsyntax.clsBaseFunction, bReset)
        ucrNewColName.SetRCode(ucrBase.clsRsyntax.clsBaseFunction, bReset)
        ucrPnlOperation.SetRCode(ucrBase.clsRsyntax.clsBaseFunction, bReset)
        ucrInputTo.SetRCode(clsConvertFunction, bReset)
        ucrInputPad.SetRCode(clsPadFunction, bReset)
        ucrNudWidth.SetRCode(clsPadFunction, bReset)
        ucrPnlPad.SetRCode(clsTrimFunction, bReset)
        ucrChkFirstOr.SetRCode(clsWordsFunction, bReset)
        ucrChkLastOr.SetRCode(clsWordsFunction, bReset)
        ucrReceiverFirstWord.SetRCode(clsWordsFunction, bReset)
        ucrReceiverLastWord.SetRCode(clsWordsFunction, bReset)
        ucrNudFirstWord.SetRCode(clsWordsFunction, bReset)
        ucrNudLastWord.SetRCode(clsWordsFunction, bReset)
        ucrInputSeparator.SetRCode(clsWordsFunction, bReset)
        ucrNudFrom.SetRCode(clsSubstringFunction, bReset)
        ucrNudTo.SetRCode(clsSubstringFunction, bReset)

        bRCodeSet = True
        DialogSize()
    End Sub`

Before using the a control like  `ucrReceiverFirstWord` the `ucrNudFirstWord` gets its value as a string from the its parameter. But after using the  `ucrReceiverFirstWord` the parameter returned is a  `clsArgumentCodeStructure` which is an `RCodeStructure`. Hence upon comparison the subroutine `SetToValue(objTemp As Object)` throws an error when line 155 gets executed. The method Decimal.Parse(<expression as string>,<result>) throws an `InvalidCastException `because the `clsArgumentCodeStructure` can't be implicitly converted to string.


returns a string as

**Comment by Patowhiz** [comment]
@dannyparsons @shadrackkibet @maxwellfundi I would like to know what parameter type do controls of type `ucrNud` return. I can see they don't have the` SetParameterIsRFunction()` . For instance I cant do `ucrNud.SetParameterIsRFunction()`.

**Comment by dannyparsons** [comment]
I think you've identified the problem here exactly. The ucrNud can't set its value from an RCodeStructure. And you are right about the cause being a parameter which switched between RFunction and String.
The ucrNud can only handle decimal values. The choice of parameter type for receivers is related to how columns are used in R code. For ucrNud there's no choice.
I agree that handling the parameter causing this bug manually is the way to solve this now.

**Comment by shadrackkibet** [comment]
This can now be closed.

**Comment by Patowhiz** [comment]
@dannyparsons , @shadrackkibet suggested that this form was unfinished. He suggested substring option needs to include the or column just like the word option. Currently you can only use the `ucrNuds ` to get the substring text transformation. However the user can't use the fields of the data frame to get substrings. Should we leave it at that or proceed to enabling that option to a new issue?

**Comment by shadrackkibet** [comment]
I suggest we have a separate issue for that then we can have a millstone set for it.

**Comment by dannyparsons** [comment]
Yes, please make a separate issue for this. Thanks for bringing this up.

**Comment by Patowhiz** [comment]
Done
