### ISSUE TITLE
NetCDF importing

### ISSUE THREAD

**Issue by rdstern** [africanmathsinitiative/R-Instat#3912]
So far I find this to be very impressive.
1. I started with ENACTS data 13 megabytes.  It gave me no information about the data at all.  Said there was nothing about X or Y.  But it imported fine - great.  The time variable went from 8404 upwards to about 21000.  I assume that there was nothing in the file to say what that meant?
2. The one aspect I would have liked (if possible) would be to know how many records this would be in the data frame.  Is this possible - could be a later enhancement if so, i.e. not necessarily for the workshop.
3. The first option says "Only include data variables".  I don't understand the "Only" here?  What do I get more if I untick it.
4. Then I tried that Tamale data.  Imported fine.  This gave me the option to choose a subset.  I tried a value out of range and it stopped me.  I can see there is a single lat and a single long value.  Would it be possible to show me how many values there are in each dimension?  (Again, if agreed, it doesn't have to be implemented for this version.)
5. The E/Net cdf data.cami file gave an error and then just read one row.  
6. The Darwin data seems odd.  It gives a warning before reading and the single variable is identical for all values.  Is this being read correctly?
7. The e-net cdf ncdata file shows the sort of function we could use in our generation of date variables.  It has a column which is 1 to 31 and says these are months from 1983-00, so 1 is Jan 1983, 13 is Jan 1984, etc.  (Clearly not for now!)

**Comment by dannyparsons** [comment]
> I started with ENACTS data 13 megabytes. It gave me no information about the data at all. Said there was nothing about X or Y. But it imported fine - great. The time variable went from 8404 upwards to about 21000. I assume that there was nothing in the file to say what that meant?

Was this the header text or the subsetting options? Sometimes it can't detect the dimensions if the metadata there and therefore can't allow subsetting.

> The one aspect I would have liked (if possible) would be to know how many records this would be in the data frame. Is this possible - could be a later enhancement if so, i.e. not necessarily for the workshop.

It's possible, and I think not too much computation needed so could be sensible on the dialog.

> The first option says "Only include data variables". I don't understand the "Only" here? What do I get more if I untick it.

Maybe not a great name., There are "data" variables and "boundary" variables, where the boundary variables are essentially just metadata about the dimensions. By default these are not imported and only the actual "data" variables are. Currently there's some issues with setting the data frames correctly with the boundary variables so this option is disabled at the moment.

> Then I tried that Tamale data. Imported fine. This gave me the option to choose a subset. I tried a value out of range and it stopped me. I can see there is a single lat and a single long value. Would it be possible to show me how many values there are in each dimension? (Again, if agreed, it doesn't have to be implemented for this version.)

Yes this is easy since it can be read directly from the header. Slightly more complex (for the time) if this should change when the subset options are changed.

There are definitely some issues with the non EUMETSAT data files which is a combination of the R functions we use and our own importing process. After the workshop it will be good to resolve all of these.
