### ISSUE TITLE
Instat Data Library, adding more packages and data

### ISSUE THREAD

**Issue by rdstern** [africanmathsinitiative/R-Instat#3977]
The library could usefully include the datasets from the robustbase package.  There may also be other packages added recently that could also be added.
[Dodoma.zip](https://github.com/africanmathsinitiative/R-Instat/files/1340098/Dodoma.zip)
Here is the Dodoma file again.  I was pleased to see it is in the climatic library twice, once as an rds file and also in the climatic library.
I leave it up to you, whether you include this one instead of the existing one.  The attached one has just the columns that come with the data, but with month and ordered factor.  The one that was there already has also the date, etc.
I like this one because it is closer to what the usual climatic data will look like.  Once we can get factor levels for the months in the "right" order I would even be happy to have this as a character - the original - but I am not sure that will be soon.

**Comment by dannyparsons** [comment]
The robustbase package issue, and other packages, is now resolved.

I think the extra dodoma file must be your own copy that you put in the library because it's not in the general library. But it would be good to have a nice RDS version of Dodoma in the library as well, with correct month and date columns and pre defined as climatic maybe, so that is a dataset ready for analysis straight away.
