### ISSUE TITLE
Procurement >Define corruption Outputs

### ISSUE THREAD

**Issue by shadrackkibet** [africanmathsinitiative/R-Instat#4011]
Do we need to change the naming of this dialog  to Define Procurement Outputs?  and also change  Calculate corruption Risk Index to Calculate Procurement Risk Index?

**Comment by dannyparsons** [comment]
Good questions. The Corruption Risks is still correct because this is a specific name of the index which is measuring corruption risks. I think the Corruption Outputs is also still right because this is defining outputs from corruption. In general the menu is Procurement because it's for any procurement data but specific dialogs can be more specific about corruption.
