### ISSUE TITLE
Tooltip implemented in receiver?

### ISSUE THREAD

**Issue by rdstern** [africanmathsinitiative/R-Instat#4030]
I was deleting some data frames.  I needed to be careful here, because the names were long and started the same.  I was really pleased that I could see the full name in the data selector.  But then I could not see that same full name in the receiver.  Could that be implemented?

**Comment by dannyparsons** [comment]
I've added the item name as the tooltip for the multiple receiver. It's not as easy to have the full column information, label and type, in the receiver, so I haven't done that. Is this useful still? 
Also, what about the single receiver? I didn't think the label would be as useful there and might look funny since you can always scroll the text box?

**Comment by rdstern** [comment]
Great.  Sounds fine.
