### ISSUE TITLE
Entering NA into the grid

### ISSUE THREAD

**Issue by rdstern** [africanmathsinitiative/R-Instat#4110]
We had to replace a single value in the grid by NA.  (This was the rainfall total in a year, and the number of rain days, where all was missing.  It would not have calculated the mean, but the total for that year was zero.)

It looked as though typing NA is not allowed.  It said the column was numeric or integer.  I think mwhat is happening is that it is <space>NA.  Can we remove spaces at the start of an entry, at least in non-character columns - perhaps in all?

I have said this is a bug.  It is close if not.

**Comment by shadrackkibet** [comment]
@rdstern  what exactly do you mean in this Bug? I loaded western kenya Rain data set and tried replacing a value with NA and it works fine for me.Furthermore , there is no space at the start an entry in my case.Please clarify this error!

**Comment by rdstern** [comment]
OK, use File > New to make a new data set and then generate a new column with the values 1 to 10.
Go to the 1 and delete it (gently), i.e. use double-click to be able to edit in the cell and then back-space and then type NA.  It gives an error.  If you mark the whole cell and backspace then you are OK.
Or try typing <space>NA, which is effectively the same thing.

![image](https://user-images.githubusercontent.com/11226469/32216241-6014a1b2-be1c-11e7-9e8a-d2555a0d44fa.png)

**Comment by dannyparsons** [comment]
Interesting. The space is there because in R all columns are formatted as character to display in the grid, and numeric columns are padded with spaces if it has less figures than the largest value in the column. This is meant to give nice alignment when you have a mono-spacing font. However we don't in our grid so it's not particularly useful and is causing this bug. I suggest we could:

1. stop this formatting from R so that we don't pad with spaces in cells.

but also,

2. From the front end, trim blank spaces around a value when the user is typing in, unless there's any need to want to have spaces at the beginning or end of a cell value? It doesn't seem sensible to do this at all, so are we ok to prevent this?

Either would solve the problem but I could see we might want to do both.

3. In the error message, put quotes around the invalid value so there's a better chance to see the mistake. So `Invalid value: " NA"`. This seems sensible to do as well and in general in error message.

**Comment by rdstern** [comment]
I'd be happy with 3 - at least for now, i.e. " NA".  That's instructive.

**Comment by dannyparsons** [comment]
2. is also easy so I would start with that too.

**Comment by dannyparsons** [comment]
2 and 3 now implemented which solves this issue.
