### ISSUE TITLE
Rerunning code from the log window

### ISSUE THREAD

**Issue by rdstern** [africanmathsinitiative/R-Instat#4116]
This is another suggestion from David!

The log window should **not** become editable.

But you could mark a selection and right-click and run it.

Or you could run from the start to the cursor.

Again I assume you right-click and have the same options on running as for the script window.  David says you know what they are?

If you run from the beginning it would first close the Instat object and would have to warn that it is doing this.

**Comment by dannyparsons** [comment]
There are two things we want here:

1. Rerun a selection of text from the log window. This could just be by highlighting and right clicking. There should be a very clear warning before running that this may give errors if a selection is incomplete or if the data has changed.

2. Rerun the log from the beginning up to a certain point. This is sort of like an "undo" or a "restore backup" because it will effectively take you back to a previous place. I think that rerunning will automatically remove the old data and work everything out, but check. Again, there should be a warning that you will lose any changes you've made up to now and should save your data before doing this if you want to keep it. I'm not sure how the user would do this. Possibly a right click option of "rerun log up to here". Need to be careful to include complete lines etc.

In both cases the code should be similar to what is done in `StartREngine()` of the `RLink` when initial code is run. It's important to run each line separately 

``` VB.NET
        For Each strLine As String In strScript.Split(Environment.NewLine)
            If strLine.Trim(vbLf).Count > 0 Then
                RunScript(strScript:=strLine.Trim(vbLf), iCallType:=iCallType, strComment:=strComment, bSeparateThread:=bSeparateThread, bSilent:=True)
            End If
            strComment = ""
        Next
```

`iCallType` is an issue because we now don't know what it should be. The only sensible choice default is `iCallType = 0`. This means graphs will come in the R viewer only. We could try to be more clever like, if the line contains **get_graphs** then we use **iCallType = 3**. Might we worth checking. But 0 is safest.
`strComment` could be a sensible default string for now, something like "code rerun from log"
`bSeparateThread` probably needs to be `False` so that graphs don't disappear, unless we get them to display nicely in the output window.
These are details that can easily be changed so I'm not so worried about getting them right at first.

Since this code will probably be used for 1. and 2. I suggest putting this into a small method in the RLink.
