### ISSUE TITLE
Restore data from backup

### ISSUE THREAD

**Issue by dannyparsons** [africanmathsinitiative/R-Instat#4184]
Original idea from #3959

This is a new dialog on the File menu, not sure where yet.

When R-Instat crashes, you have the option of opening the AutoSaveRecovery dialog, and one of the options there is to save/load the backup data file.

It would be useful to access the backup data at any time, not just after a crash.

So this new dialog will allow you to see the current backup data files (currently at most one but could be more in future) and then allow you to select one to save it somewhere as a file or load it directly into R-Instat.
The loading would replace the currently open data so a big warning is needed about saving your current file before doing this.

This will not be a standard dialog because it is not running R code in the same way. So it won't need our usual base buttons.

I suggest it has:

- A listbox showing the current backup data files (could be 0 so you can't do anything). This will have two columns for the filename and the Date/Time it was saved. In future there could be more than one which is why a listbox.
- Two radio buttons to choose whether you are saving the backup or loading the backup into R-Instat.
- If you are saving: A button, label and textbox appears to choose where to save a selected backup. This can be very similar to what is currently on the AutoSaveRecovery dialog.
- If you are loading: A button appears to load the selected data into R-Instat (replacing the current data). A big warning needed before clicking this button.
- A Help and Cancel button at the bottom of the dialog as well.

This is just a suggestion to start, so it's probably good to do the design first and then share with others for feedback.

**Comment by Patowhiz** [comment]
![dlg2](https://user-images.githubusercontent.com/21179007/33014442-5b44b230-cdf8-11e7-8527-70a7a856b0ae.JPG)
@africanmathsinitiative/developers more suggestions here.
@dannyparsons I have followed the suggestions of @rdstern and the designs below show how am planning to achieve this functionality. Am not using the usual base buttons and I have chose to use the listview instead of the listbox. 

The default selected tab will depend on whether there is an existing opened data frame. If there is one then the Backup Data tab will be selected otherwise the Previous backups tab will be the one selected.

The backup operation will maintain a registry of file locations used in the case of a user initiated backup. This will help in displaying the system default backups and the user backups. The find button will help the user find a backup from an unregistered location e.g a flashdisk ,network etc .

Am still thinking about the schedule tab. Though its supposed to give the user the freedom to choose backup time frequency. I know it has not been mentioned so probably I could ignore this.

Looking forward to suggestions.

![dlg1](https://user-images.githubusercontent.com/21179007/33014458-6d144962-cdf8-11e7-8b1d-2ae485522488.JPG)
![dlg2](https://user-images.githubusercontent.com/21179007/33014459-6db042ea-cdf8-11e7-83f6-ebf279f457de.JPG)

**Comment by Patowhiz** [comment]
@dannyparsons @rdstern . On the functionality. From issue #3959 , I can see the periodic backups are 5 minutes apart. Am proposing to extend the functionality a bit to also include event driven changes. For instance a major change in the selected data frame should warrant a threaded background backup which will be saved with the name of the change. So the user would know exactly upto which point the data frame had been operated on.

**Comment by dannyparsons** [comment]
The Previous Backup part is looking nice. Although I'm not sure what Find is for?

I'm not sure what the Backup Data tab is for? Is it to save a backup to somewhere else on my machine? If so, then I'd like this to be an option when I see the previous backups. If it is to backup the current opened data, then this is just the same as saving the file, so I don't think we need to replicate that here.

The scheduling of backup time can already be done through the Options dialog so I don't think it is needed here as well.

So I think what you have on the Previous Backup tab is mostly what's needed so we can probably avoid tabs. If we do have different views we would usually do this through tabbed radio buttons.

**Comment by dannyparsons** [comment]
The idea of linking the backup saving to major events is a nice idea as well. I'd like to keep that separate from work on this dialog since they can be done independently of each other. But it would be nice to have a separate issue on making the backing up more intelligent.

**Comment by Patowhiz** [comment]
@dannyparsons great . I had not noticed that in the options dialog. So i'll proceed with the previous backups as a standalone without the tabs since all the other functionalities are catered for in other places.
Am removing the find backup as well since this seems to be catered for in the open file .

**Comment by Patowhiz** [comment]
@dannyparsons  I can see the autobackup scheduling time is in the dataview tab in the options dialog. Wouldn't be nice to have it in this dialogue so that we can centralise the backing up functionality?

**Comment by dannyparsons** [comment]
I want to keep all the options together in the Options dialog. But possibly the Data View tab isn't the most appropriate for this option. We could have it on a different tab if the backup options become more.
I wouldn't mind having a button on the Backup dialog to open the Options dialog to be able to edit backup options, but I'm not keen on repeating the option setting in the Backup dialog.

**Comment by Patowhiz** [comment]
Okay. So the design for the form changes to this

![final](https://user-images.githubusercontent.com/21179007/33020089-f57c3fac-ce0d-11e7-90fc-0bff28c89b2a.JPG)

**Comment by Patowhiz** [comment]
Ignore that last statement of "user saved backup". The statement will just be" Previous backup versions come from periodic system backups"

**Comment by dannyparsons** [comment]
This looks good. But still missing the saving of a backup I mentioned above:

> Two radio buttons to choose whether you are saving the backup or loading the backup into R-Instat.

> If you are saving: A button, label and textbox appears to choose where to save a selected backup. This can be very similar to what is currently on the AutoSaveRecovery dialog.

**Comment by Patowhiz** [comment]
I'll include the save button

**Comment by Patowhiz** [comment]
@dannyparsons which sounds better in this case for the open button , is it "open" or "load" once the backup is selected.

**Comment by dannyparsons** [comment]
I would say Load probably.

**Comment by rdstern** [comment]
I like this work progressing.  But I see this as a blunt tool and second best as an undo facility.  I have been finding that the backing up is taking a long time on my machine and so don't want it done too often.  In the longer term I would also like us to discuss a proper undo as written in #4185.

But that shouldn't start this year.  There is so much else to do.

**Comment by maxwellfundi** [comment]
@Patowhiz  I believe this can be closed now.
