### ISSUE TITLE
Date columns with non daily data

### ISSUE THREAD

**Issue by dannyparsons** [africanmathsinitiative/R-Instat#4233]
It's useful to have a Date type column even with monthly or yearly data e.g. to plot time series. At the moment our Make Date dialog requires year, month and day columns. 
But monthly data often only have Year and Month columns and I can't do time series line/point plots without a continuous variable like a Date. So I want to create a Date column and just take a fixed day for each month e.g. 1. I can do this in two ways:
1. Create a Day column in the calculator of all 1s and then use that in the Make Date dialog
2. Use the calculator to create: `as.Date(paste(Year, Month, 1), format = "%Y %m %d))`

But neither of these I like explaining to users, especially beginners, as it's not obvious or very logical.

Our Make Date dialog should be able to do this. I suggest we allow Year, Month and Day to also be fixed numbers as well as columns. Then I could flexibly make a Date with only some of these columns.

**Comment by shadrackkibet** [comment]
Two small issues i have observed.

- When i am on **Year-Month-Day** radio button the  **format** comboboxes reset only when i click reset twice.
- Still on the third option **Year-Month-Day**, when  i click on the value radio button(month) the combobox changes to numeric and is disabled which is okay because the the input only allows you to input numeric values, i wonder if we might allow typing of characters and allow other options in future?. Another issue here is that when i reset the combobox is still disabled and my option has changed to column radio button as shown below.
![image](https://user-images.githubusercontent.com/26301973/43828560-8c35505e-9b05-11e8-92c9-a6a29af33d5f.png)

Otherwise the dialog works properly for both previous and added functionalities.
