### ISSUE TITLE
Improving the contrasts dialogue

### ISSUE THREAD

**Issue by dannyparsons** [africanmathsinitiative/R-Instat#4356]
This first topic is low priority, but other improvements, mentioned below, are straightforward.

With the default contrasts for a factor the output for coefficients when modelling is clear:

```
Coefficients:
             Estimate Std. Error t value Pr(>|t|)    
(Intercept)    59.600      3.288  18.127  < 2e-16 ***
Variety.OLD   -14.159      3.654  -3.875  0.00048 ***
Variety.TRAD  -29.600      3.700  -7.999 3.15e-09 ***
---
```

But after setting my own contrasts using the Contrasts dialog the default names for the new contrasts are 1 and 2, so I have to remember what they mean.

```
Coefficients:
            Estimate Std. Error t value Pr(>|t|)    
(Intercept)  45.0137     1.3431  33.514  < 2e-16 ***
Variety.1    14.5863     2.3254   6.273 4.33e-07 ***
Variety.2     0.4275     1.6285   0.262    0.795    
---
```
I've found a way of giving names to the contrasts in R. So we could add this to the Contrasts dialog? Currently we fill a grid to set the Contrasts, so we could allow editing the column names of the grid to name the contrasts, but I don't think this will be obvious to the user. Any other suggestions? Is it important to be able to name them at all?

**Comment by rdstern** [comment]
The above is one of a number of improvements to the Prepare > Column: Factor > Contrasts dialogue that would be useful.  Also:
a) With the default of the Treatment/Control could there be a Base label and up-down that goes from 1 up to the number of levels of the factor.  It is only visible when there is a factor chosen, and for this option.
b) The grid is visible all the time and does not resize with different factors chosen.  Currently it only need be visible for the user defined option, so the dialogue could be smaller for the other options.  
c) In the grid, there is the bar to expand vertically all the time, and no corresponding horizontal control even when needed.
d) The current label on User Defined is  `Define a Contrast:` should change to `Define Contrasts:`. 
e) In the User Defined it would be good to be able to choose the names as asked above.
f) Ideally there would be an option for the others (not User Defined) to be able to see the contrasts.  This may be reasonably easy, because they are shown in the Factor Data Frame dialogue.  This would not stay open when you change options in the dialogue.  So it could perhaps be a checkbox called Show Contrasts that is shown when ticked, and is automatically unticked when another option is chosen, or another factor or another base level, i.e. it closes when anything else is chosen.

This list is another example where pull requests may be merged when only some of the above have been implemented.  I hope @shadrackkibet could suggest who might take this up.

**Comment by anastasia-mbithe** [comment]
@shadrackkibet @dannyparsons @rdstern,
Am confused that this dialog is only giving the codes and nothing more. I have tried the different contrasts set and am getting the codes only 
![Screenshot (62)](https://user-images.githubusercontent.com/89011047/154494249-51d17a8a-2270-4a0a-ad61-334e80cef087.png)

And since the function is customized, adding a new parameter i.e. 'include_contrasts' as in the Factor DataFrame dialog is also, introducing an error, I think it should be added in the back end for it to function.

![Screenshot (63)](https://user-images.githubusercontent.com/89011047/154495129-393a5f48-71de-4be8-8626-9f598803b0aa.png)
