### ISSUE TITLE
An error on Climatic

### ISSUE THREAD

**Issue by ZIRANA11** [africanmathsinitiative/R-Instat#4378]
This error comes up every time I try to get the start of the rains, end of the season and the spells.
![error](https://user-images.githubusercontent.com/28622260/35516932-1f841616-051e-11e8-856d-f1a07705df8b.png)

**Comment by rdstern** [comment]
Thanks for reporting this.  It is all good, because it indicates what we could now try to do.

It worked fine for me, but the steps I needed to go through are different to the old Instat.  
So 2 things need to be done.
1) These steps will have to be included in the description of the tasks in e-SIAC.
2) Some users will still do what you have done, and the next steps are not clear from the error message above.  So we need to give a more helpful set of messages when there are problems.

In future it will also be good if your description of an error can give more of the background steps of what you did leading up to that error.  Then someone else can try to repeat the process.  So here is what I did:

1) I used **File > Open from Library** and opened samaru56.rds.
2) I found it had 3 columns with **Year, DOY and Rain**.  There were 20454 rows of data.
3) I used the **Climatic > Dates > Make Date** dialogue to make a column called Date1 from the Year and DOY (I had to set the DOY option to 366).
4) I used the **Climatic > Define Climatic data** to define these columns as climatic columns.
5) Then I used the **Start of the rains** with an earliest start date of 92 and just got the column of dates for a simple definition - more than 20mm in 2 days.
6) That gave me the dates as numbers.  I would still like to have them as dates in the year (as well), which is one of the improvements we need in the climatic dialogues.

**Comment by dannyparsons** [comment]
This issue was caused by the Date column not defining a valid key. The data was originally in wide format so they stacked it. It then had duplicate/missing dates which meant the climatic dialogs cannot create the Date as a key. We discussed how to resolve this in various ways e.g. filtering out wrong dates/using duplicates and the team now understand this issue.
I think it could be common enough to have it's own climatic guide. How to prepare wide data for analysis in R-Instat.

The other thing we discussed from this is that when you define climatic data it should try to create a key, either Date or Station + Date if provided. This could then tell you if you don't have unique identifies as a warning and possible prevent some functionality until this is corrected.
