### ISSUE TITLE
Adding stat_summary as a "geom"

### ISSUE THREAD

**Issue by dannyparsons** [africanmathsinitiative/R-Instat#4420]
There's a lot of `stat_???` functions in `ggplot2` which we will eventually want to implement. However, I think `stat_summary` is extremely useful even if this is the only one we have to start. 

It is coming up a lot with the agriculture type data for example, adding means or medians as points/lines on top of a plot. This is possible through our general graphics by using layers with different data frames but stat_summary does this very easily.

I believe the structure fits in to our structure of geoms in that it has aesthetics and other parameters. So I think it can just be added like a geom. @maxwellfundi can you investigate this by trying to add this as a "geom" in R-Instat? We might just want to add another property to our structure to say whether something is a "geom" or a "stat".

**Comment by rdstern** [comment]
Here is a clear discussion of stat v geom from [stack overflow](https://stackoverflow.com/questions/38775661/what-is-the-difference-between-geoms-and-stats-in-ggplot2).  It emphasises that the **stat** is needed particularly for plots of raw data like line, or point - which we use enough.  The other stat that is mentioned is identity, which is needed for bar and pie charts etc, where the data have already been summarised.

"geoms stand for "geometric objects." These are the core elements that you see on the plot, object like points, lines, areas, curves.

stats stand for "statistical transformations." These objects summarize the data in different ways such as counting observations, creating a loess line that best fits the data, or adding a confidence interval to the loess line.

As geoms are the "core" of the plot, these are required objects. On the other hand, stats are not required to produce a plot, but can greatly enhance the final plot.

As @eipi10 notes in the comments, these distinctions are somewhat conceptual as the majority of geoms undergo some statistical transformation prior to being plotted. These include geom_bar, geom_smooth, and geom_quantile. Some common exceptions where the data is presented in more or less "raw" form are geom_point and geom_line and the less commonly used geom_rug."

**Comment by dannyparsons** [comment]
@bethanclarke this is not needed by any particular deadline but something really good to have. It should be just as easy as adding a geom. Could you look into adding this when you get time?

**Comment by dannyparsons** [comment]
I've changed the milestone if geoms are being added now. This could be important for climatic? Because it makes it much easier to add summary values to a graph without having to create the summaries first and using multiple data frames in a plot

**Comment by maxwellfundi** [comment]
@dannyparsons  I see this has changed milestone and i can have a look at it this week. Hopefully by next release.

**Comment by maxwellfundi** [comment]
@dannyparsons  I think we can add this as a geom- I have been looking at it and it could work in two ways

1. As a geom  where you have no geom function, but the geom required is passed in as a parameter of the `stat_summary` like this 

`ggplot() +  stat_summary(data=mtcars, mapping= aes(cyl, mpg),fun.y = "mean", colour = "red", size = 2, geom = "line")`

or 
`ggplot(data=mtcars, mapping= aes(cyl, mpg)) +  stat_summary(fun.y = "mean", colour = "red", size = 2, geom = "line")`

This produces a graph of a line conecting the mean points from `fun.y = "mean"` to produce the below graph 

![image](https://user-images.githubusercontent.com/9798689/39696690-22e85d00-51f7-11e8-87ee-74c4c3a8a26b.png)

2. We can have it as an additional layer, where we we have our geom function, as well as our stat_summary with the geom parameter which produces a layer on top of the current geom function 

`ggplot(data=mtcars, mapping= aes(cyl, mpg)) + geom_line() +  stat_summary(fun.y = "mean", colour = "red", size = 2, geom = "line")`

and produces 

![image](https://user-images.githubusercontent.com/9798689/39696886-d193970c-51f7-11e8-9e73-255101692213.png)


My suggestion is we can add it as a geom, so that if someone wants to plot just the stat_summary or as an additional layer, then its easy.

**Comment by dannyparsons** [comment]
I'm not quite sure of the differences between these suggestions but yes it can be added as a "geom" so that it appears in the geom selector. I don't think we need a special dialog for it.

**Comment by maxwellfundi** [comment]
Great! @bethanclarke  are you still working on the geom?

**Comment by maxwellfundi** [comment]
@dannyparsons I am now adding this to the list of geoms, the parameter `geom` can take many options, bar, line, point.......etc. Have you got like the most common/desired geoms here?

**Comment by bethanclarke** [comment]
@maxwellfundi I still have geoms to add but they are not urgent. I have other work to do doing in the mean time.

**Comment by maxwellfundi** [comment]
@dannyparsons  thanks for the insight. I will add all these to the list of the geoms.
