### ISSUE TITLE
The View R Objects dialogue

### ISSUE THREAD

**Issue by rdstern** [africanmathsinitiative/R-Instat#4435]
The recent Hypothesis tests dialogue has produced more R Objects.

It would be good if the Prepare > R Objects > View dialogue had more options available.  Currently all options are disabled except graphs.

**Comment by rdstern** [comment]
Would this be a dialogue Patrick could look at?  I hope that, just checking that the str() command can be given would allow it to be useful for viewing.  And we should have the option to delete objects as well.  They used to work I think?

There are lots of ways the dialogue could be made more useful, but only if they can (at this stage) be done quickly.  Here is my initial list:
a) Can some information about the selected object be easily available within the dialogue, e.g. number of elements in the list?  The object type perhaps?
b) The data frame is itself an object.  Should this be included?
c) Perhaps the listviewer could be an option, i.e. listviewer::jsonedit(object).  This shows the content in an browser in a way that the levels of items in the list can be "unfolded".

**Comment by Patowhiz** [comment]
Let me have a look at it.

**Comment by dannyparsons** [comment]
The simple thing to get working first is just printing the object 'as is' in the output window. For certain objects things like structure and list items are very long and generally not useful whereas printing normally does something sensible. If the printing was working it would already be useful and other options can be added later.

**Comment by Patowhiz** [comment]
@dannyparsons I'm making that to fall under the "All contents" option.

**Comment by Patowhiz** [comment]
@dannyparsons what's your opinion about the data frame itself also being viewed as an object. Should this be included?

**Comment by dannyparsons** [comment]
- Deleting objects should be in a separate dialog
- I don't think data frames should be viewable here - we are looking at objects associated with a data frame and we already have a view dialog for data frames.

There's lots of interesting functions we could think of using here which could be discussed. But I think the priority now is to get something that's useful and works. So I suggest two options which are easy to get working:
"Print" which just gets the object so it displays in the output window in the default way (no need for "View Graph" radio button as a separate option as this is what "Print" should do for graphs)
"Structure" which calls `str` on the object

Print should be the default and first option.

The idea of Component is to view an item (component) from the object instead of the whole object. For example, an `lm` object has a `coefficients` component. This radio button could be disabled for now as it will need some R code to be written to get working well.

**Comment by Patowhiz** [comment]
@dannyparsons are you suggesting that I make the All contents radio button to be Print?

**Comment by dannyparsons** [comment]
I'm suggesting a radio button called "Print" which just gets the object, calling the get_objects method.
Then a second which calls str on the object.
There shouldn't be anything special needed for graph objects.

Getting components can come later because that will take more time. I chose these two because they should be simple to implement.

**Comment by Patowhiz** [comment]
My understanding is 'Print' is similar to all contents, which currently just prints the object. Not unless I'm not getting what all contents means.

**Comment by dannyparsons** [comment]
It could mean different things for some objects. In R print displays the object in a "nice" way, which may be different from the actual contents of the object. e.g. a graph is stored as a list but prints as an image.
Anyway, print is the most useful and all we need for now.

**Comment by Patowhiz** [comment]
Aha! now I get you. I'm using R command `show` for All contents. I'll add the print radio button and make it the default.

**Comment by dannyparsons** [comment]
show is the same as print - in most cases, so that's not really appropriate for All contents. I'm not sure if we will even need All Contents since str and print do most things - if we do I'm not sure what function we will use which is why I think we don't have All Contents until we decide what it should do and how.

**Comment by dannyparsons** [comment]
looks good

**Comment by dannyparsons** [comment]
We now have some options working on this dialog.
