### ISSUE TITLE
Hypothesis Calculator

### ISSUE THREAD

**Issue by lilyclements** [africanmathsinitiative/R-Instat#4440]
I had a look at the hypothesis calculator. For testing the keys/dialog as a whole:

* I noticed there were a few hypothesis tests that are missing - is this intentional? (I can't say I've heard of these, but they are `ansari`, `mantelhaen`, `quade`, `PP`)
* There's also the normal bugs which I assume are known (bugs are similar problems in the other calculator - e.g., you can insert a factor when inappropriate and hence get an error)
* Fun bug - If I click "Show Arguments" then select the test I want then it works fine, however, if I select the test I want and then click "Show Arguments", the arguments are not shown. (If I do get arguments shown and then click it to undo the arguments then it doesn't do anything)
* If I had a test selected, and then clicked a new test, it comes up as an argument in the last test (e.g. `bartlett(binom())`).
This doesn't make sense to me but just to check in case I'm missing something - would there be a situation where one test is read in as an argument to another test? (e.g. `bartlett(binom())`)
If not, then is it possible eventually perhaps to have these buttons act more like the radio buttons as boxes so that only one can be selected at a time? It could then overwrite if you select a new function (if you haven't inputted any arguments?) 
This would also help the issue I had where I selected, say, `poisson`, then wanted to remove `poisson`, and selecting `poisson` again won't remove it, it instead does `poisson(poisson())`.

![image](https://user-images.githubusercontent.com/21180424/36988722-73cca9ec-2097-11e8-9b0b-2c779ccf1c55.png)

_e.g. I've just done it for_ `bartlett`, `binom`, `Box`, `fligner`, _and_ `friedman`_here - and_ `bartlett` _is selected_

* Could there also be the tool-tips to briefly explain the tests using the descriptions in R - e.g., for the `bartlett` test _"Tests the null that the variances in each of the groups (samples) are the same."_

* For the question of how can the keyboard be improved/divided up, I just was wondering; is the idea here that the user has their data and they're looking for a test in mind? I think that the most sensible way is to do the common tests as one keyboard and less common as another.

I'll look into the `by` tomorrow, hopefully!

**Comment by rdstern** [comment]
I like those comments.  Thanks.  
1. I can't think why we need more than one test at a time.  So could pressing a button do a clear first?
2. I can't see why I messed the 4 tests ansari, mantelhaen, quade, PP.  So let's add them.
3. It is a big keyboard though, so here is my suggestion for splitting it into 2.
a) Stats1 has 16 keys plus Clear.  Though if a new key does clear anyway, then the little Clear on the bottom set may do.
b) these are the 6 on the existing top row, then fried, ks, kruskal, oneway, poisson, t, var, prop, wilcox.  Oh, that's 15, because wilcox is there twice.  So let's include shapiro.  And have them in alphabetical order.
c) Then Stats2 has ansari, fligner, macnemar, mantelhaen, mauchly, mood, the existing third row (5 items), power.t, PP, prop.trend, quade.  I think that's 15 more.  I hope I have them all.  Again, no harm to have alphabetical order.
d) Then possibly a third keyboard, which is from the agricolae package.  I don't think all the following will work easily, so some keys would be disabled.
This has (at least) the following: BIB, duncan, durbin, friedman (not friedman.test, just friedman), kruskal (not kruskal.test), LSD, Median, nonadditivity (not nonadditivity.test), PBIB, REGW, scheffe, SNK, waerden, waller .

**Comment by rdstern** [comment]
I view this dialogue as particularly useful for running a wide range of analyses that may not (quite) be in R-Instat yet.  In the past these are analyses we would try first in RStudio.  Now I want to start seeing what is possible in R-Instat.  Here is one example from the agricolae pdf:

**data(potato )
potato[,1]<-as.factor(potato[,1])
model<-lm(cutting ~ date + variety,potato)
df<-df.residual(model)
MSerror<-deviance(model)/df
analysis<-with(potato,nonadditivity(cutting, date, variety, df, MSerror))**

I take the 6 lines in turn:
**Line 1:** I have added agricolae as a package through RStudio, so I can access the data set called **potato**, from the library.  It has 4 columns and 18 rows.
**Line 2:** This makes the first variable, i.e. the column date into a factor.  I do this with the right-click and make it into a factor.  Later task is to see how I could give this as a command from the script window, i.e. follow the code above as closely as possible.
Line 3: This is the lm model, which I can do from the **Model > 3 Variables > Fit Model** dialogue.  I do that.  I presume I could also do it from the script window?  Can I do it through the hypothesis testing dialogue?
Lines 4 and 5:  This extracts things from the lm object, i.e. the residual df and the residual ms.  I can do these easily by looking at the output window, because they are both there as part of the ANOVA table.  I see that line 4 = 14 and line 5 = 3.309.  So I can proceed, but this isn't very professional!  I can't see easily how to do either of these from dialogues or from commands.  I assume I should be able to use an extended version of the Prepare > R Objects > View dialogue, or could there be an Extract dialogue?  And where would the result go, in my current Instat object? How could I do this from the script window?
Line 6: I give this line just as **agricolae::nonadditivity(cutting, date, variety, 14, 3.309)**  It works!

I view this sort of example partly as useful for testing the use of R-Instat when people read books with commands and would like to follow them, but using R-Instat.
Also in teaching.
And currently in checking what is now possible in R-Instat and what is it important that we add to be able to do this sort of analysis.
In this example we are close.  But having to type the numbers copied from the output window is unprofessional and we should be able to do better than this.

**Comment by lilyclements** [comment]
This sounds good. So we need to add the four missing tests in the stats package, 
1. If we implement a clear if you click on another button before the new test comes up, what do we want to happen if we click on the test we're already on? So I'm on `poisson` and put in my parameters etc, then click `poisson` again. Do we want this to clear the receiver completely? Or alternatively to "reset" the receiver to `poisson` before the parameters are in?

3d. From a ctrl+f search in the agricolae package I also see a `DAU.test` and `HSD.test`, are these the sort of tests we want included? There may be other tests in there I could have missed if their function name does not include `.test`. Should I check for them?

To your second message, you asked " Can I do it through the hypothesis testing dialogue? This third line is possible through the hypothesis testing dialog 
As a side note - this has drawn my attention to another bug in this dialog however since regardless if I check to save the model or not, it will save it. In the regular calculator dialog, it will not save the object just give the object if I do not click "save as". I assume that is what we want this dialog to do as well?

From what Danny says in #4386 adding the `by` looks possible and fairly straight forward? 
Perhaps the `by` option should give a receiver (`ucrReceiverFactor`) where the user can put in which factor they wish to split the data by.
This way the command box 


extract

**Comment by lilyclements** [comment]
This sounds good. So we need to add the four missing tests in the stats package, 
1. If we implement a clear if you click on another button before the new test comes up, what do we want to happen if we click on the test we're already on? So I'm on `poisson` and put in my parameters etc, then click `poisson` again. Do we want this to clear the receiver completely? Or alternatively to "reset" the receiver to `poisson` before the parameters are in?

3d. From a ctrl+f search in the agricolae package I also see a `DAU.test` and `HSD.test`, are these the sort of tests we want included? There may be other tests in there I could have missed if their function name does not include `.test`. Should I check for them?

To your second message, you asked " Can I do it through the hypothesis testing dialogue? This third line is possible through the hypothesis testing dialog 

As a side note - this has drawn my attention to another bug in this dialog however since regardless if I check to save the model or not, it will save it. In the regular calculator dialog, it will not save the object just give the object if I do not click "save as". I assume that is what we want this dialog to do as well?

As for the `by`; from what Danny says in #4386 adding the `by` looks possible and fairly straight forward? Perhaps the `by` option should give a receiver where the user can specify which factor they wish to split the data by.
This way the receiver box where the user writes the tests in remains unchanged whether the user selects `by` or not?

Then the code ran is
`by(data = survey, INDICES = survey$Village., FUN = function(x) t.test(x$Field, x$Size))`
where `data` is the data set
`INDICES` is the item in this new receiver (with data and $ in front)
`FUN = function(x)` automatically gets added and then after this adds the item in the box where the user writes out their test

**Comment by rdstern** [comment]
Two more suggestions - simple ones I hope for the Hypothesis tests dialogue.

1. Could the Stats1 and the Stats2 be on separate items, rather than side by side.  So there would be 3 options on the pull-down, bamely Stats1 Stats2 and Agricolae.

2. Could there be a **Test Help** button - just as there is for the File > Open From Library dialogue?  This would give the help from the package documentation in the same way.
