### ISSUE TITLE
Duplicate row

### ISSUE THREAD

**Issue by maxwellfundi** [africanmathsinitiative/R-Instat#4468]
I have been testing the duplicate dialog and i wanted to check how the new feature @shadrackkibet  has added works and wanted to deliberately produce a duplicate row. Like we have a duplicate column from the right click menu, I was wondering if having a duplicate row feature is a sensible option @rdstern

**Comment by dannyparsons** [comment]
I don't think this is needed in the same way duplicate column is. If there is a case then it could be on the row right click.

**Comment by maxwellfundi** [comment]
Yes, I agree it could go to the row right click menu. What i did not know is if its a sensible option to have. If there is no such case then this issue can be closed.

**Comment by rdstern** [comment]
It isn't so simple as duplicate column, because the items in the row could have different types, e.g. first one may be a factor, while the second is a variate.  I would be inclined to close it for now.
There is no special item for this in Genstat.  However, Genstat has copy/paste, which could be used for this purpose, i.e. you copy a row and then insert a blank row and then paste.
This works OK in Genstat.  
Of course Copy/Paste is general and there is then nothing to stop you moving "sideways" so the columns don't then line up.  This is detected - that it will be a mess in Genstat and isn't allowed.
So I suggest we close for now, but could return to this topic when we implement paste in the grid in R-Instat.
