### ISSUE TITLE
Position for Bar Chart dialog

### ISSUE THREAD

**Issue by dannyparsons** [africanmathsinitiative/R-Instat#4581]
From using the bar chart dialog a lot it would be useful to have the position parameter on the main dialog. It only affect the bars when you have a second factor but I find that people often want to change the position to "dodge" instead of the default "stack". There's not much on the main dialog currently so I think this can be added there.

I also wonder if we should have "dodge" as our default instead of the ggplot default "stack". It seems much easier when you have a lot of levels but maybe there's a reason "stack" is a better default?

**Comment by maxwellfundi** [comment]
We can have either thats sensible and used more. I have not known why stack is the default, but there could be a better reason why we can have dodge as our default.

**Comment by dannyparsons** [comment]
Let's go for "dodge" as the default if no one has objections. We can change it back later if we find good reasons and being on the main dialog users can easily change it.

**Comment by maxwellfundi** [comment]
Okay great! Will be on it

**Comment by rdstern** [comment]
I agree with that.  namely having Dodge as the default, then Stack and third Fill.
I assume this will only apply when there are 2 factors.  Of course it is also possible to have the 2 factors filled, when one of them is the facets.  This means that there is really only in each boxplot, but the colour etc is dictated by the second factor.

I assume this issue can be closed once this is added.  I just flag another issue with bar charts that is sometimes useful and that is the order of the bars.  Sometimes with simple bar charts you want the bars in ascending or descending order.  See [here](https://stackoverflow.com/questions/5208679/order-bars-in-ggplot2-bar-graph) for this question.

This may not be for the dialogue, because there are too many options, particularly when there are facets.  But good to be able to do this and adding more facilities for dictating with factors - using the forcats package could soon become a priority.

**Comment by dannyparsons** [comment]
When there is only one factor then position has no effect, the levels are always on the x axis.
