### ISSUE TITLE
Column summaries - small issues

### ISSUE THREAD

**Issue by rdstern** [africanmathsinitiative/R-Instat#4606]
The test set of data I used had 2 columns - from File > New
data_1 is 1,2,3,4,5,6,7,8,9,10
data_2 is 1,2,3,4,NA,5,NA,6,7,8

So very simple - no factors!
Use Prepare > Column: Reshape > Column Summaries

1. Get the proportion > 4
For data_1 it is 0.6 - correct.
For data_2 it is still 0.6 - **incorrect**.  It should be 0.5.  Presumably it is setting the missing values to TRUE.
2. Get the correlation (and covariance) of these 2 columns with data_2.  Both results are given as missing.  So the setting is wrong for those two functions.
3. Delete data_2 from the 2-variables tab.  Now run again.  It gives an error, because there is no element to get the correlations.  But (with our usual rule) if the correlation or covariance is ticked, then OK should not be enabled unless that field is filled.

**Comment by dannyparsons** [comment]
@africanmathsinitiative/developers This would be good for someone to look into carefully, particularly the problem with proportions and understand the R code and identify the problem. I'd like to point out that this was both implemented and tested without anyone noticing that it sometimes gives the wrong answer.

**Comment by bethanclarke** [comment]
I will look at these issues @rdstern

**Comment by bethanclarke** [comment]
@dannyparsons I can't seem to find the calculate_summary command anywhere. This the code for proportion > 4:
`InstatDataObject$calculate_summary(data_name="test1", columns_to_summarise=c("a","b"), test="'>'", value=4, summaries=c("proportion_calc"), silent=TRUE)`

**Comment by bethanclarke** [comment]
There is a problem when it comes to calculating the correlations. 

`summary_cor` function requires arguments x and y, however x is not defined in VB. So I am trying to implement the argument x, where x is equal to the column(s) from the multiple receiver. But when we have multiple columns it either needs to a vector, matrix or data frame containing the variables from the multiple receiver. 

First, I tried to obtain the correlation between data1 and data2 (only selected data1 in multiple receiver) and this did not work in R-Instat because x wasn't included in the code and it didn't work when I ran it in R including x parameter: 

```
InstatDataObject$calculate_summary(data_name="test1", columns_to_summarise=c("a","b"), x=a, summaries=c("summary_cor"), silent=TRUE, y=b, use = "complete.obs")
Error in summarise_impl(.data, dots) : 
  Evaluation error: formal argument "x" matched by multiple actual arguments.
Called from: summarise_impl(.data, dots)
```
where a = data1 and b = data2

The other thing I have been trying to get working is when we have multiple variables, i tried the following: 

`InstatDataObject$calculate_summary(data_name="test1", columns_to_summarise=c("a","b"), x=InstatDataObject$get_columns_from_data(data_name="test1", col_names=c("a","b")), summaries=c("summary_cor"), silent=TRUE, y=b, use = "complete.obs")`

and

`InstatDataObject$calculate_summary(data_name="test1", columns_to_summarise=c("a","b"), x=data.frame(a, b), summaries=c("summary_cor"), silent=TRUE, y=b, use = "complete.obs")`

But all three produce issues. @dannyparsons do you see what I am missing/doing wrong?

Thanks

**Comment by dannyparsons** [comment]
In `InstatDataObject$calculate_summary` it takes the `columns_to_summarise` and passes those in as `x` one at a time. So its ok not to have `x` passed in directly to `InstatDataObject$calculate_summary`. The `y` is passed in directly from the 2-variables tab on the subdialog.

I think the issue with correlations is the missing value option. `cor` has the `use` parameter to specify how to handle missing values so `na.rm` is ignored. So we just need to add something to the subdialog to handle missing values for correlations. There are quite a few options for `use` but I don't think we need all of them as some only apply to correlating more than 2 columns together.

**Comment by bethanclarke** [comment]
I have added the same missing options that we have on the Correlations dialog to the Summaries sub-dialog. 
![sdgsummaries](https://user-images.githubusercontent.com/16190039/40507593-a42f178c-5f8f-11e8-816e-51774e7a8fa8.PNG)

But when I test it in R-Instat, I get the following error message: 
![columnsummariesissue](https://user-images.githubusercontent.com/16190039/40507780-c0c4cbda-5f8f-11e8-822f-b2fe766e5fb2.PNG)

**Comment by dannyparsons** [comment]
It seems that the quotes around "complete.obs" are removed inside the function when doing the summary. One way around this quickly is to have `use = "'complete.obs'"` which is single quotes inside the double quotes. Then it will work.

I also think it's worth revisiting the options for missing values. e.g. From the help for `cor`

> If use is "complete.obs" then missing values are handled by casewise deletion (and if there are no complete cases, that gives an error).

But we don't want an error if there are no complete cases. So it might be better to have `"na.or.complete"` instead.

Also "pairwise" is only when you are doing pairwise correlations between a set of variables. Here we're just doing separate correlations so this option probably isn't needed from here.

Could you look at the set of possibilities for `use` and see which ones we want?

**Comment by bethanclarke** [comment]
Thank you @dannyparsons 
`"na.or.complete"` does seem like the most sensible option, 
After discussing with Roger today, we do not want missing options. Instead, if omit missing values is checked then we have use = "na.or.complete". The only problem is we only want to include this parameter when correlations and/or covariance is checked on the sub-dialog and I don't know how to link the two. 

Also, I think I have found the issue with proportions. I tested the `proportion_calc` function and that seems to be the problem. So I have added to this function and we now get 0.5 for data2 

```
proportion_calc <- function(x, test = "==", value, As_percentage = FALSE, na.rm = FALSE,... ){ 
  if(!na.rm){
    y <- x[eval(parse(text = paste("x", value, sep = test)))]
    if(!As_percentage){return(length(y)/length(x))}
    else {return(noquote(paste0((length(y)/length(x))*100 ,"%")))}
  }
  else {
    remove.na <- na.omit(x)
    y <- remove.na[eval(parse(text = paste("remove.na", value, sep = test)))]
    if (!As_percentage){ return(length(y)/length(remove.na))}
    else{return(noquote(paste0((length(y)/length(remove.na))*100 ,"%")))}
  }
}
```

**Comment by bethanclarke** [comment]
@rdstern you're right about the issue with trimmed mean.  I checked mean and trimmed mean on the sub-dialog but we only obtain the trimmed mean.

@dannyparsons Roger suggested writing another function for trimmed mean, what are your thoughts on this? If yes, it would be very easy for me to include.

**Comment by dannyparsons** [comment]
1. I think @shadrackkibet could look at adding the `use = "na.or.complete"`

2. In your new `proportion_calc` function, it looks good for `na.rm = TRUE` but I tried:
```
> proportion_calc(test1$b, test= ">", value = 4, na.rm=F)
[1] 0.6
```
I would expect this to either be `NA` because there are missing values or 0.4 because 4 out of 10 (including missing) are greater than 0.4. `NA` is probably the answer in line with how our other summaries deal with missing values.
You could just add the line: `if(sum(is.na(x)) > 0) return(NA)` in the case where `na.rm = FALSE`.

3. Yes, please add a function for trimmed mean. Make sure the trim argument for your new function is NOT called `trim`, otherwise this will also go into `summary_mean` and you would get the trimmed mean for both if both are checked.

**Comment by bethanclarke** [comment]
Ah of course, I didn't think of that case! Thanks @dannyparsons , I've included that line to the code and it works. 

Okay, I have added a trimmed mean function with the parameter trimmed rather than trim.

**Comment by bethanclarke** [comment]
@shadrackkibet I have just made a pull request which has the R code and a few changes to the dialogs.

**Comment by shadrackkibet** [comment]
@dannyparsons This can be closed now.
