### ISSUE TITLE
Check for Duplicates in Climatic > Define climatic data

### ISSUE THREAD

**Issue by rdstern** [africanmathsinitiative/R-Instat#4678]
See responses below for the updated suggestion.

This would use all the same code as the full Duplicates dialogue.

It might even have the same 3 buttons at the top, with the first and third being just as in the full dialogue.

But it starts with the second option.  It is in the Climatic > Check data section towards the top - could be at the top.

With the second option the difference is that there are 2 single receivers, one for Station and the other for Date.  And, assuming the data has been declared as climatic, then these are filled automatically.

There is an enhancement to consider for both the general and this dialogue.  Would it be easy to add the facility to Check Unique that is in the Prepare > Keys and Links > Add Key dialogue?

**Comment by dannyparsons** [comment]
I think the uniqueness check could be added. That would be nice because then you don't need to create the duplicates column when everything is unique.

I would like the define climatic to attempt to create a key and fail if there are duplicates, because I don't think you should be able to use all the calculation dialogs before sorting out duplicate issues. So this would work well being used before define, or if define fails and you need to look at your duplicates.

**Comment by rdstern** [comment]
Danny would now like to add a facility to check for duplicates in the Define Climatic Data.  That would be great, but also means that the Station and Year would not be pre-defined.  So I think this special dialogue will now be less useful.  I am therefore closing this issue.

On second thoughts I'll just change the name of this issue!

**Comment by rdstern** [comment]
That would be excellent.

**Comment by shadrackkibet** [comment]
@dannyparsons  @rdstern What are your views on this design?

![image](https://user-images.githubusercontent.com/26301973/41711179-2d46cb20-7550-11e8-97ac-26e1f1046bdb.png)

**Comment by dannyparsons** [comment]
I don't think we want a separate receiver for the keys. The key columns are taken automatically from Station + Date.
For the message:
1. When Station receiver is empty "If you have multiple stations, did you forget to add the station column? Otherwise, use the Climatic > Check Data > Duplicates dialog to investigate your duplicate Dates."
2. When Station receiver is not empty "Did you forget the station column? Otherwise, use the Climatic > Check Data > Duplicates dialog to investigate your duplicate Dates within Station."

I think the button shouldn't be enabled when Date is empty, because you always need Date so there's no point checking.

Also ensure that the textbox is updated when the dialog is reopened - because the data may have been modified so the textbox text should be updated.

**Comment by rdstern** [comment]
Looks nice overall.  I like the check unique there.

The message is a bit odd given that the Station and Date have been included in the dialogue.  Could the Duplicates dialogue be clearer.  If there is no Climatic Duplicates then it Could say Prepare > Check Data > Climatic.  And it would add the second part if it detects that at least one of the date or station has not been included.

**Comment by shadrackkibet** [comment]
Should we disable ok when you have duplicates in your data?

**Comment by dannyparsons** [comment]
yes I think so

**Comment by shadrackkibet** [comment]
I also suggest we make the input textbox displaying the text readonly.
