### ISSUE TITLE
Updating the data frame selector with current data frame

### ISSUE THREAD

**Issue by maxwellfundi** [africanmathsinitiative/R-Instat#4712]
If i have three dataframes open say A, B and C, i thought we had the feature where when you move from one dataframe to the other say A to B, when you open/reopen a dialog you used recently then you should have the dataframe selector having the current dataframe selected in this case B. 

What we have now, sometimes it still is on the old data frame, or it has no data frame selected and still has items on the receivers, and okay could be enabled which could cause a bug.

**Comment by dannyparsons** [comment]
On your first point, no we don't have that, the dialog opens as it was closed, that's the whole basis for our dialog system. Otherwise, if I reopen the dialog on a different data frame all the receivers should reset, and then I've lost my ability to rerun the dialog again in the same way. Also take Column Summarise which is often reopened to add more summaries. After running once you then see the summary data frame but to rerun you want to still use your original data frame not for it to open on the new summary data frame. If you reset the dialog it will update to the currently viewed dialog.

In case where the data frame is deleted, then it is blank on reopen. I don't mind too much the data frame being blank on reopen because sometimes its useful to be reminded that the data frame last used is no longer there. But the receivers still being filled is a bug and we should ensure they are cleared too.

A feature I could see as useful would be a "reset all dialogs" if you have been running a long time and used lots of dialogs and now you are moving to a different data frame you would rather everything opens like new again so this is instead of having to restart the software. However, you should have to choose do this.

**Comment by rdstern** [comment]
This is a @dannyparsons question, see above, because I like our rule that the dialogue "remembers" its setting from when it was used last and that's simple and I don't want to change that.  But:
a) I have often moved to a new data frame, perhaps opened it, and then gone back to a dialogue and forgotten it is still on the old data frame.  Could we (say) have the current data frame in the pull-down in bold and italic.  Then, when you return to a dialogue there is a small change if the visible data frame is different.
b) I am never quite sure what happens on Reset.  Maybe the action of Reset could be to reset it to assume the dialogue has never been used before.  Then it would automatically reset to the (new) current data frame.  That would enable a simple user rule - if you change data frames, then usually start by pressing Reset.

**Comment by Patowhiz** [comment]
@rdstern yes, @dannyparsons responded in my email about the idea of letting the user know about the selected sheet. And I've been looking into this.
I'm not sure if we can have styling in winforms combobox items, I'll check.
The solution I've been leading towards is showing a bold label that indicates the selected sheet in the data view window whenever it's different from the selected data frame in the dialog.

May I add this is a very good addition that will help a lot in fast tracking user training. Many users get left behind after using the wrong data frame during the training.
