### ISSUE TITLE
Hash function to anonymise ID column

### ISSUE THREAD

**Issue by dannyparsons** [africanmathsinitiative/R-Instat#4715]
I have written a function to anonymise an ID column by using a hash function from the `digest` package:

```
hashed_id <- function(x, salt, algo = "crc32") {
  y <- paste(x, salt)
  y <- sapply(y, function(X) digest::digest(X, algo = algo))
  as.character(y)
}
```
The salt argument is an arbitrary string which just increases the security as this should only be known by the user.

The usefulness of this over randomising the values or replacing them by 1 to n is that these are complex algorithms but still being reproducible and reversible with knowledge

Not urgent but this could be useful dialog under Prepare to Share and easy to create. This is not something that the `sdcMicro` package does and could be done before/after using sdcMicro and complements what it does.

**Comment by shadrackkibet** [comment]
Working on this.

**Comment by shadrackkibet** [comment]
This is the design of this dialog.
![image](https://user-images.githubusercontent.com/26301973/42830350-cf567c32-89f3-11e8-914d-c7e080e0deb7.png)

**Comment by shadrackkibet** [comment]
@dannyparsons i am going to add this as a stand alone function is that okay?

**Comment by dannyparsons** [comment]
Yes that's fine. Can you change the Salt label to "Random string (salt)"?

**Comment by shadrackkibet** [comment]
great.

**Comment by Patowhiz** [comment]
@dannyparsons @shadrackkibet I like the fact that we now have this dialog especially for users from the medical sector. However, do we have a "reversal" dialog? Probably I haven't grasped the real intention of this dialog, but one may share the anonymised data to have it analysed, say by an external expert, get it back and may want to reverse the anonymised columns to look at the data in its "original" state.

In addition, probably not a big deal but I think having CRC32 algorithm for this task is trivial. My understanding is that CRC32 algorithm mainly/widely/mostly used for error-detection code rather than hashing and cryptography, I find it convenient to protect users with lack of knowledge on how the checksum output of this algorithm can beeasily cracked and not having the option. Or rather is there an intended merit to having this option?

**Comment by dannyparsons** [comment]
A reversal option will also be useful, but depends on the algorithm used, some do not hash uniquely so it's not possible. Another option is to output a vector which shows the matchings which can be used later to recode. I think this is a good point for an issue for further work.

**Comment by shadrackkibet** [comment]
@dannyparsons  checking at R documentation `md5` is the default algorithm. Should i change this?

**Comment by Patowhiz** [comment]
@dannyparsons  you closed this issue without commenting about what I have raised about CRC32 algorithm

**Comment by dannyparsons** [comment]
This closed automatically when Shadrack's pull request was merged.

CRC32 is an option of the digest function we are using so we'd need to a good reason to remove it as an option. Note that the [digest help page](https://www.rdocumentation.org/packages/digest/versions/0.6.15/topics/digest) says:

> Please note that this package is not meant to be deployed for cryptographic purposes for which more comprehensive (and widely tested) libraries such as 'OpenSSL' should be used.

So we are not trying to provide something that is highly secure or uncrackable as this wouldn't be the appropriate package to do that.

**Comment by Patowhiz** [comment]
Okay
