### ISSUE TITLE
Access to R documentation in Help menu

### ISSUE THREAD

**Issue by rdstern** [africanmathsinitiative/R-Instat#4762]
In the File > Open from Library we can get access to any of the library data sets, and also the help information that describes the data.
Could we have a menu item in the help menu that gives similar access to the information on each function in the package?  I expect this to work in a similar way.
1. To provide this information (in a browser).
2. To have a full list of the packages accessible from R-Instat  (Whether they have data sets or not.)
3. The information includes examples.  These will usually run from our script window.  That would be a great feature!
.

**Comment by shadrackkibet** [comment]
This is my design for this dialog.
![image](https://user-images.githubusercontent.com/26301973/42873525-e29b54f4-8a87-11e8-8247-ba833cce356e.png)

**Comment by rdstern** [comment]
That looks great as a start.

With the Help option, as above, then If it is easy, could there also be a checkbox called Function.  If ticked, then for a selected package it would take you straight to the help on that function?

If unchecked, then (as now I presume) it takes you to the start of the help file.

This is like the help on the data sets that takes you to a particular one.  David thinks this addition should be easy, and suggests @dannyparsons coulkd confirm.

**Comment by dannyparsons** [comment]
I wouldn't have chosen radio buttons at the top for Help/Vignettes because this is just an option not a change in how the dialog looks or works. I would probably have had normal radio buttons under the Package Name combo box (which should be non editable), but I don't feel that strongly that it should be redesigned now.

It depends what you mean by "that function". We could easily have a textbox where you type the function name and it runs e.g. `help(topic = "geom_line", package = "ggplot2")`. But you have to know the name of the function and if you type a wrong function it won't do anything. I didn't see a way to easily extract a list of the help pages for a package, like we have for datasets, but I would guess it's possible. If it's important I could spend more time probably posting a question somewhere to ask how to do it.

**Comment by rdstern** [comment]
I don't want it to be difficult now.  So either leave it as it is, or have a checkbox to type the function name - with your caveat that it must be typed correctly.  Often I suggest a use will be to see an interesting function in the command and then want to know more details.  So it could often be copied and pasted.

**Comment by dannyparsons** [comment]
I think a textbox is fine as user should generally know the function name if they're using this. They can still access the full index as well if they don't.

**Comment by shadrackkibet** [comment]
@rdstern which package would you like to be the default on the combobox?

**Comment by rdstern** [comment]
This is working well.
A small change I would like is to add a checkbox with the label Function.  Default unchecked, which then runs as now when the function is left blank.
If checked then it opens the current field with the label Name:

This just makes it clearer that you can get the help on the whole package.
