### ISSUE TITLE
Writing to the script file from the Calculator

### ISSUE THREAD

**Issue by rdstern** [africanmathsinitiative/R-Instat#4798]
When doing a calculation the results are written OK to the output file.  But not to the script file.  There the line is missing that gets the data from the Instat object.

**Comment by shadrackkibet** [comment]
Yes, i will look into this.

**Comment by shadrackkibet** [comment]
@dannyparsons  I see in the calculator we do not need to get data from the InstatObject for this to work. The only code that i found that it is not in the script window is `detach(name=Dodoma, unload=TRUE)` because it is on Before_clickOk event as show below.

To script
` Code generated by the dialog, Calculations`
`Calc1 <- log(Tmax)`
`InstatDataObject$add_columns_to_data(col_data=Calc1, col_name="Calc1", data_name="Dodoma")`
`rm(Calc1)`


When ok is clicked.
`# Code generated by the dialog, Calculations`
`Calc1 <- log(Tmax)`
`InstatDataObject$add_columns_to_data(col_data=Calc1, col_name="Calc1", data_name="Dodoma")`
**`detach(name=Dodoma, unload=TRUE)`**
`rm(Calc1)`

**Comment by dannyparsons** [comment]
There should be an attach command run first and then detach run after, not before.

**Comment by rdstern** [comment]
I have stumbled over this problem again, i.e. the first lines of the command not being added to the script window.  Is this a difficult feature to fix?

**Comment by dannyparsons** [comment]
Yes, its because the attach/detach functions are run on the click ok events instead of as before/after codes of the RSyntax, which is our new approach to ensure the script is produced correctly.
@maxwellfundi can you assign to someone who is familiar with this?

**Comment by rdstern** [comment]
@dannyparsons and @maxwellfundi I think this is now resolved?

**Comment by shadrackkibet** [comment]
Yes
