### ISSUE TITLE
New version of ggplot2 and geom_sf

### ISSUE THREAD

**Issue by rdstern** [africanmathsinitiative/R-Instat#4804]
ggplot2 Version 3 was issued early in July 2018.  Two points to query:

a) Are we automatically using it on new releases?  It looks like a major change.
b) It also says it now has full support for geom_sf, which I assume is for shape files.  We don't currently have  this geom in our list, but I assume we will be using it for the mapping.  @JacklineKemboi is that correct?
c) The news about this version also says there are some breaking changes - so some syntax may no longer work.  I wonder if that may affect us?

**Comment by dannyparsons** [comment]
@africanmathsinitiative/developers 
We currently don't use the new version. But if you update your version in RStudio then you will be using the update in R-Instat. 

The changes are described here https://cran.r-project.org/web/packages/ggplot2/news/news.html

From looking at the breaking changes I wouldn't expect it to affect us directly, although it says it may have breaking changes for other packages. A few people should update their ggplot2 to 3.0.0 and then test R-Instat for any errors. The standard plots should be fine because they are direct uses of ggplot. Things like the inventory plot are more likely to have possible issues.

**Comment by dannyparsons** [comment]
`geom_sf` looks interesting and worth looking at. It seems to allow you to use ggplot directly on a shape file object, without needing to convert to a data frame first. I'm not sure if this is helpful or not for R-Instat at the moment.

**Comment by dannyparsons** [comment]
Something else that could affect us. Looks like a useful improvement and we won't have to do anything as it's the new default:

> New position_dodge2() provides enhanced dodging for boxplots. Compared to position_dodge(), position_dodge2() compares xmin and xmax values to determine which elements overlap, and spreads overlapping elements evenly within the region of overlap. position_dodge2() is now the default position adjustment for geom_boxplot(), because it handles varwidth = TRUE, and will be considered for other geoms in the future.

**Comment by Ogik99** [comment]
geom_sf was already added. This issue can be closed @maxwellfundi
