### ISSUE TITLE
Right click on log file

### ISSUE THREAD

**Issue by rdstern** [africanmathsinitiative/R-Instat#4822]
I'm writing a guide about using commands when running R-Instat.

So I have opened the Log file.  Then I used <Right Click>.  
It has 3 items 
a) Open Log file
b) Copy
c) Run Selected Text

1. I tried Open Log File and it failed for me though it tried to go to pdf.  I assume it means Open Log File in RStudio?  Perhaps the name of the entry could change.
2.  I tried Copy and that seems OK
3. Run Selected Text is disabled.  Can it have a short cut key - just as I would like the same key in the Script window.  <Ctrl> <Enter> as in RStudio would be good.
4. In the script window there is Save Script.  There is no equivalent Save Log.

**Comment by maxwellfundi** [comment]
@rdstern  On your issue no 1, we had that initially but then we decided to leave it as Open Log file because its not always that it will open in RStudio. it opens in any program set to open R files by default. SO it would be strange for a person to Click on Open Log on in RStudio and it opens say a text file. I stand to be corrected on this though. 

If you had no selected text then Run Selected text would not enabled  because it only gets enabled if you have some text selected. 

I think i will discuss with @dannyparsons at some point on implementation of running line by line.

**Comment by Patowhiz** [comment]
@maxwellfundi did you start work on this issue. I'm happy to take over if you have a lot on your plate. This seems identical to what I've done to the script window

**Comment by Patowhiz** [comment]
@rdstern in regard to opening log files, we can have 2 options.;  **Open file**, **open with**. When **Open file** is clicked then the log file will be opened by the default application set to open the R files. On the other hand, **Open with** can have 2 sub menu options; **Rstudio**, **Text Editor(Default)**. When Rstudio option is clicked the file will be opened by it(We can check if this fails and inform the user if he doesn't have RStudio installed). When **Text Editor(Default)** is clicked, then the file opens in the default text editor.

**Comment by dannyparsons** [comment]
I think there should only be one item to keep it simple. Although I like forcing it to open in RStudio I would rather have something that will work (almost) all the time so just opening with the default is fine.

**Comment by Patowhiz** [comment]
Well, I proposed the 2 options because it brings out the expected consistency found in other applications. In open... scenarios, most of the apps will have the 2 options. It helps the user quickly open a file with the application he wants without necessarily going to the operating system defaults. What makes it simple is that this concept has been implemented consistently in so many softwares and users already expect this(windows OS being the pioneer). But I am okay with retain this with just the single option.

**Comment by dannyparsons** [comment]
Having 3 options, and a sub menu, for a very minor feature seems over the top, and the opposite of simple, we're forcing users to stop and think what to choose, when in many cases 2 of the options do the same thing. This is only meant to be a shortcut to copy and paste, not a complete full proof file opening system. One the options (RStudio) will give an error if they don't have it, which can confuse users into thinking they have a problem or something missing. I want to avoid users getting errors. I can't think of a software, other than a full operating system, which has such complex options, even a web browser would only have 2 options to open a PDF: internally or system default. So I don't agree this is simpler and consistent with other things our users will know, a single option seems much more simple and consistent to me, happy to try to be convinced otherwise though!

**Comment by Patowhiz** [comment]
Okay. Below are the additions to the context menu. Any changes?

<img width="490" alt="log window" src="https://user-images.githubusercontent.com/21179007/45345259-78c65180-b5ae-11e8-8e15-a677f260cf28.png">

**Comment by Patowhiz** [comment]
@dannyparsons @rdstern I've noticed that any command executed leads to the log window appending the run command to itself. Should we leave this the way it is or should we modify it to not append the commands run on itself?

**Comment by rdstern** [comment]
Nice.

I think it should still append.  It is a log of the commands, so should be faithful to that.

**Comment by Patowhiz** [comment]
Okay. No help option here?

**Comment by rdstern** [comment]
Oh, good question!  There should be.  For now disabled, but I expect to get there in the next few days.

**Comment by dannyparsons** [comment]
The log must show every R command run by the user, otherwise it's not a log :)

I would reorder to have:

Copy
**(line)**
Run Current Line
Run Selected Text
Run All (any reason this isn't there?)
**(line)**
Save Log File...
Open Log File

**Comment by Patowhiz** [comment]
The menu now looks like this.

<img width="492" alt="log window" src="https://user-images.githubusercontent.com/21179007/45349196-538b1080-b5b9-11e8-9a17-3060debc991b.png">

**Comment by dannyparsons** [comment]
Looks good to me

**Comment by Patowhiz** [comment]
Okay. This is all done.
