### ISSUE TITLE
Remove .NET Framework from full installer

### ISSUE THREAD

**Issue by dannyparsons** [africanmathsinitiative/R-Instat#4841]
I suggest removing .NET Framework from the full installer for these reasons:

1. It often doesn't install as a prerequisite for the main installer, but does install separately. It's not really meant to be installed in this way and we have seen issues. e.g. There is a bug with .NET installer that when some other software or tasks are running it refuses to install. So then it has to be installed separately anyway and has slowed down the installation a lot.

2. Different Windows versions need different .NET versions. I think this is a particular issue related to Service Pack updates, so without an up to date service pack, sometimes an older .NET framework is needed which I've had to do before. So the version in the full installer doesn't always work and again has to be installed separately.

3. Most computers now have an up to date .NET framework so it's not needed very often but takes up time downloading or copying the installer. The installation file would be smaller without it.

As an alternative I suggest on the website we have clear instructions about .NET versions and link to the downloads for offline installers. If we are installing ourselves e.g. for a workshop then we take offline installers of .NET versions (which we need to do anyway now when it doesn't work).

Any thoughts on this based on others' experience installing R-Instat for different people? @africanmathsinitiative/developers @volloholic

**Comment by maxwellfundi** [comment]
I agree with you in many cases, the .NET does not install properly. I have had a few successes though with installing this. However, I find it very annoying that we have to install it separately. 

I think making the instructions more clear and removing it from our installation is a good  idea. on the other hand i think if we got a better way to install it with the rest then I would be happy to keep it. 

I would disagree that most computers have updated .NET versions because you can find still lots of people using windows 7 (not up to date) and this was part of the reason we wanted to have it bundled so that they would not need to get additional packages from the internet.

**Comment by dannyparsons** [comment]
Maybe I should rephrase that as many people already have it, and that number will only go up as computers get more up to date.

If we do find a better way it would be worth considering adding back in.

**Comment by shadrackkibet** [comment]
I agree we need to remove .NET Framework  from the full installer. Several times i have installed R-Instat i experienced this issues and i needed to install .NET Framework separately.

**Comment by dannyparsons** [comment]
I checked with Roger and David and they also agree so seems we have agreement. I'll make this as closed and from the next version we no not include .NET Framework. 

This will require changes to the installation guide @maxwellfundi
