### ISSUE TITLE
PICSA Crops definitions with missing values

### ISSUE THREAD

**Issue by dannyparsons** [africanmathsinitiative/R-Instat#4902]
We have been looking at these closely Francis and want to confirm the expected behaviour for dealing with missing values. This is our current thoughts on what it should do (not necessarily what it is doing currently)

1. If the start of the rains is missing then the planting day condition is missing

2. If the end of the rains is missing then the planting length condition is missing

3. The rain total from the planting day for the planting length is calculated with missing values removed.
**a** If the total is more than the requested total then the condition is `TRUE` (regardless of missing values - they are irrelevant)
**b** If the total is less than the requested total and there were missing rain values then the condition is `NA`.
**c** If the total is less than the requested total and there were no missing rain values then the condition is `FALSE`.

4. **Overall**
**a** If any of the three conditions are `FALSE` then then overall result is `FALSE` (regardless of missing) e.g. `FALSE & FALSE & NA` gives `FALSE` (the missing is irrelevant)
**b** If there are a mixture of just `TRUE` and `NA` conditions then the result is `NA` e.g. `TRUE & NA & TRUE` gives `NA` (the NA is important)

5. **Proportions**
If some of the overall conditions are missing there are two options for calculating the proportion of `TRUE` values:
**a** Remove missing values and give proportion of the rest (e.g. `x <- c(TRUE, TRUE, FALSE, FALSE, NA)` has `0.5` proportion of `TRUE`)
**b** Leaving the missing values so the proportion is missing
(Our proportion option in summary dialog can do both of these depending on `na.rm`)
Francis says he is currently doing **a** so this could be the default for the dialog. But we could also have the option to do **b**.

So any comments on these so that we get to an agreement? Once we're agreed I can implement any changes to code if necessary. 

(I haven't explained what the dialog is currently doing to avoid the issue being overly complicated but 3. and 5. are not currently implemented as I have described removed.)

**Comment by rdstern** [comment]
[dodomacrops.zip](https://github.com/africanmathsinitiative/R-Instat/files/3395739/dodomacrops.zip)
This file shows a problem with the crops when there are missing values in the data.
This is the dialogue:
![image](https://user-images.githubusercontent.com/11226469/61272926-32c6b500-a7a0-11e9-887e-839d3c95cf86.png)
The detailed results are in the sheet called crop_def that gives the results each year.  In the first year (1934/5) there is no starting date, because the data start in Jan 1 1935.  So the starting date is correctly given as NA.  I don't know why the total is given as zero, because the data do start on day 185.  But it may be because of the lack of starting date?  However the overall result is then given as FALSE, when it should be NA.  The same problem is for the last 2 years.

The same problem seems to affect the conditional results.  They also give FALSE when there are missing values.

**Comment by dannyparsons** [comment]
fixed by #5447
