### ISSUE TITLE
Import or Open?

### ISSUE THREAD

**Issue by dannyparsons** [africanmathsinitiative/R-Instat#4983]
We have both Open and Import in various places on File and Climatic menus. On the climatic menu particularly it is looks very inconsistent. There's also just 'Climsoft' and 'Clidata' with no open or import.

![image](https://user-images.githubusercontent.com/11214914/45983488-cc16b600-c02a-11e8-8a8a-e08392ac7dd9.png)

This relates to #4981 and might be good to resolve while doing the help.

I would suggest these are all **Import** because there is some kind of converting going on - they are not _R-Instat files_ - but then I would like to keep **Open from File** on the File menu and I don't have a good reason for this difference. 

Any thoughts?

**Comment by rdstern** [comment]
I would suggest we draw a mild distinction that Open is used when we usually take the whole file.  We just Open it - at least that's the default.
Import from is when we usually decide what we want from something larger.

Now, with Open we do have options, e.g. from Excel we usually open a single sheet, or even part of a sheet.  And with NetCDF we can get an interesting subset.  But the default is usually to take what's there.

So I am still happy with Open NetCDF, and would usually have Open.  Hence I would change Import Shape Files, in your example above, to **Open Shape File** (and also singular - we only open one at a time).

I would change CLIMSOFT to **Import From CLIMSOFT** and **Import From CLIDATA**.  I would change Import Gridded Data (for now) to **Open Gridded Data**, because we usually do the selection at IRI.  (Later it might be dropped, because it is simply another example of NetCDF).

On the file menu I would change Import from ODK to Open ODK and Open CSPRO  (no From, or from). Then **Import From Databases**.

**Comment by dannyparsons** [comment]
That's different to what I was thinking but happy with that distinction. Although I would have thought with this logic that it should be Import from ODK or Open from ODK since ODK is a software and not a file or file type.

**Comment by rdstern** [comment]
Agreed with the from ODK,  I would say Open From ODK then, (and Open From CSPRO, because you usually take the lot.

**Comment by Muthenya** [comment]
Is there any more discussions on this @dannyparsons and @rdstern?
Work can begin on this, possibly by @Wycklife or @Ivanluv.

**Comment by dannyparsons** [comment]
I'm happy with Roger's distinctions.
