### ISSUE TITLE
Consistency in Buttons leading to the subdialog.

### ISSUE THREAD

**Issue by shadrackkibet** [africanmathsinitiative/R-Instat#5008]
**Describe the bug**
I had a quick look at the buttons leading to the subdialog in most of our dialogs and i find that they are not consistent. Some have ellipses(...) and others don't . I think we should agree which format to follow.
Looking at Describe menu almost all buttons do not have ellipses. In models,Prepare and climatic some dialogs have this. Is this a decision that was made before?
![image](https://user-images.githubusercontent.com/26301973/46522962-f23f2000-c88c-11e8-98f4-52f4220e9f70.png)
![image](https://user-images.githubusercontent.com/26301973/46522979-fc611e80-c88c-11e8-8103-600fbee69f27.png)

**Comment by dannyparsons** [comment]
I think we later decided not to have `...` which is why some earlier dialogs still have them. I think @lilyclements looked into the standard for this before?

**Comment by lilyclements** [comment]
So, I went through these guides 18 months ago:
https://msdn.microsoft.com/en-us/library/windows/desktop/dn742401(v=vs.85).aspx
https://msdn.microsoft.com/en-us/library/windows/desktop/dn742478.aspx

Then I wrote up key points from them which I sent over at the time. I'll send over to you Shadrack since this was before you started so you most definitely haven't seen it before. However, since it was 18 months ago the software has "developed" somewhat and so some of these ideas are not used. I'll send it to Daniel again too. These key points probably need going-over again, and to be clarified a little better

What the first link says about Command Buttons is if it leads to a dialog where you can give more information, then it should have an ellipsis.
The link gives an example that "Print" indicates that clicking it will mean that it prints straight away, whereas "Print..." indicates that it will open a new window for print options.
However, it states that "this doesn't mean you should use an ellipsis whenever an action displays another window only when additional information is required to perform the action. Consequently, any command button whose implicit verb is to "show another window" doesn't take an ellipsis, such as with the commands About, Advanced, Help (or any other command linking to a Help topic), Options, Properties, or Settings."

So by that logic, these plot options shouldn't have an ellipsis since the word "options" implies that it will lead to another window.

Do we think "Function" on the model dialog needs an ellipsis?

**Comment by dannyparsons** [comment]
@africanmathsinitiative/developers someone could go through all dialogs with links to subdialogs and make changes to have consistency.
I think most of our buttons should **not** have `...` from the explanation above.

Maybe "Function..." should keep the `...`? This might be rare enough that we remove it for this case too.

**Comment by shadrackkibet** [comment]
@Wycklife @Ivanluv can someone volunteer to check this?

**Comment by shadrackkibet** [comment]
@lilyclements can you also add this into your list? looks related to the sort of things you are now working on. Thanks.
