### ISSUE TITLE
Export to CPT Enabled bug

### ISSUE THREAD

**Issue by maxwellfundi** [africanmathsinitiative/R-Instat#5018]
**Describe the bug**
- [ ] Okay is enabled even when the file path is empty
- [ ] After saving there is no message or indication that saving has been successful
- [ ] Currently the output file is a txt file
- [ ] Currently with missing values are left blank on the output file

**Expected behaviour**
- Okay should not be enabled when the save file path is empty. 
- We need a message box after saving which would give the directory of where it file has been saved
- We need the output from this dialog to be a csv file
- the missing values on the output file should be -99999

**Comment by maxwellfundi** [comment]
@rdstern Please confirm the missing value options here.

**Comment by rdstern** [comment]
1. I think the output to CPT is OK as a txt file for now.  I'll check later.
2. There should be a numeric input control with label **Code Missing Values as:** .  The default is -999.  It is to type in and not an up-down control.
3. This replacement of blank by -999 is not (quite the) same as doing it within the (single) output variable, because there may be additional missing values caused by the different years in the different stations.  It needs to be added after the data are unstacked and ready to be written out. Check with @dannyparsons  if need be.
4. On output, if there are spaces in the station names, (that's is in the levels of the Station factor) then the space is replaced by an underscore.

It is good that this is being done now.  The Rwanda team will appreciate it.

**Comment by dannyparsons** [comment]
I've changed the bug bullet points to checkboxes in the first comment so that they can be checked off separately. 

The missing values sounds like it should be done within the R method. It should be simple R code but I can look at that if needed.

Also @maxwellfundi it is not very clear why some of these things are bugs. It would be useful to others who don't know about the dialog to have this described. e.g. the missing values shouldn't be blank because CPT requires... etc.

On your second point of displaying a message after saving, I'm interested to know why you think this is needed? We don't have this for any other dialog which saves a file so I think this needs a justification to be done. e.g. are you suggesting this is done here only, and if so why, or on all dialogs which save a file?

**Comment by Muthenya** [comment]
The first checkbox can be checked now.
Then I guess we are now remaining with the last checkbox since the second one has been clarified by Roger and I'm don' think there is justification for the third one.

**Comment by dannyparsons** [comment]
@Muthenya @rdstern I think all the main points here have been resolved. Is that correct?

**Comment by Muthenya** [comment]
Yes, they have
