### ISSUE TITLE
Small issue in the Tidy dialogue

### ISSUE THREAD

**Issue by rdstern** [africanmathsinitiative/R-Instat#5043]
The dialogue to tidy the daily data is working well, at least for the examples I have had recently - mainly in the old Instat layout!

Today I had a new (small) problem.  Some whole years were missing.  So, when the data were imported from Excel, they came as logical columns, not numeric.  The dialogue insists on numeric, but I think it would work OK with those logical columns.  They are anyway NA all the time.

I made them numeric and then all was fine.  But perhaps the dialogue could allow either numeric or logical?

**Comment by dannyparsons** [comment]
I thought we actually agreed that the receiver would accept all columns for cases where the years are character columns. It's a rare case where it is better to allow any column and then give an error for character columns because it would be very easy to not notice that one year is missing from the list if character columns are excluded.

And here this is a reason for allowing logical columns so I suggest the receiver does not restrict to any column type.

**Comment by Muthenya** [comment]
Currently the receiver has no restrictions.

**Comment by Muthenya** [comment]
@dannyparsons could you have a look at this?
