### ISSUE TITLE
Using the new File > New with the wakefield package

### ISSUE THREAD

**Issue by rdstern** [africanmathsinitiative/R-Instat#5087]
The wakefield packages generates random samples.  I can easily use it to generate single columns.  I just put, for example, 
wakefield::animal(100)
to generaqte a single column.  That's great.

But there is also the command
wakefield::r_data_theme(n = 100, data_theme = "the_works")
or "survey" or "survey2".

This generates a whole data frame.  I tried as a command and it gave an error, namely:

Error running R command(s)

Error in file(file, ifelse(append, "a", "w")) : 
  cannot open the connection

The error occurred in attempting to run the following R command(s):
**data2 <- wakefield::r_data_theme(n = 100, data_theme = "the_works")
data_book$import_data(data_tables=list(data2=data2))**
OK

**Comment by dannyparsons** [comment]
This is an issue with the wakefield package where that function doens't work without the package being loaded. We could report this to the developers.

**Comment by rdstern** [comment]
I had loaded wakefield ealier, so did have it on my machine anyway

**Comment by dannyparsons** [comment]
I distinguish between **installing** and **loading** a package. R-Instat installs over 200 packages (including `wakefield`) but we only load a handful on start up.

When I say **loaded** I mean running the line: `library(wakefield)` in your R session to load the package into the namespace (meaning `wakefield::` isn't needed any more). You should be able to run any function from a package without loading it (if it's installed) if you use `package::` but for some reason this gives an error with some of the `wakefield` functions.

`wakefield` is one of our installed packages already but we could also make sure it loads on startup each time R-Instat opens so that this issue won't happen. It adds one more line of R code that runs on startup but I don't think it will make a significant difference to startup time.

**Comment by Patowhiz** [comment]
As @dannyparsons says, I found this issue when creating and testing this dialog. It also occurred in RStudio. There are certain wakefield functions that use a function which fails to run when the package is not explicitly loaded. It

**Comment by Patowhiz** [comment]
I mentioned the same in the PR that was addressing this dialog PR [4439](https://github.com/africanmathsinitiative/R-Instat/issues/4439)

> @dannyparsons sorry, I meant, it's that specific function that @rdstern asked me to add - `wakefield::r_data_theme(n = 100, data_theme = "the_works")` . It throws an error (**Error in r_data_frame(n = 100, id, likert(name = "Item"), likert(name = "Item"), : could not find function "r_data_frame"**), when you run it without explicitly importing the library in the first run(the function fails to identify function `r_data_frame ` of the wakefield, probably it's masked). The same applies to
> `r_data_theme(, "survey")`
> `r_data_theme(, "survey2")`
> 
> However a function like
> `wakefield::r_data_frame(n = 30, id, race, age, sex, hour, iq, height, died, Scoring = rnorm, Smoker = valid)` runs without explicitly importing the library on the first run.
> The same occurs in RStudio.

**Comment by dannyparsons** [comment]
I've set wakefield to load on startup to avoid this issue. If the problem gets fixed in wakefield itself we can remove this.
