### ISSUE TITLE
Specifying Date Format

### ISSUE THREAD

**Issue by mmumbo** [africanmathsinitiative/R-Instat#5113]
**Describe the bug**
On the make date dialog, while trying to **Specify Format** for instance when you want to change from YY/MM/DD to DD/MM/YY it does not accept the format, is this the same from your side?

**The snapshot is shown below**
![image](https://user-images.githubusercontent.com/11607243/48710353-11b1c280-ec19-11e8-9b3a-025eb9a093d0.png)

**Comment by dannyparsons** [comment]
The Specify Format is to specify the format of your text column so that R is able to know how to convert it to a Date. A Date column itself is then only displayed in a single format. 
For the standard formats you don't need to specify the format but if your text column was `1-Jan-2018` you would have to specify a format `%d-%m-%Y`, but then the new Date column would look the same.

This should be made clear in the help file since its easy to misunderstand the meaning of format.
