### ISSUE TITLE
Filter Dialog Layout

### ISSUE THREAD

**Issue by dannyparsons** [africanmathsinitiative/R-Instat#5151]
The filter dialog now looks a bit strange. Can I suggest the filter preview box has its width reduced so the dialog doesn't need to be extended. But then make it a multi line textbox so more is visible. The label could then be moved up closer the group box.

![image](https://user-images.githubusercontent.com/11214914/52333337-0ac37080-2a0e-11e9-85bc-d5e4262961e0.png)

**Comment by rdstern** [comment]
Agreed.  It is usually relatively short anyway, so even making it multi-line is a luxury.  But great if it is easy.

**Comment by dannyparsons** [comment]
@Ivanluv @Wycklife @Muthenya could someone who is free take this up?

**Comment by Muthenya** [comment]
There is a control between the label and the group box, that is, the  ucrSave for when you pick the **Apply as subset option**. Will the length of the preview textbox need to be increased since it is now multi-line like below or can it remain as it was before?

![image](https://user-images.githubusercontent.com/32125033/52407805-4cbde680-2ae2-11e9-8f8b-5f70c45cc804.png)

**Comment by dannyparsons** [comment]
This looks good in your image.
