### ISSUE TITLE
NetCDF gives an error on import on using the Options first

### ISSUE THREAD

**Issue by rdstern** [africanmathsinitiative/R-Instat#5185]
This is an almost bug, plus an inconvenience.

a) You can currently open a file, then go to Options and change the options to point, or points.  They are initially blank.  With them still blank you can press ok and it doesn't know what to do, so it gives an error message.

My simple solution is to disable OK when they are not filled in.

b) In the same Options sub-dialogue there is X and Y.  Now X is (Long) and Y is (Lat).  Could those please be added, i.e. it says X (Long) and Y (Lat).  I keep having to think which way round they are!

**Comment by dannyparsons** [comment]
The X and Y are actually supposed to display as they are labelled in the NETcdf file, which is sometimes x/lon/X/long etc. - although I realised that wasn't working in checking this and it was fixed as X! So that is now fixed and I also added the condition to display (lon)/(lat) as well when the labels in the file are just x/y.
