### ISSUE TITLE
Minor change on the importing from Excel

### ISSUE THREAD

**Issue by rdstern** [africanmathsinitiative/R-Instat#5235]
**Is your feature request related to a problem? Please describe.**
It is great that we can now import multiple sheets from Excel.  But often I would like to import only 1 sheet.
Currently the first sheet is ticked by default.

**Describe the solution you'd like**
Either have no sheets ticked by default.  Only enable ok when one or more is ticked.
Or have a checkbox (switch) at the top which says Multiple Sheets.  Default is ticked.  If you untick then you only can tick a single sheet.

**Comment by Wycklife** [comment]
@rdstern Which options should we go with?

**Comment by Wycklife** [comment]
According to me, the multiple sheets receiver seems to work the same way as Select All receiver. What do others think about this?

**Comment by dannyparsons** [comment]
Roger's suggestion is that the multiple sheets checkbox only allows you to check one item when it is unchecked - so the sheet items become like radio buttons. The Select All is different it just selects all the sheets.

I thought about not having any sheets checked by default but I think the most common case is you want the first sheet so its extra work to always have to select a sheet.

I'm not sure I see the advantage of the new button but it still adds another thing to click. Is it because you want to select the sheets one by one so that you see what they are in the preview?

**Comment by rdstern** [comment]
OK.  I can live with it, as it is.  I am usually importing from Excel files with multiple sheets and not wanting the first.  This "feature" is currently the same as in the Filter sub-dialogue, where the first factor level is ticked by default - and I get messed up by that on occasions too.  
But let's leave it as it is for now.  It works well overall.

**Comment by dannyparsons** [comment]
For the filter I think I agree we don't need the first level checked by default, because it's not more common than other levels. That could be raised in a new issue.
