### ISSUE TITLE
Adding a line to connect medians in a boxplot

### ISSUE THREAD

**Issue by rdstern** [africanmathsinitiative/R-Instat#5236]
I am trying to produce the following graph - which is easy in the old Instat - as shown below:
![image](https://user-images.githubusercontent.com/11226469/54002138-9ae2fb80-411b-11e9-8c47-bfff8ec1fa06.png)

This is a single set of boxplots with a line connecting the medians.
In R-Instat I first got the boxplots.
Then added a layer.  I used stat_summary
Then I use the layer parameters.  I make the fun.y the **median** and the geom the **line**
So far so good.  
Then I press return and I have the 2 layers.
Then I return again and try the plot.  It doesn't seem to work.
Now I return to the dialogue and find the second layer doesn't exist any more.
(In fact I later find that after the first Return, I then opt to edit the second layer and it has reset the layer parameters.)
What is wrong or what am I doing wrong?
Note: Even though the stat.summary layer is apparently no longer there, when I run again I still get the stat.summary in the R command.  I need to do a reset to get rid of the code..

**Comment by dannyparsons** [comment]
@Wycklife could you try and reproduce this?

**Comment by Wycklife** [comment]
@dannyparsons I'm going through it now

**Comment by Wycklife** [comment]
@dannyparsons I'm going through it now

**Comment by Wycklife** [comment]
@dannyparsons I've try this and getting the same issues. I have used dodoma dataset to try this.

**Comment by dannyparsons** [comment]
Can you then look into the R code and see what the issues are? Does it give an R error? Or is it that the dialog is not adding R code for the layer? Or is it adding the layer incorrectly etc.
You should be able to give a much more technical description of the problem than Roger because he's only testing as a user. Good that you've been able to replicate, but now you should be trying to debug.

**Comment by Wycklife** [comment]
We have been looking at this and we found that we needed to add the `geom="line"` as well as the `group=1` parameter into the `stat_summary` to have 

`stat_summary(fun.y = median, geom="line", group=  1, color= "blue", size = 1.5)`

@maxwellfundi  Suggests that we add a checkbox on the layer parameters to add in the group parameter into `stat_summary` so that its passed in. 

However we will need to solve the issue with the disappearing layers on the on the plot options sub dialog.

**Comment by dannyparsons** [comment]
Thanks good to see how this works now. The `group` issue is interesting because its also an aesthetic. What have we done for other geoms where group is an aesthetic and layer parameter?

If we want to make this easier for boxplots we could have a checkbox on the main dialog that would add this layer?

**Comment by maxwellfundi** [comment]
@dannyparsons At the moment we do not have any of the geoms with the ability to add `aes` on the layer parameters. 

I had discussed with @Wycklife that its alot easier to have a checkbox on main dialog but from the issue it seemed that its not whats needed. 

Do you think we can just have this checkbox on the main dialog now? @rdstern would that be okay with you?

**Comment by rdstern** [comment]
I would be ok with that

**Comment by maxwellfundi** [comment]
@Wycklife  you can now take up this and add the check box on the main dialog

**Comment by dannyparsons** [comment]
We should only have this on the main dialog if we actually want it there, not just because its difficult any other way.
I'm happy if its felt to be common enough for the main dialog. But if not, we should not make the main dialog more busy then necessary and look to solve the general problem.

**Comment by rdstern** [comment]
I agree we should try to solve the main problem.  And we may also want to connect other aspects, not least the means, quartiles and there are nice examples connecting the data points.  However, having one example as a tickbox on the main boxplot dialogue would be useful and the obvious one is either the medians or to have an option to display and then connect the means.  So the only simple ones is medians.

**Comment by dannyparsons** [comment]
How about a checkbox to connect boxplots with a line and a dropdown to choose median/mean/LQ/UQ? That would be simple as its just the function parameter in the geom.

**Comment by rdstern** [comment]
Lovely.  Could we then have more than one???

**Comment by dannyparsons** [comment]
Now you're pushing it! 
I can't think of an easy way to design that without taking a lot of space. If there was we could. The advantage of the simple dropdown is that other functions could also be typed in.

**Comment by rdstern** [comment]
I understand.  In that case could my pull-down have mean, median, quartiles, rather than lower and upper separately?

**Comment by dannyparsons** [comment]
Possibly, that would then be 2 extra layers. Someone could try to do it and see if its difficult or not,

**Comment by rdstern** [comment]
Let's start with just one then first.  The mean or median would be fine and the most used options by far.

**Comment by maxwellfundi** [comment]
@Wycklife  I have been reviewing this and works well in many ways. However I found a few issues that are easy to fix

1. When I check the `Groups to Connect` checkbox, then select `Mean `or `Median`, it produces desired results. The issue is, when i reopen then the checkbox is not checked- you might want to check your `SetRCodeForControls`

2. The Lower and Upper Quartile doesnt seem to produce any line

**Comment by Wycklife** [comment]
@maxwellfundi  On the second part, only the mean and median were to be implemented first as they are the most used options.

**Comment by maxwellfundi** [comment]
Then you can get rid of the two. @rdstern  are the quartiles needed here?

**Comment by dannyparsons** [comment]
If the items for quartiles are available then they should be working. It's not acceptable to have available features that don't work. They can either be implemented or removed, either is fine but we can't have what is there now.

**Comment by dannyparsons** [comment]
Great.
