### ISSUE TITLE
View dialogue gives error

### ISSUE THREAD

**Issue by rdstern** [africanmathsinitiative/R-Instat#5239]
When you use Prepare > Data Frame > View and opt to select the columns the 3rd option is for html in the output window.
This gives the sjplot stuff and gives the error below.  I suspect the command has changed?  

If it isn't easy to fix then perhaps we can disable for now?

**Error running R command(s)

Error: 'sjt.df' is not an exported object from 'namespace:sjPlot'
The error occurred in attempting to run the following R command(s):

sjPlot::sjt.df(describe=FALSE, altr.row.col=TRUE, hide.progress=TRUE, mydf=data_book$get_columns_from_data(data_name="Moorings_monthly", col_names=c("s_year","month","rain","raindays"), force_as_data_frame=TRUE))
OK**

**Comment by Patowhiz** [comment]
@rdstern your suspicions are true, according to [CRAN NEWS](https://cran.r-project.org/web/packages/sjPlot/news/news.html) as of sjPlot 2.5.0 the `sjPlot::sjt.df` was deprecated and replaced with `sjPlot::tab_df` . The parameter names used are also different.

```
tab_df(x, title = NULL, footnote = NULL, col.header = NULL,
show.type = FALSE, show.rownames = TRUE, show.footnote = FALSE,
alternate.rows = FALSE, sort.column = NULL, encoding = "UTF-8",
CSS = NULL, file = NULL, use.viewer = TRUE, ...)
```

I'll go ahead and replace this with the new function name.

**Comment by Patowhiz** [comment]
Different proposition.

Currently the display as html and display in separate window options don't have the feature to set the number of rows that a user wants to be displayed. It's fine for display in separate  window option because the data frame don't take long to be displayed. But for display as html if the records are many then it takes long. Was this done intentionally, if not then we could probably do this in another

![view html](https://user-images.githubusercontent.com/21179007/61949141-7c8a7900-afb2-11e9-98ea-36d8a0ff0d31.PNG)

**Comment by dannyparsons** [comment]
If easy to add then yes, it could be useful.

**Comment by Patowhiz** [comment]
We now have a new release of this package, [sjPlot 2.7.1](https://cran.r-project.org/web/packages/sjPlot/news/news.html) in which a new parameter **digits** has been added to the function for printing html.

```
tab_df(x, title = NULL, footnote = NULL, col.header = NULL,
show.type = FALSE, show.rownames = TRUE, show.footnote = FALSE,
alternate.rows = FALSE, sort.column = NULL, **digits = 2**,
encoding = "UTF-8", CSS = NULL, file = NULL, use.viewer = TRUE,
...)
```
