### ISSUE TITLE
Add a Use Model halfway dialogue

### ISSUE THREAD

**Issue by rdstern** [africanmathsinitiative/R-Instat#5263]
This might be a single Use Model dialogue or a Use Model/Object dialogue, or there might later be 2 separate dialogues.  

As it is a halfway dialogue it will be useful to something that users can try and assess whether improvements are needed.  It needs to cater for the following situations:

1. Once we have a model there are many things we can do with it.  Some are general and Predict is particularly important.  We have proposed the prediction package (single function in the package) could be used and it applies to many different types of model.  The possibility of prediction is described in #5127.  (It may be sensible for it to be a separate dialogue.)
2. In some packages the model is first fitted and then many special functions act on this model.  The extremes package is an example.  These functions are really just for the extremes package.  We already have an extremes keyboard in our existing **Model**  dialogue.  In this case we might have a similar keyboard in the new Use Model dialogue, or the same Model dialogue could add those functions, and they would just look for those extremes objects in the data selector.
3. There are some types of data (survey and survival are examples) where the data - rather than the model - is first made into a survey/survival object.  Again, the commands to make the object could perhaps be added to the current Model dialogue, and then the Use Model dialogue takes over.  Or all or some could also be added to the current Model dialogue.

**Comment by dannyparsons** [comment]
I agree with your 1 and 2. Prediction might be there, but might also need its own dialog, particularly because it often returns a column or a data frame and we want to easily be able to save this.

I am not keen to have survey objects created by the Model dialog and used in the Use Model dialog. The survey object is essentially a data frame with some extra metadata. So I don't think it would make sense to have this object accessible from the Use Model dialog because almost none of the generic functions we will have in the Use Model dialog will work on a survey object. We would be better off having a way to "convert" a data frame into a survey data frame, like we have for a shapefile data frame and then use it like a data frame. 
I would need to look more at the survival object but I suspect it might be similar to this.

**Comment by dannyparsons** [comment]
@africanmathsinitiative/developers can someone take this up for the upcoming release?

**Comment by Ogik99** [comment]
I will take this up.

**Comment by Ivanluv** [comment]
@dannyparsons  I can take this

**Comment by dannyparsons** [comment]
Here are some initial buttons:

### General
-	print
-	summary
-	anova
-	coefficients
-	fitted.values
-	residuals
-	AIC
-	BIC
-	car::outlierTest
-	car::ncvTest
-	car:: durbinWatsonTest
-	car::Anova

### extRemes
- ci
- distill
- erlevd
- findpars
- is.fixedfevd
- lr.test

**Comment by dannyparsons** [comment]
resolved by #5284
