### ISSUE TITLE
Adding labels on to the station maps

### ISSUE THREAD

**Issue by maxwellfundi** [africanmathsinitiative/R-Instat#5290]
**Describe the bug**
When I produce a map and add points for the stations, that works very well and its very impressive. However, when I want to add the labels for the stations either using geom_text or geom_label, that doesn't seem to work very well. 
This is because `data` is not added as a parameter to the `text `or `label` layer. See code below ;-

**Expected behaviour**
The points on the maps would have been labeled accordingly.

## The error message
If applicable, add screenshots to help explain your problem, particularly of error messages.
![image](https://user-images.githubusercontent.com/9798689/55482073-08ebe700-5624-11e9-9c59-804788d2f885.png)

**R script or commands**
# Code generated by the dialog, Climatic Maps
Malawi_Admin <- data_book$get_data_frame(data_name="Malawi_Admin")
Malawi.stations.updated. <- data_book$get_data_frame(data_name="Malawi.stations.updated.")
last_map <- ggplot2::ggplot() + ggplot2::geom_sf(data=Malawi_Admin, ggplot2::aes(fill=ADM2_EN)) + ggplot2::geom_point(data=Malawi.stations.updated., ggplot2::aes(x=longitude, y=latitude)) + **ggplot2::geom_label(mapping=ggplot2::aes(x=longitude, y=latitude, label=station_name))** + theme_grey() + ggplot2::theme(axis.text.x=ggplot2::element_text())
data_book$add_graph(graph_name="last_map", graph=last_map, data_name="Malawi_Admin")
data_book$get_graphs(data_name="Malawi_Admin", graph_name="last_map")

What we need is to have 
**ggplot2::geom_label(data=Malawi.stations.updated.,mapping=ggplot2::aes(x=longitude, y=latitude, label=station_name))**

I suggest, because I have found out that most of the things that people would like to do is to produce the map, then add stations and their names, then we can have a checkbox that says- Add stations names that would add these labels without going all the way to layers. 

In addition, we could have, the selectors at the top in a group box indicating which file would produce the map outline and which would be used to create the maps.

**Comment by dannyparsons** [comment]
Yes to both your suggestions.

The station name can just be another receiver with the other receivers which set the points, since the labels will come from the same data frame as the points. There's no need for a checkbox, if the receiver is blank then labels aren't added.

**Comment by maxwellfundi** [comment]
Great, I am happy with that. @Wycklife you can take up this task. 
I see a potential problem here that am sure @rdstern might be familiar with. We will have sometimes- a number of stations outside the coordinates for the country, then the map will be cluttered with labels. @Wycklife Please consider the size of the labels too.

**Comment by dannyparsons** [comment]
We might want to consider `geom_text_repel()` and `geom_label_repel()` from `ggrepel` https://cran.r-project.org/web/packages/ggrepel/vignettes/ggrepel.html.

I've found these useful before. I am not sure if there is then any case where you would want `geom_label()` over `geom_label_repel()`.

**Comment by Wycklife** [comment]
@maxwellfundi Just for clarity, do we add group box for each selector and if so, what could be the appropriate name the the group boxes.

**Comment by maxwellfundi** [comment]
So the controls on the left side (the selector and the receiver), you can have a group box saying `Map Outline` and the controls of the right- Receivers and Selector- saying `Stations`. @dannyparsons can check if these titles are sensible. But thats a minor detail at the moment. If you can get the `geom_label_repel()` working that would be good.

**Comment by dannyparsons** [comment]
The second group box can be called Points, that's usually stations but doesn't have to be.

**Comment by Wycklife** [comment]
@dannyparsons So I should change the name to points instead of Station?

**Comment by dannyparsons** [comment]
Yes I think so.

**Comment by shadrackkibet** [comment]
In addition to the above suggestions. I read a paper which can be found [here](https://scholar.google.com/scholar?hl=en&as_sdt=0%2C5&q=Homogenization+of+Climate+Data%3A+Review+and+New+Perspectives+Using+Geostatistics&btnG=) on climatic data homogenization I saw this kind of map. 
![image](https://user-images.githubusercontent.com/26301973/57786694-e2918f00-772b-11e9-8a13-4e747043082d.png)
Since this dialog is mainly meant to map stations for now. Isn't it interesting to produce such a map in R-Instat?. Perhaps even without Inset map. The red pantagon labeled stations are the candidate stations for homogenization. When I have data from different stations and I want to do homogenization I would like to map stations and then distinguish some stations as shown above. I think is a useful map that we might want to produce in future. R has evolved alot in terms of mapping and the recent addition of `geom_sf`  in ggplot2 is bringing a new dimension of mapping in R. Several mapping packages like **tmap** which follows the general idea of grammar of graphics is another nice package. **Cartogram** package is another package for producing cartograms which are better than ordinary Choropleth maps and produces nice maps in combination with **tmap** package. When working with a student here we managed to produce below maps. They look intresting for me. I we should consider this packages when we plan to make maps general in R-Instat. An online book on Geocomputation with R [here](https://geocompr.robinlovelace.net/) chapter 8 focussing on making maps in R **tmap** package is discussed in detail. Very nice maps. Extending this to animated and interactive maps will be also nice but this will require several other packages. What about Inset maps?. My thoughts.

 Below are maps from a student.


![Rplot01](https://user-images.githubusercontent.com/26301973/57790360-7b2b0d80-7732-11e9-8ff8-7d81c75a687d.png)
![Rplot02](https://user-images.githubusercontent.com/26301973/57790362-7b2b0d80-7732-11e9-9a8d-12ea3690c760.png)
![Rplot03](https://user-images.githubusercontent.com/26301973/57790363-7b2b0d80-7732-11e9-9196-44d3dcc7a3c2.png)
![Rplot05](https://user-images.githubusercontent.com/26301973/57793977-841fdd00-773a-11e9-91c1-85399ef6d1cb.png)

**Comment by maxwellfundi** [comment]
@shadrackkibet thanks for the insight about these maps. I believe if they are easily produced in R then we can also easily do them. 

I am not sure how much they might be needed by our climatic audience. @rdstern any ideas about how they are used by our climatic audience?

**Comment by dannyparsons** [comment]
Lots of very nice ideas here. 
@maxwellfundi I think the first step is how easily can you produce the first map of stations with R-Instat? Not with the full layout but a map with two types of stations.

**Comment by maxwellfundi** [comment]
I think that would not be difficult, because we would need to have the shape receiver filled to produce different shapes for the two kinds of stations.

**Comment by dannyparsons** [comment]
Well there is also two colours - black and red - and only the red ones are labelled. Can you do all that?
