### ISSUE TITLE
Histograms to show proportions or percentages

### ISSUE THREAD

**Issue by rdstern** [africanmathsinitiative/R-Instat#5343]
Currently our histograms show counts (frequencies).  How can we use our dialogues to show proportions or percentages.

There are questions on stack-overflow , for example [here](https://stackoverflow.com/questions/3695497/show-instead-of-counts-in-charts-of-categorical-variables).  

The solution appears to be to add a y to the aes.  I give an example of the additional code below:

It is just the bit in bold that needs to be added, i.e. **y = (..count..)/sum(..count..)**  The rest is easy from the dialogue.  If you multiply by 100 you get percentages and alternatively that can be done with scale_y_continuous(labels = percent).

last_graph <- ggplot2::ggplot(data=mydata, mapping=ggplot2::aes(x=wd1,**y = (..count..)/sum(..count..)**)) + ggplot2::geom_histogram(fill="blue", boundary=-5, bins=36) + theme_grey()+coord_polar(start=0)+ ggplot2::scale_y_continuous(limits=c(-2, 10))

But how can we do this sort of stuff from the dialogue, rather than the script?

**Comment by dannyparsons** [comment]
I believe the use of these special variables `..count..`, `..density..` etc. was a "quick fix" for doing some of these things in `ggplot`. I think there is now a better system for doing these described here https://ggplot2.tidyverse.org/reference/stat.html. We could have these two cases as options in the dialog.
In a single dialog this is easy to implement but will be harder to build into our general system.

**Comment by rdstern** [comment]
I like the improvement.  The ".." system seemed like a "bodge".
I notice the example you reference has the default now as  geom_histogram(aes(y = stat(count))), where we currently just have geom_histogram() as the default.  
The second example is stat(count/max(count)) which gives the highest bar as 1.
I think what I want is stat(count/sum(count)) for proportion or stat (100*count/sum(count)) for the percentage.

How do we do this on the dialogue(s)?  If I am right, then could we start by simply giving the default text as geom_histogram(aes(y = stat(count))) instead of geom_histogram().  That would be no change, but would make the editing of the script for other options so much easier.

**Comment by dannyparsons** [comment]
Yes, and we could easily have an option on the dialog: count, proportion or percentages which changes the `stat` function for each option.
So the options are:

| Option | Code |
|-------------|------------------------------|
| **counts** | `stat(count)` |
| **proportions** | `stat(count/max(count))` |
| **percentages** | `100 * stat(count/max(count))` |

**Comment by rdstern** [comment]
Yes, and overall


replace proportions above by fractions and have a checkbox for the percentages
then also proportion which is stat(count).sum(count) also with the checkbox for percentage

**Comment by Wycklife** [comment]
@rdstern  @dannyparsons  Should the check boxes be added on the main dialog or on the plot options?

**Comment by rdstern** [comment]
At this stage I would be inclined to put it on the sub-dialogue as another geom property for the Histogram options.  Later we could then decide whether we **also** want it on the main dialogue.
It could perhaps be called Statistic (or Stat).  It would have a pull-down as do many of the other options.  The default is Count, Then Fraction (Proportion) and lastly Percentage.

**Comment by dannyparsons** [comment]
It can't be on the histogram sub dialog because that is specifically for parameters to the geom function, this is about setting the y aes.
I think it could stay on the main dialog.

There is actually a better way to do percentages than I suggested, you can add `scale_y_continuous(labels = scales::percent_format())` and it will display fractions as percentages on the y-axis with a % sign too. (Eventually this goes on the Plot Options subdialog)

So I think we have a combo box for the two options (sorry I confused **max** and **sum** in my previous table):

| Option | Code |
|-------------|------------------------------|
| **counts** | `stat(count)`|
| **fractions** | `stat(count/sum(count))` |

Then a separate checkbox to "Display as percentages" which adds the code above (remember to not create a new `scale_y_continuous` function for this because this is already in the list of ggplot functions linked to the sub dialog, ask @maxwellfundi if this is unclear). This checkbox is only visible for the **fractions** option (and the third option below if we include it)

There might be a third option for `stat(count/sum(count))`

@rdstern when I wrote the option `stat(count/max(count))` I actually was thinking `stat(count/sum(count))`. But I see that `stat(count/max(count))` is in [the documentation](https://ggplot2.tidyverse.org/reference/stat.html) too. We can easily include it, do we want it? If so, what would we call it? Proportion is too similar to fraction I think. I was thinking something like "Scaled fraction" or "Scaled to unit".

**Comment by rdstern** [comment]
I like this a lot.  On the last point I prefer "Scaled Fraction".

**Comment by dannyparsons** [comment]
"Scaled Fraction" sounds good. So the options are now:

| Option | Code |
|-------------|------------------------------|
| **Counts** | `stat(count)` |
| **Fractions** | `stat(count/sum(count))` |
| **Scaled Fractions** | `stat(count/max(count))` |

Counts is the default. If either of the last two are selected, the percentage checkbox is visible.
