### ISSUE TITLE
Annoying small point about the graphics axes

### ISSUE THREAD

**Issue by rdstern** [africanmathsinitiative/R-Instat#5349]
I am pleased with the steady improvements in the "graphics system" in R-Instat.  Here is a small point that I have marked as a bug, but it is more an inconvenience.

Go to any Describe > Specific > Boxplot (say) but any example will do.  Then use Plot Options and either X-axis or Y-axis.  It always starts with Discrete as the default, which is inconvenient as we usually need Continuous.  If you change to Continuous it works fine and settings can be done.

But, when you return to the main dialogue and then return to that tab again on the sub-dialogue, it is back to Discrete again.  It just loves Discrete.

The settings under continuous are remembered, but I suggest that Continuous should be the default and it should also return to the setting that was used on a future occasion.

I assume (hope) that this is easy to fix, and I am not opening a "can of worms" here.  If so, then change the milestone.

**Comment by dannyparsons** [comment]
This is supposed to detect the type of variable used on each axis and then set to continuous/discrete appropriately. So if its not then it is probably the code doing the detection which is having some issues.

**Comment by N-thony** [comment]
@anastasia-mbithe please, can you try this? Thanks.

**Comment by anastasia-mbithe** [comment]
I have two scenarios for this issue, using a scatter/point plot; 
When the receivers are empty, the X/Y axes show discrete, when you fill the receivers with variables, the X/Y axes automatically changes to continuous.
When we do the same for the general graphics dialog, the X/Y axes remain discrete in both cases.

Looking at the code, the axes look for when the global aesthetics is >0, then it's continuous. This is what happens in the scatter/point plot.
From my point of view, looks like the problem is from the global aesthetics of each dialog, since some dialogs work fine and others don't.
I had explained this to @N-thony. Please could you give an update on the subsequent discussions you were to have concerning this issue.
