### ISSUE TITLE
The Position tab on the summaries dialogue?

### ISSUE THREAD

**Issue by rdstern** [africanmathsinitiative/R-Instat#5371]
The Prepare > Column: Reshape > Column Summaries (and Climatic > Prepare > Climatic Summaries has a Position tab on the summaries.

This has First, Nth, Last and then allows a Reordering as well.  

What is this for?  I thought it would be what I have been wishing for, namely we could include the value of another variable for those summaries where there is often a postion at which the summary is reached.

For example, for daily rainfall (column, rain) I could get the maximum value each year and also the doy (or date) when the maximum is first reached.  But I can't see how to use it for this.

Help please - what haven't I understood?

**Comment by dannyparsons** [comment]
You can use this to get the doy of the max rainfall. Because of how the dialog works you would want to use the dialog twice. First summarise the rain to get the maximum, then summarise the doy to get first (or last, can't remember which is for max/min) and order by rain.
Because you want to summarise different columns with different summaries you need to do this in 2 steps.

**Comment by rdstern** [comment]
Aaaah! Clever.  Now I understand!

**Comment by dannyparsons** [comment]
It's possibly something we want to think about being able to do in one step, or maybe just through climatic summaries.

**Comment by rdstern** [comment]
Currently I am really happy with that.  We can do it (in the 2 steps) already in the Climatic summaries.  I am just wondering about a 4th button at the top to give extremes - (summaries in general) at the Station level, and that would then include the date of the largest rainfall or the maximum temperature ever, etc.

I am not particularly concerned that it is 2 steps.  It is (sort of) 2 ideas, namely "what" and "when".
