### ISSUE TITLE
Additional feature - Conversions dialog or elsewhere

### ISSUE THREAD

**Issue by shadrackkibet** [africanmathsinitiative/R-Instat#5395]
I have stations catalogue and I would like to map all stations at KMD. Below is a section of the data.

![image](https://user-images.githubusercontent.com/26301973/60316175-32da4e80-9972-11e9-9f03-ee8dcee3a4f6.png)

I would like to have a facility in R-Instat to convert Degrees and minutes + seconds(when available) to latitude and longitudes.

This is possible in R using `dms2dd()` function from **biogeo** package.  Using `str_extract()` from **stringr** package I extract `letters (N, S, E, W)` and minutes of latitude or longitude from Minutes columns. This is already possible using Find Replace dialog . You need to know some regex to be able to give the correct pattern. How can this be made easy for users who are not familiar with Regex? Here is a section of result columns.

![image](https://user-images.githubusercontent.com/26301973/60316889-3b805400-9975-11e9-9fb9-74342b990432.png)

Another alternative is using  `measurements::conv_unit()` but this doesn't deal with "E/W" "N/S" entries, it requires positive/negative degrees.

I suggest this as another option in the conversions dialog or we can have this as a special dialog under mapping section? @rdstern @dannyparsons what are your views?

**Comment by rdstern** [comment]
It would be good to have this.

If I have understood you correctly then we can take out the N, S, E, W using Prepare > Column: Text > Transform > Substring.  Then doing from 1 to -2 will get the number part and from -2 to -1 will get the direction.

Then I have used the Calculate simply as degrees + minutes/60, but it would be better to have an extra option on the conversions dialogue, because that would also cope better with the N/S question.

Nice example.  I wonder how many countries follow the KMD example.  It isn't "tidy" to mix the minutes and the N/S or E/W?

I would also like eventually to include regex as well!

Cheers

Roger

Roger Stern
Statistical Services Centre
University of Reading, Whiteknights Road, Reading RG6 6FN
Tel: +44 (0) 118 378 6421 (or 8025)
e-mail r.d.stern@reading.ac.uk<mailto:r.d.stern@reading.ac.uk>
web: www.reading.ac.uk/ssc<http://www.reading.ac.uk/ssc>

________________________________

**Comment by dannyparsons** [comment]
We've discussed this with Shadrack and think the best approach is to write our own function so we can make a few additions to the `dms2dd()` function and also avoid having to add a whole package for a single function.

**Comment by shadrackkibet** [comment]
```

dms2dd <- function (dd, mm, ss, ns) {
  n <- match(toupper(ns), LETTERS)
  we1 <- n == 19 | n == 23
  sgn <- ifelse(we1 == T, -1, 1)
  mm1 <- ifelse(missing(mm), 0, mm)
  ss1 <- ifelse(missing(ss), 0, ss)
  if(missing(dd))  stop("degrees must be supplied")
  decdeg <- (dd + ((mm1 * 60) + (ss1))/3600) * sgn
  return(decdeg)
}
```
@dannyparsons here is the implementation of the R function. Any comments?

**Comment by shadrackkibet** [comment]
Here is the design. 

![image](https://user-images.githubusercontent.com/26301973/62070573-73640b00-b243-11e9-89b7-017b61727f1d.png)

**Comment by dannyparsons** [comment]
Looks pretty good. Few small points:
- We can add a check that `ns` only contains the right letters, currently I could have "y" and it wouldn't complain.
- `we1 == T` can be replaced with `we1`, since it's already logical
- instead of checking if `mm` and `ss` are missing I would have 0 as their defaults, then a check is not needed. That's then clearer to the user what is happening
- it would be good to have a slightly different name for the function than `dms2dd` to avoid a clash
- I think you want `mm1 / 60` instead of `*`
- We can have a check that `mm` and `ss` are between 0 and 60
- If `ns` is applied then `dd` must be positive (I think that's right?) as another check

I think adding these checks are important because its good quality control of the type of data that will be used for this

**Comment by shadrackkibet** [comment]
Thanks, yes it is true that when `ns` is provided then `dd` should be positive. On your 5th point, I want  `/` and not `*` because I have minutes converted to seconds.

```
convert_to_dec_deg <- function (dd, mm = 0 , ss = 0, ns) {
  n <- match(toupper(ns), LETTERS)
  if(!all(toupper(ns) %in% c("E","W","N","S"))) stop("ns must be one of E, W, N or S")
  if(missing(dd))  stop("dd must be supplied")
  if(!all(mm %in% 0:60)|!all(ss %in% 0:60)) stop("mm and ss must be between 0 and 60")
  if(!missing(ns)&any(dd<0)) stop("dd must be positive") 
  we1 <- n == 19 | n == 23
  sgn <- ifelse(we1, -1, 1)
  decdeg <- (dd + ((mm * 60) + (ss))/3600) * sgn
  return(decdeg)
}
```

I am not sure if it is common to have N/S E/W column. I think if this is not available then `dd` has positives\negatives. What do you think,  should we also add a check if `dd` has positives and negatives then `ns` isn't needed.

**Comment by dannyparsons** [comment]
You don't want `%in% 0:60` because that only allows integers.
I've simplified a bit. I don't think we get too complicated with the checks, if `dd` has negative values and `dir` is also supplied they should go back and decide what they want to do. I've modified it so that `dir` is not required. We don't have to use this if we don't want to.
A length check would be good but if any are length 1 then that shouldn't get any message, otherwise it should give an error since we can't calculate with different lengths.
We should also check it works with missing values - if any component is missing the result is missing.

```R
convert_to_dec_deg <- function (dd, mm = 0 , ss = 0, dir) {
  if(missing(dd))  stop("dd must be supplied")
  if(!missing(dir)) {
    dir <- toupper(dir)
    if(!all(na.omit(dir) %in% c("E", "W", "N", "S"))) stop("dir must only contain direction letters E, W, N or S")
  if(any(dd < 0)) stop("dd must be positive if dir is supplied") 
  }
  if(!all(mm >= 0 & mm <= 60, na.rm = TRUE)) stop("mm must be between 0 and 60")
  if(!all(ss >= 0 & ss <= 60, na.rm = TRUE)) stop("ss must be between 0 and 60")
  sgn <- ifelse(is.na(dir), NA, ifelse(dir %in% c("S", "W"), -1, 1))
  decdeg <- (dd + ((mm * 60) + ss)/3600) * sgn
  return(decdeg)
}
```

**Comment by shadrackkibet** [comment]
Thanks.
