### ISSUE TITLE
Simplifying the Define Climatic Data system

### ISSUE THREAD

**Issue by rdstern** [africanmathsinitiative/R-Instat#5428]
I am thinking here of the dates part of the system particularly.  This is what is filled automatically on many of the climatic dialogues.  This follows discussions with @volloholic .

I propose we only define one (date value) at a time.  For example, for Dodoma we sometimes need doy and sometimes s_doy.  Only one is defined at a time.  If you want to change then you can.  So you could do some analyses for Jan to Dec with doy.  Then you return to the dialogue with the shifted values.
This saves a lot of housekeeping for the system.
In the dialogues it is completed if that column is found - otherwise it provides all columns.  So the "climatic system" becomes a convenience.  You don't have to use it, but then nothing is completed for you.  

While we are doing that, should we add Lat and Long to the climatic definitions?.  Then it could be used by data frames with Station Lat and Long and they could also be auto-completed.  I am thinking of the mapping etc dialogues here. 

I have put this as 0.5.3 simply so we discuss by then - unless it is simple.

**Comment by shadrackkibet** [comment]
In addition to the above, this dialogue should give a message somewhere when defining variables as climatic is successful.

**Comment by dannyparsons** [comment]
I think these will be good improvements to the system.

**Comment by maxwellfundi** [comment]
Yes, Shadrack you are right. I think a message box to say it's successful
would be an awesome idea.
Mostly people don't know if the operation is successful or not because they
are used to see some something happen on clicking ok.

**Comment by dannyparsons** [comment]
An output message when defining is now done.

**Comment by dannyparsons** [comment]
The changes in use of defined climatic variables (when merged) with require some changes in climatic dialogs:

- The method `SetClimaticType` can still be used - but what it does will change. Instead of restricting the selector to only show variables of a certain climatic type it will set the receiver to autofill the variable of that type if one and only one exists, and will still show the full list of variables.
- Some dialogs like Climatic Summaries still use `.AddIncludedMetadataProperty("Climatic_Type", {Chr(34) & "station" & Chr(34)})` instead of `SetClimaticType`. This will need to be replaced by `SetClimaticType(Chr(34) & "station" & Chr(34)` since they now do different things.
- The selector headers will need to be changed - since it will no longer be only "year variables" in the selector.
- We will have to restrict the receivers to appropriate types e.g. "numeric", "factor", on climatic dialogs now as all variables will be shown by default - not all receivers needs to be restricted but e.g. element should be "numeric".
- Set climatic type for more receivers! e.g. QC temp can now set tmin and tmax receivers to those types so they autofill but will still be changeable.

**Comment by rdstern** [comment]
They sound great.  One small change I would like to confirm will happen automatically in the PICSA rainfall is that the station will (by default) be included in the facets on the main dialogue.

**Comment by dannyparsons** [comment]
Yes, the good thing is that we can now set two kinds of types for a receiver. A facet receiver can be restricted to only show factors (if we want) and also have an autofill type which is climatic - year variables so if there is only one climatic - year variable it will autofill, and the selector will show all variables of the first type (factors in this case).

I have set it up so that the climatic type must also be the same type as the restriction i.e. a receiver for climatic - year will not autofill if your year variable is numeric and your receiver only accepts factors. I know this could cause issue but we just need to be careful what we restrict.
In this case we could decide not to restrict a facet receiver to factors so that a numeric year would still be accepted.

**Comment by dannyparsons** [comment]
The system is now implemented meaning that setting the **climatic type** of a receiver only controls what is autofilled by default, other variables will still be displayed in the selector.
This means we likely want to set the climatic type for more receviers now, where we have an obvious default but we previously didn't want to restrict what the user could choose. 
Please add suggestions to the following list. Or disagree with some of these, they are my initial quick ideas.

| Dialog | Receiver | Climatic Type |
|-----------------------|----------|---------------|
| PICSA Rainfall Graphs | Facet By | Station |
| QC Rainfall  | Element | rain |
| QC Temperature  | Element 1  | tmax  |
| QC Temperature  | Element 2  | tmin  |
| Climatic Summaries | Element | rain |
| Wind Rose | Wind Speed | ws |
| Wind Rose | Wind Direction | wd |
| Wind Rose | Facet By | station |
| Display daily | Element | rain |
| Spells | Element | rain |
| Extremes | Element | rain |

**Comment by rdstern** [comment]
@dannyparsons  I agree with the above:.  We can add gradually to it:

**_Fill Date Gaps_** - this may have been updated.  Currently the date is autofilled and the focus remains there.  The focus should be on the factor - Usually the station.  This could be done after the data has been defined as climatic.  If so, then the Station should be filled.
**_Inventory_** Focus is fine.  Can we have all the defined elements as the default?
_**Climatic Boxplot**_  I tried with the recently merged version and only rain and the month was included.  The station, date and doy should be added.  
Ideally for the element, if a temperature is included then it is added.  (perhaps the next element defined is included after rainfall.  Otherwise my complicated request would be that if **if the only climatic element defined is rainfall** then it is included.  And, if it is included, then the > 0 checkbox is ticked and also the variable width.  If that is too difficult then just include rainfall anyway if it is all that is included.
**_Transform_**  Rainfall.  If climatic without rainfall then the first climatic element.
**_Conversions_**  If on rain, then rain, on temperature then first temp, on wind speed the ws if exists

**Comment by shadrackkibet** [comment]
> Fill Date Gaps - this may have been updated. Currently the date is autofilled and the focus remains there. The focus should be on the factor - Usually the station. This could be done after the data has been defined as climatic. If so, then the Station should be filled.

I have changed focus for this [here](https://github.com/africanmathsinitiative/R-Instat/pull/5425/commits/ced8b80e056242c5a127fc05712ad9405f12ddc9) but not auto-filled.

**Comment by dannyparsons** [comment]
I think we could add a further metadata property for climatic data. 

`element_type` - It has 3 values: 0 - not an element column (e.g. station), 1 - an element column, 2 - the primary element column (this would be rain by default but changeable on the define dialog)

So `element_type` of 1 or 2 property would autofilling all elements on the inventory plot dialog.
The primary element could be used on dialogs such as transform, summaries, display daily, which you want as your main element. 
We can also set it up so that if you haven't defined a primary element, but you only have one element, this is considered the "primary" element. I think this would give us some powerful flexibility for autofilling.

**Comment by dannyparsons** [comment]
I think something discussed but not written down was that you can now only have one column for each climatic type. i.e. there is only one year column. Is that correct? It hasn't been implemented in the code yet.
With the new system, there wouldn't be much use for having two columns defined as the same type because it would then prevent the autofilling and it's now not being used to restrict the selector so its not doing anything really.

**Comment by rdstern** [comment]
Yes I was assuming that.  You are welcome to have tow day-of-year columns, say, but only one will be defined at a time.  So you could then easily do an analysis from January to December.  Then later, redefine the date elements and do an analysis for the shifted dates.

You could then, alternatively, change the automatically filled in variables on each dialogue - good luck if you went that tortuous route!

**Comment by dannyparsons** [comment]
Another point related to this is that the **Use Date** dialog currently automatically defines year, doy etc. columns as climatic, if the data frame is already climatic - which is useful to avoid having to go back to the define dialog.  Now with only allowing one column of each type its not so clear this should be done in the background.

I think its obvious that if you create a year column in **Use Date** and there is no year column defined as climatic already then the new column becomes the climatic year column.

What if you define a second year column (maybe shifted) and you already have a year column defined as climatic? I suggest the second column is then **not** defined as the new year column, and this needs to be done manually in the defined dialog.

**Comment by rdstern** [comment]
I agree with all you are saying here.  It may also apply when you make a date variable?
You could define a data frame as climatic with just the date variable defined.  (Perhaps also with just year, month, day, but without a date variable?)
Then you return to the Climatic > Date and define a date variable.  If this is the only date variable, then it is added to the definition.
Similarly, (as you say above) if you had a date variable and now define the year, month, etc.  Then they can safely be added to the climatic definition if they are the only ones.  But not otherwise.  
This could get slightly complicated if you define in multiple ways.  This is currently for year and month.  For the year, it is only the simple year that is part of the definition.  I think defining the year "label" e.g. 1922/23 is not sensible as part of the definition?
For the month you could define a numeric value and abbreviated, say.  Then it is abbreviated that is added to the definition.
When something is added, then should there be a print-out in the output window?

**Comment by dannyparsons** [comment]
Currently nothing is done with the date column and I think it is different because a different date variable may be invalid (duplicates, missing values) so you can't just change the date column so easily without the checks. Since you can't define a data frame as climatic without a date variable, I don't think we need to add anything automatic here.

There's no distinction in the climatic system for numeric/factor/labelled columns so any of these types can be set as the year/month column etc.

If you create two month columns in one go then maybe the "first" should be defined, where the order is numeric>abbreviated>full, or none of them?

**Comment by rdstern** [comment]
OK for the date column.  On the month variable, if it is labelled then I would go with the "lowest" being defined where numeric>abbreviated>full.  If you defined full, then this is probably what you want to see in the results.

**Comment by dannyparsons** [comment]
ok sounds good

**Comment by dannyparsons** [comment]
I'm also setting it so that a doy_365 column from **Use Date** is not defined as the climatic doy column (even if there is none). Only the doy_366 column will be automatically defined as the climatic doy column. I assume that's sensible.
