### ISSUE TITLE
Correct the order of commands given from Prepare > Column: Calculate > Calculations

### ISSUE THREAD

**Issue by rdstern** [africanmathsinitiative/R-Instat#5548]
When the calculate command is given it first attaches the data frame.  Then the comment is given, and then the calculation.  Here is an example:

![image](https://user-images.githubusercontent.com/11226469/66670368-8175d500-ec51-11e9-9213-bee1591f710e.png)

If the command is passed to the script window, then the attach is omitted.  So the result is:
![image](https://user-images.githubusercontent.com/11226469/66670534-efba9780-ec51-11e9-8a2e-308b54c101b2.png)

I hope this might be very simple to correct?

**Comment by Patowhiz** [comment]
This is because the attach and detach commands are being run on Before_Click_OK and on Click_OK events respectively. We can quickly fix this by adding the before_ClickToScript and ClickToScript events which will be adding the commands.

However, I noticed another issue, the comment is not the first item generated by the dialog, this is different from the other dialogs. @dannyparsons I checked on the code that generates the dialogues scripts and noticed that the comment is not added before the before_ClickOK event. Was this done intentionally?

![calculator](https://user-images.githubusercontent.com/21179007/66902663-ae3b3b00-f009-11e9-8a07-bb2bef730859.JPG)

**Comment by Patowhiz** [comment]
This problem is much deeper than I thought. We don't have the equivalent events of ToScript and equivalent way of arranging the scripts to be run in regard to before_ClickOk and On ClickOk when it comes to ToScript functionality.

**Comment by rdstern** [comment]
@Patowhiz I believe that after discussion with @dannyparsons and others it may be relatively straightforward to fix this.  At least that's what I think Danny said?

**Comment by rdstern** [comment]
This now seems to be fixed.  So I am closing it.
