### ISSUE TITLE
Calculator

### ISSUE THREAD

**Issue by shadrackkibet** [africanmathsinitiative/R-Instat#5580]
**Describe the bug**
Perhaps this is reported elsewhere, if yes please close this. The try button is really useful in the calculator to check errors in command. If there is an error in command I think it is logical not to allow a user to click Ok, otherwise, there will be an error message generated.
**Expected behaviour**
The textbox should turn **red** and Ok disabled. I think also we should apply the same idea in other places where we use Try button eg Hypothesis testing

**Screenshots**
![image](https://user-images.githubusercontent.com/26301973/69022861-ba7e3380-09cd-11ea-9281-a1b68435658b.png)

**Comment by rdstern** [comment]
I agree it is very useful and we are currently adding Try to more dialogues.  
But I also often still use Ok, because the Try information doesn't tell me what the error is.

**Comment by Ivanluv** [comment]
@rdstern  should I add the property of the textbox turning red  when the command prodeces an error ?

**Comment by rdstern** [comment]
Up to you and could check with the others.  I really like the Try textbox and (in general) I like consistency.  Usually the textbox turns green for an ok command and red if an error is detected.  It is different here, because it gives the result (or part of it) when it works.  And it says there is an error otherwise.  As it is different anyway (for a good reason) I am quite happy as it is.  The red in a large textbox is a bit "in your face" and I am not sure we need that.

If you are discussing the Try textbox with David and Danny it may be a good time to check #5604 with them, i.e. is there a way I could click on something when there is an error, so I get more details about what it is, e.g. is it a bracket missing.
