### ISSUE TITLE
Two variable graph dialogue

### ISSUE THREAD

**Issue by rdstern** [africanmathsinitiative/R-Instat#5582]
Basing this on the design of the 2-variable summarise might be quick - I hope, and could be great.
a) There would be just the same main part with numeric by numeric, etc as in summarise.
b) Then the current sub-dialogue is very limited.  It doesn't give options of display, just the type of graph.  I strongly propose that this be moved to the main dialogue, where only 1 of the 4 options is available - depending on the combination of numeric by numeric, etc.
c) If there are multiple elements in the receiver, then there will usually be facets - I assume with one for each of the receivers.  This will often be a situation where Free y scale is needed, so that could also perhaps be on the main dialogue.  It is currently nowhere.
d) The by option would have a facet for each level of the second variable.  (Rather than considering it as the x-variable in the plot.  So with multiple there would usually be 2 facet variables.  So, thyere might be by (row) and by (col) as options where you choose how to use the second variable.
e) We keep a sub-dialogue for other options of the plotting.  This could usefully become a mini-version of the main plotting sub-dialogue.  For example, for facets the only option may be margins.  (Or we may be able to include our main graphics sub-dialogue.  In that case I would like margins to be on the main dialogue, i.e. we add a few more common potions to make it rare that the sub-dialogue is needed.  There may also be a useful half-way house, where we have the full set of options and also a special small set of common additions.)

**Comment by dannyparsons** [comment]
Currently there's no real difference between **numeric by continuous** and **continuous by numeric** on this dialog. In the 2 variable summarise dialog **numeric by continuous** does summaries by the levels of the factor and **continuous by numeric** does ANOVA.
So my suggestion is to have the following as the defaults.
**numeric by continuous**: standard boxplots for each factor level (same as currently)
**continous by numeric**: something like the graph below, because this relates to ANOVA ideas. Either with or without points by default.

I think the graph types available can be same for both options because they are all possible with both, just the defaults change.
``` r
ggplot(iris, aes(Species, Sepal.Length)) + 
   stat_summary(fun.y = "mean", fun.ymin = "mean", fun.ymax = "mean", size= 0.5, geom = "crossbar", colour = "red") + 
   geom_jitter(width = 0.2, alpha = 0.2) + 
   stat_summary(fun.y = mean, geom = "hline", aes(x = 1, y = Sepal.Length, yintercept = ..y..), inherit.aes = FALSE)
```
![image](https://user-images.githubusercontent.com/11214914/70853139-dfb57300-1ea1-11ea-8640-0b7d4102cec1.png)

and with multiple factors - the factors are "stacked" by the dialog so it's possible to do a facet for each factor, same y but different x's.
![image](https://user-images.githubusercontent.com/11214914/70853341-8438b480-1ea4-11ea-9364-b2e4b89387a5.png)

**Comment by rdstern** [comment]
I like that idea.  And it seems appropriate that the default is a sort of graph that corresponds to ANOVA.  Is it sensible (easy) for those graphs to offer options for the line to be the median or the mean, and perhaps also to optionally include quartiles?  I think I'd prefer including points to be the default.

It isn't here, but I am very conscious of the fact that some are obsessed by bar charts (or column charts).  I need to look through for one variable and two variable to see where they figure and also what easy alternatives we offer.  That's also going to be really important for the teaching.

**Comment by dannyparsons** [comment]
Option for mean/median is easy to add. 
I've called this graph "Summary bars" but realise now this could be confusing with "Bar charts" so I'm open to a better name.
I've removed Dot Plots from categorical by categorical, since we removed it as a dialog, and replaced with mosaic plots. Do we want pie charts too? Are there any other obvious plots?
