### ISSUE TITLE
Remember the directory when using the R-Instat library

### ISSUE THREAD

**Issue by rdstern** [africanmathsinitiative/R-Instat#5587]
Open from Library seems to work well.  I am thinking here of the Instat files.  When I use Open from Library or the library in Open and tidy NetCDF files it always goes to the right place.
I would like the ordinary File > Open from File to be separate from the Open from Library.  

Currently if I use Open from File I then go to the directory I need.  Then, the next time it returns to that directory.  However if I have an Open from Library then the Open from File has forgotten the previous directory and now takes me to the library.  I don't like that, because if I wanted to return to the library then I would have used that dialogue (or Library button in the Open NetCDF dialogue).
@volloholic says this is easy to do and could be a good task for @Patowhiz?  It should be done only in the Open from Library code.  It would proceed by saving the location of the last file there and then restoring that location when the library call is done.  There shouldn't need to be a change anywhere else.

I hope he is right!

**Comment by Patowhiz** [comment]
Well, yes I agree this is doable at the **Open from Library** dialog. The reason as to why the dialog overwrites the previous values of open from file is because they are using a shared instance. When you just call an **anyformdialog.ShowDialog()**, basically what VB.Net does is it just instantiates the dialog for you and puts it in memory. When you call the same statement even somewhere else, it retrieves it from the memory instead of creating another. So you end up manipulating just 1 object. This is somehow memory efficient but it leads to such problems.

I can use another easier way and just have the **Open from Library dialog** instantiate it's **own** **Open from file dialog**. This will ensure that the dialog doesn't overwrite the shared object. That way I don't need to bother with saving and restoring whatever values were set when opening the dialog from a different location. Which will help in code separation etc.

**Comment by rdstern** [comment]
Two more suggestions for the Open from Library.  At least the first (I assume) will be easy.
When I use Open from Library I su=ometimes want to look at multiple examples from the same package.  Currently it doesn't seem to remember the last file I used.  

As an example try the agrecolae package where there are many datasets.  When I return to the dialogue having opened a data frame I return to the top of the list of datasets, and not to where I was before.  I would like to carry on down  - looking at the datasets.  I assume it could remember where I was last?

More difficult (I assume) is to investigate reading more of the datasets, i.e. some that are more complicated than a single data frame.  I think quite a lot are a list of multiple data frames.  Here is an example I could read 

```
# Code generated by the dialog, Open Dataset from Library
utils::data(package="agricolae", X=DC)
DC <- DC
data_book$import_data(data_tables=list(DC=DC))
rm(DC)
```
This is the R-code and it gives an error.  If I add to it, with [[2]] then it reads fine and reads the second data frame from the list of 3, i.e. :
```
# Code generated by the dialog, Open Dataset from Library

utils::data(package="agricolae", X=DC)
DC <- DC
data_book$import_data(data_tables=list(DC=DC[[2]]))

rm(DC)
```
Could we extend the reading for these examples by detecting it is a list and reading all data frames into separate data frames?

I know there will be other examples that still can't be read, but this would be useful.

**Comment by Patowhiz** [comment]
@rdstern this is now solved.

> When I use Open from Library I su=ometimes want to look at multiple examples from the same package. Currently it doesn't seem to remember the last file I used.

**Comment by rdstern** [comment]
Great. So closing.
