### ISSUE TITLE
PICSA Rainfall Graph Dialog

### ISSUE THREAD

**Issue by Patowhiz** [africanmathsinitiative/R-Instat#5707]
When you select from the receiver from single Variable to multiple variable, the selector shows date columns only instead of numeric variables.

![3](https://user-images.githubusercontent.com/21179007/74467053-705ffd80-4ea9-11ea-9186-749b765b03c2.JPG)

**Comment by rdstern** [comment]
Is this a simple fix @Ivanluv?

**Comment by Ivanluv** [comment]
This is happening because the `SetExcludedDataTypes` function is including variables for the multiple receiver and at the same time excluding the variable for the single receiver.So am not sure if thats how its supposed to work or @Danny  should I edit the ` ucrMultipleVariables.SetIncludedDataTypes(strExclude)` code in `SetExcludedDataTypes` to ` ucrMultipleVariables.SetExcludedDataTypes(strExclude)`.
