### ISSUE TITLE
Illegal file name in File Open dialogue

### ISSUE THREAD

**Issue by rdstern** [africanmathsinitiative/R-Instat#5725]
At last I am (again) back on the track of problems we had reading Excel - and also perhaps csv files into R-Instat.  I thought it was sheet names with spaces.  But I think that may be ok.  It seems to be the file names that are not fully trapped?  Here is an example where there are some French accents.
[DonnéesClimatiquesSadoré 1983_2014.xlsx](https://github.com/africanmathsinitiative/R-Instat/files/4235867/DonneesClimatiquesSadore.1983_2014.xlsx)

I hope this might be easy to fix?  Of course the work-around is just to rename the file!

**Comment by dannyparsons** [comment]
Just to check, are we getting the same error here? This is what I get when I choose the file. The dialog then doesn't show any sheet names.

![image](https://user-images.githubusercontent.com/11214914/75039800-128f6f00-54c2-11ea-8bfe-6f49d28b9dcb.png)

**Comment by rdstern** [comment]
That's the same that I got.

**Comment by dannyparsons** [comment]
Yes it's the accents. I'll check if there's anything quick, otherwise we should put this in writing for users and workshops, particularly for West Africa!

**Comment by dannyparsons** [comment]
I think what's happening is that the file name is getting slightly modified in the front end, possibly the accents are coded slightly differently. Then when it's passed to R this error message is saying that the file can't be found, because it interprets it as a different path to what it actually is.
Not as simple to identify and fix as I hoped. I suggest we inform users of this issue and recommend renaming files to import.

**Comment by Patowhiz** [comment]
The file opened on my machine? @rdstern did you get this problem after the changes made on the import dialog?

**Comment by Patowhiz** [comment]
Oh! I understand why it opened, when I downloaded the file, chrome just renamed it for me to equivalent English name

**Comment by lloyddewit** [comment]
Issue 1:
If the user selects `File / Open From File ...` then the file open dialog opens. If the user selects `DonnéesClimatiquesSadoré 1983_2014.xlsx` and tries to open it, then R-Instat calls the following R command:

`readxl::excel_sheets(path=""C:/Users/steph/OneDrive/Desktop/DonnéesClimatiquesSadoré 1983_2014.xlsx"")`

This command incorrectly encodes the special characters in the file name. This makes the file name incorrect, and means that the file cannot be found or opened.

The solution is to force R to correctly encode the file name. This can be done using `enc2native`:

`readxl::excel_sheets(path=enc2native(""C:/Users/steph/OneDrive/Desktop/DonnéesClimatiquesSadoré 1983_2014.xlsx""))`

I put a break point on `dlgImportDataset.vb` line 790, and forced this change in the debugger. It worked but I did not change the R-Instat code yet. If the user then selects a single sheet then the data frame name is set to the name of the sheet. For this file, none of the sheet names contain special characters. The sheets are imported without any error messages and the bug appears to be solved.

However, if the user selects all the sheets then the data frame name is set to the name of the file (including the special characters). This causes a 2nd issue ...

Issue 2:
The proposed data frame name contains illegal characters:

![image](https://user-images.githubusercontent.com/57253949/77223908-0ea64980-6b61-11ea-85b6-6edd293cc5d3.png)

This triggers the following errors:

![image](https://user-images.githubusercontent.com/57253949/77223722-65128880-6b5f-11ea-99ba-8de03f6f86bd.png)
![image](https://user-images.githubusercontent.com/57253949/77223750-9c813500-6b5f-11ea-8342-6f3d15fcf255.png)

The variable name causing the issue is set from `strFileName` (a public data member of `dlgImportDataset`). The solution is to ensure that there are no special characters in `strFileName`. This variable is set in `dlgImportDataset.vb` lines 556 and 969.

Next steps:
I will try and implement the identified solutions for issue 1 and issue 2.
