### ISSUE TITLE
Line Plot Multiple Variables

### ISSUE THREAD

**Issue by Patowhiz** [africanmathsinitiative/R-Instat#5747]
@rdstern I don't know if this is a bug or it's done that way intentionally.

When I select multiple variables in the Line Plot dialog, the factor receiver is disable and also the plot options are disabled. That means I can't even do facets for multiple variables. I think we had a similar issue during the workshop.

Is this a bug?

**Comment by rdstern** [comment]
@dannyparsons may comment further.  The factor being disabled is intentional, because the data are stacked behind the scenes and so the index of the stacked data becomes the factor.
Having the plot options disabled has been (I think) in case there are options that are inconsistent with the stacking.  I do facets by having it on single, then doing the facets and then going back to multiple.  It then "remembers" what was done in the sub-dialogue.  But that (at the same time) negates any reason for disabling the option.  Perhaps it should therefore be enabled?  We want to make things simple - and this feature is against that!

**Comment by Patowhiz** [comment]
@rdstern in that case, shouldn't we be hiding the receiver instead of disabling? Though I can see the receiver still writes to the script

**Comment by rdstern** [comment]
I am quite happy here that we disable, rather than hide the receiver.  Usually I prefer to hide in these circumstances, but this time it is easier to explain to a user what is happening, if the receiver is still visible, i.e. that effectively the multiple variables are becoming the factor.

**Comment by Patowhiz** [comment]
Okay, I'm closing this issue then. I've understood why this is the way it is and I agree with the functionality. I guess we will have all that in the help menu somehow.
