### ISSUE TITLE
Import file with an odd extension

### ISSUE THREAD

**Issue by rdstern** [africanmathsinitiative/R-Instat#5788]
[LIVING01_test.zip](https://github.com/africanmathsinitiative/R-Instat/files/4599826/LIVING01_test.zip)

This is a small file of the type sent by Zambia Met service.  It has the extension dly.  Currently the importing (using rio) assumes the format from the extension.  So if I change the extension to txt it works well.
But rio gives the option to override the default.  If I include the argument format =",", then it reads fine.  That's a bit odd to me, because this file isn't comma separated, but it works fine from the script window.  
Ideally it would check this earlier, so it can give a preview in our dialogue.

**Comment by Patowhiz** [comment]
Aha! this is a good observation and question. Package `rio` allows to use _shortcuts_ in place of _character string code_ when using the "format" parameter specifier. For instance shortcut " `,` " can be used in place of "`csv`". What this mean the `rio` package will assume the file as `csv`. So the sample code below will give you the same results.

```
x <- rio::import(file="E:/LIVING01_test - 2.dly", format ="csv")
x <- rio::import(file="E:/LIVING01_test - 2.dly", format =",")
```
In this case, you are technically instructing `rio` to **ignore or override** the extension `.dly` and assume the file has extension `.csv` and therefore to read it as a normal `csv` file.

Now, remember that rio has good features like automatic detection of the **character separator** of a `csv` or `txt` file, so in this case it goes ahead and uses these features to import  the file without additional specification.

So this may look odd but its actually not odd. You are basically telling `rio`, assume the file is `csv` and use your powerful autodetection of the **character separator** to know how you will import the file!

In regards to the file not showing in the preview. This is because of how the dialog is implemented. Currently it doesn't have an interface for the user to specify how the `rio` package should override the file extension, so the R code for `rio` tries to execute the file as `.dly` file which is not supported.

I hope my long explanation makes sense...

More explanation of how the import command works is available in this [link](https://cran.r-project.org/web/packages/rio/rio.pdf)

**Comment by Patowhiz** [comment]
@Ivanluv I've noticed you have already tried to address this issue. You can either solve it the way you have done it or just take advantage of how rio is able to simply override the file format. Both should work fine and have minimal changes.

**Comment by Patowhiz** [comment]
I would also like to add that a  .dly format is a simple variable length file with the elements blocked into fixed positions (e.g., variable is given in spaces 18-21)

**Comment by rdstern** [comment]
@Patowhiz said (I think) that he is waiting for my response on this issue.  I am quite sure how to respond.  If changing what it doesn't recognise to format = "csv" will work as I think I understand you mean, then that would be good.  Of course it isn't csv here - it has spaces between variables I think.  I assume that still works for this file.

**Comment by Patowhiz** [comment]
Thank you for the feedback @rdstern. Will solve this in a more general manner.
