### ISSUE TITLE
Histogram, boxplot and bar chart dialogs

### ISSUE THREAD

**Issue by shadrackkibet** [africanmathsinitiative/R-Instat#5800]
**Question:** Why is this dialog called histogram? It doesn't produce histograms only, it does density and frequency polygon. 

![image](https://user-images.githubusercontent.com/26301973/82787466-248cff00-9e6f-11ea-9069-aaf6632fe6a7.png)

Similar case here

![image](https://user-images.githubusercontent.com/26301973/82787764-d0cee580-9e6f-11ea-9a12-6a9053626b07.png)

Different case

![image](https://user-images.githubusercontent.com/26301973/82787806-e9d79680-9e6f-11ea-8ad1-bd61c42caf3b.png)

**Comment by shadrackkibet** [comment]
@rdstern @dannyparsons any comments on this?

**Comment by HawardKetoyoMsatsi** [comment]
From my discussion with @shadrackkibet and @rdstern menus for these dialogs could be renamed so that the name can reflect the exact plots in the given dialog. From Describe>Specific> we can have the menus as **Histogram/Density/Frequency...** instead of **Histogram...** and **Boxplot/Jitter/Violin plot...** instead of **Boxplot...** and **Bar and Pie Chart...** instead of **Bar Chart...**. The same names will be used for the dialog names. Another option was to have a tooltip that will indicate all plots found in a given dialog.
Further suggestions were to rename the menu **Describe>Specific>Scatter Plot...** to **Describe>Specific>Point Plot...**
**Describe>Specific>Dot Plot** and **Describe>Specific>Multiple Response** menus should be made not visible until they are fully implemented.
@rdstern perhaps you could comment something on this
