### ISSUE TITLE
Add a new Structured menu to R-Instat

### ISSUE THREAD

**Issue by rdstern** [africanmathsinitiative/R-Instat#5839]
This is from @volloholic and has grown from looking where to add time series analysis into the current menu structure in R-Instat.
The idea is to have a **_new Menu, called Structured,_** just after the Model menu, so before Climatic.
This would have the same general structure as the whole system, so Prepare, Describe, Model.  (I don't think we need File, at least initially.)
Currently I suggest the Menu as follows:
```
Structured
Define (dialogue moved from Prepare menu.  Only item currently in the Prepare section.)
-------
Describe
-------
Model
```
In the **_Describe_** section we either  have a submenu, perhaps initially as follows: 
```
Circular
Low-Flow
Survival
Time Series
```

Or we have **_Describe: Circular_** on the main Structured menu, etc

Similarly for the Model section.

We have (at least) four types of structured data.
1) **_Circula_**r is currently the only type of data in the **_Prepare > Define_** menu.  We are ready to define time series data (ts, xts, zoo).
2) We are also adding the lfstat package (for hydrology) and this has the **_lfobj_** object, which is usually created from a ts object.
3) The **_surviva_**l package defines a survival object
4) **_Time series_** may be ts, or xts, or zoo object.

I am including quite a number of people, simply so we discuss this issue and can proceed reasonably quickly.  It is quite a big change, but is growing on me.  It fits with the R principle of defining structures and these are all examples where there is a key variable, plus additional meta-data.  The extra data may be because of an additional variable, e.g. the censoring variable in survival or in information derived from the structure or additional variables, such as time series.

**Comment by dannyparsons** [comment]
I like the idea of separating these out from the main menus.

On the structure of the menu, I would first subdivide by type: Circular, Low-Flow, Survival, Time Series. Then they have their own submenus: Prepare, Describe, Model, or if there are few items, it could be one submenu with separators for Prepare, Describe, Model to avoid going down two levels.

I think it would be confusing if e.g. the Prepare dialogs for all these types are together when there's nothing that really overlaps of associates them together.

If we did it like this, we could allow users to move a specific type "up" to the top menu e.g. I do a lot of time series so I move it up to the menu menu alongside Climatic.

This same idea could even apply to our other type of special menus Climatic, Procurement etc. where users could move them up or down from the top menu instead of hiding them completely as we currently do.

**Comment by rdstern** [comment]
So, if I have understood @dannyparsons suggestion - which @volloholic supports, there would be a new menu.  And (though not with much enthusiasm) we continue for now with the name Structured.  The possible menu could be

```
Structured
------------
Circular
Low-Flow
Survival
Time Series
------------
Climatic
Procurement
Options by Context
```
Any of these (eventually could be their own menu instead, i.r. moved to the top.  Perhaps there would be a third option (later) to display neither.  For now, they don't seem to do any harm being here.  
Within the new 4 menus, e.g. Time Series the sub-menu is perhaps:

Define
--------
Describe - One Variable
Describe - General
---------
Model - One Variable
Model - General
