### ISSUE TITLE
New dialogue called Verification Summary

### ISSUE THREAD

**Issue by rdstern** [africanmathsinitiative/R-Instat#5843]
This builds on the current verification facilities.  It uses the ideas of the summary dialogue to be able to produce the verification summaries for any combination of factor levels, including station and season.  The other difference is that (like the existing summaries) the results will usually be saved in a new data frame.

There will now be 2 dialogues.  We suggest Compare be moved to its own section below the one for start, end, extremes. Compare: Calculation.  Then the new one is Compare: Summary.  

This has the same structure as the top of the existing dialogue (no radio buttons though).  Under the second receiver is another multiple receiver - like the ordinary summary dialogue, i.e. for Factors and labellled the same.

As with the ordinary summary dialogue there is then a Summary button.  

Some of the other options of the ordinary summary dialogue might also be present, though it is always saved to the summary level.

What is not so clear is the structure of the sub-dialogue.  It may have 3 (or 4) tabs, though perhaps at least initially, there could just be a single tab.  There would then be 3 (or 4) blocks with labels:

Continuous, Categorical, Binary and possibly Probabilistic

The Continuous would combine the summaries from the HydroGOF and Verification, while the others would all come from the Verification.  

There will later be a tricky bit to detect the type of data in the single receivers, so the summaries are appropriate.  Perhaps that code can be added later?

**Comment by shadrackkibet** [comment]
Another idea could be to make **Continuous, Categorical, Binary**  top radio buttons so that this choice is explicit, and then we have all the summaries as checkboxes in the main dialog. The summaries can then be grouped depending on the options above. That means we will not need the sub dialog and also no need to detect data in the receivers, we will instead hide variables in the selector depending on the option selected at the top and which receiver is the active mode (turquoise colour). I think there will be enough space for hydroGOF options on the main dialog.

**Comment by rdstern** [comment]
@shadrackkibet that seemed to me to be a very good suggestion and I have discussed with @dannyparsons .  He also supports it.  It greatly simplifies the work in creating this new dialogue.  It means that users need to be aware themselves, of the type of their data and hence the sort of test they need.  I agree with you that this is a sensible change.
