### ISSUE TITLE
Add to the graph option on the toolbar

### ISSUE THREAD

**Issue by rdstern** [africanmathsinitiative/R-Instat#5884]
We now have a good example of a non-ggplot graph in R-Instat.  (This is a Taylor plot in the Climatic > Prepare menuIt would be good for this to display "In R window".  This can be done via the Tools > Options > Graph Options menu.  

But this is tedious.  It would be good if it could be an option on the toolbar and the graph icon does just what is needed for a ggplot graph.  Could it also do it for an ordinary graph?  If not could the same code as is used in the Tools > Options, perhaps as an extra option.  
(The difference is that the Tools > Options then sets it this way for ever.  So ideally it would be a switch so it could be set back to the Output window again.  Perhaps both could be done?)

If it is easy to do this, then please consider a similar change in the Describe > Display graph dialogue.  There again, Display in R viewer only works for ggplot graphs.

**Comment by Patowhiz** [comment]
I have also added menu items for pasting as shown below. users can also use Ctrl + V to copy into a cell.

Pasting into column
<img width="292" alt="paste into column" src="https://user-images.githubusercontent.com/21179007/93231867-e56a1d00-f781-11ea-9979-e8155b513d87.png">

Pasting into cell
<img width="323" alt="paste into cell" src="https://user-images.githubusercontent.com/21179007/93231911-f3b83900-f781-11ea-9f8d-e8f63a3e2117.png">

**Comment by Patowhiz** [comment]
I had previously thought that this was a problem in the front end but after looking into the code much further, I realised this is deeper in the R backend 

@dannyparsons can verify this
My understanding is, fundamentally, currently graphs are determined by checking the class types of the objects stored. The current class types recognised as graphs are `ggplot, gg, gtable, grob, ggmultiplot, ggsurv, ggsurvplot` .
So whenever graphs are added, the taylor plot object which is of class type `openair` is not "recognised" as a graph , thus not available as a "last graph".
 
The easier way to solve this I think will be just adding a check of `openair` class types. Though I find this not a good implementation, because as more types of graphs are added, we will have to keep on adding the class types checked. I think we should work towards a more general and better way of recognising the graphs produced. For the long term I would propose creating a metadata of the objects that are graphs whenever objects are created through the instant object `add_graph` command. This could also enhance how R-Instant treats the graph objects. 

I have implemented what I think is an easier option in PR #5990.

**Comment by Patowhiz** [comment]
I'm adding @rdstern comment and my comment from the PR here. This for @dannyparsons to counter check my findings.

@rdstern comment
> So, the next challenge is (I think) and ordinary graph. This uses the fitdistrplus package. I continued with the dodoma data and used Model > One Variable > Fit Model. Then use, say tmax and check that the display will give a multiplot (say). This is in the output window, but (as expected) the plot icon doesn't yet work for this graph.
> 
> And we are just about to add a series of dialogues that give graphs from the circular package. An example is the code here (we don't have the dialogues yet, but will soon. The circular package (and also the extRemes package, that has graphs as well) use the ordinary R graphics system. For now here is an example that runs in the script window.
> 
> ```
> # Generate 100 observations from a von Mises distribution.
> # with mean direction 0 and concentration 3.
> data.vm <- circular::rvonmises(n=100, mu=circular(0), kappa=1)
> # Plot data set. All points do not fit on plot.
> plot(data.vm, stack=TRUE, bins=150)
> ```

My reply
> @rdstern **Model > One Variable > Fit Model** dialog uses the graphics package to produce the plot. The `graphics::plot()` function returns `NULL` . So the function does not even produce an object. All graphs are handled as objects in R-Instat and since the plot function does not return any object, I think the current R-Instat way of handling graphs cannot work. @dannyparsons can verify this .
> 
> Script produced by the dialog
> 
> ```
> # Code generated by the dialog, One Variable Fit Model
> 
> tmax <- data_book$get_columns_from_data(data_name="dodoma", col_names="tmax")
> last_model <- fitdistrplus::fitdist(data=as.vector(x=stats::na.exclude(object=tmax)), method="mle", distr="norm")
> data_book$add_model(model_name="last_model", model=last_model, data_name="dodoma")
> data_book$get_models(data_name="dodoma", model_name="last_model")
> last_graph <- graphics::plot(x=data_book$get_models(data_name="dodoma", model_name="last_model"))
> data_book$add_graph(graph_name="last_graph", graph=last_graph, data_name="dodoma")
> data_book$get_graphs(data_name="dodoma", graph_name="last_graph")
> rm(list=c("last_model", "tmax", "last_graph"))
> ```
> 
> Of course the above script code shows that the produced script code is not optimised (and I think the dialog needs to be re-looked at, to ensure the redundant script code is not produced) but that is besides the point. The point is, I think running `data_book$add_graph(graph_name="last_graph", graph=last_graph, data_name="dodoma")` has no effect, because no object will added to the list of objects and thus last graph cannot be reproduced. the object ending up being produced by this dialog is the model object.
> 
> So I'm unable to solve this dialog and I think any dialog that uses the `graphics::plot()` function to produce graphs in the way I have done in this PR. In fact I'm strongly leaning towards proposing against handling graphs as objects. Should we ever use other packages that have plot functions that don't produce objects, using current R-Instat implementation, I think we won't be able to view and get last plot.
