### ISSUE TITLE
Testing Taylor diagram

### ISSUE THREAD

**Issue by Cal-Insta** [africanmathsinitiative/R-Instat#5910]
**Describe the bug**
In comparing the newly created Taylor diagrams in R-Instat, The Saltpond dataset which is merged dataset containing sunshine data from a station and also data from a satellite were used in exploring the diagrams as a graphical method of comparing the satellite and satellite data.

The data was filtered and missing values were removed from the dataset. The Taylor diagram drawn to the filtered and unfiltered data produced an error.

The Taylor diagram worked on the dataset using R code in R-Studio. Other datasets Dodoma, Floods, etc, however, worked well and were without issues in R-Instat. I wonder why it did not work for the salt pond dataset!

Attached is the dataset and error message.

[mergedsunshinedata.xlsx](https://github.com/africanmathsinitiative/R-Instat/files/4970909/mergedsunshinedata.xlsx)
![taylor error 1](https://user-images.githubusercontent.com/66616144/88373426-b641bb80-cd8f-11ea-9451-b04cd3c91870.png)
@shadrackkibet kindly have a look at this.

**Comment by shadrackkibet** [comment]
@Cal-Insta thanks for reporting this bug. Really good that you are testing this dialog and reporting issues you find. Please keep testing and reporting any bugs. 

In trying to investigate the source of the bug, I didn't replicate the bug you got above. I did import the data directly as `.xlsx` into R-Instat. First I notice you have data for two stations (Salpond and Tamale) so that should be taken into account in the dialog i.e the station receiver should be filled. See below my screenshots using your unfiltered data with the graph I got. I thought this will give an error from your statement?

> The data was filtered and missing values were removed from the dataset. The Taylor diagram drawn to the filtered and unfiltered data produced an error.

![image](https://user-images.githubusercontent.com/26301973/88376295-c6649580-cda5-11ea-9e8c-30553a779130.png)
![image](https://user-images.githubusercontent.com/26301973/88376357-e300cd80-cda5-11ea-82e8-106876931a0c.png)


You filtered the data, from which column did you filter? I tried filtering "SDU" and "sunshine_hours" to remain with non-missing then tried to obtain Taylor diagrams but I didn't get an error. How did you do the filtering? please give more details.

>  I wonder why it did not work for the salt pond dataset!

This is a dataset with two stations, did you filter to remain with only saltpond? I tried that and now without the station I got a separate error not as above reported see below, which is also produced when you don't filter the data but you leave the station receiver empty.

![image](https://user-images.githubusercontent.com/26301973/88377464-e72dea80-cda7-11ea-8f59-394efff1fbc4.png)

>The Taylor diagram worked on the dataset using R code in R-Studio. Other datasets Dodoma, Floods, etc, however, worked well and were without issues in R-Instat. 

It worked in Rstudio which dataset did you use there? Is it the same dataset as used in R-Instat? Please give more details.

**Comment by Cal-Insta** [comment]
@shadrackkibet thank you for the clarification and having a closer look at it. I figured the problem was from leaving the station receiver empty and not an issue with the dialogue. The oversight was not seeing the dataset contained multiple stations.
I am now clearly satisfied with the diagrams and I believe this issue can be closed.
