### ISSUE TITLE
Pasting New Columns to Data Frame

### ISSUE THREAD

**Issue by Patowhiz** [africanmathsinitiative/R-Instat#5991]
As mentioned in issue #5619, a user may want to paste to a new column rather than an existing column.

It would be good to add this feature, currently there is no undo in pasting to existing columns, which overwrites existing data, this may be undesirable to the users .

**Comment by Patowhiz** [comment]
@rdstern also adds

> I look forward to the ambitious extensions, namely to paste into new column(s) and to paste a new sheet. When pasting into new columns, then it could roughly be the same as Enter.
> 
> 1. If the paste is too long, then it is truncated.
> 2. If the paste is too short, then the rest is NA.  (It could be - like a regular sequence, that there is an option to recycle the data.

**Comment by dannyparsons** [comment]
I don't quite agree with Roger's comment. I think it's really easy to mistakenly copy the wrong thing which then ends up being longer or shorter than intended. If this happens you may then be pasting everything one cell too high/low. This is really dangerous and could mess up a whole analysis. 

So I would like it to be a requirement that pasting a completely new column is the correct length. I think we need to be strict about the structure of data frames so if you want to copy and paste, make sure you have the right length. If it's not the right length, then it probably doesn't make sense for it to be in that data frame.

**Comment by Patowhiz** [comment]
@rdstern at the moment we have pasting to existing new columns. Where it always assumes that there are no column headers in the copied data. I'm not sure if pasting to new columns should always be through a dialog or not. If not a must, I'm not sure on the default functionality in terms of whether the column header should always be assumed not to be in the copied data. 

@rdstern below is a sketch of dialog that could be used for pasting new columns.
![paste_new_column](https://user-images.githubusercontent.com/21179007/97678032-3c168680-1aa4-11eb-984b-918134b0199a.jpg)

**Comment by Patowhiz** [comment]
@rdstern the label "Click ok to paste data to new columns" will also be used to give user feedback on why the data cannot be pasted. It's colour will change to red when there is something wrong with the data(for instance longer data length than the selected data frame).

**Comment by rdstern** [comment]
1) I assume this will always be after the existing data?  Or is the first control "Paste Data To" giving where?  If so, then could it be "Paste Data After Variable".  Default could be the last variable in the existing data.  Perhaps None, or blank could mean it is at the start?  
2) Should the header should be Paste Data to New Columns, rather than Column?
3) In the Prepare > Column: Calculate > Regular Sequence it also says how the number of elements being produced will match (or otherwise) the length of the data frame.  

![image](https://user-images.githubusercontent.com/11226469/97776551-ff5c9500-1b60-11eb-835d-5fe654d9e1b0.png)

What are your plans if it is too short or too long?  Are there options?
a) If right length then could give the number and then be ready to paste.
b) If too short, then could repeat - which is ok for a regular sequence, but not so useful here.  So the rest could be NA?  Or it doesn't allow? 
c) If too long then either don't allow, or truncate - as we do for regular sequence.  If truncate then indicated on dialogue that this will be done and possibly also put a message to this effect in the output window.

**Comment by Patowhiz** [comment]
@rdstern current implementation is; 
a) If it is too short, then missing values(NA) will be appended. 
b) If it is too long, data will not be pasted.

I'm happy to change the functionality
Feedback is given to the user before proceeding. See example screenshot below.

<img width="452" alt="pasting_1" src="https://user-images.githubusercontent.com/21179007/97886599-d80cf000-1d39-11eb-9bb9-538c769b0536.PNG">

**Comment by Patowhiz** [comment]
> 1. I assume this will always be after the existing data? Or is the first control "Paste Data To" giving where? If so, then could it be "Paste Data After Variable". Default could be the last variable in the existing data. Perhaps None, or blank could mean it is at the start?
> 2. Should the header should be Paste Data to New Columns, rather than Column?

@rdstern a user can paste more than 1 column. So the "Paste Data To" is meant to select the data frame.
I used Paste Data to New Column(s) because it could be 1 or more new columns.

Will push the PR for this for more testing.

**Comment by rdstern** [comment]
@Patowhiz this looks great.  I look forward to the PR.
My question above was partly on where the new variables are pasted within the existing data frame.  I assume the default is after the existing data?

**Comment by Patowhiz** [comment]
> 1. My question above was partly on where the new variables are pasted within the existing data frame. I assume the default is after the existing data?

@rdstern yes. At the moment ,the new variables are saved after the existing data i.e after the last column.

**Comment by Patowhiz** [comment]
@rdstern under what menu should this dialog be opened from?

**Comment by dannyparsons** [comment]
This should be under the Edit menu I believe. 

I like the ideas here. I hadn't thought of a dialog for pasting new columns but this is nice because you can check what will happen and make sure it's as expected.

Where does pasting as a new data frame come in? It's basically the same so I think it can also be in this dialog. Possibly an option at the top to paste into an existing data frame or a new data frame.

In the preview, can the number of previous rows be an nud option as in the import dialog?

On the lengths, if pasting into an existing data frame then it should require the lengths to be the same. If it's not the same length then it's likely not the right thing and padding with `NA`s is unlikely to be the correct solution.

The label with info on rows and columns is very useful but I don't think we need "Click ok to paste data to new columns". This is what you do on every dialog already.

Could the info be presented as

> Number of columns: x
> Number of rows: y too few rows to paste into this data frame. This data frame requires xxx rows

or "too many" in the other case. And maybe when it's green:

> Number of columns: x
> Number of rows: y correct length

Of course when pasting into a new data frame any length is ok.

Possibly only the Rows label should change from red/green? Since number of columns is not an issue.

**Comment by Patowhiz** [comment]
@rdstern @dannyparsons, Racheal's issue on copy has reminded me of this issue too.
We now have different **Paste** options under the **Edit** menu as shown in the screenshot below. I think the **Paste New Data Frame** dialog should be combined with the **Paste New Columns** dialog  just like @dannyparsons has suggested in the [comment](https://github.com/africanmathsinitiative/R-Instat/issues/5991#issuecomment-722530899) above. We could just enhance that dialog to have the 2 options. This means that we can have one menu item, **Paste Special** that opens a dialog with the 2 options in it. 
@rdstern @dannyparsons what do you think? @rdstern I acknowledge we may have discussed why we came up with the **Paste New Data Frame** options, though I can't remember the reason.
![paste_options](https://user-images.githubusercontent.com/21179007/153467143-cc92c7f5-a30f-45d1-802e-420a579ba949.png)

**Comment by dannyparsons** [comment]
How about just changing **Paste Special** to **Paste Columns**? They are quite different things so I don't mind them being separate dialogs, especially as the menu is short.

**Comment by Patowhiz** [comment]
@dannyparsons great, what about calling it **Paste New Columns**?

**Comment by dannyparsons** [comment]
Yes, sounds good.
