### ISSUE TITLE
Change as.factor to as_factor?

### ISSUE THREAD

**Issue by rdstern** [africanmathsinitiative/R-Instat#6005]
We currently have 4 ways to make a factor variable.  We can use right-click, or the Prepare > Factor > Convert to Factor, or Prepare > Data Frame > Convert, or Prepare > Calculator

I suggest we make them consistent, by using as_factor (from forcats) rather than the base as.factor.  Currently the calculator uses forcats, so this doesn't have to change.  The others would change.

**Comment by lilyclements** [comment]
1. I'm happy to change these. I just want to double check what is the difference between converting something to an ordered factor against converting to a factor?
2. There are two dialogs where `as.factor` is run as an additional function (not the main function). These dialogs are dlgClimaticBoxplot and dlgTwoVariableFitModel. Should I convert these to `forcats::as_factor` as well?
3. Additionally, `as.factor` is used in some R codes (DateManipulationMethods.R, climate_data_refclass.R, climate_refclass.R, display_rain_running_total_method.R, display_water_balance_method.R). Should these also be converted to `forcats::as_factor`?
4. As a side note the parameters are in the wrong order when you use right-click to convert to a factor. The function specifies that `col_names` parameter should be before the `to_type` parameter:
If you right click to convert to factor:
`data_book$convert_column_to_type(data_name="cars", to_type="factor", col_names=c("speed"))`
If you go through dlgConvertColumns (accessed by the Prepare menu):
`data_book$convert_column_to_type(data_name="cars", col_names="speed", to_type="factor")`

**Comment by lilyclements** [comment]
1. I'm happy to change these. I just want to double check what is the difference between converting something to an ordered factor against converting to a factor? [Edit: I have worked this out now - see end for an additional comment]
2. There are two dialogs where `as.factor` is run as an additional function (not the main function). These dialogs are dlgClimaticBoxplot and dlgTwoVariableFitModel. Should I convert these to `forcats::as_factor` as well?
3. Additionally, `as.factor` is used in some R codes (DateManipulationMethods.R, climate_data_refclass.R, climate_refclass.R, display_rain_running_total_method.R, display_water_balance_method.R). Should these also be converted to `forcats::as_factor`?
4. As a side note the parameters are in the wrong order when you use right-click to convert to a factor. The function specifies that `col_names` parameter should be before the `to_type` parameter:
If you right click to convert to factor:
`data_book$convert_column_to_type(data_name="cars", to_type="factor", col_names=c("speed"))`
If you go through dlgConvertColumns (accessed by the Prepare menu):
`data_book$convert_column_to_type(data_name="cars", col_names="speed", to_type="factor")`


**Edit to 1:**
In the R-Instat code, `as.factor` is not used to convert a variable to a factor since it does not have an ordered parameter. Instead, `factor` is used because this has an `ordered` parameter.
An ordered parameter is therefore not present for `forcats::as_factor`, however, ordered factors can be done (I believe) by `forcats::fct_inorder`
So the R code in R-Instat here uses `factor` not `as.factor`. Should I change this to be `forcats::fct_inorder`?

```
class(factor(LETTERS[3:1], ordered = TRUE))
[1] "ordered" "factor" 

class(forcats::as_factor(LETTERS[3:1]))
[1] "factor"

class(forcats::fct_inorder(LETTERS[3:1], ordered = TRUE))
[1] "ordered" "factor"
```
