### ISSUE TITLE
Grid to display accents and other symbols?

### ISSUE THREAD

**Issue by rdstern** [africanmathsinitiative/R-Instat#6024]
![image](https://user-images.githubusercontent.com/11226469/96302335-8ef63580-0ff0-11eb-9301-e2932d8c4a6d.png)
[Station and Elements Niger.xlsx](https://github.com/africanmathsinitiative/R-Instat/files/5393964/Station.and.Elements.Niger.xlsx)

The elements imports easily into R-Instat.  And the information is correctly imported, including accents and symbols like the degree symbol.  But they don't display in the grid.

I wonder if this is an easy thing to correct.  It comes in one of the videos we will be preparing.

**Comment by Patowhiz** [comment]
@rdstern by grid, you mean the data view window?

**Comment by rdstern** [comment]
Yes the reogrid.  
Here is an example showing it doesn't display extended characters
![image](https://user-images.githubusercontent.com/11226469/96408861-44391100-11dc-11eb-9347-00c4317719d4.png)
[Station and Elements Niger.xlsx](https://github.com/africanmathsinitiative/R-Instat/files/5399504/Station.and.Elements.Niger.xlsx)
This is the file I used. - First sheet

**Comment by Patowhiz** [comment]
@rdstern in my laptop. I'm also unable to view the Name column which has the accents. I'm wondering why it seems to be visible in your laptop.

<img width="477" alt="no_col" src="https://user-images.githubusercontent.com/21179007/96862332-005d3a80-146e-11eb-8783-8ac8899a36ba.PNG">

**Comment by rdstern** [comment]
@Patowhiz that's a different feature.  Make the R view of the data much wider and you will then see the last variable.  Or, I assume, use the scroll bar

**Comment by Patowhiz** [comment]
I initially thought that the problem was in the grid itself, searching online I couldn't find a similar problem. Then upon looking into the grid much more in detail I noticed that these accents are displayed well in the import dialog preview. Looking into the settings of the 2 grids, their set up is relatively the same.

Looking into it from the R perspective;
To preview the data, the import dialog fundamentally runs the following script, internally, 
`.temp <- convert_to_character_matrix(data=rio::import(file="C:/Users/PatoWhiz/Downloads/Station.and.Elements.Niger.xlsx", guess_max=Inf, which=1, n_max=10))`
It then converts the VB.Net object produced to an R.NET data frame object when is then used to fill the reogrid.

The same import dialog runs the following script when you click OK;
```
Elementd <- rio::import(file="C:/Users/PatoWhiz/Downloads/Station.and.Elements.Niger.xlsx", guess_max=Inf, which=1)
data_book$import_data(data_tables=list(Elementd=Elementd))
```
However, the `clsRunLink` updates the `ucrDataView` reogrid  through the `clsGridLink` which runs the following script to get the data frame, internally;
`.temp <- data_book$get_data_frame(convert_to_character=TRUE, include_hidden_columns=FALSE, use_current_filter=TRUE, max_cols=30, max_rows=1000, data_name="Elementd")`
It then converts the VB.Net object produced to an R.NET data frame object when is then used to fill the reogrid.

When you view the data through the R Viewer, the following script is run 
```
Elementd <- data_book$get_data_frame(data_name="Elementd")
View(x=Elementd)
```
When you look at the default parameter values of `data_book$get_data_frame` , parameter `convert_to_character` is `FALSE` by default. 

To me, it became clear that parameter `convert_to_character`  in the `clsGridLink` script was the problem. Changing the value to `FALSE`, made the french accent values to be displayed correctly in the reogrid i.e

From
`.temp <- data_book$get_data_frame(convert_to_character=TRUE, include_hidden_columns=FALSE, use_current_filter=TRUE, max_cols=30, max_rows=1000, data_name="Elementd")`

To

`.temp <- data_book$get_data_frame(convert_to_character=FALSE, include_hidden_columns=FALSE, use_current_filter=TRUE, max_cols=30, max_rows=1000, data_name="Elementd")`

@dannyparsons why is the parameter `convert_to_character` is currently set as `TRUE` in the `clsGridLink` and what problems would arise if this was set to `TRUE` ? I only noticed a difference in the row contents of the data frames . See image below. Changing this value to TRUE solves the problem but 

<img width="555" alt="accent_code" src="https://user-images.githubusercontent.com/21179007/97009787-36252080-154d-11eb-8019-0f961366e2f5.PNG">

**Comment by dannyparsons** [comment]
`convert_to_character` is used to take care of formatting of columns to display in the grid using the metadata. This issue definitely looks solveable from what you've looked at. The important question though, is why the convert option messes up the display. That's the next thing to find out. I can look into that in the R code or you may want to continue?

There is also inconsistency in how we display data in different places, the grid, import preview and R viewer. We should be using the same approach so it's consistent in all places. That's a slightly separate issue but related to the differences observed here.

**Comment by Patowhiz** [comment]
This comment is an addition to the above [comment](https://github.com/africanmathsinitiative/R-Instat/issues/6024#issuecomment-715346098);

@dannyparsons I looked into the R code. I traced the problem to a line in a function called `convert_to_character_matrix` located in **stand_alone_functions.R** file. Code line 21 `out[,i] <- format(data[[i]], digits = decimal_places[i], scientific = is_scientific[i])` of function `convert_to_character_matrix` is executed when `get_data_frame` is called for filling the grid. See screenshot below.

`convert_to_character_matrix` function in **stand_alone_functions.R** file.
![stand_alone_functions](https://user-images.githubusercontent.com/21179007/123286764-0b67df00-d4c3-11eb-8f7e-69b267a7c08e.PNG)

`get_data_frame` function in **data_object_R6.R** file.
![get_dataframe_smippet](https://user-images.githubusercontent.com/21179007/123286807-16bb0a80-d4c3-11eb-97b6-390bea8843ff.PNG)

Though according to the [documentation](https://www.rdocumentation.org/packages/base/versions/3.6.2/topics/format) of the R base `format` function, it's meant to _Format an R object for pretty printing_, however, when called for character objects, the R.NET `DataFrame` object fails to correctly recognize the returned converted French accents. I couldn't understand, I think it has to do with how the `DataFrame` object encodes such character accents when they are from the `format` R function. 
When I used `as.character`, the returned characters were recognized with accents correctly.

When R `format` is used in converting characters with French accents
![accent problem](https://user-images.githubusercontent.com/21179007/123291652-25a3bc00-d4c7-11eb-9fad-b75753750e30.png)

And the above is not the only problem, even spaces within characters
![space problem](https://user-images.githubusercontent.com/21179007/123291842-57b51e00-d4c7-11eb-99ad-c5b5040ab5c5.png)

I also noticed the extra spaces that the R `format` adds to the characters
![more into it](https://user-images.githubusercontent.com/21179007/123291928-6dc2de80-d4c7-11eb-8d57-cd815b81de00.png)

**Comment by Patowhiz** [comment]
@dannyparsons I suggest letting the characters be converted using `as.characters`. By commenting out or removing the code below in the `get_data_frame` R function , the `convert_to_character_matrix` will work fine. However I welcome you suggestion, I may be missing something here.

![get_dataframe_smippet](https://user-images.githubusercontent.com/21179007/123293928-3e14d600-d4c9-11eb-844b-a7dbf74dea84.PNG)

**Comment by Patowhiz** [comment]
@ChrisMarsh82 you may also want to have a look at the issue outlined here, including my findings. They somehow related to the grid.
