### ISSUE TITLE
Serious bug with the Position button

### ISSUE THREAD

**Issue by rdstern** [africanmathsinitiative/R-Instat#6042]
The recent version (0.6.3) has introduced a bug on the dialogues that use the Position button.
I originally thought this was linked to the new Calculator dialogue that has been updated to include this facility.  But it seems more general than this.
I just tried also with the Right-click > Duplicate dialogue and have the same bug.  After using this facility it doesn't recognise the new variable.  It gives an error when going into any dialogue after this and then when making any change in a receiver within that dialogue.

I think the Duplicate dialogue may give rise to the problem even if you use the default settings.

Added later:  I have just checked and the Duplicate dialogue does give a problem.  Here is how to get it - I am trying on the new master version.
a) Load (say) Dodoma from the Excel file in Open from Library > R-Instat > Browse > Climatic > Climatic data sets, dodoma.  (I think any file will do!)
b) Make year into a factor.
c) Right-click and Duplicate column.  Change type and make year1 numeric.
d) Try (for example) Describe > One Variable > Summarise.

It gives an error message multiple times and then goes into the dialogue.  Then it repeats the error whenever using a control.  It isn't recognising the new variable.

**Comment by Patowhiz** [comment]
@rdstern @dannyparsons this bug is as a result of the updated package, `dplyr`. The script that adds new column has the functionality of positioning the newly added column. The part which positions the column uses `dplyr::select()` function. And it does this by passing parameters that select the variables of the data frame in the rearranged order(see screenshot below). However, when doing this, the package assumes some of the parameters are may be "calculated" and thus "ambiguous". The text below is the warning produced when I run individual scripts, I think it explains better
```
Note: Using an external vector in selections is ambiguous.
i Use `all_of(ind)` instead of `ind` to silence this message.
i See <https://tidyselect.r-lib.org/reference/faq-external-vector.html>.
This message is displayed once per session.
Note: Using an external vector in selections is ambiguous.
i Use `all_of(previous_length)` instead of `previous_length` to silence this message.
i See <https://tidyselect.r-lib.org/reference/faq-external-vector.html>.
This message is displayed once per session.
```

Below is the section of the `add_columns_to_data` script that produces the above warning.
<img width="906" alt="obsolete_script_code" src="https://user-images.githubusercontent.com/21179007/97269150-17b97080-183e-11eb-9411-5f513655abae.PNG">

I have 2 possible solutions for this;
1. I can amend this "ambiguity" and use the same `dplyr::select()` function to rearrange the variables to the new order, or,
2. I can use an existing R-Instat function to reorder the columns whenever needed. I have done a similar solution  in PR #6043. I had also made a similar suggestion in this [comment](https://github.com/africanmathsinitiative/R-Instat/pull/6043#issuecomment-716620523). I didn't use `dplyr::select()` because I found it to be an unnecessary complexity to a problem that could be solved using an existing functionality.

If you both agree with solution (2), I can solve this bug in PR #6043 and harmonize the implementation in a way that doesn't add redundant checks. If not, I can amend the "ambiguity" in a separate PR.

**Comment by dannyparsons** [comment]
Thanks for looking into that and finding the existing function for reordering, that's better than the existing code which is a repetition.

We should gradually move all our data management tasks to align with `dplyr` which will give more consistency but that can be done over time.
