### ISSUE TITLE
Tool bar items - column and data frame metadata, log and script window

### ISSUE THREAD

**Issue by shadrackkibet** [africanmathsinitiative/R-Instat#6207]
The following toolbar items should be checked when the respective windows are active. This is working when you use the view menu (See below). Ensure sync between toolbar icons and view menu.

![image](https://user-images.githubusercontent.com/26301973/106894655-50e86300-6700-11eb-93a0-c0984f3c8e9e.png)
![image](https://user-images.githubusercontent.com/26301973/106894698-5d6cbb80-6700-11eb-92e8-4c128b4257d3.png)
![image](https://user-images.githubusercontent.com/26301973/106895096-dd932100-6700-11eb-90f7-762b620b2385.png)

A question to @rdstern. When you reset the layout (using the icon or via view menu) I think the tailored menus (climatic, procurement etc) should be enabled if they are hidden as shown below.
![image](https://user-images.githubusercontent.com/26301973/106896350-81310100-6702-11eb-8a97-8014ea033273.png)

Then some inconsistency, the icon tooltip says (**Reset Layout**) while using the view menu we have **Reset to Default Layout**. Shouldn't this be the same?

**Comment by shadrackkibet** [comment]
My argument is partly because I think the menu items **(Prepare. Describe Model etc)** are part of the layout, therefore, it is logical to reset to default i.e show all menu items when they are hidden.

**Comment by rdstern** [comment]
I am not sure if I am following all the points.  I agree with the checks on the toolbar and that the toolbar icon should have the same "Reset to Default Layout" tooltip.

I see a distinction between the extra menus and the set of Windows.  I like the fact that the extra menus are on the view menu, so they are easy to show and hide.  However, I treat the "layout" as referring to the 6 windows and not necessarily to the extra menus.  Perhaps, therefore the Reset to Default Layout is in the wrong place on the View Menu.  It could be  either just after Data Frame Metadata or perhaps there, but with a line before, so it is seen to be a bit different.

To me the fundamental difference is that I may need any of the Windows to examine and analyse any dataset.  So that part of the layout can change quite a lot.  In contrast I would usually keep the climatic menu open permanently or not need it at all.  So, for most people the visibility of the extra menus is a pretty fixed thing.
