### ISSUE TITLE
Add boxplots without box when needed - from Tufte?

### ISSUE THREAD

**Issue by rdstern** [africanmathsinitiative/R-Instat#6251]
One example [here](https://stackoverflow.com/questions/2076370/most-underused-data-visualization) of a neglected graph is the adaptation of a boxplot, without the unnecessary box.

Here is an example - the code uses lattice, but you will get the idea:
```
library(lattice)
library(taRifx)
compareplot(~weight | Diet * Time * Chick, 
  data.frame=cw , 
  main = "Chick Weights",
  box.show.mean=FALSE,
  box.show.whiskers=FALSE,
  box.show.box=FALSE
  ).
```
The resulting boxplot is like this:
![image](https://user-images.githubusercontent.com/11226469/110220080-4960d900-7ebb-11eb-8a1b-cd4b0c26b3be.png)

In ggplot2 I think this is a special geom, i.e. geom_tufteboxplot in the ggthemes package that is currently installed with R-Instat.  The latest version - later than in current R-Instat - has corrected some bits in this function.

This would be useful to test with the Ghana dataset.  I suggest - for the climatic boxplot - it might open the door to being able to perhaps have better boxplots for year, and also possibly to permit boxplots for both year and month together.  It is designed particularly for situations where there are many categorical levels, which is just what we have here.  

Useful to consider it also for the general boxplots dialogue - possibly just an option, or its own radio button even.  This needs investigation.  Really useful also for our teaching of "good graphics".

**Comment by rdstern** [comment]
@jkmusyoka welcome today to Manor House.  In your investigation of the tufteboxplot I find it is already in the released R-Instat!  That means it will be very easy to investigate through the script file.  Then adding it to the climatic boxplot dialogue might also be a very small job!  Perhaps it can get promoted into 0.7.0?

**Comment by jkmusyoka** [comment]
There are several variants of the tufte boxplot see [https://jrnold.github.io/ggthemes/reference/geom_tufteboxplot.html]

R-Instat copes well with the R code for these variants and produces the expected graphs. In the script window, however, one has to stop calling the ggplot2 package in the geom part of the code. This is because the geom_tufteboxplot is associate with the ggthemes package. 

Implementing this functionality in the dialogues can achieved by adding the possibility of using a point or a line to represent the median and whiskers of the boxplot.

**Comment by rdstern** [comment]
@haward, could you check on the alternative Tufte boxplots, and then propose to choose one to add.

Then could you first see how this option could easily be added, initially to the climatic boxplot dialogue and then also to the ordinary boxplot dialogue.  Ideally - at least for the climatic - it is just a checkbox to use the Tufte, rather than the ordinary boxplot. Could it be a checkbox (only when boxplot is used) under the Within Year saying `Use Tufte Boxplot`.  Then the option button would also change from Boxplot Options to `Tufte Options`.

I am particularly interested when we might want boxplots by year and month - say.  So there are many of them.

**Comment by HawardKetoyoMsatsi** [comment]
![image](https://user-images.githubusercontent.com/16137042/122005349-34e78300-cdbe-11eb-9bea-122450b87dc3.png)

![image](https://user-images.githubusercontent.com/16137042/122005569-7aa44b80-cdbe-11eb-8ed5-fcf497bc565e.png)

Looking at the Tufte plots against the basic box plots, the basic box plots seem to work better when dealing with outliers, unlike the Tufte plots. Even though the Tufte plots have parameters to specify the outliers It seemed not to work for me.
I don't think Tufte plots will save any space or work better than the normal box plots when dealing with a larger number of data points. the bars/boxes seem to be equispaced just like in the boxplots despite the Tufte plots using thinner lines. I however don't know if the Tufte plots give an illusion of not overcrowding that could be useful on the plot.

The compareplot() function on the other hand seems not to be suitable since it is not as flexible as we would like it to be. It takes exactly three variables to plot and it can't accept any more or any fewer variables.

**Comment by rdstern** [comment]
@HawardKetoyoMsatsi that's a good start.  There is more to do, before you leave this topic.
a) You need to understand why no outliers, or perhaps use a different implementation of the tufte boxplots.  There are various.
b) Check whether you can adapt the ordinary boxplot further so it is more like the Tufte.  I think you can change the width - can you make it very small, so it becomes similar to Tufte?  If so, can you put the median in a different colour.
c) You don't say how you are getting these examples.  Can they be through R-Instat with tweaking the script?  
d) The Tufte boxplot is already available as a gwom.  So could you use the general graph to produce it.
e) Could you work on this with one of the documentation team, so they can take over the problem.  It is relatively little programming now.  Perhaps Wycklife could work with you to document what is happening.  His work could also include the skew boxplot.
f) I don't know about the compareplot function.  Is it in R-Instat?  When doing comparisons I was simply thinking of adding facets, not changing the function.  Please enlighten me where this has come from.

**Comment by rdstern** [comment]
@HawardKetoyoMsatsi I have looked a bit more and now have a suggestion for you.
![image](https://user-images.githubusercontent.com/11226469/122023948-ea670600-cdbf-11eb-9bf0-d2f6198c0729.png)

This is a boxplot with the ordinary ggplot dialogue.  Now I am reasonably happy with this being (roughly) a Tufte-type boxplot.  

I found 2 problems in doing this:
a) The width isn't there.  I think (for the boxplot geom size is the size of the outlier.  But you can include width and it then changes the width of the box.  That could be added above the glyph.  As an up-down the default is (I think) 0.5 and it should go in steps of 0.01.  Possibly the maximum is 1 and the minimum is 0?  The example above has a width of 0.06.
b) When the box width is so low, then you also "lose" the median.  That can always be added - if needed, using an additional layer with Stat_summary

**Comment by HawardKetoyoMsatsi** [comment]
I now think that we should add a button for tuftebox. let me try and explain my findings. 
Adding to the dialog qont make it crowded since it will only need a button at the top but all the othe controls and sub dialogs remain as they are.
We can ass well tweak the code in the script window which I did and produced the below plots using the script window in R instat. We will however discuss this with @rdstern  and @Wycklife (we discussed and found that we need to be advised on how this should be written incase it is not implemented in the dialog). 
About outliers I still find it a poor tool to handle outliers. There are no many implementations of tuftebox as stated in this discussion, the implementation of tuftebox tend to rely on the function `geom_tuftebox()` with difference in the plots seen by varrying parameters which varry the median and whisker  line types and the offset of the median, the below plots are done in R instat. 

![image](https://user-images.githubusercontent.com/16137042/122566155-e7824480-d04f-11eb-8d55-6bde23eb0368.png)
when the median.type is set to a line and the whisker.type set to a point
`last_graph <- ggplot2::ggplot(data=ghana, mapping=ggplot2::aes(y=min_temperature, fill=station, x=station, group=station, colour=station)) + ggthemes::geom_tufteboxplot(median.type = "line", whisker.type = "point", hoffset = 0) + theme_grey() + ggplot2::theme(axis.text.x=ggplot2::element_text())`

![image](https://user-images.githubusercontent.com/16137042/122566454-3af49280-d050-11eb-80be-ba97230056f9.png)
when median.type is set to be a line of width 3 with no offset
`last_graph <- ggplot2::ggplot(data=ghana, mapping=ggplot2::aes(y=min_temperature, fill=station, x=station, group=station, colour=station)) + ggthemes::geom_tufteboxplot(median.type = "line", hoffset = 0, width = 3) + theme_grey() + ggplot2::theme(axis.text.x=ggplot2::element_text())`

![image](https://user-images.githubusercontent.com/16137042/122566683-80b15b00-d050-11eb-9a38-e0723d50ca84.png)
when median.type is set to be a line
`last_graph <- ggplot2::ggplot(data=ghana, mapping=ggplot2::aes(y=min_temperature, fill=station, x=station, group=station, colour=station)) + ggthemes::geom_tufteboxplot(median.type = "line") + theme_grey() + ggplot2::theme(axis.text.x=ggplot2::element_text())`

compareplot() function is not in R-Instat, was mentioned by @rdstern in the preamble to this Issue and thats why I looked at it. It is however not suitable. since It takes exactly three variables to plot and it can't accept any more or any fewer variables.
The suggestion to add  width of the boxplots and add a median is also great and we can implement it incase we dont implement the tuftebox in the dialog.
