### ISSUE TITLE
Improving the General Fit Model dialogue

### ISSUE THREAD

**Issue by lilyclements** [africanmathsinitiative/R-Instat#6345]
**Describe the bug**
There is a developer error in the ucrDistributions that occurs on a modelling dialog when "Reset" is hit, if the response variable does not have a corresponding distribution. 

**To Reproduce**
Steps to reproduce the behaviour:
1. Upload data (for example, `diamonds` in the `ggplot2` library
2. Open the `General Model` dialog (under Model > Fit Model > General...)
3. As the response variable, input a variable which does not have a corresponding distribution associated to it. For example, a factor variable (e.g. `cut` in the `diamonds` data set)
4. Click reset, and a developer error occurs
 "Developer error: Cannot set value of ucrFamily because cannot find a distribution matching the function and parameter given"

**Comment by rdstern** [comment]
@lily This error is still here.  I suggest instead of fixing the error, we add further distribution options to the current list.  This would be useful anyway.
a) I hope a "quick-win" - though not a solution to the error is to add `glm.nb `(negative binomial) from the MASS package.  This should be included whenever the poisson is there.  We already detect integer variables, so this may be easy.
b) Could we then add `polr` from the MASS package.  That is particularly for ordered factors, but I assume we could also allow it for any factors?  That would then avoid the error, by having a distribution for any type of y data.
c) Then there is multinom from the nnet package.  That's for any factor.

That would be quite good for now.

But while I am "on a roll" the `arm` package has
bayesglm
bayespolyr
So I wonder if they could be added to the dialogue too? 

I am assuming we work with the Fit Model > General initially.  Later we could see what to add to the 2/3/4 variables.  I assume the distributions would add automatically there too?

**Comment by Vitalis95** [comment]
The dialog runs `stats::anova` to the saved model. This gives an error in R for factor response variable
```
survey <- new_RDS$get_data_frame(data_name = "survey")
x <- MASS::polr(data = survey, formula = village ~ size)
stats::anova(x)
```
```
"Error in anova.polr(x) :
  anova is not implemented for a single "polr" object"
```
If instead you use `car::Anova`, then it works.
This is the description of the function;
Calculates type-II or type-III analysis-of-variance tables for model objects produced by` lm, glm, multinom` (in the `nnet` package), `polr` (in the `MASS` package), `coxph` (in the `survival` package), `coxme` (in the `coxme` pckage), `svyglm` (in the survey package), `rlm` (in the `MASS` package), `lmer` in the `lme4` package, `lme` in the `nlme` package, and (by the default method) for most models with a linear predictor and asymptotically normal coefficients.

@rdstern , @lilyclements what is your take on this
