### ISSUE TITLE
Unable to Open the germany_4plus_sat data

### ISSUE THREAD

**Issue by berylwaswa** [africanmathsinitiative/R-Instat#6398]
**Describe the bug**
When importing this data to R-Instat from the library the error on the image pops up

**Screenshot**
![Screenshot (6)](https://user-images.githubusercontent.com/28622260/114007887-6433be00-986a-11eb-9f16-903c86b593ad.png)

**Comment by rdstern** [comment]
@berylwaswa I missed your comment above that you were trying to open the file from the library.  Rachel had a similar problem.  Now we have "twigged" we find nothing from the library opens.  @Patowhiz notice the message also that the multiple files can be read.  The library is (I think) unusable in Version 0.7.0.  

And there is another serious error that I reported in #6383 and will report again, because it is stopping Rachel in preparing the videos.

**Comment by shadrackkibet** [comment]
I think the bug reported by @berylwaswa above is specific to the import dialog. I was able to trigger the error and the code is as shown below. 
```
# Code generated by the dialog, Import Dataset
germany_4stations <- rio::import(file="C:/Program Files/R-Instat/0.7.0/static/Library/Climatic/Lesotho/mokhotlong_1966.RDS")
data_book$import_data(data_tables=germany_4stations, data_names=c("Arkona", "Greifswald", "Rostock_Warnemunde", "Schwerin"))

rm(germany_4stations)
```

Notice that the paths don't update properly!

@berylwaswa could you post the code displayed in your output window? Please always add the code you get in the output window, that always helps during investigations.
