### ISSUE TITLE
Bug when adding a comment in data entry dialog

### ISSUE THREAD

**Issue by N-thony** [africanmathsinitiative/R-Instat#6437]
**Describe the bug**
![image](https://user-images.githubusercontent.com/68591383/116802511-bb4c4c00-ab13-11eb-9193-a9e9185c55e9.png)
The first one occurs when for the first time you select a row, and click on add comment. There is no row number in the input row, you should close and opened the comment sub dialog again to have the row number of the selected row in the grid.
![image](https://user-images.githubusercontent.com/68591383/116802580-17af6b80-ab14-11eb-9f59-5b4632597a7b.png)
This one is due by the fact that the add comment button is supposed to be disable if there is no key in the data frame when trying to add a comment, but here it is enable even if there is no key in a data frame that allow the add comment function to run.

**Comment by lloyddewit** [comment]
@shadrackkibet - @N-thony suggested that we assign this issue to you because it's related to your work on the data entry dialog. If you prefer someone else to be assigned then let me know, thanks

**Comment by shadrackkibet** [comment]
I don't think the second should be a problem. The error is informative to the user and it guides the user to the appropriate dialog where to add a key -  This is a deficiency in the R-Instat way of relaying such informative errors.  I am not of the opinion of disabling Ok when there is no key. This will be confusing to users because they will not know why Add comment button is not enabled. I also do not think the tooltip is the most effective way to notify the user why Ok is not enabled.
