### ISSUE TITLE
Improving the consistency of our dialogues?

### ISSUE THREAD

**Issue by rdstern** [africanmathsinitiative/R-Instat#6473]
This suggestion relates to 2 existing issues.  Namely:
1) The comments below in issue #6469  and 2) a comment #6472 on implementing a dialogue in the standard way.

@lloyddewit I suggest after this being merged, to work on the Climatic menu in one PR.

@N-thony Thanks, good idea
Please could you try and resolve the remaining parts of issue #6454, issue #6464 and issue #6465; and then start checking/updating the dialogs in the Climatic menu?

@rdstern Is that OK from your side or did you have a different task you'd prefer @N-thony to work on?

I like to propose a slightly different system that examines dialogues for a number of aspects at the same time. 

My suggestion is to work dialogue-by-dialogue, rather than menu by menu.  In each "offending" dialogue, whenever there is anyone of the following points, then the list below is checked.  An issue is made for that dialogue, with the new Consistency label.  And a variety of aspects are checked - and if necessary - corrected at the same time.  In future then we will steadily go through quite a lot of the dialogues and those that are checked will all have the consistency label attached.

So here is my initial list of checks:
a)  Implementation is in the "standard" way.
b) Labels are appropriate length for the French.
c) The new Save control - when relevant - is completed and saves the new variable(s) in a consistent way.
d) Spacing of controls on the dialogue is consistent and well aligned.

Are there other topics to add?  What do you think?
If so, then this will be quite a bit of work.  It could wait (perhaps, or just be tested) until the next level of translation is available?  Then a dialogue for checking is "triggered" by any of the above aspects.  But once triggered each of the above is considered.  The pull request when triggered by labels can just report "Implementation is already standard".

**Comment by lloyddewit** [comment]
@rdstern small comment: I assume you mean **PR** #6469 above, not issue

**Comment by rdstern** [comment]
@lloyddewit yes I do.  

I also realise I was not sure what @N-thony was planning in regard to the climatic menu.  If it is the crowdin stuff, then that still stands as before.  My suggestions only affact the code/programming

**Comment by lloyddewit** [comment]
@rdstern Thank you for the suggestions. I liked your checklist. I discussed with @N-thony 

> a) Implementation is in the "standard" way

There are many aspects to this, checking them all would be huge effort. I suggest to limit the scope just to ensure that the translation is done at the end of the load function. I will take this task. I hope that I can write a short script to identify which dialogs have this problem. I can then correct these dialogs. I will do this in a dedicated PR.

> b) Labels are appropriate length for the French.
d) Spacing of controls on the dialogue is consistent and well aligned.

@N-thony kindly agreed to work on this. It's more efficient for him to resolve these small problems directly rather than raising issues to be solved later. He would like to start with the climatic dialogs because his internship focuses on climatic. He could then include this work in his internship report. He will see how long it takes to do the climatic dialogs. We can then make a plan for the other dialogs, potentially sharing the work between different developers. 
@N-thony will also solve the remaining parts of issue #6454, issue #6464 and issue #6465.
In parallel, if you or others find translation issues in non-climatic dialogs then these could be raised as issues according to your checklist.

> c) The new Save control - when relevant - is completed and saves the new variable(s) in a consistent way.

The save control functionality is not related to the translations. However, @N-thony kindly agreed to check the save controls at the same time that he reviews the climatic dialog translations. 

@rdstern Is the above OK for you?
@N-thony If I misuderstood anything above, then please let me know

**Comment by rdstern** [comment]
@N-thony and @lloyddewit that's all fine.

**Comment by lloyddewit** [comment]
@N-thony the following issues about French translations are still open:

- [ ] issue #6464
- [ ] issue #6465

Please could you review the above issues and resolve any remaining problems. Please let me know when you're done, and we can then close the above issues.
Thanks

**Comment by lloyddewit** [comment]
@rdstern , @N-thony 

I understand that this issue is now completely resolved apart from:

> b) Labels are appropriate length for the French.
d) Spacing of controls on the dialogue is consistent and well aligned.

@N-thony already completed the above for the climatic menus in PR #6479. The same now needs to be done for the dialogs in the remaining menus.

**Comment by lloyddewit** [comment]
I think we can close this issue because everything is either resolved or reflected in the PRs and issues referenced above, plus PR #6543 PR #6557 , PR #6558  and PR #6580 .

**Comment by lloyddewit** [comment]
I think we can close this issue because everything is either resolved or reflected in the PRs and issues referenced above, plus PR #6543 PR #6557 , PR #6558 and PR #6580 .
