### ISSUE TITLE
Variable names sometimes translated

### ISSUE THREAD

**Issue by rdstern** [africanmathsinitiative/R-Instat#6519]
This took quite a time to find.  Here is an example:
![image](https://user-images.githubusercontent.com/11226469/121331636-f9a50a00-c90e-11eb-8090-7249dd1d581b.png)

No, it is easy to get directly - it seems to be dataset dependent.  I tried with our usual survey data and never got the problem.
But starting R-Instat, then open samrain from the climatic guide datasets.  Run the bar chart graph with the option set to value, and year as the variable and (say) strt1 as the y-variable.  Runs fine.  Then return to the dialogue and it has replaced year by annee!

**Comment by lloyddewit** [comment]
@rdstern Thanks for reporting this.
This is an instance of missing functionality as described in issue #3721 (3rd item down) :
![image](https://user-images.githubusercontent.com/57253949/121511693-347b7080-c9e9-11eb-8e05-1c4f9ede858b.png)

I can fix the specific issue above by tagging the 'Variable X' receiver as 'do not translate'. This is a one-row change in the database (no code change needed). I tested this and it works.

I can raise a PR for this, but I would prefer to fix this in a more generalized way. I'm thinking that by default, receiver text should **not** be translated. This is because the receiver should take over the text from a selector without changing anything. Does this make sense?

**Comment by rdstern** [comment]
I agree that receiver text, for single and multiple receivers, should not be translated.  They contain the names of variables and they need to stay in their "neat" form.

**Comment by lloyddewit** [comment]
Fixed in PR #6544
