### ISSUE TITLE
Translation Layout Issue in Import Dataset Dialog

### ISSUE THREAD

**Issue by rachelkg** [africanmathsinitiative/R-Instat#6556]
@Patowhiz I have been looking over the Import Dataset Dialog to check how the French translation looks. 

I have found that when I import an .RDS file the Overwrite existing if duplicates (checkbox text) is cut off in French. However, I cannot find it in Visual Studio to change it. Please could you tell me where/how to find the different layers? 

Also how many different configurations of this dialog are there? I need to check them all. 

It seems a very complex dialog! (I will stop working on it until I hear back) 

Thanks, 

Rachel 
![Import dataset](https://user-images.githubusercontent.com/85707390/123312115-c51f7980-d4dc-11eb-8b64-1a56c580bda6.png)

**Comment by Patowhiz** [comment]
@rachelkg yes the dialog has multiple controls for different configurations, and since we are using `winforms `we are currently dependent on pixel perfect design, which means some controls have to be hidden even during design mode.

The import control rds, text, csv and excel as the main configuration(represented by 3 group boxes, namely; `grpText`, `grpRDS`, `grpCSV`). We also reuse these configurations for other file types.

The screenshots below demonstrate how you can get to the `groupbox` for `rds` files options (I'm happy to demonstrate this through an online call if the below steps are not clear enough.);

1. Select the `grpRDS` control using the properties palette.
![selecting grpRds](https://user-images.githubusercontent.com/21179007/123379897-9ab4d700-d543-11eb-9d66-73123b0ef4bf.png)

2. After selecting the `grpRDS`, on the form, you will see it highlighted though still hidden, just right click on the boundaries to access the context menu shown. Then click on the bring to front.
![2 bring to front](https://user-images.githubusercontent.com/21179007/123379918-a1dbe500-d543-11eb-93a7-99e74ab8cd4e.png)

3. After the above 2 steps, you will have access to the `rds` controls options.
![3 final](https://user-images.githubusercontent.com/21179007/123379949-aa342000-d543-11eb-833d-1c0e56069fe6.png)

**Comment by rachelkg** [comment]
@Patowhiz Thank you so much Patrick. this is really helpful. I will give it a try and request a call if I get stuck.

**Comment by Patowhiz** [comment]
@rachelkg did you manage to sort this out? if so, then you could close this issue.

**Comment by rachelkg** [comment]
@patowihiz Roger recommended that I do this dialog at the end as it is one of the most complicated and other people might be working on it at the moment. I have read your information but not yet worked on the dialog, so was leaving it open until I do. Is that ok?

**Comment by Patowhiz** [comment]
@rachelkg I'm okay with that. I'm the one working on it. I'll revert back to you once I'm done refactoring the code in the dialog.

**Comment by rachelkg** [comment]
Great thanks.
