### ISSUE TITLE
Add facility to view English in translated menus

### ISSUE THREAD

**Issue by rdstern** [africanmathsinitiative/R-Instat#6570]
This suggestion is after discussion with @dannyparsons.  I hope it is pleasantly simple!

We now have a Lan button to quickly see the English on dialofues, and now on sub-dialogues.  It would be good to have the same facility for the menus.  The suggestion is to add a Lan option to the end of the main menu when a language other than English is selected.  This is a switch.  Pressing it will change all the language in frm_main back to English.  Press it again to go back into the other language.  Leaving frm_main, e.g. going into a dialogue, also goes back to the selected language.

**Comment by lloyddewit** [comment]
@N-thony You recently added a 'lan' button to the subdialogs. This worked great. I think the feature @rdstern is asking for could be implemented in a similar way. The main difference, I think, is that you would call `translateMenu` rather than `autoTranslate`.
Would you be willing to implement this issue? If needed, then I'm happy to support on the translation aspects.

**Comment by lloyddewit** [comment]
This is fixed in #6572
