### ISSUE TITLE
Scatter plot options

### ISSUE THREAD

**Issue by rachelkg** [africanmathsinitiative/R-Instat#6576]
Hello @Patowhiz and @N-thony,

I wonder if you can help with the Scatter Plot Options dialog (ucrLayerParameters.vb) 
![Scatter plot options](https://user-images.githubusercontent.com/85707390/124315650-1953da80-db29-11eb-911c-1fd161c74647.png).

As you can see from the picture the check boxes are all misaligned with the associated text. Previously I have changed the size of the box containing the text and checkbox to make it thinner and this brings it back into alignment; however that do not work here. If I make the overall box thinner it cuts into the dropdown menu box. Any ideas on how to resolve this? 

Thanks, 

Rachel

**Comment by Patowhiz** [comment]
@rachelkg this issue is caused by the use of Dock property just as explained in issue #6558. 
The `ucrCheck` contained in `ucrLayerParameters.vb` is Docked to the left. Because it's docked to the left, when the parent container height is increased, also the  `ucrCheck` increase in size. However because the "box" is part of the VB.NET check box, it doesn't increase in size cause it was not designed to do so by default.

I think use of Anchor property instead of docking should solve this.

**Comment by rachelkg** [comment]
@Patowhiz Thanks for the explanation. Would you be able to resolve this? 

Thanks, 

Rachel
