### ISSUE TITLE
Lining up the variable button and selector

### ISSUE THREAD

**Issue by rachelkg** [africanmathsinitiative/R-Instat#6577]
Hello @Patowhiz and @N-thony, 

I have noticed that the Single/multiple Variable button does not quite line up with the selector below it. However, when i go to change the size of the button I can't see how to do it. The two are an item called ucrVariablesAsFactor but when i look at that item them seem to line up. Do you have any idea how to address this? 

Thanks, 

Rachel 
![Point plot](https://user-images.githubusercontent.com/85707390/124317443-0b538900-db2c-11eb-9607-17982411d267.png)
![ucrVariablesasfactor](https://user-images.githubusercontent.com/85707390/124317446-0bec1f80-db2c-11eb-92d6-30ab5d9b5b28.png)

**Comment by Patowhiz** [comment]
@rachelkg thanks for noting this. This issue is caused by how the control is designed. The button in the `ucrVariablesAsFactor` is set to always be `docked` at the top, effectively making it grow with the parent container. The receiver, which is the control below it, is set not set to grow with the container. 

The remedy would be I think to use the `Anchor` property instead of `Dock` property.
Would you like me to do this? or you could attempt to do it via the visual studio properties pallet. All the 2 properties are accessible there.

Button docked
![docked](https://user-images.githubusercontent.com/21179007/124752574-e02aba00-dedc-11eb-8cd7-27bc4ce9f1d2.png)

Button grows with the parent container
![grows with it](https://user-images.githubusercontent.com/21179007/124752615-ec167c00-dedc-11eb-9e8f-5523ce33b894.PNG)

**Comment by rachelkg** [comment]
@Patowhiz Thanks for your prompt response. If you could do this that would be great. 

Thanks, 

Rachel
