### ISSUE TITLE
urcSave.vb position button misaligned

### ISSUE THREAD

**Issue by rachelkg** [africanmathsinitiative/R-Instat#6596]
@Patowhiz In urcSave.vb the position button is slightly too low. However I do not seem to be able to move it? I tried changing the Anchor setting and the Dock settings but this did not resolve it. do you think you could take a look please? 

Thank you

Rachel 

![Convert to circle](https://user-images.githubusercontent.com/85707390/125120132-e79dbf00-e0a6-11eb-9aa8-fcbc09d6f54f.png)
![UrcSave](https://user-images.githubusercontent.com/85707390/125120126-e40a3800-e0a6-11eb-8ddc-353590224fcc.png)

**Comment by lloyddewit** [comment]
@rachelkg I had a quick look. I couldn't see any manually entered code (i.e. code in 'ucrSave.vb') that changes the position button location, so it appears that the button position is determined automatically by the WinForms library.
If I go in the designer and click on the button, combo box and text box, one after the other, then the dotted lines around the controls all seem to be aligned. So it appears that as far as WinForms is concerned, the 3 controls are aligned. But to the human eye, the controls are not aligned. Maybe we could work around this by overriding the automatic locations but I'm not sure it's worth it.
@shadrackkibet you have more experience with designing dialogs, do you have any ideas?

**Comment by rachelkg** [comment]
Thanks for looking into this @lloyddewit. I am the right person to decide about "Maybe we could work around this by overriding the automatic locations but I'm not sure it's worth it.". @rdstern do you have any thoughts?

**Comment by Patowhiz** [comment]
@lloyddewit I once looked at this, my theory is a bit different. I think the misalignments are due to wrong use of the dock properties. Different controls on the control are docked but their visibility during runtime is changed, and also, the parent control used in different dialogs vary in sizes which again affects the internally docked controls alignments. So the alignments calculated by the designer end up changing in unpredictable way.

I'm skeptical when we start adding code that tries to align controls in runtime, because we are mixing design and logic code. My suggestion leans to finding alternative designs even though currently this may not be worth the time.


I'm looking into other controls mentioned by @rachelkg that behave in a similar way. I think (lightly) design solutions I'm coming up with could be applied to this.

**Comment by Patowhiz** [comment]
@rachelkg I have fixed the above issue for the dialog you have shown above(Convert to circular dialog). If there are other dialogs you could just do something similar to what I have done in PR #6612.

I did the same before for various other dialogs that @rdstern had raised an issue for.
![convert_to_circular](https://user-images.githubusercontent.com/21179007/125777764-d9f4d40c-db5e-46bb-ae59-595d68c7efef.PNG)
