### ISSUE TITLE
Adding pivot tables

### ISSUE THREAD

**Issue by lilyclements** [africanmathsinitiative/R-Instat#6634]
I came across the `rpivotTable` package which introduces pivot tables as a little widget in R. The user can get the results of a single summary statistic and move variables around the table.
Function-wise it looks relatively straightforward, able to run with just a `data` variable given. 
A lot of the other parameters are all options that can be specified when running the R-code, or can be decided once the table is created
* `rows` - variables in the rows (however, can be changed after the table has run)
* `cols` - variables on the columns (however, can be changed after the table has run)
* `rendererName` -  whether a table, heattable, etc is shown (however, can be changed after the table has run)
* `inclusions` - levels of a variable to be included in the output
* `exclusions`, an alternative to `inclusions` - levels of a variable to not be included in the output (e.g. in `diamonds` data to not show the level `A` in the `color` variable, run the parameter: `exclusions=list(color="A")`)

For example, 

```
library(rpivotTable)
library(ggplot2)

rpivotTable(diamonds,
            cols = c("color"),
            rows = c("clarity", "cut")
            exclusions=list(color="E"))
```

![image](https://user-images.githubusercontent.com/21180424/126512985-6ee137c0-3885-478d-aed5-41c31b5717e2.png)

But the columns can be shifted around easily

![image](https://user-images.githubusercontent.com/21180424/126513129-8ad5656f-9dc5-4429-b64a-a23706e95977.png)

It looks like a flexible but simple function. I wasn't sure what thoughts were on perhaps including this as an option in R-Instat?

**Comment by rdstern** [comment]
@lilyclements this seems excellent.  It should be very simple to add the dialogue(s).  It works easily from within R-Instat, so we just need to add the appropriate dialogues.
a) It handles multiple factors on either rows or columns.
b) It allows for summaries of numerical variables as well.
c) It has the different types of percentages we need for the frequencies
d) It has a wide variety of graphical displays of the data
e) It really is a good parallel to the pivot tables and graphs in Excel.

I am not sure how to save the graphs/tables.  Is this through shiny?
It is currently (from R-Instat) in a browser.  I assume it can be in our output window once that is the new version that @ChrisMarsh82 is investigating.

It is also good at selecting levels of a factor for the displays.  

I have no ideas how to change (say) the colours in the graphs.  I suggest we don't bother with that, because we have ggplot2 for the presentation graphs.
It has a complicated way of trying to change the orders of a factor variable.  I suggest we do that in the dialogue.
It seems to have something to add for sub-totals.  I suggest we omit that.  This is a really flexible exploration tool.  That's what we use it for.
It seems a bit messy when there are lots of variables.  I suggest with data frames that have many variables, we can include a subset, rather than having to include them all.  
The display becomes a bit messy when variable names are very long (the procurement data is an example.  We recognise this weakness.
So I suggest a new dialogue under Describe > Two Variables and also under Describe > Three variables

With two variables we have the usual data selector.  Then two single receivers labelled Row Factor and Column Factor.  Next to each of them is a pull-down as for the bar charts with the 4 options As Given, Reverse, Ascending, Descending.

Below is a checkbox default unchecked with label With Selected Variables.  There is a tooltip "Include the data frame if unchecked."
If checked, then there is a multiple receiver for as many variables as needed.  They can be any type, not just factors.  A dataframe is made from those, plus the 2 factors.

In the 3 variables case it is the same, but there is an additional third single receiver.  3rd Variable.  It can be anything.  If a factor , then it again could be sorted.  and it is an additional row factor.  If not, then the pull-down asks for the initial summary pull down is sum, mean minimum, maximum, median.  The table starts with this initial statistic. 

As a start we need to add this package.

**Comment by rdstern** [comment]
Aha I have found a (slight?) complication.  See the figure below:

![image](https://user-images.githubusercontent.com/11226469/126620767-c5c42be0-8e1a-42c6-abe2-79c9abfb9f0d.png)

This is very powerful.  These are daily data and this has given monthly summaries.  Add the day factor and you see the daily with these means becoming sub-totals!  And the summaries can be counts, means or sums.


Notice the order of the months is alphabetical.  But it isn't in R-Instat, it goes from Jan to Dec as I would wish.

This issue is addressed in the documentation, and the vignette vives an example.  Here is what it says:

```
sorter: String name this allows to implement a javascript function to specify the ad hoc
sorting of certain values. See vignette for an example. It is especially useful
with time divisions like days of the week or months of the year (where the alphabetical order does not work).
```
Here is the example code:

```
library(rpivotTable)
data(HairEyeColor)
rpivotTable(data = HairEyeColor, rows = "Hair",cols="Eye", vals = "Freq", aggregatorName = "Sum", rendererName = "Table", sorters = "
function(attr) {
var sortAs = $.pivotUtilities.sortAs;
if (attr == \"Hair\") { return sortAs([\"Red\", \"Brown\", \"Blond\", \"Black\"]); }
}", width="100%", height="400px")

```
I assume this might need a bit of nifty programming?

**Comment by lilyclements** [comment]
That's interesting. After a little playaround, the code to rearrange the factor levels in the pivot table to be the same as defined in R-Instat is:

```
month_levels_given<- paste(shQuote(levels(dodoma$month_abbr), type="cmd"), collapse=", ")

rpivotTable(data = dodoma,
            rendererName = "Table",
            sorters = paste("
function(attr) { 
var sortAs = $.pivotUtilities.sortAs;
if (attr == \"month_abbr\") { return sortAs([", month_levels_given,"]); }
}"), width="100%", height="400px")
```

So I guess we should say in the dialog code that if a variable in the data set is a factor, then run the 

`month_levels_given` part and the
`if (attr == \"month_abbr\") { return sortAs([", month_levels_given,"]); }`


As a side note - another parameter I've just noticed is `locale` which changes the language for the table - with french (amongst others!) as an option.

**Comment by lilyclements** [comment]
> Below is a checkbox default unchecked with label With Selected Variables. There is a tooltip "Include the data frame if unchecked."
> If checked, then there is a multiple receiver for as many variables as needed. They can be any type, not just factors. A dataframe is made from those, plus the 2 factors.

@rdstern I just wanted to clarify what you meant by this point of the data frame.
Does this mean that we want to subset the data frame to the variables in the row, column, and multiple receivers, and then this "shortened" data frame is the data frame in the `rpivotTable` command?

**Comment by rdstern** [comment]
@lilyclements that's right.  The dialogue uses the "whole" data frame and sometimes we may have 100s of variables.  It becomes messy then, so it would be good to be able to limit the variables for this.  I see this as just the same as in that most dialogues would take account of a filter - and assume we will do the same here.

**Comment by Ivanluv** [comment]
> In the 3 variables case it is the same, but there is an additional third single receiver. 3rd Variable. It can be anything. If a factor , then it again could be sorted. and it is an additional row factor. If not, then the pull-down asks for the initial summary pull down is sum, mean minimum, maximum, median. The table starts with this initial statistic.

@rdstern  for the three variables, which parameter should I be updating with the additional third Single receiver?

Also @lilyclements Should I have this run ie 

> month_levels_given<- paste(shQuote(levels(dodoma$month_abbr), type="cmd"), collapse=", ")
rpivotTable(data = dodoma,
            rendererName = "Table",
            sorters = paste("
function(attr) { 
var sortAs = $.pivotUtilities.sortAs;
if (attr ==", "\"month_abbr\"", ") { return sortAs([", levels_given,"]); }
}"), width="100%", height="400px")

every time the third receiver is has a factor column?

**Comment by lilyclements** [comment]
@Ivanluv i guess we would ideally want that to run any time a receiver is a factor. Perhaps we can do a check like to run it if the levels of a factor variable is not alphabetical (ie isn’t default levels)

**Comment by rdstern** [comment]
@Ivanluv hope all is going well with the pivot tables?  If the factor sorting is proving a puzzle then let's get the rest working and make an issue to add that feature later?
Could you also add the Help IDs to these dialogues.  It is 417 for the 2 variable and 601 for the 3 variable.

Thanks

**Comment by Ivanluv** [comment]
@rdstern I have the pivot tables for the three variable ready but there are existing PRs with form main changes ,so if create also create a PR there will be conflicts. Am waiting for the PRs to be merged then I can   create the PR on these

**Comment by shadrackkibet** [comment]
@Ivanluv which PR's is blocking this for quick action?

**Comment by Ivanluv** [comment]
PRs #6635, #6752, #6774

**Comment by shadrackkibet** [comment]
@Ivanluv Looking into these PRs it contains changes from other files and some already with conflicts. We always want the main form changes done in one PR so that we can review quickly and merge. I suggest as follows;

- First, create a PR showing the work on three variable pivot tables.
- Enable three variable pivot tables on a separate PR for quick review and merging
- Once merged update the three variable pivot tables PR with the master branch

**Comment by rdstern** [comment]
I am re-opening this issue to combine the 2 dialogues for the pivot tables.  
a) I suggest adapting the current dialogue that is under 3 variables.
b) Once that is accepted and merged, then it will replace the pivot-table dialogue under 2 variables.  Then we will be deleting the Describe > Three Variables menu.
c) The current label `Variable` becomes a checkbox saying `Numeric Variable (Optional):`  Default unchecked.  When checked, the control is visible.
d) While unchecked the Table/Chart and Summary controls are not visible.  When the numeric variable is checked, they become visible as now.
e) Track down this error that I get occasionally.  
![image](https://user-images.githubusercontent.com/11226469/157866169-3f4fadfd-6a01-4e42-aa4a-75d1195d0baf.png)

The code generated when I get this error is:
```
diamonds <- data_book$get_data_frame(data_name="diamonds")
last_table <- rpivotTable::rpivotTable(data=diamonds, rendererName="Table", aggregatorName="Count")
data_book$add_table(table_name="last_table", table=last_table, data_name="diamonds")

data_book$get_objects(data_name="diamonds", object_name="pivot_table")
```
When I return to the dialogue and run again, the code is the same, except now the last line is:
`data_book$get_objects(data_name="diamonds", object_name="last_table")`

And this time it runs fine.  So, why does the command occasionally want to use the name pivot_table, when it sorted out the object called last_table?  That's the puzzle to unravel.

Note that Ok is enabled even if nothing has been entered into the controls.  That's correct.  It is then possible to construct the table once the default is there.

**Comment by Ivanluv** [comment]
Am working on this
