### ISSUE TITLE
Bug when trying to open the View>script and other windows

### ISSUE THREAD

**Issue by N-thony** [africanmathsinitiative/R-Instat#6895]
I have tried to open the script window but unfortunately, I'm getting the error in the screenshot below
![image](https://user-images.githubusercontent.com/68591383/140024623-7dda97c0-67e1-49e7-a616-df78b2f9a153.png)

**Comment by shadrackkibet** [comment]
Using the **To Script** button from diaogs right?

**Comment by N-thony** [comment]
> Using the **To Script** button from diaogs right?

From the menu
![image](https://user-images.githubusercontent.com/68591383/140041028-8a178dea-ec1b-4dfc-8889-94fc0ed69abb.png)

**Comment by N-thony** [comment]
@shadrackkibet I found that this issue is coming after the change for the paging of wide data sets feature.
Should I move it to #6882?

**Comment by N-thony** [comment]
> @shadrackkibet I found that this issue is occurring after the change for the paging of wide data sets feature. Should I move it to #6882?

**Comment by shadrackkibet** [comment]
Yes please

**Comment by rdstern** [comment]
@N-thony I checked your figure above with Version 0.7.2, and it does seem ok there.
@ChrisMarsh82 in the merged version I don't get as far as Antoine's figure above.  It also looks odd before the script window, because the Data Frame metadata isn't that - but is the data window - empty of course.
I get a crash from the initial front menu, as soon as I try to press the button on the tool bar for the column metadata  - I am not sure why one would want that, before having any data, but it shouldn't crash.  It takes me to line 503 in (I think) frmmain
![image](https://user-images.githubusercontent.com/11226469/140134391-17375f32-ac0b-4349-8b0f-aa6eff65740d.png)
