### ISSUE TITLE
Change "Transpose" to extend and be consistent with Tidyverse

### ISSUE THREAD

**Issue by lilyclements** [africanmathsinitiative/R-Instat#6905]
I have been looking at the dialogs in the "Data Reshape" sub-menu to check for consistencies with Tidyverse.

Reading [here](https://newbedev.com/how-to-transpose-t-in-the-tidyverse-using-tidyr) shows that transposing with the Tidyverse is a little less simple than the current `t()` command. For example:

```
library(dplyr)

# Currently how we transpose data in R-Instat
as.data.frame(x=t(chickwts$weight))

# How we can transpose using tidyverse code
chickwts %>%
  dplyr::select(c(weight)) %>%
  tibble::rownames_to_column() %>%  
  pivot_longer(-rowname) %>%
  pivot_wider(names_from=rowname, values_from=value)
```

Additionally, transposing using the Tidyverse introduces new problems - such as an error if there is a factor and a numerical variable that are both being transposed.

@rdstern I suggest we keep this as it is for now using the `t` function. What do you think?

**Comment by rdstern** [comment]
@lilyclements sorry for the delay in this reply - I am now using the break to catch up a bit - and to write the help for R-Instat.  I suggest a change in the transpose command as follows:
a) Use the data.table::transpose command instead of t.  We already (I think) load into R-Instat data.table, so that should be easy.
b) Add a single receiver, below the Multiple one.  It has the Label `Variable Names` and adds the make.names argument to the command.  This is optional, so Ok is enabled as soon as the multiple receiver has data in it.
c) At the same time please change the R command generated, so that the first line gets the data frame.  Currently it is all in a single (complicated) line.  

The facility can be tested with the tidyr world bank data file.  Filter so the data are for a single country - say Kenya.  There will then be 4 rows of data and columns are from 2000 to 2017.

**Comment by lilyclements** [comment]
@rdstern this sounds like a good solution. 
I also suggest we could make use of the `keep.names` argument. This takes a string for a new column name, and the values given are the variables.

E.g.
```
library(data.table)
library(ggplot2)
head(diamonds)
dd <- head(diamonds, 6)
transpose(dd)
```

```
      V1      V2   V3      V4   V5        V6
1   0.23    0.21 0.23    0.29 0.31      0.24
2  Ideal Premium Good Premium Good Very Good
3      E       E    E       I    J         J
4    SI2     SI1  VS1     VS2  SI2      VVS2
5   61.5    59.8 56.9    62.4 63.3      62.8
6     55      61   65      58   58        57
7    326     326  327     334  335       336
8   3.95    3.89 4.05     4.2 4.34      3.94
9   3.98    3.84 4.07    4.23 4.35      3.96
10  2.43    2.31 2.31    2.63 2.75      2.48
```

```
transpose(dd, keep.names = "Names")
```

```
     Names    V1      V2   V3      V4   V5        V6
1    carat  0.23    0.21 0.23    0.29 0.31      0.24
2      cut Ideal Premium Good Premium Good Very Good
3    color     E       E    E       I    J         J
4  clarity   SI2     SI1  VS1     VS2  SI2      VVS2
5    depth  61.5    59.8 56.9    62.4 63.3      62.8
6    table    55      61   65      58   58        57
7    price   326     326  327     334  335       336
8        x  3.95    3.89 4.05     4.2 4.34      3.94
9        y  3.98    3.84 4.07    4.23 4.35      3.96
10       z  2.43    2.31 2.31    2.63 2.75      2.48
```

**Comment by rdstern** [comment]
@lilyclements sounds good.  Agreed.

**Comment by lilyclements** [comment]
@rdstern great. Who do you suggest takes this task on?
