### ISSUE TITLE
Data frame info doesn't update correctly

### ISSUE THREAD

**Issue by dannyparsons** [africanmathsinitiative/R-Instat#6907]
> When I do simple operations, like adding a variable, the grid refreshes fine, but the information on the bottom line doesn't refresh. For example, if I start with 7 variables and add 3 more it still says 7.

**Comment by dannyparsons** [comment]
Specifically, the information updates when there are multiple sheets and you switch between sheets, including displaying the filter details correctly. It just doesn't refresh after an operation has run.

**Comment by rdstern** [comment]
Aha, I confirm and that's a relief, because it should be easily fixed.  I tried with the Pakistan data and a filter and this information appeared nicely after I switched, and then returned.
I also deleted some variables and that information was also updated.
I deleted one of the data frames and that seems to be different.  It still looks as though it is there.  That information was updated when I imported another dataset.
