### ISSUE TITLE
Check on function for infilling daily climatic data

### ISSUE THREAD

**Issue by rdstern** [africanmathsinitiative/R-Instat#6915]
This should be a useful function and can be mentioned, and perhaps promoted.  This is the dialogue: 

![image](https://user-images.githubusercontent.com/11226469/141082209-8ecfe0f0-3979-41af-a4d9-f50bf9456026.png)

It currently uses an out-of-date function from chillR and perhaps there could be a quick check that this works.  Also I wonder if it works - or could work - with a filter.  I wonder whether infilling might be better if there were an option to do it separatley in (say) Winter and Summer?
We should also get someone in the team to try this out.  Could we get some sample datasets - possibly using CHIRTS and/or ERA5?

**Comment by dannyparsons** [comment]
The new function `chillR::patch_daily_temps()` looks to be comparable with the old one `chillR::patch_daily_temperatures()`.

The new function has an additional parameter which looks very nice:

> time_interval	
> time interval for which mean bias and standard deviation of the bias are to be evaluated. This defaults to "month", which means that the function looks for overlapping days between weather and patch_weather for each calendar month. Bias correction is then also done on a monthly basis. 'time_interval' can also assume other values, such as 'week' or '2 weeks'.

I believe it will be a simple change over to the new function. Since the old function still works, I suggest being cautious and not changing it over now before the new version, just in case there are breaking changes or changes to output etc. we might have missed.

**Comment by dannyparsons** [comment]
Anyone could take this up and do the following:

- Change the function name to the new one
- Add the `time_interval` parameter. I think the options for this are the same as on the PICSA graph sub dialog for choosing the break points of a date axis i.e. a number followed by week/month
