### ISSUE TITLE
Problem with deleting the dataset from the dataview seems to persist

### ISSUE THREAD

**Issue by N-thony** [africanmathsinitiative/R-Instat#6927]
I have loaded two datasets words and sentences from the library - stringr package and tried to delete the sentences dataset from Data View right-click on the tab of sentences but after deleting, the sentences were still present in the Data View. Then I have tried the load another dataset, you can try with any, in my case I have tried with rwanda dataset, and found that the sentences dataset was no longer in the Data View.
Here is the screenshot after deleting sentences dataset from Data View
![image](https://user-images.githubusercontent.com/68591383/141250915-f0ab5989-00d9-4865-9470-d3d345d615f5.png)
Then here after loading rwanda dataset
![image](https://user-images.githubusercontent.com/68591383/141251028-806b2ff8-f1c1-4618-b0c5-7b70b7ba3adc.png)

But check first if you can reproduce that.

**Comment by rdstern** [comment]
@N-thony thanks for this.  I thought this was ok in the latest merged version, but I confirm that this still remains to be fixed. 

There remains also the minor, but perhaps related issue that @dannyparsons raised yesterday.  Namely I open `words `from the stringr library and that's fine.  Then I open `sentences` and it used to change the focus to the new data frame, which it doesn't do now.  
And I have not checked on that happens to the focus in the column dataframe window either.  I am still keen that with large datasets we may want to work with the 2 basic windows being the column metadata plus output, rather than data plus output.

Anyway back to your problem.  I tried deleting first `sentences `and then `words`.  It (I assume) works fine, but they are still there in the data window - didn't check the other windows.  When I return to the dialogue they are not in the data selector - which is good - but they are still in the data receiver - that's not new - it is a long standing "feature".

What is great now is that `File > Close Data Book` is now working perfectly, including returning us to the initial screen.

**Comment by dannyparsons** [comment]
The first issue still remains. The second on switching to the new tab when loading a second data frame is now fixed, but not for the Column Metadata, I will add that to the issue #6917
