### ISSUE TITLE
Levels/Labels dialog freezes when there's too many levels

### ISSUE THREAD

**Issue by dannyparsons** [africanmathsinitiative/R-Instat#6936]
From https://github.com/africanmathsinitiative/R-Instat/issues/6900#issuecomment-962964087

> I have now found another bug in this dialogue and am delighted, because this is within a topic we should investigate more generally.
> This one is also present in Version 0.7.2, so has not been introduced by recent changes.
> Again, please see first if you can repeat it!
> a) Open the diamonds dataset from the library. It is the first example in the ggplot2 package.
> b) It has 10 variables, of which 3 are (ordered) factors and the other 7 are numeric.
> c) Make those 7 numeric variables into factors. The one called price is what causes the problem, so you can start there if you prefer.
> d) Now use right-click and the Levels/Labels dialogue. Once in the dialogue you can look at any of the factor variables. I often look at just one, and then right-click on others as I examine them.
> e) They have between 127 and 554 levels - except for price and that has 11602 different levels.
> f) Close, or press OK on the Levels/Labels dialogue after price.
> g) Then I am stuck. The program freezes.

**Comment by dannyparsons** [comment]
@ChrisMarsh82 This is where your idea of lazy loading could come in. Or the grid control could have the same paging structure as the Data Grid.

**Comment by Patowhiz** [comment]
@rdstern @dannyparsons @N-thony this is caused by repeated function calls at the `ucrFactor` control level. The effect is not noticeable when the levels are a few but when we have over 1000 values, this is expected. Omitting the repetition in calling of functions when the dialog reloads should fix this issue.  

From my assessment, we have 2 possible approaches;
1. Short term fix - introduce a flag that prevents function calls repetition when reloading dialog.
2. Long term fix - refactoring the dialog. I highly recommend this. 

After refactoring I would also recommend a discussion about how many levels should we allow to be viewable in the grid, probably similar functionality to the data view?

**Comment by rdstern** [comment]
@Patowhiz thanks for that.  I don't quite understand refactoring, but the change needs to be well done.  There are other dialogues, particularly the filter that also show the different levels of a factor.  I wonder what happens to them?

**Comment by Patowhiz** [comment]
@rdstern okay. I'm now refactoring this control.

**Comment by rdstern** [comment]
@Patowhiz that's great.  There are quite a number of dialogues that load a factor.  For example the Filter dialogue has filter from factor, and also loads the levels when you want to choose a subset of the levels.  I am hoping they all use (or will use) the same.

**Comment by Patowhiz** [comment]
Yes.
