### ISSUE TITLE
Ctrl + C when highlighting text on the Output Window doesn't work

### ISSUE THREAD

**Issue by dannyparsons** [africanmathsinitiative/R-Instat#7000]

**Comment by N-thony** [comment]
@dannyparsons just a quick check, when I try with `Ctrl+Shift+C` it seems to copy the highlighting text on the Output Window. Do you mean it should be `Ctrl + C` rather than `Ctrl+Shift+C`?

**Comment by N-thony** [comment]
> _No description provided._

@dannyparsons I found also when the text is copied from the Output Window and then pasted in Script Window, the copy is one line rather than multiple if so from the Output Window. @ChrisMarsh82 I made a small improvement of `CopySelectedElementsToClipboard()` in the linked PR.

![image](https://user-images.githubusercontent.com/68591383/145933454-d81afe87-e612-47f7-938a-5d90d6688f86.png)
