### ISSUE TITLE
The sheets tab is hidden by the scroll bar when a dataset is loaded

### ISSUE THREAD

**Issue by dannyparsons** [africanmathsinitiative/R-Instat#7006]

**Comment by dannyparsons** [comment]
@Patowhiz Chris has been looking into this and can't seem to see why the sizing of the tab buttons is ignored/reset for the Data View. It works ok for the Column Metadata Window. Could you have a look at this? Possibly comparing to the previous code before Chris's changes might help.

**Comment by Patowhiz** [comment]
@dannyparsons let me have a look at it.

**Comment by Patowhiz** [comment]
@dannyparsons @ChrisMarsh82 my understanding is `ucrDataView`  is now using the `TableLayoutPanel` VB.Net control to align the 3 controls that are in it;  the _launch panel, linux grid, windows grid_. Then it dynamically changes the size of these docked controls by setting its column size.

@dannyparsons this issue is caused by the dynamic change of the `TableLayoutPanel` column sizes. The `reogrid` ends up changing its `SheetTabWidth` property from **450** to **60**, thus hiding sheet names from the user. When the column size of the `TableLayoutPanel` 'housing' is changed from **0** to **100%**, the `SheetTabWidth` of the `reogrid` remains at 60 pixels, thus sheet names remains hidden.

I have fixed this in PR #7111. inside the `SetGridVisibility()` subroutine, which I think is the best place to fix this.

@ChrisMarsh82 you may have a different idea in regards to where this `SheetTabWidth` resizing should be set (the data view control has significantly changed from how I last understood its base code, you now understand it better).

@dannyparsons below is a quick code preview of the current code and what I have added to save your time.

![ucrDataview](https://user-images.githubusercontent.com/21179007/149174421-53404f6c-cadb-4143-9621-e4c9352d2165.PNG)

**Comment by dannyparsons** [comment]
Thanks very much for looking into this in detail! I've replied to the PR with a suggestion, but great that we have something that works.
