### ISSUE TITLE
Update Merge Additional Data dialog

### ISSUE THREAD

**Issue by dannyparsons** [africanmathsinitiative/R-Instat#7029]
This dialog: Options by Context > Prepare > Merge Additional Data
is a simplified merge that does a left join and saves the result back into the same data frame.

This is useful when you just want to merge additional columns from another data frame which has matching values to join by so won't change the structure of your data. It's convenient for this to be saved as the same data frame to avoid producing multiple copies of your data. The merge dialog doesn't do this as it often produces something new or goes wrong.

The dialog currently looks for a key and if it exists it uses that as the join options. Otherwise you can define them. You have the choice of selecting columns from the second data frame but the first is fixed to have all the columns.

This dialog could be used generally, not just in this menu. Before that, there could be some improvements:

- It should check that the result will not add any extra rows i.e. all values in the join columns in the second data frame must appear in the first, otherwise it should give an error.
- It currently doesn't save over the first data frame but produces a new one
- I couldn't seem to get it to work when I defined the join columns manually - maybe this wasn't implemented yet
- The data frame labels should be something like "Main Data Frame" and "Additional Data Frame"

This might need some more specification and view from @rdstern

**Comment by rdstern** [comment]
@dannyparsons I like this idea a lot.  
Here is the existing dialogue
![image](https://user-images.githubusercontent.com/11226469/144805262-e5e83266-dc5b-4597-8455-c7b7dcc2054e.png)

1) I suggest the first data frame adds the word Main., i.e. it is `Main Data Frame`
2) Currently it seems to add the key variables into the receiver.  I don't want to add those, because they are already there.
3) I assume the new variables will be added to the end.  Could there be a checkbox `Add at Start`.  Default is unchecked.  We could be more ambitious and include the Position button, but I think, but I think the Options for Start and End will be sufficient.    Then we can always reorder later if more is needed.
4) I assume the name will be Merge Additional Data and it will be just under the existing Merge dialogue?

**Comment by dannyparsons** [comment]
Sounds good apart from 3. The position of columns is fixed by the way the merge is done. It would be messy to try to reorder as well in this dialog. I think it's easier if this is done after if possible.

For 2. I feel it's more natural to include the joining columns here too because they are part of what you are merging - as well as making the code a lot easier.

**Comment by dannyparsons** [comment]
And the check is essentially that the join columns could form a link between the two data frames. We basically want to ensure the join will not change the structure of the original data frame. 

I think this would always be a left join so that there won't also be any additional values in the join columns in the second data frame that aren't in the first.

**Comment by rdstern** [comment]
ok @dannyparsons to my request to choose the position of the merged variables.  Happy for the default from merge.
On including the key variables, my point 2.  I don't quite understand your response.  They currently appear in the receiver automatically as well as the variables I want to copy over.  That confused me, because I don't want a second copy of those variables.  I assume I don't get that, and you are just saying that it makes the code simpler if they are there in the receiver.  Correct?  If so, that's fine.

And (as you say) it is fixed as a left join, so the data frame remains at its original length.  If anything else is needed, then the ordinary merge is used.

**Comment by rdstern** [comment]
In the Instat library climatic **_rwanda.rds_** has a good example.  In the daily data delete ID, and lat, long, elev.  They are in the second data frame.  Then use this dialogue to improve them.

The existing dialogue is (just about) working.
a) The suggested joins should use the code from the current Merge dialogue.  In my example above it currently gets station_ID as the suggested merging variable.  And it is in gray, even though station_ID isn't in one of the files.  It should find station_name.  (When I used the sub-dialogue it merged ok.
b) As @dannyparsons says, it should add to the first data frame, not make an additional one.  (That's the whole point of this additional dialogue.
c) I suggest we keep the first label as simply Data Frame.  Change the second label to **_Add Data From:_**
d) Now, what do we call it, and where does it go?  It can't go in Data Reshape, because it isn't reshaping!  I suggest it goes in Prepare > Data Frame and is after Reorder Columns and is titled simply Add Columns!

**Comment by rdstern** [comment]
@dannyparsons I would like this now to be done - and it is a good task for the team.  Are you happy (or at least ok) with my suggested placing of the dialogue?

**Comment by shadrackkibet** [comment]
@EstherNjeriLiberatta could you report on your progress on this task?

**Comment by dannyparsons** [comment]
I don't particularly like it in Prepare > Data Frame because I don't think users will find it easily, but if this is considered a more "dangerous" operation maybe that isn't too bad. It would be nice if there was a way to link to it from the Merge dialog somehow - we can do that in the help at least.

**Comment by shadrackkibet** [comment]
> @EstherNjeriLiberatta could you report on your progress on this task?

@EstherNjeriLiberatta?

**Comment by EstherNjeriLiberatta** [comment]
@shadrackkibet I've not yet started on this. I'm still working on issue #6905. Thanks

**Comment by EstherNjeriLiberatta** [comment]
@shadrackkibet could we have a skype call over this?

**Comment by shadrackkibet** [comment]
Sure, anytime.
