### ISSUE TITLE
Problem with Climatic > Check Data > QC Rainfall dialogue

### ISSUE THREAD

**Issue by N-thony** [africanmathsinitiative/R-Instat#7050]
I have used the `dodoma.RDS` with the QC Rainfall dialogue as shown in the first screenshot, when I click OK I get the following error in the second screenshot

![image](https://user-images.githubusercontent.com/68591383/145167339-98f9e008-4f18-415a-837d-0703b0751482.png)

![image](https://user-images.githubusercontent.com/68591383/145166933-2972d00c-12c3-42b3-925b-04b0c3f80c5e.png)

**Comment by rdstern** [comment]
@N-thony that's a good one to find.  I tried with a different dataset and get the same.
The error is presumably because none of the checks are enabled, but Ok is still enabled.  This may have been there for a long time!
I notice that this problem does not exist for the Temperature QC, where Ok is only enabled when one of the checkboxes is activated.  Perhaps you could make the same change for the rainfall dialogue?
I am really pleased that we are gradually spotting these problems and correcting them.
