### ISSUE TITLE
Recent files now seem to show lots of repeats?

### ISSUE THREAD

**Issue by rdstern** [africanmathsinitiative/R-Instat#7163]
I am using the recent master, but have also noticed this "feature" recently when examining various pull requests.
![image](https://user-images.githubusercontent.com/11226469/151016844-253ce2cf-5679-4f38-a754-7107f278723c.png)

I seem to have repeats in my list of recent files.  I don't find this to be a serious problem, but is this what is intended?  @ChrisMarsh82 I am not assuming you will fix, but you are perhaps well placed to say if it should be an easy fix.

**Comment by dannyparsons** [comment]
@Patowhiz Could probably look into this quickly.

**Comment by Patowhiz** [comment]
I'm looking into this.

**Comment by Patowhiz** [comment]
@rdstern thanks for noticing this.
@dannyparsons I traced this problem to 112 of class `clsRecentFiles`, it was added in your PR #7100. The line unintentionally allowed duplicates from existing saved recent file paths. There was always a risk of this happening because I think we are using the wrong data structure for the functionality. I can easily fix this by ensuring uniqueness is always checked before adding the paths to the list but I recommend using [HashSet](https://docs.microsoft.com/en-us/dotnet/api/system.collections.generic.hashset-1?redirectedfrom=MSDN&view=net-6.0) collection to avoid same logical bug in future? What do you think? 

![add_menu](https://user-images.githubusercontent.com/21179007/152317199-5308afd4-7548-4baf-86fd-4e816a981865.PNG)

**Comment by Patowhiz** [comment]
@rdstern @dannyparsons now that I'm looking into this, don't you think it's generally a good idea to **display** to windows users the file separators used in windows? Same for Mac and Linux users? It's a trivial functionality but making the software to be consistent with the platform is always recommended. This is generally a bigger task and can be done in another PR by someone else if you agree.
