### ISSUE TITLE
New grid has row size problem for some datasets

### ISSUE THREAD

**Issue by rdstern** [africanmathsinitiative/R-Instat#7165]
The example I am using is a single row - but many other examples are possible.  The data are from [gadm](https://gadm.org/download_country.html).
This figure uses Version 0.7.2 so with the old coding for the grid.
![image](https://user-images.githubusercontent.com/11226469/151022463-8fe4870b-8135-4ed3-a774-1bba9381b11f.png)

Notice the metadata is a bit messy.  But the data grid is fine - well at least the rows are ordinary size.

Here is the same data in 7.3.1.  The multipolygon has become a list of lists.  The metadata is as before.

:
![image](https://user-images.githubusercontent.com/11226469/151023675-7cf6f4fc-a420-4f86-b9fa-c69b9585390c.png)
This cell in the grid now goes on forever - well almost!
I really like it that reogrid sometimes stores lists in a cell, and have other examples.  But can we either avoid wordwrap, or have an option to turn it on and off?

I assume this is initially a question to @ChrisMarsh82 or @dannyparsons and might then be pretty easy for someone to fix?

**Comment by dannyparsons** [comment]
I think the solution we would want is to display complex column types in a more concise way.

We could consider the format used by `tibble` i.e. `<named list [3]>`

```r
df <- tibble(
  character = c("Toothless", "Dory"),
  metadata = list(
    list(
      species = "dragon",
      color = "black",
      films = c(
        "How to Train Your Dragon",
        "How to Train Your Dragon 2",
        "How to Train Your Dragon: The Hidden World"
       )
    ),
    list(
      species = "blue tang",
      color = "blue",
      films = c("Finding Nemo", "Finding Dory")
    )
  )
)
df
#> # A tibble: 2 × 2
#>   character metadata        
#>   <chr>     <list>          
#> 1 Toothless <named list [3]>
#> 2 Dory      <named list [3]>

```

or like the RStudio data viewer which cuts off the characters at a certain point:

![image](https://user-images.githubusercontent.com/11214914/153240870-9a255203-25c9-401c-bb29-f667f272437a.png)

Our grid is more like the RStudio data viewer than the very concise `tibble` output so that is probably a good baseline for us.

I think it would be worth checking the `tibble` and RStudio display for the column types in the shapefile example to see what sensible options might be in these cases.

The place to make these changes is in `convert_to_character_matrix()` in stand_alone_functions. We could build up the set of column types recognised and formatted in better ways. 
@shadrackkibet Could work on this or support someone to do so.

**Comment by shadrackkibet** [comment]
@Vitalis95 could you have a quick look into this? Let me know if this is something you can try with my support.

**Comment by Vitalis95** [comment]
![image](https://user-images.githubusercontent.com/89011415/154451403-be018822-ad43-4f66-bdc5-7364cb886f68.png)
@shadrackkibet can we have a call?  I am a bit confused about the r code
I am also getting the above error while importing the data from https://gadm.org/download_country.html to R-Instat

**Comment by shadrackkibet** [comment]
Importing Shapefiles is currently done using "Climatic>File>Import and Tidy Shapefile".

- I think we should add this dialog to the main File menu.
- We might also consider detecting the file type and then loading this dialog when using - Import Dataset dialog. The same can be done for `NetCDF` files

**Comment by Patowhiz** [comment]
> Importing Shapefiles is currently done using "Climatic>File>Import and Tidy Shapefile".
> 
> * I think we should add this dialog to the main File menu.
> * We might also consider detecting the file type and then loading this dialog when using - Import Dataset dialog. The same can be done for `NetCDF` files

@rdstern please note point 2 from @shadrackkibet comment. I would recommend the same for simplicity. And there are various way we can detect this and show the user the right dialog.

That point can be it's own issue.

**Comment by Patowhiz** [comment]
@dannyparsons @rdstern I've been looking at this. Below are my findings and suggestions.

The column that is the source of trouble is of class/type `"sfc_MULTIPOLYGON" "sfc"`.

The `convert_to_character_matrix()` R function, used by the data viewer grid, uses `as.character()` to convert any non-numeric columns to character columns so that the data view can be able to display them. 

Assuming you have a column of type `sfc_MULTIPOLYGON` called `geometry` in a data frame called `gadm40_GHA_0`, doing;

`as.character(gadm40_GHA_0$geometry)` will return 
![new_lines](https://user-images.githubusercontent.com/21179007/171026140-d74e5d3b-67e9-4614-83a1-f326f624fc56.PNG)

Notice the escape characters `\n`, which basically translates to new line in VB.NET. This is what makes the data viewer grid display such a column with a wider height. The R Studio viewer recognizes the escape characters and the entire string as type `list`. This made me try to explore the same functionality(on a separate note, ideally by recognizing `Lists`, just like R studio, we could build in a functionality that allows users to view lists in a 'structured' way, a functionality that I think we don't  need for `geometries`).

However, after going through the [documentation](https://r-spatial.github.io/sf/articles/sf1.html#wkb) of the `sf` package, I realized, the package already has functions of converting `sfc_MULTIPOLYGON` or rather `sfc`(to be more general) types to the standard _well-known text_ that is human readable. I prefer this option.

So instead of using `as.character(gadm40_GHA_0$geometry)`, all we have to do is to call `sf::st_as_text(gadm40_GHA_0$geometry)`
