### ISSUE TITLE
Compare Columns

### ISSUE THREAD

**Issue by rachelkg** [africanmathsinitiative/R-Instat#7197]
Hello @dannyparsons, I wasnt sure who this should be for so hope that you could assign it? 

On the Compare Columns dialog I have two issues. 

1. Roger says that the Use unique names for comparisons checkbox needs to be removed. 

![2022-02-03_14-10-27](https://user-images.githubusercontent.com/85707390/152443591-1e2cd533-56ce-480d-801a-32461492f149.png)
 
2. I am trying to write the Help and i do not understand what the Sort checkbox does. What does it sort? The columns being compared? The results (I dont see how as this is a logical column)? I have tried checking this and unchecking this and I cant see a difference in my results.

Thanks, 

Rachel

**Comment by dannyparsons** [comment]
1. Yes that option can be removed from the dialog and the argument removed from the function. @africanmathsinitiative/developers Could someone take this up?

2. This sorts the values for the display in the output window, but it doesn't change the logical column, because it doesn't affect what values are being checked. See the differences in the order of the values in two outputs below with sorted and unsorted options. Hope that makes sense!

Note that if the columns are character or numeric the sort is in normal alphabetical/numerical order, whereas if the columns are factors then the sort is done by the order of the factor levels (which might not be alphabetical).

```
# sorted
Columns contain all the same values: FALSE
First column: Data.Name 
Second column: Stations.Name 
Values in first not in second: 
Values in second not in first: 'Bilma', 'Gaya', 'Maine-Sorda', 'Maradi', 'N'Guigni', 'Tahoua', 'Tillabery'
```

```
# not sorted
Columns contain all the same values: FALSE
First column: Data.Name 
Second column: Stations.Name 
Values in first not in second: 
Values in second not in first: 'Bilma', 'Tillabery', 'Tahoua', 'N'Guigni', 'Maradi', 'Maine-Sorda', 'Gaya'
```

**Comment by shadrackkibet** [comment]
@mmulahvictor should we be closing this? did you fully fix it in the linked PR?

Thanks for clarifying.

**Comment by mmulahvictor** [comment]
@shadrackkibet I fixed this PR and you can close it.

**Comment by shadrackkibet** [comment]
@rachelkg we think this has been sorted out. Danny also gave an example to illustrate Sort.

Please reopen if you are of a different opinion.
