### ISSUE TITLE
fastDummies package not included in 7.4

### ISSUE THREAD

**Issue by rachelkg** [africanmathsinitiative/R-Instat#7222]
Hello @shadrackkibet 

In using 7.4 I have noticed that fastDummies has not been loaded so needs to be added. Sorry I don't have a picture of the error message as I installed the package and now I don't get it anymore, but this is a picture of the dialog which causes it to come up in 7.4.

Let me know if you need any more information. 

Thanks, 

Rachel 

![2022-02-10_11-08-17](https://user-images.githubusercontent.com/85707390/153479327-01ad25c7-c83f-45b7-9b95-b8a8a67a5340.png)

**Comment by shadrackkibet** [comment]
@rachelkg good catch! this is because we missed adding this package [here](https://github.com/africanmathsinitiative/R-Instat/issues/6854) for the release. I will go ahead and add it now.


@africanmathsinitiative/developers always make sure any new packages are added into the branch that added features into R-Instat. How to add a new package is explained [here](https://github.com/africanmathsinitiative/R-Instat/wiki/Information-for-developers)
