### ISSUE TITLE
New bug in File > Open

### ISSUE THREAD

**Issue by rdstern** [africanmathsinitiative/R-Instat#7298]
This has been there for a long time!  There have been some bugs introduced in Version 0.7.4 and this is different.

![image](https://user-images.githubusercontent.com/11226469/158057092-0496adf0-5645-4aee-8e45-395d06a8c87e.png)

The message says it all!  Here is how to get it.
a) Open From Library > Instat > Browse > Climatic > Niger and open sadore.xlxs.  Open the sheet called sadore.
b) Now return to the library and open the rds file called sadore.  
That gives the bug.
Note I can open the xlxs file twice and it traps this situation, and gives the file a different name.  I can open the rds file twice and it is ok.  The problem is opening an Excel file first and an rds file second.  

The other way round seems ok, namely rds file first and Excel file second is ok!

I assume this should be easy to fix

**Comment by Patowhiz** [comment]
@rdstern the bug is caused by R function `data_book$import_RDS` R function.

When importing excel, csv and other non rds files we use, `data_book$import_data`. This function converts the set data frame names into lower case before checking on whether to rename or not. However the `data_book$import_RDS` doesn't do that. 

In summary;
1. `data_book$import_RDS` implementation will just do a check like  `Sadore` = `sadore`. That's it doesn't rename it.
2. `data_book$import_data` implementation will do `tolower(Sadore)` = `tolower(sadore)`. That's why it renames `Sadore` to `sadore1`.

That's why the reogrid breaks, because the sheet names aren't unique in this (it's case insensitive).

So  we just need to make `data_book$import_RDS` do the same check like `data_book$import_data`.
Thanks.
