### ISSUE TITLE
Extend the PCA dialogue

### ISSUE THREAD

**Issue by rdstern** [africanmathsinitiative/R-Instat#7318]
Looking in more detail this should be a reasonably easy improvement.
We currently already use the factominer package.  
Here is the current dialogue:
![image](https://user-images.githubusercontent.com/11226469/158806613-69140d2d-fc28-453f-952f-9f4e88458a51.png)

The factominer package says:
```
Description
Performs Principal Component Analysis (PCA) with supplementary individuals, supplementary
quantitative variables and supplementary categorical variables.
Missing values are replaced by the column mean.
Usage
PCA(X, scale.unit = TRUE, ncp = 5, ind.sup = NULL,quanti.sup = NULL, quali.sup = NULL, row.w = NULL,col.w = NULL, graph = TRUE,axes = c(1,2))
```
These are exciting additions, particularly:
a) Multiple receiver for additional numeric variables.  Suppl. Numeric
b) Multiple receiver for additional factor variables.  Suppl. Factors
c) Receiver for Additional individuals - a filter for us! 
In the examples it seems to code them numerically.  I assume we can use variable names?  I am not sure about c)
Then it is important that we get a pca object.  
There is a video, that then shows many alternative graphs from the pca object.
There is plot, predict, print and summary for the object.
There is a video, and it looks very nice.  How can we do that sort of investigation in R-Instat?

There is also fviz_pca and fviz_pca_var and get_pca from the factoextra package.

It looks as though (at least for multivariate, we want to get a pca object and then use it.  This is the parallel of our modelling ideas, i.e. fit and use, where we also have keyboards.  
We might even want to consider keyboards in multivariate, just as we have in the modelling???
We can possibly investigate by using the current modelling keyboard dialogues, before seeing if that could supply an "advanced" option for factoMiner to start with.  The fit keyboard could then not just be for pca, but for each of the methods?
 With dialogues we can start with Principal Components

**Comment by rdstern** [comment]
The initial changes in this dialogue should be easy.  This is to add a multiple receiver that can accept either numeric or factor type data - so relatively unrestricted.  There should be a checkbox, default unchecked, with label Extra Variables.  If checked, then the multiple receiver becomes visible. 
Then the dialogue needs correction.  The existing script (with the error) is as follows:

```
# Code generated by the dialog, Principal Component Analysis

last_model <- FactoMineR::PCA(X=data_book$get_columns_from_data(data_name="rice_survey", col_names=c("Field","Size","Fert","Yield")), graph=FALSE, ncp=4)
data_book$add_model(model_name="last_model", model=last_model, data_name="rice_survey")

data_book$get_from_model(data_name="rice_survey", value1="eig", model_name="last_model")
data_book$get_from_model(data_name="rice_survey", model_name="last_model", value1="ind", value2="coord")
sweep(STATS=sqrt(data_book$get_from_model(data_name="rice_survey", model_name="last_model", value1="eig")[,1]), x=data_book$get_from_model(data_name="rice_survey", model_name="last_model", value1="var", value2="coord"), MARGIN=2, FUN= ''''/'''')
factoextra::fviz_screeplot(X=data_book$get_models(data_name="rice_survey", model_name="last_model")) + ggplot2::theme_minimal()
rm(last_model)
```

So, I see we already use the FactoMineR package.  And there is an error, but that's in the line starting sweep, and I don't quite know why we need that line at all.

We will need some extra output - at least graphical - to make use of the extra variables (numeric or factor) and I don't know what happens if a numeric variable is in both - the assumption is that if it is an "Extra Variable", then it isn't used to make the PCAs.  

The factominer video may help to specify what is needed in extra output, particularly when the Extra Variables are included in the dialogue.  I assume the graphical display with those available, would be extra, and would only become available if there were variables included.

**Comment by Vitalis95** [comment]
@lilyclements , I am asking you help here;
this is the code
`PCA(X, scale.unit = TRUE, ncp = 5, ind.sup = NULL,quanti.sup = NULL, quali.sup = NULL, row.w = NULL,col.w = NULL, graph = TRUE,axes = c(1,2))`

But `ind.sup = NULL,quanti.sup = NULL, quali.sup = NULL` does not take the column names but rather takes the ****position** of the column,** i.e `ind.sup = 8,quanti.sup = 11:12, quali.sup = 13` when you put column names you will get an error.
is there a way I can implement that? because in R-Instat `data_book$get_columns_from_data()`  will get the column names

**Comment by lilyclements** [comment]
@Vitalis95 good question! I suggest we do this using the `which` function.

I don't know what `X` is in your example, so I'll give an example with the `decathlon` data set in the `FactoMineR` package.

If we wanted to give the axis for the `100m` and `Long.jump` variables, we can create `col_1` and `col_2` below and call them into the `axes` argument:

```
library(FactoMineR)
data("decathlon")
col_1 <- which(colnames(decathlon) == "100m")
col_2 <- which(colnames(decathlon) == "Long.jump")
PCA(decathlon, scale.unit = TRUE, ncp = 5,
    quanti.sup = 11:12, quali.sup=13,
    graph = TRUE, axes = c(col_1, col_2))
```

**Comment by Vitalis95** [comment]
> @Vitalis95 good question! I suggest we do this using the `which` function.
> 
> I don't know what `X` is in your example, so I'll give an example with the `decathlon` data set in the `FactoMineR` package.
> 
> If we wanted to give the axis for the `100m` and `Long.jump` variables, we can create `col_1` and `col_2` below and call them into the `axes` argument:
> 
> ```
> library(FactoMineR)
> data("decathlon")
> col_1 <- which(colnames(decathlon) == "100m")
> col_2 <- which(colnames(decathlon) == "Long.jump")
> PCA(decathlon, scale.unit = TRUE, ncp = 5,
>     quanti.sup = 11:12, quali.sup=13,
>     graph = TRUE, axes = c(col_1, col_2))
> ```

@lilyclements , thanks 
The arguments I am suppose to add are `quanti.sup ` and  `quali.sup`  and they don't take the column names but they take the column position. The arguments also may take more than one variable.

**Comment by lilyclements** [comment]
@Vitalis95 great - that can be sorted the same way as with the axes argument (so using  ‘which’). 
just set quali.sub to be equal to a vector of values and input them in e.g. quali.sub = c(col_3, col_4)

**Comment by Vitalis95** [comment]
@lilyclements , I tried running the following in the script window, col_1 and col_2 are quantitative while col_3 is qualitative but I got an error

`library(FactoMineR)`
`data("decathlon")`
`col_1 <- which(colnames(decathlon) == "100m")`
`col_2 <- which(colnames(decathlon) == "Long.jump")`
`col_3 <-which(colnames(decathlon) == "Competition")`
`last_model <- FactoMineR::PCA(X=data_book$get_columns_from_data(data_name="decathlon", col_names=c("X100m","Long.jump","High.jump")), quanti.sup=c(col_1,col_2 ), quali.sup=col_3 ,ncp=3, graph=FALSE)`
`last_model`

![image](https://user-images.githubusercontent.com/89011415/176647950-d4a65ea4-5fdc-4f88-9c6d-34623144cc95.png)

**Comment by lilyclements** [comment]
@Vitalis95 thanks for giving the code with the output. 

There's a few very small things going on here.

I'll outline my thinking to solve this.

The code you've given is running:

```
FactoMineR::PCA(X=data_book$get_columns_from_data(data_name="decathlon", col_names=c("X100m","Long.jump","High.jump")), quanti.sup=c(col_1,col_2 ), quali.sup=col_3 ,ncp=3, graph=FALSE)
```

The error says "undefined columns selected".

From this we can gather there is an issue with the columns given.  "undefined columns selected" generally means it does not recognise the column names.

Looking at the values in the `col_names` parameter, we can see `X100m`, `Long.jump`, `High.jump`.

In `R`, in the `decathlon` data set, one column name is `100m`. We change this in R-Instat to `X100m` since there are issues when it comes to having a variable name starting with a number.

However, from using the R code I gave, you are running
```
col_1 <- which(colnames(decathlon) == "100m")
```

We just need to change this line to 
```
col_1 <- which(colnames(decathlon) == "X100m")
```

When you implement this in the dialog, it will automatically have the variable name as `X100m` not `100m`, so there won't need to be any further worries there!
It's just one of those little R things. It's fair that you didn't expect it - I didn't think of it either!

Another issue here is with the `get_columns_from_data` argument. First you want to run this *before* running the `which` parameters. This is because `get_columns_from_data` filters the decathlon data set to a subset of variables. As a result, the order where the variables are changes.

Secondly, you need to include all variables in here, including variables which are `quanti.sup` and `quali.sup` (i.e., "Competition").
I'm not sure how the dialog is set up, but perhaps would it make sense in R-Instat for the variables that can be chosen for the `quanti.sup` or `quali.sup` receiver are limited to the explanatory variables in the multiple receiver for PCA? This occurs in another dialog in R-Instat so it is possible (I cannot remember where!).

So overall the code to run is something like:

```
col_data <- data_book$get_columns_from_data(data_name="decathlon",
                                            col_names=c("X100m","Long.jump","High.jump", "Competition"))

col_1 <- which(colnames(col_data) == "X100m")

col_2 <- which(colnames(col_data) == "Long.jump")

col_3 <-which(colnames(col_data) == "Competition")

last_model <- FactoMineR::PCA(X=col_data,
                              quanti.sup=c(col_1, col_2), quali.sup=col_3, ncp=3, graph=FALSE)

last_model
```

**Comment by N-thony** [comment]
@Vitalis95 any progress from Lily's code?

**Comment by lilyclements** [comment]
> @lilyclements When I Print the summaries of principal component analysis objects using `summary` function as shown below, the object `'last_model'` I have assigned is not found. It comes as an empty list @Ivanluv also looked on that issue and we couldn't find a solution

@Vitalis95 if you run this in your script window, you'll see it works. The issue is that your summary object is not a model, so it does not save into the add_model properly.

If you instead run,

```
last_model <- (object=FactoMineR::PCA(X=col_data, graph=FALSE))
data_book$add_model(model_name="last_model", model=last_model, data_name="decathlon")
data_book$get_models(data_name="decathlon", model_name = "last_model")
```

(i.e., remove the `summary`) you'll see it works. So if it is a `summary` object it should not be saved as a `model` (I think it's saved as a table? But I suggest checking the One Variable > Summary dialog).

**Comment by Ivanluv** [comment]
@lilyclements  when I try to get `last_summary `, in the code below ,after the assignment I get `NULL  ` object.I think  the problem might be with the summary function

`utils::data(package="factoextra", X=decathlon2)`

`data_book$import_data(data_tables=list(decathlon2=decathlon2))`
`col_data <- data_book$get_columns_from_data(data_name="decathlon2", 
                                            col_names=c("X100m","Long.jump","Shot.put"))
last_summary <- summary(object=FactoMineR::PCA(X=col_data, ncp=3, graph=FALSE))`

`last_summary`

**Comment by lilyclements** [comment]
@Ivanluv if you run the following, then the summary is given: 

`last_summary <- summary(object=FactoMineR::PCA(X=col_data, ncp=3, graph=FALSE))`

But it is a good point that `last_summary` is a `NULL` object. From looking at the `summary.PCA` function, this is occurring because the function calls `cat` not `print`/`return`. `cat` doesn't have a return value, so we cannot save this summary using the summary function.

E.g.

```
x <- cat(1:10)
x

x <- print(1:10)
x
```

Do we want the summary function? Can we instead call the objects in the `PCA` object?

E.g.

```
last_model <- FactoMineR::PCA(X=col_data, graph=FALSE)
last_model$eig
last_model$var
```
etc (see under "Values" in the "help" file for PCA).

**Comment by Ivanluv** [comment]
@lilyclements  I would prefer not saving the ` summary` done on the `PCA `object and just have the results printed on the output window

**Comment by Vitalis95** [comment]
> > There is plot, predict, print and summary for the object.
> 
> @Ivanluv and @Vitalis95 have found a problem with using `summary` on a `PCA` object. It can be run but cannot be saved, @rdstern, is it OK if we run and do not save the `summary` PCA object. If it is not, we can either write our own function to do it, or, have the option to call elements in the `PCA` object, e.g.,
> 
> ```
> last_model <- FactoMineR::PCA(X=col_data, graph=FALSE)
> last_model$eig
> last_model$var
> ```
> 
> @Vitalis95 @Ivanluv do you have any other suggestions?

@rdstern  What do you think of this?

**Comment by N-thony** [comment]
> > > There is plot, predict, print and summary for the object.
> > 
> > 
> > @Ivanluv and @Vitalis95 have found a problem with using `summary` on a `PCA` object. It can be run but cannot be saved, @rdstern, is it OK if we run and do not save the `summary` PCA object. If it is not, we can either write our own function to do it, or, have the option to call elements in the `PCA` object, e.g.,
> > ```
> > last_model <- FactoMineR::PCA(X=col_data, graph=FALSE)
> > last_model$eig
> > last_model$var
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > @Vitalis95 @Ivanluv do you have any other suggestions?
> 
> @rdstern What do you think of this?

@rdstern do you have any suggestions? Thanks.
