### ISSUE TITLE
A csv file that File > Open has trouble with?

### ISSUE THREAD

**Issue by rdstern** [africanmathsinitiative/R-Instat#7374]
[TTC 1981-2018.zip](https://github.com/africanmathsinitiative/R-Instat/files/8478380/TTC.1981-2018.zip)

I was able to read it, by opening in Excel and then saving as xlsx.  But opening as csv gave an error

Perhaps @Patowhiz or @N-thony could examine?

**Comment by Patowhiz** [comment]
I'm looking into this.

**Comment by N-thony** [comment]
> I'm looking into this.

Okay.

**Comment by Patowhiz** [comment]
@rdstern just to be clear the error is only thrown when you skip 2 lines? That's what is happening on my machine. I'm able to import it when I don't skip any lines, or when I skip 1,3 or more lines.

**Comment by N-thony** [comment]
> @rdstern just to be clear the error is only thrown when you skip 2 lines? That's what is happening on my machine. I'm able to import it when I don't skip any lines, or when I skip 1,3 or more lines.
I get this error
![image](https://user-images.githubusercontent.com/68591383/163386945-6036ddff-482c-4843-91e0-9c476413e43a.png)

**Comment by Patowhiz** [comment]
@rdstern currently, in R-Instat, we can't  handle duplicate column names when **importing** csv files. That's what is causing the bug. 

When you skip 2 lines, the **Date/Lat** row which becomes the column header ends up having duplicate columns names, notice the `-3.4` is twice when you view the csv file in an editor. You can't see this in the preview window because the sequence of commands used are a bit different. The import preview uses `convert_to_character_matrix()` function, which internally uniquifies  data frame column names. 

Importing as excel works because `rio` package by default returns the data frame with unique columns names. 

I'll do 2 PR's for this;
1. Make sure that R-Instat makes column unique at R level
2. Make sure R-Instat doesn't break at .Net level if there is a problem with getting the data frame(this will include some refactoring of the new structures added).

@N-thony I'm not able to reproduce your error when I convert the file to excel, probably you changed the file the extension instead of saving as excel. If so, then changing the file extension doesn't change the file type structure, so `rio` functions would definitely not work.
