### ISSUE TITLE
Two additions to the File > New Data Frame

### ISSUE THREAD

**Issue by rdstern** [africanmathsinitiative/R-Instat#7387]
I suggest this might become 2 separate pull requests, but just one if they both prove to be easy.
a) As mentioned in the Discussion topic #7378 add a further "data type" called Sequence.  The default is a variable from 1, 2, 3, ... .  I think that is simply the command seq(1,length).  Optionally you can give a default number, in which case, for a value, x, it gives seq(x, length+x-1).
b) Add a new button, perhaps the last one, called Lists.  It gives access to all the datasets in the rcorpora package.  for example currently give the command `data.frame(data=rcorpora::corpora("mathematics/fibonnaciSequence"))`
and this gives the first 1000 fibonacci numbers.  There is a bit of a design issue to make it easy.  Possibly there are 2 Pull-down controls, with the first giving the category and the second giving the list within that category.  
There are something like 42 categories and then (I think) 293 datasets overall.

The command data.frame(data=rcorpora::corpora( ) ), gives a list of the names of all the 293 datasets. It would be useful to be able to do that.  
Perhaps if you give a category and then don't specify the example, it gives all data frames in that category?
Usually you give a category and a dataset as above, e.g.   
![image](https://user-images.githubusercontent.com/11226469/163834391-8a6f5238-e510-4453-bb36-957889167d65.png)

to give:
![image](https://user-images.githubusercontent.com/11226469/163834469-7ce51741-f7b8-41fa-8447-4630996eac00.png)

@N-thony I suggest you may like to do the first part as it should be quick for you.  Perhaps both, or maybe pass the second part on to someone else?

**Comment by Patowhiz** [comment]
@rdstern I read the issue #7378. Interesting and good ideas.
I'm just a bit concerned with the consistency that we generally want to introduce in R-Instat.
I thought the column types that we have in this dialog should generally be consistent with those supported in R-Instat as displayed in the data viewer? Or you are leaning towards sacrificing that consistency for the functionality?

**Comment by rdstern** [comment]
@Patowhiz goodpoint, it isn't a type in quite the same way.  However, I am happy with the result, namely to be able (easily) to have a new data frame with just a sequence variable - and no variables with NAs that we then don't use.  Maybe a horizontal line before sequence, or a completely different way to add this variable could be interesting?

**Comment by Patowhiz** [comment]
@rdstern I suggest a right click or a button inside the **Default** column cells that opens a pop up or pop down, in which a user can choose expressions that will give the default values, and these expressions can of course have brief explanations of what they are (similar to what we have in the command and construct examples). This design also allows us to toggle the expressions shown based on the **type** of the column selected. For instance we can choose to only display sequence expressions when **numeric** or **date** column **type** is selected.

Why I'm I against adding **Sequence** as a type in the drop down you may ask? because as user, by default, I expect those column types I select in the drop down to literary correspond to actual R-Instat supported types that I'm used to seeing in main or column metadata grid.

![new_data_frame](https://user-images.githubusercontent.com/21179007/164892130-afdd1cea-3e51-4ae6-87e1-ae552030b439.PNG)

**Comment by N-thony** [comment]
@rdstern could you test this now? Thanks.

**Comment by N-thony** [comment]
At the same time, it will be good to make the 2 `Nud controls`  a bit wider
![image](https://user-images.githubusercontent.com/68591383/167136220-cf5b27af-3cd1-4145-a9bd-e95f00fab132.png)

**Comment by Patowhiz** [comment]
@rdstern @N-thony keep in mind that we need a more general solution for other dialogs too, in regards to inputting and displaying these long numbers.
