### ISSUE TITLE
Very small change needed in Contrasts dialogue

### ISSUE THREAD

**Issue by rdstern** [africanmathsinitiative/R-Instat#7392]
@anastasia-mbithe  This is looking very good now.  But it only allows factors.  This should include ordered factors.  You don't need to change anything on the display, but just include them in what you allow.  (Though perhaps you do, see below.)

I am confused now, because I defined fert1 in the rice survey data in the calculator as ceiling(fert).  Then made it an ordered factor and it didn't appear in the list in the contrasts dialogue (with the current merged version).  Then I made it an ordinary factor and it still didn't appear.  Then saved the data with this extra factor and re-opened and it still didn't appear.  Then closed R-Instat and tried again and it is fine now - it appears also for an ordered factor.  (There's something flaky here!)

I did find another point that we may have discussed before.  In the polynomial the contrasts are displayed with many decimal places.  Can the precision be limited to a maximum of 3 decimals?

**Comment by anastasia-mbithe** [comment]
@rdstern,
 So the dialog is already set to allow factors and ordered factors. Our problem is that the Selector does not update on reopening the dialog. I used the survey data and converted "field" to factor, opened the dialog for the first time and "field" was added to the list of factors. I then Converted another variable, "size" to a factor, this time it was not updated in the selector. 
I have also realized that this problem is across all dialogs that use factors. I have tried with the Reorder factor dialog and the Labels/Levels dialog and it behaves the same way.

You could investigate this from your end.

**Comment by anastasia-mbithe** [comment]
I have fixed the last part of the issue in PR #7411

**Comment by anastasia-mbithe** [comment]
I am closing this issue because it was fixed in PR #7411 and in issue #7421
