### ISSUE TITLE
Column Metadata doesn't open with the default selected dataset in the Data View

### ISSUE THREAD

**Issue by N-thony** [africanmathsinitiative/R-Instat#7477]
I have loaded the survey for `rwanda.RDS` file which comes with two datasets `rwanda_daily` and `rwanda_stations`, the default selected data in the `Data View window` is `rwanda_daily` but I select `rwanda_stations` then when I open `Column Metadata` it still open `rwanda_daily` by default rather than `rwanda_stations`. This was abit confusing for user during the workshop and always we were supposed to remind them to change the `dataset`.
![image](https://user-images.githubusercontent.com/68591383/168562225-24354577-3da8-49a9-bc3f-81ba778167d0.png)

**Comment by rdstern** [comment]
I agree, but it is only (I assume) the first time the meta-data are loaded?  Once they have been loaded on one occasion I assume they will remember their position - that's what we do with dialogues.  So, I see this failure the first time as a bit of an inconvenience and would be happy for it to be fixed, but only if it is really quick and easy.

**Comment by Patowhiz** [comment]
@rdstern from your above [comment](https://github.com/africanmathsinitiative/R-Instat/issues/7477#issuecomment-1127499183), did you mean that you only want this functionality when the user views the column metadata viewer the first time? If so, then please note that PR #7526 implementation seems to have added code that will always change the selected column metadata in the viewer, that is, "it won't remember it's position." @N-thony I'm I correct? And if so then @rdstern are you happy with that? 

Note also for the dialogs we simply decided to change the color of the selected data frame instead of selecting on behalf of the user.
