### ISSUE TITLE
Bug in the Start of Rains Dialogue 

### ISSUE THREAD

**Issue by derekagorhom** [africanmathsinitiative/R-Instat#7488]
We encountered this bug during the GMet workshop, this bug is found in the `0.7.5` version of R-instat but not in the older version (`0.7.4` seems to work fine)
![Start of Rains Bug](https://user-images.githubusercontent.com/76208189/169515476-a1d24e57-1b04-4f38-8b98-a0023d1fa624.png)

This bug occurred when we used the` Start of Rain` dialogue
1. Go to 'Climatic'
2. Click on 'Prepare'
3. Scroll down and select 'Start of Rains'
4. input the necessary Variables and conditions
5. The error is in the above the screenshot
![Screenshot (427)](https://user-images.githubusercontent.com/76208189/169516043-db4f8a10-18c2-4e49-87af-9ff34a289623.png)

The R commands for this dialogue in the `0.7.5` version seem to work fine for the `0.7.4` version.

**Comment by VimbayiChimonyo** [comment]
Hi, I have the same problem.
![image](https://user-images.githubusercontent.com/87077260/169797881-fe7e2acb-40a9-4ec7-8957-5c228475e9b2.png)


Thanks for the assist

**Comment by N-thony** [comment]
> Hi, I have the same problem. ![image](https://user-images.githubusercontent.com/87077260/169797881-fe7e2acb-40a9-4ec7-8957-5c228475e9b2.png)
> 
> Thanks for the assist

@VimbayiChimonyo I'm looking into this, I will let you know once fixed it.

**Comment by rdstern** [comment]
@N-thony thanks for looking at this.  I couldn't see the variable col_name in the code, so I assume the bug might be caused by something changed (maybe by Patrick) in the metadata?  I hope it will be easy to find.  I hope it will be pretty obvious, particularly as it has appeared since version 0.7.4.  If not obvious, then you could ask Danny to have a quick look?
