### ISSUE TITLE
Implement the PICSA Temperature dialogue

### ISSUE THREAD

**Issue by rdstern** [africanmathsinitiative/R-Instat#7499]
@N-thony I suggest this can start initially in a very simple way.  So there is a chance it can be implemented in Version 0.7.6?  Later in the implementation it will need some skillful R, and I suggest @shadrackkibet may help with the R aspects.  I am not sure who is best placed to do this.
a) It can start as a copy of the PICSA rainfall dialogue, though the sub-dialogue will be slightly different. 
b) @dannyparsons may be able to advise, because the only real differences will be in the fitted lines.  
c) The current rainfall graphs work fine for the temperatures, except that we need to fit a line as a default, rather than having horizontal lines  as an option.
d) We also need to be able to use monthly data, and the current rainfall graph already works fine for that.
e) So the main addition initially is simply to add the controls from the main Line plot.  So Add Fitted Line (rather than line of best fit) ticked by default, and Add se, unticked by default.  
f) Perhaps instead of Lines in the PICSA options we have Labels.  There we have various options for labelling the fitted lines.  I like slope per 100 years, perhaps with a significance level as an option.
g) When facets is not None, then there needs to be an option to Fit parallel Lines.  We now have geom_parallel, but should also do the analysis to provide the significance levels.

**Comment by dannyparsons** [comment]
Given that the code for this dialog is so large and complex I suggest we should not make a copy but use the same dialog and subdialog where different parts could be shown/hidden depending on the "mode" it is opened in i.e. "rainfall", "temperature" or "general".

The general can have all the available options whereas the "rainfall" and "temperature" can show/hide the relevant section and change labels.

So this means we're building the temperatures dialog into the rainfall dialog instead of starting with a new dialog. They can still be separate menu items which just set a variable to say which "mode" the dialog is opening in.
