### ISSUE TITLE
Plotting bug in PICSA rainfall is still there occasionally!

### ISSUE THREAD

**Issue by rdstern** [africanmathsinitiative/R-Instat#7534]
Here is the dialogue, with multiple y-variables - that's the new feature.
![image](https://user-images.githubusercontent.com/11226469/172590904-a6ed4e4e-caa0-4f9e-aa68-08dd076c31c3.png)

Here are the results - note the means the same for the 2 stations, and they are clearly not the same!

![image](https://user-images.githubusercontent.com/11226469/172591290-a61ce26d-1fd9-4958-9fca-cd141f4d1b0b.png)
 For what it's worth, here is the R-code:

```
# Code generated by the dialog, PICSA Rainfall Graphs
stationsJuly_by_station_s_year1 <- data_book$get_data_frame(data_name="stationsJuly_by_station_s_year1", stack_data=TRUE, measure.vars=c("min_s_doy","max_s_doy"))
stationsJuly_by_station_s_year1 <- stationsJuly_by_station_s_year1 %>% dplyr::group_by(variable) %>% dplyr::mutate(.mean_y=as.Date(x=round(mean(x=value, na.rm=TRUE)), origin="2015-06-30"))
last_graph <- ggplot2::ggplot(data=stationsJuly_by_station_s_year1, mapping=ggplot2::aes(y=as.Date(x=value, origin="2015-06-30"), colour=variable, x=s_year1)) + ggplot2::geom_line(size=0.8) + ggplot2::geom_point(size=3, colour="red") + ggplot2::geom_hline(mapping=ggplot2::aes(yintercept=.mean_y), size=1.5) + ggplot2::geom_label(mapping=ggplot2::aes(x=-Inf, y=.mean_y, label=paste("Mean:", format(x=.mean_y, format="%d %b"))), hjust=0, vjust=-0.3) + ggplot2::theme(panel.grid.major=ggplot2::element_line(colour="lightblue", linetype="longdash", size=1), panel.grid.minor=ggplot2::element_line(colour="lightblue", linetype="longdash", size=1), panel.border=ggplot2::element_rect(colour="black", fill="NA", size=0), axis.text.x=ggplot2::element_text(angle=90, size=12, vjust=0.4), axis.title.x=ggplot2::element_text(size=14), axis.title.y=ggplot2::element_text(size=14), title=ggplot2::element_text(size=20), plot.subtitle=ggplot2::element_text(size=15), plot.caption=ggplot2::element_text(size=8), axis.text.y=ggplot2::element_text(size=12), panel.background=ggplot2::element_rect(colour="white", fill="white", size=0.5, linetype="solid")) + ggplot2::xlab(label="") + ggplot2::ylab(label="") + ggplot2::scale_y_date(date_labels="%d %b") + ggplot2::facet_wrap(facets= ~ station)
data_book$add_graph(graph_name="last_graph", graph=last_graph, data_name="stationsJuly_by_station_s_year1")
data_book$get_graphs(data_name="stationsJuly_by_station_s_year1", graph_name="last_graph")


```

**Comment by N-thony** [comment]
@derekagorhom I think you worked on this dialogue recently, while working on this issue can you fix this small problem? When you click on multiple receive, the single receiver is still present
![image](https://user-images.githubusercontent.com/68591383/172848353-d9260faf-3f09-4a81-926f-2a9b8113a831.png)

**Comment by Vitalis95** [comment]
@derekagorhom, after pulling the changes you made on PR #7505 , I got the following bugs; These bugs were not there before because I am also working on the same dialog. As you work on this issue can you also fix these small problems?
This is the dialog when I load a dataset;
![image](https://user-images.githubusercontent.com/89011415/172861723-d13ac59a-074b-45e0-9239-6f4028e87e25.png)

When I go to PICSA Options sub-dialog and I click any button, (say) lines then I tick Add mean line and the label; 

![image](https://user-images.githubusercontent.com/89011415/172862594-117472f5-5dff-435c-b1f2-ee2d40c274cb.png)

When I click OK, I get the following error;

![image](https://user-images.githubusercontent.com/89011415/172863029-78cfa92a-383d-4520-9e14-eee0c1302306.png)
 
Also, when I go back to the dialog, the variable in the  single receiver is not there again;

![image](https://user-images.githubusercontent.com/89011415/172863452-ea37a0c6-8ed5-466d-a638-12df5754b32b.png)

Then when I add it back , the test OK now is disabled
![image](https://user-images.githubusercontent.com/89011415/172863692-ac4d5a92-fc0d-4a01-a5a6-f749222c56ac.png)

**Comment by derekagorhom** [comment]
I am currently working on it
