### ISSUE TITLE
Very small change in New-Filter sub-dialogue

### ISSUE THREAD

**Issue by rdstern** [africanmathsinitiative/R-Instat#7617]
The problem is shown here

![image](https://user-images.githubusercontent.com/11226469/179018237-137707b7-b658-4798-8063-89bc2cbff190.png)

Here are the data:
[test_of_blank.csv](https://github.com/africanmathsinitiative/R-Instat/files/9113102/test_of_blank.csv)

It imports with variable b as a factor, so right-click and make it a character variable.  Then try and make the filter.

The correction is simple (I think) It is just that the Add Condition button is disabled if the field is empty.  All we need to do is enable it.

@N-thony to allocate please

**Comment by shadrackkibet** [comment]
@rdstern what's the problem here? Isn't it correct to disable **Add Condition** until when the input control contains something?

I think the issue here is making it "user friendly" so that it is obvious to the user that this field should contain something so that **Add Condition** is enabled. Another way could be to make it obvious when is **Add condition** enabled.

**Comment by rdstern** [comment]
@shadrackkibet the example of data shows that we sometimes want to select all rows when the character variable is empty.  We can't put "", because the system adds the quotes.  So if it is enabled with an empty string, then we can select to choose or avoid those rows.

When the variable is a factor, we can choose that level easily - just select that category.  How to choose the empty rows for a character variable is the issue.
