### ISSUE TITLE
Translation issues on Select Columns Dialog

### ISSUE THREAD

**Issue by MeSophie** [africanmathsinitiative/R-Instat#7675]
Using the French translation of R-Instat 0.7.7 there are some words which are still in English on Select Columns Dialog  (refer to figure ).

![image](https://user-images.githubusercontent.com/106779233/181636705-d85cd0f3-5e69-4ae3-809b-11faf741da20.png)

**Comment by rdstern** [comment]
@MeSophie I also notice the title is "Selection de colonne", i.e. singular.  That's the literal translation of "Column Selection".  But that could be (and usually is) plural.  So I suggest the translation should be "Selection des colonnes"?  Agreed?

**Comment by MeSophie** [comment]
@rdstern yes Roger you are right.

**Comment by N-thony** [comment]
> @MeSophie I also notice the title is "Selection de colonne", i.e. singular. That's the literal translation of "Column Selection". But that could be (and usually is) plural. So I suggest the translation should be "Selection des colonnes"? Agreed?

@MeSophie this one can be done directly in CrowdIn.

**Comment by lloyddewit** [comment]
> Selection is in CrowdIn and translated to Sélection but on the dialogue it is still Selection

@N-thony Thank you for your Slack message above. The translated controls for this dialog are shown below. I think that the reason 'Selection' is not translated is because `lblSelection` is not in the database.

I suggest that:
- I update the `form_controls` table in the database. 
- @MeSophie Updates CrowdIn with all the necessary translations

We can then close this issue. Is that OK from your side?
Thanks

![image](https://user-images.githubusercontent.com/57253949/181705417-8fc2083b-4161-48e9-840a-a9c873c7e75e.png)

**Comment by N-thony** [comment]
@lloyddewit exactly, most of the new controls are not in the database, update the `form_controls` table in the database will sort out most of the translations problem we have.
@MeSophie I will go with you through `CrowdIn` later today or early tomorrow, to show you how you can correct/translate the text directly from your end.

**Comment by lloyddewit** [comment]
@N-thony @MeSophie I updated the `form_controls` table in PR #7686 and merged it into 'master'.
You should be able to fix the remaining issues in CrowdIn.
Note: 'Selection:' is not yet in CrowdIn (but 'Selection`, without the colon, is in).
