### ISSUE TITLE
Translation issues on Display Daily Data Dialog

### ISSUE THREAD

**Issue by MeSophie** [africanmathsinitiative/R-Instat#7683]
1- Following the step _Climatic> Check Data> Display Daily Data_ in French translation of R-Instat 0.7.7,  the names of colours  are still in English for the three options _Graph, Graph by Day and Table_. Also it will be nice to change **Tableau de données** to **Tableaux des  données**, **Option de données** to **Option des données**  and translate  **Rug colours** to French in Graph by Day option.

![image](https://user-images.githubusercontent.com/106779233/181696853-e8d351f4-fc40-441f-be04-a2d625cf1160.png)

2- Following the step _Climatic> Check Data> Display Daily Data>data option>Rows_ the words **Filter** and **no Filter** are not translate.

![image](https://user-images.githubusercontent.com/106779233/181702542-7e6fe074-ecbd-4bdc-8cf7-963633592610.png)

3- Following the step _Climatic> Check Data> Display Daily Data>data option>Columns_  some words are still in English.

![image](https://user-images.githubusercontent.com/106779233/181703046-d7ed5456-e19b-4d30-b2e9-67a246600753.png)

**Comment by lloyddewit** [comment]
@MeSophie Thank you for the clearly written issue. I especially appreciated that you gave the full menu path for each dialog.

Summary:

Climatic> Check Data> Display Daily Data 

- [x] the names of colours are still in English for the three options Graph, Graph by Day and Table. <- drop down lists are not translated, already covered by issue #3721  
- [ ] it will be nice to change Tableau de données to Tableaux des données <-- if we change this translation in CrowdIn, then it will change the translation in multiple dialogs. Do we want this? If we need a special translation for this dialog, then it is possible (but a bit more complex), let me know
- [ ] change Option de données to Option des données <-- @N-thony Please could you (or your delegate) do this in CrowdIn?
- [x] translate Rug colours to French in Graph by Day option <-- fixed in PR #7710

Climatic> Check Data> Display Daily Data>data option>

- [ ] Filter and no Filter are not translated <-- I will check if it can be resolved in CrowdIn

Climatic> Check Data> Display Daily Data>data option>Columns 

- [ ] some words are still in English <-- I will check if it can be resolved in CrowdIn

**Comment by N-thony** [comment]
Now I think @MeSophie got the access to the Repo in CrowdIn, so it will be good that @rachelkg @MeSophie and I to go ahead and make the corrections/translations in CrowdIn.
