### ISSUE TITLE
Bug in Filer Rows Dialogue

### ISSUE THREAD

**Issue by N-thony** [africanmathsinitiative/R-Instat#7684]
This bug occurs when after filter the rows and you want to create a subset with that has the same name of an existing data in the Data View instead of adding `1`. In the screenshot below the new dataframe was expecting to be `Mayange1` but it overwrites `Mayange` with the new one
![image](https://user-images.githubusercontent.com/68591383/181712859-dcb47bc6-8cba-48d3-9083-b99e9b3e295e.png)

**Comment by anastasia-mbithe** [comment]
@N-thony, am not sure if we have to change anything, because when we use, Apply As Filter option it overwrites and replaces the original dataset. Yet, when you use, Apply As Subset it does not replace the original and automatically adds a new sheet. So, in your case, you needed to use the subset option. You can correct me if that is not what you intended.

![image](https://user-images.githubusercontent.com/89011047/185087144-080d4cf2-7b78-4b05-a9f8-59ab58c4a37b.png)

**Comment by N-thony** [comment]
@rdstern since we have two possibilities here of choosing either we create a new data frame containing the filtered data or over write the existing with the filtered data.
I think we can close this issue.
