### ISSUE TITLE
Translate the comments and improve the translation database

### ISSUE THREAD

**Issue by rdstern** [africanmathsinitiative/R-Instat#7773]
We used the French version last week - for the first time in anger!  
a) It went well in that there were no instances where the fact we used French seemed to be the cause of a specific problem
b) But it showed that there is a lot to add to the database, so the translation is more complete.
There were some on the DRC workshop who were relative beginners in computing, and in English.  A more complete translation would have helped them.

We have the 2 components, namely to make the database more complete and also check that the visible text is clear on the dialogues.  I would like to concentrate primarily - at least for the next 2 weeks - on the database.

In adding to the database please also be able to subtract items if they are not used?  Or is there a way this can be checked periodically?

And when there are changes in dialogues that will affect the translation database, can we add a suitable label to the issue, or pull request - I think perhaps the issue, and then change the pull request to "partially".  Then we can regularly check on the issues with that label.  @lloyddewit what do you think?

![image](https://user-images.githubusercontent.com/11226469/184589392-321cc3a0-bd5f-4e74-9870-7ba084a649a3.png)

a) On the main menu it is just the new item `Experiments` that is not translated.
b) The Prepare menu, seems all to be translated.  Good.
c) The sub-menu shown has 4 items that need translation.  Two of the items may be new (Select Columns and Add (Merge) Columns, and the other two (Rename Columns and Duplicate Column are probably very minor edits of what was there before?)

Here is an example of a dialogue:

![image](https://user-images.githubusercontent.com/11226469/184591030-3b1d1205-3321-405d-99ce-6cc42387a32c.png)

d) One recent addition in the dialogue needs to be translated.
But, I am also interested in 2 more general points:
e) The dialogue name at the top is not translated, even though the corresponding menu item is translated.
f) And the comment is all still in English.

I am particularly keen on the comment being translated into the new language.  I hope this is easy.  There are two parts to the comment.  The first is shown below from Tools > Options
![image](https://user-images.githubusercontent.com/11226469/184591591-50dfb6c7-b98c-4811-948e-63d275a9212a.png)

The second is the name of the dialogue - which should pick up the translated name.

I hope this item (f) might be easy - perhaps done by @lloyddewit?

**Comment by lloyddewit** [comment]
@rdstern, thanks for all the feedback.

> when there are changes in dialogues that will affect the translation database, can we add a suitable label to the issue, or pull request - I think perhaps the issue, and then change the pull request to "partially". Then we can regularly check on the issues with that label. @lloyddewit what do you think?

I am currently drafting a PR 'done criteria' checklist. Whenever a developer creates a PR thay should complete the checklist before they request test/review. I propose that the checklist includes:

- 'Change the R-Instat language to Russian. View each changed dialog/form/menu in Russian. If there is any text that is not translated (even if the text was not added/updated in your PR), then create an issue. The issue should have 'translation' in the title, and reference your PR.'

Using Russian was your idea and I think it's a good one. Untranslated text should be very obvious. 

I'd prefer not to block PRs due to missing translations because translation changes are best done by a couple of experienced individuals. Database changes are prone to merge conflicts so the work is best done by a couple of people who can coordinate. They can also fix multiple translation issues at once. @MeSophie has done an awesome job over the last few weeks raising translation issues.

What do you think?

> f) And the comment is all still in English.

I will look at this
