### ISSUE TITLE
Translate popup menus in R-Instat

### ISSUE THREAD

**Issue by rdstern** [africanmathsinitiative/R-Instat#7774]
Is there an easy way to find them all in the code?

I have an impression that none, or hardly any are translated so far.  And the nature of a popup is that this was an unwelcome surprise in the workshop.

I am using the French version:
a) Here is right-click > Convert to numeric
![image](https://user-images.githubusercontent.com/11226469/184596745-a9ef8eaa-bea8-49d1-9351-ba61342856f7.png)

b) Here is File > Close Data Book
![image](https://user-images.githubusercontent.com/11226469/184596943-105dbc94-9f60-4f6f-b57b-5e33ac49b5ff.png)

c) Here is the message when you exit R-Instat
![image](https://user-images.githubusercontent.com/11226469/184597052-589282f1-3fff-4a4e-87de-9d5c0a870197.png)

d)  Right-click and delete columns

![image](https://user-images.githubusercontent.com/11226469/184619207-ce02f56a-4608-49f1-95ed-1e7ce604e464.png)

e) Similar is the message from Try
![image](https://user-images.githubusercontent.com/11226469/184597589-2d278ede-f517-43ab-bb75-8cf200b56e5f.png)
@N-thony can you do this, or allocate?

**Comment by lloyddewit** [comment]
The majority of this issue is covered by issue #3721. I added a note:

![image](https://user-images.githubusercontent.com/57253949/186598703-6b67684d-eb6c-4abe-8848-5e6861714003.png)

However, the final example above is a text field. We will try and fix this.
@MeSophie Please could you check which error messages can be displayed in the `Essayer` text field and add these messages to the English JSON file? thanks

![image](https://user-images.githubusercontent.com/57253949/186599122-11207579-3125-4761-9761-05e8a18a61de.png)
