### ISSUE TITLE
How we process, store and retrieve objects in the R data book

### ISSUE THREAD

**Issue by Patowhiz** [africanmathsinitiative/R-Instat#7808]
@lloyddewit @ChrisMarsh82 @dannyparsons @rdstern @lilyclements 
Currently we rely on the class type of objects to identify and filter the objects contained in the data book in R.
Some packages produce objects that have multiple class types which overlap with other "category" of objects.
For instance;
1. Graphs could be in html "category". 
2. Tables could be in html or text "category".

That means if I want to identify graphs only in the set of objects. I will need to check more than the object class type.
Functions `add_objects` , `get_objects`  and `get_object_names` in R level demonstrates my above observations.

I suggest when adding objects in the data book we also require an extra  parameter for specifying the "type_label" of the object. 
This "type_label" can then be used to determine how we process, store and retrieve the object. This may require changing the data structure used for holding the objects.

**Comment by lloyddewit** [comment]
@Patowhiz 
- are you saying that a table is either an 'html' or 'text' object and we currently have no way of checking if it's a table?
- or are you saying that there is a table class with multiple inheritance from both 'html' and 'text' classes?

**Comment by Patowhiz** [comment]
After thinking about this further, I suggest using 4 parameters in processing, storing and retrieving objects, namely; 
1. `data_name` - used to identify the data name that the object belongs to. 
2.  `object_name` - used to identify the name of the object. 
3.  `object_type` - used to identify the _type_ of the object, for instance, graph, table, model, string
4.  `object_format` -  used to identify the displayable format, for instance, image, html, text

**Comment by Patowhiz** [comment]
Below is a presentation of the object metadata I suggest we store, than can simplify objects processing.
| object_name | object_type | object_format | object |
| ------ | ------ | ------ | ------ |
| "scatter_plot1" | "graph" | "image" | scatter_plot |
| "rain_bar_chart" | "graph" | "image" | rain_bar_chart |
| "summary_table1" | "table" | "text" | summary_table1 |
| "summary_vars_table" | "table" | "html" | summary_vars_table |
| "surv1" | "structure" | "text" | surv1 |
| "summary1" | "summary" | "text" | summary1 |
| "model1" | "model" | "text" | model |

After discussing with @lilyclements we suggest having the following `object_type`(s);

1. `graph` - this is visually a plot. Can be of `object_format` image or html.
2. `table` - this will always be a 2 dimensional structure, that visually has rows and columns. Can be of `object_format` image, html or text.
3. `model` - this is produced by model functions. Can be of `object_format` image, html or text.
4. `structure` - for instance the survival  and circular objects. Can be of `object_format` image, html or text.
5. `summary` - for instance a `skimr` summary or any text output that can't be classified in the above types. Can be of `object_format` image, html or text.

**Comment by dannyparsons** [comment]
I'm happy with this approach to object metadata. This is an improvement on our current system where types are not well defined. I would just suggest changing `object_label` to `object_type`, as label is too generic and this is describing the type of the object.

When changing internal structures in the data book you need to consider backward compatibility of older RDS files/data books i.e. you need to be able to deal with objects which will not have these properties because they were created before this change, probably by retaining the old code in these cases and relying on the object's class. This can be tested by creating an RDS file with saved objects with a previous version and trying to load it into your new version.

Related, you will also need to update the data sheet clone method to be able to copy the list of objects from both the old and new formats (into the new format). I can write more about this if that would be useful.

**Comment by Patowhiz** [comment]
@dannyparsons thanks for your feedback.
I changed `object_label` to `object_type_label`, is that more descriptive enough?
In regards to backward compatibility of older RDS, I had not thought about that. I will add that functionality as well, and also try to detect the `object_type_labe`l from the class type just like before. 
I'll also look into the cloning aspects.

**Comment by Patowhiz** [comment]
@dannyparsons on a separate note. 
We are now thinking about staking advantage of the new implementation in saving objects as an RDS file.
I noticed you decided to put graphs inside a separate data book. Key point being the data book, I wonder why? 
I intend to suggest storing all objects together, we can now definitively identify them. 
I wonder what other alternative we have in saving these objects and reloading them back to the data book. Any suggestions?
This is something that we are still discussing with @lilyclements, your suggestion will be highly appreciated.

**Comment by lloyddewit** [comment]
@Patowhiz Thank you for the discussion yesterday. I also support storing the metadata explicitly, rather than trying to deduce it. 

I understand that you propose to store metadata in a 2-dimensional table with one row for each 'object_name', and 1 column for 'object_type_label', 'object_format' and 'object' respectively. Did I understand correctly?

Should we instead consider an 'output_object' class with the following data members:
- object_type_label (enumeration of graph, table, model, structure, summary)
- object_format (enumeration of image, html, text)
- object (the R object itself)

The class constructor and get/set operations would ensure that only valid combinations are allowed (e.g. a graph is always an image). We would then have a 1-dimensional list of 'output_object's. 

For common OO languages, this would be the normal approach. Would it also make sense in R?

**Comment by Patowhiz** [comment]
@lloyddewit thanks for the queries.

> I understand that you propose to store metadata in a 2-dimensional table with one row for each 'object_name', and 1 column for 'object_type_label', 'object_format' and 'object' respectively. Did I understand correctly?

Yes, It's a 2 dimensional structure implemented through a list of list. The "outer" list has named elements and that's where the `object_name` is used.  The "inner" list which is basically the element of the "outer" list contains the `object_type_label`, `object_format` and `object` as elements.
I used this approach to just build on what was existing.

> Should we instead consider an 'output_object' class with the following data members

I find R to be very different in the way code is designed and written, even as a functional language.
R has 3 class systems, namely, S3, S4, and Reference class. Here is [link](https://www.geeksforgeeks.org/classes-in-r-programming/) that explains more on this (it's a 10 minute read). Here is another [link](https://www.programiz.com/r/objects-classes#:~:text=Class%20System%20in%20R,Reference%20Class) that explains the main differences.

It's fairly easy to convert my current implementation to use this class system but it's still not clear to me if I will gain the benefits that we gain the benefits that you've outlined. Notice the class systems are simply using lists which is what I'm currently using. If we are to use the S3 or Reference class, the access to the fields will be the same as the current implementation.
In addition, the class system we should generally use internally in R-Instat needs a discussion with the team (@dannyparsons @lloyddewit).
This is an interesting topic and I suggest we create a separate issue on it that can be expounded into other functionalities as well.
Thanks

**Comment by lloyddewit** [comment]
@Patowhiz ok, fair point, thank you
@lilyclements do you have a view on using classes versus lists in R?

**Comment by lilyclements** [comment]
I don't have experience in using classes in R, unfortunately. I know a little about R6 classes, but not enough to form a useful opinion. I would suggest that @dannyparsons would be very useful in this discussion

**Comment by dannyparsons** [comment]
I'm happy starting with a list for now as we can quite easily convert this to a class later.

On graphs being stored outside the data_book, this was a temporary fix due to some types of graphs being extremely large when saved within the RDS file and this was causing saving and auto saving to be very slow. The big disadvantage of the separate data_book is that saved graphs are lost after the session is closed.

I discussed with Roger and agreed we should now save graphs in the main data_book, as the problem graphs are not that common. I believe there is a TRUE/FALSE argument to the save graph functions which could simply have its default changed to now save in the data_book.

In future we might want to detect the problem type of graphs and save those in a separate data_book still.

**Comment by Patowhiz** [comment]
In addition we now also have html objects which can be bigger in size than even graph objects. 
We need a general design of how we will save objects efficiently, elaborately and in a consistent way.
