### ISSUE TITLE
Options to show/hide the comments and R-commands in output window no longer work?

### ISSUE THREAD

**Issue by rdstern** [africanmathsinitiative/R-Instat#7959]
@ChrisMarsh82 and @Patowhiz we used to have the option in Tools > Options > Output Window to show or hide the R-commands and the comments.
They no longer appear to work.
I wondered whether this might be related to Patrick's changes for html, but they don't work either in Version 0.7.7?
I would be happy for the options to be implemented differently, if that is your preference, but would like the option to not show R commands in the next release, if at all possible.

**Comment by Patowhiz** [comment]
It's absolutely possible.  Will look into it

**Comment by rdstern** [comment]
@Patowhiz just to mention that the old system worked fine, but only for the future.  So if you switched off the commands, then they remained for the past and were off from when you did it.
The converse is more important, because ideally our default would be to not show command.  Then you could always switch them on later.  It would be ideal if it then showed the commands for the whole session, and not just from when you switch.  
But I would still be happy with the simpler system we had before, where the change is for the future, and ignores the past.

**Comment by Patowhiz** [comment]
@rdstern I've been thinking about this for a while now, More comments below.

 I find the current default counter intuitive because;

1. We have a "To Script" button I every dialog. Any user can always go back to the dialog and use the button to have a look at the code.
2. We have an Audit log that can always be viewed. It has a log of all the scripts produced. Users can always go to it and check on the scripts.
3. We could re-design the outputs in a way that they are always associated with the scripts in a different way, for instance,  "tabbed with scripts" or have clickable "links" that show the scripts behind the output. The design here can be very flexible, there is nothing we can't come up with.

I really like the 3rd option. It removes the need of the toggling settings and yet retains the reproducibility setting, and the length of outputs will be immensely reduced.

**Comment by rdstern** [comment]
@ChrisMarsh82 I am hoping that the option to not show the R commands in the output window could be restored for the next release.
Further - after checking with Danny and David - that the default, when R-Instat starts is to hide the R-commands.  
The option is still in the Tools > Options dialogue.  I think the comments switch still works, but the option to disable the commands seems not to work in the recent output window.

**Comment by Patowhiz** [comment]
@rdstern this is part of my work this week. Thanks.

**Comment by rdstern** [comment]
Oh great.  Thanks
