### ISSUE TITLE
Regular Sequence Dialog

### ISSUE THREAD

**Issue by berylwaswa** [africanmathsinitiative/R-Instat#8051]
When I open the regular sequence dialog, on the right side it says no preview available so I cannot see a preview of the sequence I am creating. 
I need this fixed so that it's okay in the next release.

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to 'Prepare>Column: Numeric>Regular Sequence'
2. Look at the right side of the dialog
3. See error

**Expected behaviour**
I expect to see a preview on the right side of the dialog when I open it but there's none.

**Screenshots**
![Regular Sequence 1_13_2023 2_17_38 PM](https://user-images.githubusercontent.com/28622260/212312336-3c44fed0-b355-42ea-919a-61c6a2606b2d.png)

**R script or commands**

regular <- rep(x=seq(from=1, to=100, by=1), each=1, length.out=100)
data_book$add_columns_to_data(data_name="data", col_name="regular", col_data=regular, before=FALSE)

rm(regular)

**Comment by N-thony** [comment]
@berylwaswa which data did you use? I guess the one from File > New Data Frame x1 numeric from 1 to 100?

**Comment by rdstern** [comment]
@N-thony that - with variables of length 100 is one example.  But recently I have also not found an example where the preview works.  I know there was a change, because earleir it gave the preview, even for long data frames and this was sometimes very slow.  We now seem to have hit the other extreme!

**Comment by berylwaswa** [comment]
Yes, it's the one I used,  File > New Data Frame x1 numeric from 1 to 100.

Kind Regards,
Beryl Waswa.

**Comment by N-thony** [comment]
Okay, let me look at it

**Comment by berylwaswa** [comment]
It works fine now.

**Comment by rdstern** [comment]
@berylwaswa I am keen that you become a good tester.  I note you are happy now - and I was not!  Once we are both happy it will be good for you to see if there are any general lessons in that process.  Testers need to ask "What is a user did, or had this?"  And for lots of examples of "this".  I usually test by including contrasting data frames and also seeing what happens when you use a dialogue repeatedly - and possibly in a different way.

**Comment by berylwaswa** [comment]
Well noted with thanks.

**Comment by rdstern** [comment]
@N-thony Here is an example that should have a preview - but doesn't.  It is just of length 10.  I assumed we would have a preview up to length about 10,000?

![image](https://user-images.githubusercontent.com/11226469/214163828-139a2539-133d-40cf-976b-ec443bdf258e.png)

So I am re-opening the issue.
