### ISSUE TITLE
Small change on the window number feature

### ISSUE THREAD

**Issue by rdstern** [africanmathsinitiative/R-Instat#8086]
@N-thony here is an example:

![image](https://user-images.githubusercontent.com/11226469/215037764-ce0df32e-9e67-4ef9-9d17-c6cf62c5b573.png)

I needed to go to row 3226.  So I know it is in the 3000 range, and I type 4 - rather than 3!  I did that quite a lot with these data and found it quite annoying!

My suggestion, for a minimal change is that in the message above you change 1-125 into 0-124.  So then I enter 3 to get the 4th window - which is usually the 3000's.

At the same time I have added a place in the Help file - so could you add the help context 294.  It will come in the February update to the Help!

**Comment by N-thony** [comment]
@rdstern maybe we can have a quick chat, the `data view` show 1000 rows per page, for row 3226 which is in range 3000, I would expect 3 rather than 4. 
And I think if we change the message from 1 to zero it will no longer be consistent with the text on the bottom of the grid which start for the first page from `1 to ...`
![image](https://user-images.githubusercontent.com/68591383/215483844-123ca516-7efb-4648-924c-ff90de71ac1f.png)
