### ISSUE TITLE
Minor bug in the File > New Dataframe Dialogue

### ISSUE THREAD

**Issue by N-thony** [africanmathsinitiative/R-Instat#8120]
@derekagorhom when I try to change the default it becomes black which makes it hard to change. Can you fix this?
![image](https://user-images.githubusercontent.com/68591383/217818707-f60372a1-956b-4892-9924-7b5d63318826.png)

**Comment by rdstern** [comment]
@N-thony and @derekagorhom at the same time can you look at the dialogue when you produce lots of variables and tick the variable names checkbox.

![image](https://user-images.githubusercontent.com/11226469/218389626-b6688e13-e3c4-4ac9-9d7e-52238644dac6.png)

You can see here that it has gone badly wrong - only 2 rows in the grid are numbered and I got 4 variables rather than 54.  In testing try also with examples that have more than 1000 rows, and you therefore have also to change the cell with the default of 1,1000 as mentioned above - though I hadn't noticed that problem.

**Comment by derekagorhom** [comment]
I and Antione had a discussion about the issue and we discovered it only happened to some and not all the laptops (it could be a configuration problem from the user PC). we didn't think it warranted a Pull request least it ended with another bug,  so i think yours will be the one we will attempt. 

> @derekagorhom when I try to change the default it becomes black which makes it hard to change. Can you fix this? ![image](https://user-images.githubusercontent.com/68591383/217818707-f60372a1-956b-4892-9924-7b5d63318826.png)

**Comment by rdstern** [comment]
@derekagorhom sounds good.  And that bug that appears on just a few machines is like some complications we found on the recent workshop where we had more than a dozen different machines.  It will be good track down some of those issues gradually too - as R-Instat is used more.
