### ISSUE TITLE
"ok" button in climndex is disabled

### ISSUE THREAD

**Issue by WezzieBanda** [africanmathsinitiative/R-Instat#8225]
**Describe the bug**

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to 'climatic'
2. Click on 'prepare'
3. Scroll down to 'climndex'

**Expected behaviour**
"ok" button should be enabled.
![IMG_20230320_222829](https://user-images.githubusercontent.com/106272881/226459610-d50710b1-1b69-4028-b984-832083fef6cc.jpg)
![IMG_20230320_222829](https://user-images.githubusercontent.com/106272881/226460128-91c1ce10-a2eb-4c19-86ba-e65a88f0b9eb.jpg)

**Details (optional):**
 - OS: [e.g. Windows 10]
 - R-Instat Version [e.g. 0.7.9]

**Comment by rdstern** [comment]
@WezzieBanda thanks for noting this problem.  It ius good that you show the screen-shot.  You mentioned that Ok is still disabled as the problem, but that's ok, because no indices have been selected yet.

There is a problem in the dialogue here, that the text is displaced - so that the number of indices selected is in the middle of the message.  That should be changed.
