### ISSUE TITLE
Improve the R code in back-to-back bar charts

### ISSUE THREAD

**Issue by rdstern** [africanmathsinitiative/R-Instat#8300]
@COLIEWO many thanks for your document on the back-to-back histograms (population pyramids) in R-Instat.  That set me on the right track to be able to produce them.  The R code needs a careful study and I had to make a small change to get it to work.  Could you check please and advise the programmers.

I used the research funding rates data from the dslabs package.  I tried both with the data as imported (9 rows) and also after stacking into 18 rows, so the men and women can be used as an ordinary factor. Here it is with the data as imported:

![image](https://user-images.githubusercontent.com/11226469/235583450-ff88cf4b-d3e9-41d0-a8b7-6cd658fb99fc.png)

This didn't work for me, giving this result.

![image](https://user-images.githubusercontent.com/11226469/235583651-da6e0b87-09bc-45b8-8f57-f05514e2b568.png)

I checked the R-code produced, which was as follows:

```
# Code generated by the dialog

research_funding_rates <- data_book$get_data_frame(data_name="research_funding_rates", stack_data=TRUE, measure.vars=c("applications_men","applications_women"))
research_funding_rates <- data_book$get_data_frame(data_name="research_funding_rates", stack_data=TRUE, measure.vars=c("applications_men","applications_women"))
research_funding_rates <- data_book$get_data_frame(data_name="research_funding_rates", stack_data=TRUE, measure.vars=c("applications_men","applications_women"))
last_graph <- ggplot2::ggplot(research_funding_rates, mapping=ggplot2::aes(x=reorder(x=discipline, X=-value), y=value, fill=variable)) + ggplot2::geom_bar(data=subset(research_funding_rates, variable == levels(x=variable)[1]), stat="identity", aes(y=value)) + ggplot2::geom_bar(position="fill", stat="identity") + ggplot2::geom_bar(data=subset(research_funding_rates, variable == levels(x=variable)[2]), aes=aes(y=-value), stat="identity") + lemon::scale_y_symmetric(labels=abs) + theme_grey() + ggplot2::coord_flip()
data_book$add_object(data_name="research_funding_rates", object_name="last_graph", object_type_label="graph", object_format="image", object=check_graph(graph_object=last_graph))
data_book$get_object_data(data_name="research_funding_rates", object_name="last_graph", as_file=TRUE)
rm(list=c("last_graph", "research_funding_rates"))
```
There seem to be at least 2 problems with the R-code:
a) The first line is repeated 3 times.
b) The line beginning last_graph is pretty complicated to me.  Within this I changed `aes=aes(y=-value)` into simply `aes(y=-yvalue) ` This changed the result to:

![image](https://user-images.githubusercontent.com/11226469/235584659-d7887a9b-5290-42f6-992a-74a1335bf4d8.png)

Hey presto we have a population pyramid.

Please could you check the above and suggest what should be done in the dialogue.
a) Should those changes be made in the code.  Does this then work ok?  Could you try more examples.
b) What should change in the dialogue?  I suggest that when you tick the back-to-back checkbox, the position control is not visible and the code always uses Fill?  Or perhaps there are useful alternatives with other settings?

**Comment by COLIEWO** [comment]
@rdstern upon further testing and looking at the code; on part (a) editing from `aes=aes(y=-value)` to `aes(y=-value)` for the level 2 variable seems to fix the plot when the input is **Multiple Variables**, however for the **Single Variable** input this is not enough since the graph still isn't centered on the x-axis.

| Initial Plot | On editing `aes(y=-population)` |
| ------------- |-------------|
| ![initial](https://user-images.githubusercontent.com/124562645/235647708-66d9bba5-6849-47e4-8d2b-307ed982f247.png) | ![first edit](https://user-images.githubusercontent.com/124562645/235647798-ff01b466-60ca-47c1-9371-8da6f9839627.png) |

Further editing the initial code:
`Population <- data_book$get_data_frame(data_name="Population")
Population <- data_book$get_data_frame(data_name="Population")
Population <- data_book$get_data_frame(data_name="Population")
last_graph <- ggplot2::ggplot(Population, mapping=ggplot2::aes(x=age, y=population, fill=gender)) + ggplot2::geom_bar(data=subset(Population, gender == levels(x=gender)[1]), stat="identity", aes(y=population)) + ggplot2::geom_bar(position="fill", stat="identity") + ggplot2::geom_bar(data=subset(Population, gender == levels(x=gender)[2]), aes(y=-population), stat="identity") + lemon::scale_y_symmetric(labels=abs) + theme_grey() + ggplot2::coord_flip()
data_book$add_object(data_name="Population", object_name="last_graph", object_type_label="graph", object_format="image", object=check_graph(graph_object=last_graph))
data_book$get_object_data(data_name="Population", object_name="last_graph", as_file=TRUE)
rm(list=c("last_graph", "Population"))`

by deleting `+ ggplot2::geom_bar(position="fill", stat="identity")` gets a good graph below;
![final](https://user-images.githubusercontent.com/124562645/235656021-3bd09cbc-fe25-495d-a4ee-1a20eb2c87f6.png)
Thus on point (b) I am of the opinion that the position control not be mandatory.
