### ISSUE TITLE
The New Data Frame Dialog Buttons

### ISSUE THREAD

**Issue by berylwaswa** [africanmathsinitiative/R-Instat#8321]
On opening the new data frame dialog, for both Kiswahili and English, the buttons are separated. Initially, all five buttons were together, now the first and second buttons are on their own and the last three are together. I suggest that all 5 be stuck together for a better look.

Also when I am using Kiswahili as my language the translations for columns and rows overlap with the receivers. I suggest reducing the sizes of the box to allow the text to fit well.
Here is an image of the dialog.
![new](https://github.com/africanmathsinitiative/R-Instat/assets/28622260/1864bccd-b98b-48c9-8a28-936a51fdda9c)

**Comment by rdstern** [comment]
@berylwaswa oh damn - you are not the first to assume that separating the top radio buttons must be a mistake, because they used to be stuck together.  Notice the name has also changed from Empty to New, and the order of the buttons is now different.

My reasoning was that most users of this dialogue would just use the first option - namely New.  Then the second option is also pretty simple (Lists) and we have a video on that.  Then the third to the fifth buttons all involve R commands, as are more complicated.  So I thought separating the buttons was a pretty brilliant idea - but no one seems to agree with me!

@berylwaswa now you have my explanation, I am happy to go with whatever you prefer.  Would you still prefer to have the buttons together - as we usually do in dialogues with radio buttons?

I also quickly checked the layout for the Rows and Columns in the other languages.  The others are ok, and I assume you are happy with the translation - it is just that the up-down need to be moved a bit to the right.  And if ok for Kiswahili, then that's all that is needed.

**Comment by berylwaswa** [comment]
@rdstern I prefer them stuck together, separated it doesn't look good.
The translation is okay the boxes just need to be moved.

**Comment by rdstern** [comment]
@derekagorhom I hope you could quickly do these 2 tasks.  We are using this dialogue in a number of the videos.
a) Put the radio buttons back together again - (as they are in most other dialogues).  I have had a lot of critisism of their current arrangement, with people thinking it must be an error!
b) Move the 2 up-down controls a bit to the right, so the Kiswahili text is complete - see above.

Thanks
