### ISSUE TITLE
A new option to make renaming columns easier

### ISSUE THREAD

**Issue by lilyclements** [africanmathsinitiative/R-Instat#8439]
@serifatf is looking at analysing the app data in R-Instat. One of the immediate questions that came up was whether there was an approach to remove the same string from all column names. This would be a problem in our app and chatbot data since they all start with a long string (e.g., "rp.contacts.field." in the app data).
There are hundreds of rows, so doing this manually would be very time consuming. As well as this, it takes up a lot of space in the column titles making it less clear.

Fortunately there's some very easy code to fix this! Using `starts_with` in `tidyselect`, we can just find all the cases that start with a certain string, and replace that string with anything we like (including an empty string, as we want to here).

```
data_book$rename_column_in_data(data_name="data_RDS", type="rename_with",
                                 .fn=stringr::str_replace,
                                .cols=tidyselect::starts_with("rp.contact.field."),
                                pattern = "rp.contact.field.",
                                replacement = "")
```

I suggest we add this to our "Rename With" tab on the Rename Columns dialog. We currently have three radio buttons, but I suggest we add one more:

* Replace Name (or something like this!)

When that is selected, we have a ucrInputDropDown (non editable) where you can select one of "Starts with", "Ends with", "Contains", "Matches"
There is also two ucr Inputs: one with the string to rename, and one with the value to rename it to.
Only the first needs to be filled. If you want to remove that part of the column name completely, you rename it to an empty string, `""`.

The corresponding functions
* If the rdo button is selected, we run `.fn = stringr::str_replace`
* If `starts_with` is selected, we run `.cols = starts_with` as the function
* If `ends_with` is selected, we run `.cols = ends_with` as the function
* If `matches` is selected, we run `.cols = matches` as the function
* If `contains` is selected, we run `.cols = contains` as the function

Then
* The ucr input with the string to rename is the value of the parameter `pattern` as well as the value that is read into our `starts_with` (or `ends_with`, `matches`, `contains`) function. This needs to be filled if the rdo is checked.
* The ucr input with the value to rename it to is `replacement`, this is default `""`

@rdstern what do you think? This is the start of using R-Instat for analysing the App and Chatbot data, which would be great. Do you think this should be four options - one for "starts with", "ends with", "contains", and "matches"? Or just one option about replacing a part of a string?

Side note: Matches vs Contains - 
`matches` will match a regular expression, `contains` is for a string.

**Comment by serifatf** [comment]
@lilyclements , good to connect with you here.

**Comment by rdstern** [comment]
@lilyclements that sounds excellent.  @N-thony wrote most of the new rename dialog so is well places to add - or to allocate - this feature.  @N-thony you might also check on the details of the location of the extra control.  You are good at that! 

There is the similar drop-down control in the Select columns sub-dialog:

<img width="382" alt="image" src="https://github.com/africanmathsinitiative/R-Instat/assets/11226469/6263bfca-79d2-489f-b4ef-5bd11e907a89">


Maybe call it `Edit Names: `as the checkbox.

Then, as you say, if checked it shows the drop down, followed by `Replace: <input string> By: <replacement string>`

a) If the second is left blank, then the replace string is removed.
b) If this results in an illegal name then it is made legal.  That includes the situation where the whole name may be deleted.
c) Could the output window report the number of names edited?
d) If a Select is "operational" in the dialog, then it only renames those that are within the select.

**Comment by MeSophie** [comment]
@rdstern  and @lilyclements Please I need Some clarifications.
This is what I did from up to now.

![image](https://github.com/africanmathsinitiative/R-Instat/assets/106779233/8c6c001c-53e3-43fa-97a6-c425f8a4eab6)

So @lilyclements please is the parameter `type` will always has the value `rename-with`? I assume that `rp.contact.field.` in your code above represente the `string to be replace`. 
Than is this code only works in all the columns. I means because we don't have any controls where we can specify the colum is mean that the code will replace the string everewhere? Don we need another control where we can specify the column(s)?
Also i don't know if this code that I obtain following your code is correct I have every parameters but when I run nothing change. 
`data_book$rename_column_in_data(data_name="survey", .fn=stringr::str_replace, .cols=tidyselect::starts_with("OLD"), pattern="OLD", replacement="NONE", type="starts_with")`

 @rdstern  Please can you give more explanation about part b) (What do you mean by illagal name?) and  part d)?

**Comment by rdstern** [comment]
@MeSophie it is good you asked.  I'll give you my answer, and @lilyclements can add if I have it wrong.  
I have an example dataset.  I have used the DAAG package, and it has a dataset called rockart.  See here:

<img width="519" alt="image" src="https://github.com/africanmathsinitiative/R-Instat/assets/11226469/78c28fc3-a113-4439-a887-6a5d5cc88549">

You see there are a lot of names that start with SS for example SSn33, SSn34 and so on.  Suppose I want to change the SS to Sophie in all these names.  So I really need a find and replace that works on column names.

Lily suggests adding a 4th option on this button shown, rather than a new button.  So it is all within the `Rename with`. It goes under `Abbreviate` and I suggest you just call it `Replace`   (It doesn't need to be Replace Name, because the whole dialog is about Rename.)

Then you can, as Lily says, take advantage of the "language" to have a `pull-down` to choose where in the name you are replacing.  And I mentioned above, that most of the options lily mentions are already given in the Select feature, that we have already.  In the example above you would use `Starts With`.    Then you need a foeld into which we can type `SS` and then a `By: `label and another field, into which you can type `Sophie`.   And if you type nothing into the second field, then it will simply delete the SS in the first field.

If you need help on the details of the Find/Replace then @N-thony may also be able to help, as he wrote most of the ordinary Find/Replace in the Prepare > Column: Text menu.

And keep asking questions on anything you are unsure about.
